feat: nextjs app directory example
wundergraph/wundergraph pull request #1002
Opened 2023-05-26 12:33 UTC by DaniAkash

## Motivation and Context

Add an example project on how to use WunderGraph with Next.js 13 App Directory along with both Server Components & Server Actions.

## Marketing Changelog

An Example TodoList app built with Next.js 13 App Directory along with Server Components & Server Actions.

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-26 14:44 UTC, jensneuse approved these changes

2023-05-26 14:44 UTC, jensneuse commented
This is super cool @DaniAkash!

2023-05-26 15:01 UTC, StarpTech requested changes
Please add an integration test per example.

2023-06-26 07:59 UTC, StarpTech approved these changes
LGTM

2023-07-26 19:34 UTC, Balance8 commented on examples/nextjs-relay-todos/.wundergraph/operations/relay/persisted.json
> +  "5ce551f3c418699ad61443ed34aa470f": "mutation TodoListAddTodoMutation(\n  $todo: todos_NewTodoInput!\n) {\n  todos_addTodo(todo: $todo) {\n    id\n    text\n    isCompleted\n  }\n}\n",
Why does the relay app need to be updated with this example?

2023-08-01 05:16 UTC, DaniAkash commented on examples/nextjs-relay-todos/.wundergraph/operations/relay/persisted.json
> +  "5ce551f3c418699ad61443ed34aa470f": "mutation TodoListAddTodoMutation(\n  $todo: todos_NewTodoInput!\n) {\n  todos_addTodo(todo: $todo) {\n    id\n    text\n    isCompleted\n  }\n}\n",
Seems like an accidental change - reverting it

2023-08-03 10:01 UTC, merged