fix: use Node.js fetch that supports web stream api
wundergraph/wundergraph pull request #1007
Opened 2023-05-27 14:43 UTC by StarpTech

The cross-fetch package does not provide a web-streams compatible API required by the base client implementation. This cause `response.body.getReader is not a function` when starting a subscription with the operations client. This PR removes this package. We will use the native `fetch` implementation shipped with Node.js 18

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-27 14:53 UTC, JivusAyrus approved these changes

2023-05-27 16:11 UTC, Aenimus commented on packages/sdk/src/server/operations-client.ts
> +		const { clientRequest, ...rest } = options;
Eelco literally just fixed this a few days ago.
https://discord.com/channels/738739428314316823/738740476940910692/1110856784924659712

2023-05-27 16:13 UTC, Aenimus commented on packages/sdk/src/server/operations-client.ts
> +		const { clientRequest, ...rest } = options;
https://linear.app/wundergraph/issue/ENG-2321/customfetch-not-passed-down-to-the-base-client-in-operationclient

2023-05-27 16:18 UTC, Pagebakers requested changes
It would be better to fall back to a polyfill solution if fetch is undefined, but i believe cross fetch does this already. 

We can plan to remove it and make node 18 the minimal node version, but im not sure its time for thast yet.

2023-05-27 21:35 UTC, StarpTech commented on packages/sdk/src/server/operations-client.ts
> +		const { clientRequest, ...rest } = options;
Nothing has changed except using a fetch implementation that also work with web streams

2023-05-27 21:49 UTC, StarpTech commented
> It would be better to fall back to a polyfill solution if fetch is undefined, but i believe cross fetch does this already.
We can plan to remove it and make node 18 the minimal node version, but im not sure its time for thast yet.

Done. I use undici as polyfill on the server

2023-05-27 22:18 UTC, Aenimus approved these changes

2023-05-28 18:48 UTC, Pagebakers approved these changes

2023-05-28 18:52 UTC, merged