fix: hook server strictness
wundergraph/wundergraph pull request #1013
Opened 2023-05-29 14:24 UTC by Pagebakers

## Motivation and Context

This fix makes the hook server config stricter so any user errors in the config are highlighted.

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-29 16:05 UTC, StarpTech commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> +export class MyContext {
Anyway, how can we prevent a regression in the future? A test?

2023-05-29 17:35 UTC, Pagebakers commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> +export class MyContext {
There are 2 ways to make the config 100% strict so our type tests will pick up on everything, but we need to discuss it because how the server config is implemented hasn't changed in over a year (before I started). The problem is now we cannot be too strict, otherwise the initial config generation will not work.

2023-05-29 17:46 UTC, StarpTech commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> +export class MyContext {
Ok, let's discuss a potential solution tomorrow.

2023-05-29 17:47 UTC, StarpTech commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> +export class MyContext {
What exact scenario does this PR improve?

2023-05-30 09:47 UTC, StarpTech requested changes

2023-05-30 09:47 UTC, StarpTech commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
>  					console.log('###mutatingPostResolve', hook);
Please use the sdk logger

2023-05-30 09:51 UTC, jensneuse approved these changes

2023-05-30 11:02 UTC, Pagebakers commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
>  					console.log('###mutatingPostResolve', hook);
Can you open an issue for this? it's not something I changed in this PR, it's used on other tests apps also.

2023-05-30 11:06 UTC, StarpTech approved these changes
LGTM

2023-05-30 12:29 UTC, fiam approved these changes
LGTM

2023-05-30 18:09 UTC, merged