feat: implement removeNullVariables for DB datasources
wundergraph/wundergraph pull request #1041
Opened 2023-06-03 00:29 UTC by Aenimus

## Motivation and Context

Add removeNullVariables directive for database data sources

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-06-03 04:06 UTC, jensneuse approved these changes

2023-06-05 08:15 UTC, devsergiy requested changes

2023-06-05 08:15 UTC, devsergiy commented on pkg/datasources/database/datasource.go
> +		input.Variables = httpclient.SetInputFlag(input.Variables, httpclient.UNNULLVARIABLES)
please change to
```
input = httpclient.SetInputFlag(input, httpclient.UNNULLVARIABLES)
```

input.Variables should not be touched as it is variables which we will send to upstream

2023-06-05 08:15 UTC, devsergiy commented on pkg/datasources/database/datasource.go
> +	if err == nil && httpclient.IsInputFlagSet(variables, httpclient.UNNULLVARIABLES) {
and this also need to be updated
```
httpclient.IsInputFlagSet(input, httpclient.UNNULLVARIABLES)
```

2023-06-05 10:11 UTC, devsergiy approved these changes

2023-06-05 10:13 UTC, merged