feat: add logging interface
wundergraph/wundergraph pull request #1043
Opened 2023-06-05 11:22 UTC by fiam

- Add RequestLogger interface, which specifies and documents the supported
logging methods available for hooks/webhooks/operations
- Add unit tests for RequestLogger
- Make sure we initialize pino propertly
- Ensure the correct logger type is passed to webhooks, hooks and functions
in the integration tests

Fixes ENG-2433, ENG-2434, ENG-2435

## Motivation and Context

Previously we were exporting pino and fastify loggers directly, which created a problem
for documentation as well as making the API non obvious.

## Marketing Changelog

WunderGraph applications can now use structured logging with well defined semantics

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-06-05 11:47 UTC, StarpTech requested changes

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.test.ts
> +describe.only('Logger', () => {
Remove `only`

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.test.ts
> +	test('log string and object', async () => {
Great test setup

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.test.ts
> +		}).toMatch(`{"level":10,"msg":"trace"}`);
Can we work with trace level as a string rather than a number that is hard to understand from outside.

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.ts
> +	child: <T extends LogObject>(bindings: T) => RequestLogger;
I also thought about it a bit, and I agree it's a great feature to expose.

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.ts
> +		const pinoMsg = msg.replace('%', '%%');
Should we inform the user that he should use `levelf` functions instead? Should we introduce them now?

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.ts
> +	child<T extends LogObject>(bindings: T): RequestLogger {
I think `withFields` is much more apparent to users.

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.test.ts
> +		expectLog((logger) => {
What happens in the following cases:

1. Pass Error as the first argument. Are props, and stacks correctly attached? `logger.error('oh', new Error())`

2023-06-05 11:47 UTC, StarpTech commented on packages/sdk/src/server/logger.ts
> +	error?: Error;
Please add some docs here too.

2023-06-05 12:35 UTC, fiam commented on packages/sdk/src/server/logger.test.ts
> +		expectLog((logger) => {
Pino does interprets it as an error if either it's in the `errorKey` argument of it's the whole object is an `Error`, see the docs here https://github.com/pinojs/pino/blob/master/docs/api.md#mergingobject - I'm adding a test to ensure it works.

2023-06-05 12:46 UTC, StarpTech commented on packages/sdk/src/server/logger.test.ts
> +		expectLog((logger) => {
Great

2023-06-05 12:58 UTC, fiam commented on packages/sdk/src/server/logger.ts
> +	child<T extends LogObject>(bindings: T): RequestLogger {
I've renamed it

2023-06-05 12:59 UTC, fiam commented on packages/sdk/src/server/logger.test.ts
> +describe.only('Logger', () => {
Removed

2023-06-05 14:43 UTC, StarpTech commented on testapps/default/.wundergraph/webhooks/github.ts
> +		context.log.info('headers', event.headers);
Should we provide an overload (passing an object as first arg) to be handy in such cases? `msg` would be empty if not specified. WDYT?

2023-06-05 14:45 UTC, StarpTech commented on testapps/default/.wundergraph/webhooks/github.ts
> +		context.log.info('headers', event.headers);
or `log.info({ msg: '', ...rest })`

2023-06-05 14:48 UTC, StarpTech commented on testapps/default/.wundergraph/webhooks/github.ts
> +		context.log.info('headers', event.headers);
I revoke :smiley_cat:

2023-06-06 07:57 UTC, StarpTech commented on docs-website/src/pages/docs/guides/logging.md
> +This means every logging function accepts a `string` as a first argument, optionally followed
> This means every logging function accepts a `string` as a first argument which represent the log message, optionally...

2023-06-06 11:25 UTC, fiam commented on docs-website/src/pages/docs/guides/logging.md
> +WunderGraph includes built-in support for structured logging, using the `RequestLogger`
Isn't that redundant? All user defined code is ran in the context of the WunderGraph server

2023-06-06 11:30 UTC, fiam commented on docs-website/src/pages/docs/guides/logging.md
> +it will be interpreted as an error to be unwrapped, logging its message and stack too.
Added

2023-06-06 11:30 UTC, fiam commented on docs-website/src/pages/docs/guides/logging.md
> +This means every logging function accepts a `string` as a first argument, optionally followed
Reworded

2023-06-06 12:35 UTC, StarpTech approved these changes
LGTM

2023-06-06 13:15 UTC, Aenimus approved these changes

2023-06-06 14:42 UTC, merged