feat: pass internal requests from ORM into GraphQLHandler
wundergraph/wundergraph pull request #1049
Opened 2023-06-06 11:20 UTC by fiam

- When the ORM receives a clientRequest, pass it as part of the query
in __wg.clientRequest
- In GraphQLHandler, decode __wg.clientRequest when serving internal
requests

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-06-06 13:53 UTC, Pagebakers commented on packages/sdk/src/server/plugins/functions.ts
> +							graph: orm.withRawClientRequest(clientRequest),
Seems a bit of an odd ball that. we pass the orm from the fastify config instead of initializing here?

2023-06-07 11:33 UTC, fiam commented on packages/sdk/src/server/plugins/functions.ts
> +							graph: orm.withRawClientRequest(clientRequest),
It's because of the conditional initialization with the experimental flag

2023-06-07 15:02 UTC, Pagebakers commented on packages/sdk/src/server/plugins/functions.ts
> +							graph: orm.withRawClientRequest(clientRequest),
Got it!

2023-06-07 15:05 UTC, Pagebakers requested changes
I'd add one more test where you use setExtraHeaders on the client and also use withHeaders in a ts operation.

2023-06-08 07:32 UTC, Pagebakers approved these changes
Great!

2023-06-08 07:36 UTC, jensneuse approved these changes

2023-06-08 07:38 UTC, merged