feat: unify authentication mechanisms, redirect back with errors
wundergraph/wundergraph pull request #1059
Opened 2023-06-10 08:23 UTC by fiam

- Unify OIDC and GH authentication moving the common parts into an OAuth2
authentication handler, which also allows us to easily add more mechanism
in the future.

- Handle authentication errors by redirecting to redirect_uri with some
parameters signaling the error added.

To be followed up with frontend improvements to handle these errors

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-06-14 19:28 UTC, fiam commented on packages/sdk/src/client/client.ts
> +				throw new ResponseError({ code, message, statusCode: 401 });
@jensneuse We could use the new `NoUserError` here once #1063 is merged

2023-06-15 08:57 UTC, jensneuse requested changes

2023-06-15 09:47 UTC, fiam commented on packages/sdk/src/client/client.ts
> +	private handleAuthenticationError() {
Sounds good to me, let’s await for @Pagebakers’ feedback

2023-07-27 14:56 UTC, Pagebakers requested changes

2023-07-27 14:56 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +		this.handleAuthenticationError();
Don't think this should be here, should not call this automatically in the client, but let this be handled in the client implementations like @jensneuse suggested. In that case it could perhaps also have an option callback function that can be called.

2023-07-27 15:07 UTC, Pagebakers approved these changes

2023-07-27 15:17 UTC, fiam commented on packages/sdk/src/client/client.ts
> +				throw new ResponseError({ code, message, statusCode: 401 });
Changed to `NoUserError`

2023-07-28 13:47 UTC, jensneuse approved these changes

2023-07-28 14:07 UTC, merged