fix: produce JSONPatch patches with removals in the right order
wundergraph/wundergraph pull request #1060
Opened 2023-06-12 13:04 UTC by fiam

Add a small wrapper around github.com/mattbaird/jsonpatch which fixes
the removal order by sorting consecutive remove operations

## Motivation and Context

This caused a problem every time a live query deleted multiple entries at the end
of the list at the same time.

## Marketing Changelog

Live Queries now work with bulk deletions

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-06-13 06:56 UTC, jensneuse commented
Would it not make sense to fork the upstream, provide a fix, and use our fork until it's merged?

2023-06-13 14:07 UTC, fiam commented
> Would it not make sense to fork the upstream, provide a fix, and use our fork until it's merged? I think someone mentioned it already: [mattbaird/jsonpatch#30](https://github.com/mattbaird/jsonpatch/issues/30)
> 
> So we can open a PR and help them improve their lib.

As discussed, we've added integration tests and replaced the library with another one.

2023-06-15 10:50 UTC, StarpTech requested changes

2023-06-15 10:50 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +				if (!(e instanceof Error) || !e.message.indexOf('aborted')) {
Could you add a comment for which case this is required? AbortController?

2023-06-15 11:06 UTC, StarpTech approved these changes
LGTM

2023-06-21 10:20 UTC, JivusAyrus approved these changes

2023-06-21 10:21 UTC, devsergiy approved these changes

2023-06-21 10:30 UTC, merged