perf: improve config generation/loading performance
wundergraph/wundergraph pull request #1070
Opened 2023-06-14 16:14 UTC by fiam

- Use structuredCopy to copy values when available
- Use protocol buffers as a serialization format
- Use string references for storing database prisma/graphql schemas

- Reduces generation time (on M1) from ~3.8s to ~2.9s in apps/basic => -900ms, -28%
- Reduces config size from ~25MB to ~1.8MB in apps/basic => -23.2MB, -92.8%
- Reduces config loading time (on M1) from 110ms to 7ms => -103ms, -93.7%)

Fixes #1020

## Motivation and Context

Large schemas are slow to generate/load, so we're improving them bit by bit

## Marketing Changelog

Code generation time reduced by 30%, startup time improved by several seconds with
large schemas.

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-06-15 07:47 UTC, jensneuse requested changes

2023-06-15 07:47 UTC, jensneuse commented on cli/commands/root.go
> +	serializedConfigFilename = "wundergraph.config.wg"
How about using `.buf` to indicate that the content of the file is a protobuf?

2023-06-15 07:47 UTC, jensneuse commented on packages/sdk/src/codegen/templates/typescript/helpers.ts
> +	const copy = deepClone(application);
Is it actually necessary to make such a copy?

2023-06-15 07:51 UTC, fiam commented on cli/commands/root.go
> +	serializedConfigFilename = "wundergraph.config.wg"
According to one of the creators of PB, it is better to make it application specific because you do need the schema to be able to decode it https://groups.google.com/g/protobuf/c/JWZx9n8CUvw/m/bwvQWPL70Y8J - No strong feelings, though, if you'd prefer `.buf` or `.pb` (or anything else) that's fine by me.

2023-06-15 07:54 UTC, fiam commented on packages/sdk/src/codegen/templates/typescript/helpers.ts
> +	const copy = deepClone(application);
It didn't seem necessary to me, but I thought I might be missing something. I'll take a look and I'll see if we can get rid of the copy.

2023-06-15 07:54 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	return `string://${key}`;
Good idea, I'll change it.

2023-06-15 07:59 UTC, jensneuse commented on cli/commands/root.go
> +	serializedConfigFilename = "wundergraph.config.wg"
That makes sense. If we follow this rule, we could name it e.g. `config.wundergraphconfig`, or `file.wgconfig`, because we will also need to find a different name for operations, like `OperationName.wgoperation`. Any good ideas?

2023-06-15 08:10 UTC, devsergiy commented on pkg/engineconfigloader/engineconfigloader.go
> +			graphqlSchema, err := l.LoadStoredString(engineConfig, in.CustomDatabase.GraphqlSchema)
are we using this only for prisma? could we do the same for the graphql datasource for the upstream schema?

2023-06-15 10:43 UTC, fiam commented on packages/sdk/src/codegen/templates/typescript/helpers.ts
> +	const copy = deepClone(application);
It is necessary because the idea behind that function is to obtain a `ResolvedApplication` that includes only the TS operations and can be passed to https://github.com/wundergraph/wundergraph/blob/b7a0fc604d54f1711ae68ace29242eab46a2b668/packages/sdk/src/codegen/templates/typescript/helpers.ts#L30 (which filters based on operation type)

2023-06-15 10:44 UTC, fiam commented on cli/commands/root.go
> +	serializedConfigFilename = "wundergraph.config.wg"
I've renamed it

2023-06-15 10:44 UTC, fiam commented on pkg/engineconfigloader/engineconfigloader.go
> +			graphqlSchema, err := l.LoadStoredString(engineConfig, in.CustomDatabase.GraphqlSchema)
Your wish is my command, PTAL

2023-06-15 10:45 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	return `string://${key}`;
I've added an `InternedString` that stores the references, PTAL

2023-06-15 15:16 UTC, devsergiy approved these changes

2023-06-16 10:16 UTC, jensneuse approved these changes

2023-06-16 10:17 UTC, merged