feat: add grpc datasource support
wundergraph/wundergraph pull request #109
Opened 2022-08-02 11:41 UTC by spetrunin

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-08-05 08:35 UTC, jensneuse commented
@spetrunin can you please add intructions to default test app README on how to start the dev grpc service

2022-08-05 09:01 UTC, jensneuse requested changes

2022-08-08 09:08 UTC, StarpTech requested changes
Only small points except for the insecure grpc connection. Great overall PR :+1:

2022-08-08 09:08 UTC, StarpTech commented on pkg/datasources/grpc/planner.go
> +		grpc.WithTransportCredentials(insecure.NewCredentials()),
I think this must be configurable or secure by default.

2022-08-08 09:09 UTC, StarpTech commented on pkg/datasources/grpc/planner.go
> +		grpc.WithTransportCredentials(insecure.NewCredentials()),
Would also be fine to me to address that in a separate PR:

2022-09-26 00:30 UTC, closed without merging