feat: initial support for license management and generation
wundergraph/wundergraph pull request #1108
Opened 2023-07-05 20:26 UTC by fiam

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-07-17 12:44 UTC, Pagebakers requested changes

2023-07-17 12:44 UTC, Pagebakers commented on pkg/features/features.go
> +	return true
Seems like all features are enterprise now?

2023-07-17 12:46 UTC, fiam commented on pkg/features/features.go
> +	return true
Accidentally committed a change meant for testing locally, it should be good now. Thanks for the heads up!

2023-07-18 09:07 UTC, Pagebakers approved these changes

2023-07-18 10:47 UTC, jensneuse approved these changes

2023-07-18 13:28 UTC, merged