feat: unify pretty logs
wundergraph/wundergraph pull request #1139
Opened 2023-07-19 15:09 UTC by fiam

- Make the Node side always emit JSON logs, prettify them in the node
- Make wunderctl start not use pretty logging by default
- Cleanup code for passing around whether logs should be prettified
- Use a more human-readable format for pretty logs
- Unify colors for levels across both sides of the SDK

Fixes ENG-3334

## Motivation and Context

More friendly logs improve the developer experience by making it easier to debug your WG application

## Marketing Changelog

Pretty logging is now even prettier with a more human readable format

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-07-20 08:12 UTC, StarpTech requested changes

2023-07-20 08:12 UTC, StarpTech commented on cli/commands/root.go
> +func workaroundBugWithDuplicatedFlags(cmd *cobra.Command) {
Could you explain again why you need this?

2023-07-20 08:12 UTC, StarpTech commented on packages/sdk/src/logger/index.ts
> -	if (enablePretty) {
That means wundergraph server prettify their logs through wundergraph? That implicit that the server can't run standalone in pretty log mode. I'm ok with it.

2023-07-20 08:12 UTC, StarpTech commented on pkg/logging/pretty_encoder.go
> +		// If prettifying fails, return the raw log line
Please add tests here as well

2023-07-20 08:12 UTC, StarpTech commented on pkg/scriptrunner/scriptrunner.go
> +				fmt.Fprintln(options.stdout, line)
Did you consider in your change that the script runner is a generic module that is used to execute any kind of command?

2023-07-20 12:27 UTC, fiam commented on cli/commands/root.go
> +func workaroundBugWithDuplicatedFlags(cmd *cobra.Command) {
It's because the `pretty-logging` flag has different values for the global flag (defaults to `false`) vs the `wunderctl up` flag (defaults to `true`). This is not really supported by cobra/viper so we have do to some fixups to make it work.

2023-07-20 12:29 UTC, fiam commented on packages/sdk/src/logger/index.ts
> -	if (enablePretty) {
That's right. I went for this design because it allows us to have a single prettifier implementation and it also reduces startup time for the server since we no longer import `pino-pretty`. The only downside is that the server on its own can't prettify logs, but I thought that was a reasonable tradeoff.

2023-07-20 15:44 UTC, Pagebakers approved these changes
A small step for man, a huge leap for mankind

2023-07-20 16:02 UTC, StarpTech commented on cli/commands/root.go
> +func workaroundBugWithDuplicatedFlags(cmd *cobra.Command) {
ok, I just find it hard to understand why it was necessary.

2023-07-20 16:02 UTC, StarpTech commented on packages/sdk/src/logger/index.ts
> -	if (enablePretty) {
ok

2023-07-20 21:57 UTC, fiam commented on pkg/logging/prettifier.go
> +	o := orderedmap.New()
I've added tests for the prettifier

2023-07-20 22:00 UTC, fiam commented on pkg/logging/pretty_encoder.go
> +		// If prettifying fails, return the raw log line
Do you mean tests for `prettyEncoder`? Most of the functionality is in `Prettifier` while `prettyEncoder` is a very small Encoder for zap, so I'm not sure how we should test it. Could you clarify what you have in mind? Thanks!

2023-07-20 22:22 UTC, fiam commented on pkg/scriptrunner/scriptrunner.go
> +				fmt.Fprintln(options.stdout, line)
I did. By default, it will print to stdout/stderr, but the new API allows you to redirect its outputs (e.g. to discard them for the TUI) as well as to set a pipe function that rewrites each line before it gets outputted.

2023-07-21 08:13 UTC, StarpTech commented on pkg/logging/pretty_encoder.go
> +		// If prettifying fails, return the raw log line
Fine for me. It was important to have some coverage.

2023-07-21 08:13 UTC, StarpTech approved these changes
LGTM

2023-07-21 08:19 UTC, merged