fix: allow setting logging levels from command line
wundergraph/wundergraph pull request #1141
Opened 2023-07-21 13:46 UTC by fiam

- Make the command line flag propagate correctly to the TS side
- Correctly update the logging level when the config is parsed
- Introduce a TRACE level for the TS side (zap doesn't support it)

Fixes ENG-3335
Fixes ENG-3357

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-07-23 19:03 UTC, bitcoinfinancier approved these changes

2023-08-01 09:39 UTC, jensneuse approved these changes

2023-08-03 13:02 UTC, Pagebakers requested changes
We need to update the docs to reflect the changed options.

2023-08-03 13:14 UTC, Pagebakers approved these changes

2023-08-21 15:19 UTC, merged