perf: make wunderctl faster, add a few more trace log messages
wundergraph/wundergraph pull request #1294
Opened 2023-09-28 13:44 UTC by fiam

- Avoid using objectHash() on the whole application object. It gets
slow when there are many operations. Use an md5 of its JSON representation
which should be good enough for our purposes (generating a different URL
when the config caches)
- Avoid generating the same templates twice, use an in-memory cache during
generation
- Remove a few unneccesary copies performed during code generation
- Avoid double calculations

Fixes ENG-4045

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-09-28 13:47 UTC, Aenimus approved these changes

2023-09-29 10:33 UTC, StarpTech requested changes

2023-09-29 10:33 UTC, StarpTech commented on packages/nextjs/src/template.ts
> +			applicationHash: configurationHash(config),
This is a dangerous change. Object-hash respects all kinds of data types. Are you sure we cover all cases with just a hash?

2023-09-29 13:31 UTC, StarpTech approved these changes
LGTM

2023-09-29 13:31 UTC, StarpTech commented on packages/nextjs/src/template.ts
> +			applicationHash: configurationHash(config),
Clarified internally

2023-10-03 10:24 UTC, merged