fix: s3 upload client
wundergraph/wundergraph pull request #139
Opened 2022-08-24 17:09 UTC by YuriBuerov

Bug description
------
 - It's impossible to upload small files, like the ssh public key in my case. 
 - It's impossible to upload files when the boundary prefix is followed by a double dash, space, tab, cr, nl, or end of input. 
 
In both these cases, EOF error returned within the response.  This is not correct, EOF should not be treated as an error in this case. 

There are a few issues with the existing implementation: 

```golang
contentTypeBuff := make([]byte, 512) // too much
_, err := part.Read(contentTypeBuff)
if err != nil {
        // io.EOF error should be handled  
	return nil, err
}
filetype := http.DetectContentType(contentTypeBuff) 
recycled := io.MultiReader(bytes.NewReader(contentTypeBuff), part)
```

```multipart.Part``` ```Read```  reads the body of a part, after its headers (!), and could return EOF.  Which is not handled, but if it would be handled like: ```if err != io.EOF { return nil, err }```  uploaded data could be corrupted (first case in bug description) because of preallocated bytes in ```contentTypeBuff```,  and it will not be possible to detect the correct content type. 

Solution
------

 - ```multipart.Part``` comes with prepopulated headers, in most cases, it should be enough to get content type.
 -  if we couldn't find the content type based on the file header, try based on the extension
 -  additionally, I removed the extra step with temp file creation, which makes upload a bit faster. 

TODO:
 - tests?
  

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-08-24 18:22 UTC, StarpTech requested changes
Hi @YuriBuerov thank you for opening a PR :100: I have left some comments.

2022-08-24 18:22 UTC, StarpTech commented on pkg/s3uploadclient/s3uploadclient.go
> +	if t := mime.TypeByExtension(extension); t != "" {
We can get rid of this when we use `FPutObject` from the minio client library. See https://github.com/minio/minio-go/blob/174b4c070788c7c1eed4ba4bf6d5497198aaf2e6/api-put-object-file-context.go#L58-L62

2022-08-25 15:20 UTC, YuriBuerov commented on pkg/s3uploadclient/s3uploadclient.go
> +	body, err := io.ReadAll(part)
@StarpTech Thanks for your comments. I do agree that ```ReadAll``` is not efficient, in the case of large files, supposing that ```MaxUploadSize``` will become configurable someday.  Good point, I missed this. At the same time temporary file creation and multiple ```io.Copy()``` calls could be quite costly as well. Copy does not take out all the data at one time (which is a big advantage compared to ```ReaadAll```), but keeps reading and writing. 

What if we pass ```part *multipart.Ppart``` directly to minio client?  Streaming approach, without extra steps, fast, and less code. We will not be able to precalculate size, but minio can do this for us if we pass -1 as the size parameter. 

The only drawback is that in this case, we lose de-dup feature ```filename := hex.EncodeToString(hasher.Sum(nil)) + extension```, which prevents uploading the same file twice and could save some storage space, but it still updates the existing file even if the content was not changed. 

What do you think? The only alternative I see is using ```FPutObject``` as you've suggested and keeping temp file creation.

2022-08-25 16:06 UTC, StarpTech commented on pkg/s3uploadclient/s3uploadclient.go
> +	body, err := io.ReadAll(part)
I'd always favor reliability over performance when performance is still good. Passing `-1` will according to https://github.com/minio/minio-go/blob/master/docs/API.md#putobjectctx-contextcontext-bucketname-objectname-string-reader-ioreader-objectsize-int64opts-putobjectoptions-info-uploadinfo-err-error consume a lot of memory. The de-dup feature is pretty important for space efficiency. I suggest `FPutObject`.

2022-08-26 13:35 UTC, YuriBuerov commented
@StarpTech I implemented tests, using docker. Would you like me to push tests as well? If so, I will have to make some changes. 

There are 3 options:
- run docker in tests using dockertest (may be slow on ci?)
- wrap minio client to be able to mock it
- pass transport within ```Options``` to ```NewS3UploadClient``` and rewrite it in tests

2022-08-26 14:20 UTC, StarpTech commented
Hi @YuriBuerov I like the idea of an simple integration test. What do you think about using minio image with Github CI service containers https://docs.github.com/en/actions/using-containerized-services/about-service-containers#creating-service-containers? Locally, we could boostrap minio with a simple script like https://github.com/wundergraph/wundergraph/blob/main/packages/nextjs-testapp/minio/setup.sh? I think this works well enough before we pull a library like dockertest into the codebase.

2022-08-27 15:01 UTC, StarpTech requested changes

2022-08-27 15:01 UTC, StarpTech commented on .github/workflows/engine-ci.yaml
> +      - run: wget https://dl.min.io/client/mc/release/linux-amd64/mc
Please put it in a script so it can be reproduced locally.

2022-08-27 18:35 UTC, StarpTech requested changes

2022-08-27 18:35 UTC, StarpTech commented on pkg/s3uploadclient/s3uploadclient_test.go
> +func initClient() *s3uploadclient.S3UploadClient {
Could you put the test helper in a separate file? This makes reading the test cases easier. Ideally, you can put the testdata under fixtures directory.

2022-08-28 10:37 UTC, YuriBuerov commented on pkg/s3uploadclient/s3uploadclient_test.go
> +func initClient() *s3uploadclient.S3UploadClient {
@StarpTech Would it be better to put testdata.go under a ```testdata``` directory so the build will ignore it? Either put a json file under  ```fixtures``` directory and open this file in the test.

2022-08-28 11:29 UTC, StarpTech commented on pkg/s3uploadclient/s3uploadclient_test.go
> +func initClient() *s3uploadclient.S3UploadClient {
Sounds good! I like the `testdata` idea.

2022-08-28 13:48 UTC, StarpTech requested changes

2022-08-28 13:48 UTC, StarpTech commented on scripts/minio-setup.sh
> +chmod +x ./scripts/mc
I think you need to add "mc" binary to .gitignore?

2022-08-28 13:48 UTC, StarpTech commented on scripts/minio-setup.sh
> +if [[ "$OSTYPE" == "linux-gnu"* ]]; then
Can we check if the binary exists to avoid redownloading it?

2022-08-28 14:13 UTC, YuriBuerov commented on scripts/minio-setup.sh
> +chmod +x ./scripts/mc
The script deletes it at the end

2022-08-28 14:14 UTC, YuriBuerov commented on scripts/minio-setup.sh
> +if [[ "$OSTYPE" == "linux-gnu"* ]]; then
Do you mean redownloading if we rerun ci?

2022-08-28 14:31 UTC, StarpTech commented on scripts/minio-setup.sh
> +if [[ "$OSTYPE" == "linux-gnu"* ]]; then
I mean if you have already installed it locally. I think for CI this is negotiable.

2022-08-28 14:32 UTC, StarpTech commented on scripts/minio-setup.sh
> +chmod +x ./scripts/mc
I'd still add it because when one command fails the binary is not deleted.

2022-08-28 14:33 UTC, StarpTech commented on scripts/minio-setup.sh
> +
Always add `set -e`

2022-08-28 16:40 UTC, StarpTech approved these changes
LGTM

2022-08-28 16:45 UTC, StarpTech commented
@YuriBuerov ready to merge?

2022-08-29 10:41 UTC, YuriBuerov commented
> @YuriBuerov ready to merge?

@StarpTech Ready

2022-08-29 10:51 UTC, merged