Sergey/eng 302 Use config as a source for listeners and urls
wundergraph/wundergraph pull request #151
Opened 2022-08-30 17:43 UTC by spetrunin

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-07 17:03 UTC, StarpTech requested changes

2022-09-07 17:03 UTC, StarpTech commented on packages/sdk/src/middleware/server.ts
> +		logger.level = config.api.serverOptions.logger.level;
This should be loaded from the config as well.

2022-09-07 17:04 UTC, StarpTech commented on cli/commands/up.go
> +		killExistingHooksProcess(9992)
As discussed: Load the value from the config after the config was generated and try to kill the server before we start the new one.

2022-09-07 17:05 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +		options.logger.level = new EnvironmentVariable(WgEnv.LogLevel, 'WARNING');
As discussed: We should also ensure that the user can't define an invalid Log Level.

```ts
export interface ServerLogger {
	level?: InputVariable<PinoLogLevel>;
}
```

2022-09-08 15:03 UTC, StarpTech requested changes

2022-09-08 15:03 UTC, StarpTech commented on packages/sdk/src/middleware/server.ts
>  		process.exit(1);
This is not necessary after fatal.

2022-09-08 16:53 UTC, StarpTech requested changes

2022-09-08 16:53 UTC, StarpTech commented on cli/commands/up.go
> +					if err == nil {
I'd exit the process here when the config is corrupt.

2022-09-08 18:57 UTC, StarpTech requested changes

2022-09-08 18:57 UTC, StarpTech commented on cli/commands/up.go
> +						log.Info("could not read server port from config file", abstractlogger.String("configFile", configJsonPath))
Could you use fatal? :smile:

2022-09-08 18:57 UTC, StarpTech commented on packages/sdk/src/middleware/server.ts
> -		process.exit(1);
This is a bit confusing. The logger does not exit the process on `fatal`. `process.exit` is still required.

2022-09-09 09:08 UTC, StarpTech requested changes

2022-09-09 09:08 UTC, StarpTech commented on cli/commands/node.go
> +			WG_SECRET=secret WG_SERVER_URL=http://127.0.0.1:9992 WG_NODE_ADDR=127.0.0.1:9991 wunderctl node start
Does it need to be updated?

2022-09-09 09:08 UTC, StarpTech commented on cli/commands/node.go
> +	nodeCmd.AddCommand(nodeStartCmd)
Can we document the `WG_*` with cobra?

2022-09-09 09:08 UTC, StarpTech commented on cli/commands/node.go
> +	RunE: func(cmd *cobra.Command, args []string) error {
Remove?

2022-09-09 09:08 UTC, StarpTech commented on cli/commands/node.go
> +	nodeCmd.AddCommand(nodeStartCmd)
Can we also add the `--cloud` to the cobra interface?

2022-09-09 15:41 UTC, StarpTech requested changes

2022-09-09 15:41 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +			if (nodeUrl.charAt(nodeUrl.length - 1) == '/') {
This can be done with
```go
p = strings.TrimSuffix(p, "/")
```

2022-09-09 15:41 UTC, StarpTech commented on packages/sdk/src/postman/builder.ts
> +// TS types of these modules are so bad, I opt out!
:smiley:

2022-09-09 15:49 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +			if (nodeUrl.charAt(nodeUrl.length - 1) == '/') {
Do we also have to do this with serverUrl in the node?

2022-09-09 16:01 UTC, spetrunin commented on packages/sdk/src/configure/index.ts
> +			if (nodeUrl.charAt(nodeUrl.length - 1) == '/') {
yep, it is already done in the node

2022-09-09 18:34 UTC, StarpTech requested changes

2022-09-09 18:34 UTC, StarpTech commented on .github/actions/node/action.yaml
> +      uses: abelfodil/protoc-action@v1
Why did you change that? The action seems unmaintained.

2022-09-09 18:45 UTC, spetrunin commented on .github/actions/node/action.yaml
> +      uses: abelfodil/protoc-action@v1
`arduino/setup-protoc` is too opinionated about checking version correctness and it could not download the latest version due to its internal checks 
here is issue about that https://github.com/arduino/setup-protoc/issues/33 which is not fixed for 3 months already

`abelfodil/protoc-action` - is not doing such checks, but is still enough to install the release version - the only thing that you have to specify a correct released version
but proto has not changed release files naming convention, they changed only  versions convention

So until `arduino/setup-protoc` will fix the issue we could have properly running CI and no conflicts between team members `protoc` version

2022-09-09 21:44 UTC, StarpTech commented on .github/actions/node/action.yaml
> +      uses: abelfodil/protoc-action@v1
Can't we just isntall via bash command? https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os

2022-09-13 08:51 UTC, StarpTech requested changes
Great PR. I left some comments to improve the docs.

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/architecture/wundergraph-conventions.md
> +| `WG_LOG_LEVEL`   | The log level of the `WunderNode`/`WunderGraph Server`. | `info`                  |
Could you also name some other log levels?

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/architecture/wundergraph-conventions.md
> +import { WgEnv } from '@wundergraph/sdk'
From my understanding, we always fall back into those environment variables when the user hasn't defined something. Why do we need to expose them via SDK?

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/components-of-wundergraph/wundernode-wundergraph-server.md
> +WunderGraph Server - is optinal fastify based server. It is responsible for processing `hooks` and running `Custom GraphQL Servers`.
`optinal` typo? I wouldn't name such internals. It doesn't matter if it is fastify or anything else.

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-generate.md
> +When you are generating your production config please make sure that you have provided all the necessary environment variables:
This sounds like it is required but we will fallback to defaults.

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-node-start.md
> +The cmd `wunderctl node start` stars WunderNode in the production mode.
`starts`

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-node-start.md
> +When you are running node in production make sure that mandatory environment variables are provided:
Same here.

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-server-start.md
> +When you are running node in production make sure that mandatory environment variables are provided:
Same here.

2022-09-13 08:51 UTC, StarpTech commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-start.md
> +The cmd `wunderctl start` starts WunderNode and WunderGraph Server.
Could you explain a bit further that this command is the "production" variant of `wunderctl up`?

2022-09-13 08:51 UTC, StarpTech commented on docs/migrations/wunderctl-0.106.3-0.107.0.md
> +- `wundergraph.config.json` to be present in the `.wundegraph` directory.
I'd remove this and only explain that `wunderctl node start or server start` can only be run after generating. That the required files are generated is an internal detail.

2022-09-13 08:51 UTC, StarpTech commented
Please consider this as well https://wundergraph.slack.com/archives/C03PE1KU073/p1663058726485299

2022-09-13 09:09 UTC, StarpTech commented
Please ensure that an error is thrown when a required environment variable wasn't set when generating the config.

2022-09-13 09:57 UTC, StarpTech requested changes

2022-09-13 09:57 UTC, StarpTech commented on cli/commands/node.go
> +		configFile := path.Join(wgDir, "generated", "wundergraph.config.json")
Could you use the constant here?

2022-09-13 09:57 UTC, StarpTech commented on cli/commands/up.go
> +						helpers.KillExistingHooksProcess(port, log)
This should only be called once before we launch the command. https://github.com/wundergraph/wundergraph/blob/f220c823f94122ac826996844b632a55173a3209/cli/commands/up.go#L57

2022-09-13 09:57 UTC, StarpTech commented on cli/commands/up.go
> +					if newPort, err := helpers.ServerPortFromConfig(configJsonPath); err != nil {
The whole kill section is not needed. The line `<-hookServerRunner.Run(ctx)` will restart the server.

2022-09-13 10:00 UTC, StarpTech commented
In that case, the server config is not used on the node:

```ts
// wundergraph.server.ts
	options: {
		listen: {
			port: '4009',
		},
	},
```

`wunderctl up --debug`

I use the `default-testapp`.

```
http://127.0.0.1:9991/app/main/operations/JSP
```

The server still tries to make a request against `9992`

```
2022-09-13T11:59:19+02:00       debug   hook request call       {"attempt": 0, "url": "http://localhost:9992/global/httpTransport/onOriginRequest"}

```

2022-09-13 10:02 UTC, StarpTech commented
When I run `wunderctl server start --debug` the server is not properly exited when I sent SIGINT. The process is still alive. See `lsof -i tcp:9992` after exiting the process. I'd also expect a graceful shutdown because it's a production command.

2022-09-13 11:48 UTC, YuriBuerov commented on cli/commands/node.go
> +			log.Fatal("Config file is empty", abstractlogger.String("filePath", configFile), abstractlogger.Error(err))
`abstractlogger.Error(err)` but the error will be nil

2022-09-13 12:42 UTC, spetrunin commented on cli/commands/up.go
> +						helpers.KillExistingHooksProcess(port, log)
you could change a port in a config during UP command is running

2022-09-13 12:44 UTC, StarpTech commented on cli/commands/node.go
> +			log.Fatal("Failed to unmarshal", abstractlogger.String("filePath", configFile), abstractlogger.Error(err))
Good question and worth checking. According to https://pkg.go.dev/github.com/pkg/errors#hdr-Retrieving_the_stack_trace_of_an_error_or_wrapper is already wrapped, but I'm not sure if the logging implementation takes care of it. Please create an issue for that. It could be part of our refactoring of unified logging in general.

2022-09-13 12:46 UTC, StarpTech commented on cli/commands/up.go
> +						helpers.KillExistingHooksProcess(port, log)
I thought the server is restarted after the config change.

2022-09-13 12:48 UTC, spetrunin commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-node-start.md
> +The cmd `wunderctl node start` stars WunderNode in the production mode.
fixed

2022-09-13 12:53 UTC, spetrunin commented on docs-website/src/pages/docs/architecture/wundergraph-conventions.md
> +| `WG_LOG_LEVEL`   | The log level of the `WunderNode`/`WunderGraph Server`. | `info`                  |
added a list of log levels as next section

2022-09-13 12:53 UTC, spetrunin commented on docs-website/src/pages/docs/components-of-wundergraph/wundernode-wundergraph-server.md
> +WunderGraph Server - is optinal fastify based server. It is responsible for processing `hooks` and running `Custom GraphQL Servers`.
fixed

2022-09-13 12:54 UTC, spetrunin commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-generate.md
> +When you are generating your production config please make sure that you have provided all the necessary environment variables:
seems to be fixed

2022-09-13 12:55 UTC, spetrunin commented on docs-website/src/pages/docs/wunderctl-reference/wunderctl-start.md
> +The cmd `wunderctl start` starts WunderNode and WunderGraph Server.
up or start?

2022-09-13 13:01 UTC, spetrunin commented on cli/commands/up.go
> +					if newPort, err := helpers.ServerPortFromConfig(configJsonPath); err != nil {
done

2022-09-13 13:03 UTC, spetrunin commented on cli/commands/node.go
> +			log.Fatal("Config file is empty", abstractlogger.String("filePath", configFile), abstractlogger.Error(err))
fixed

2022-09-13 13:04 UTC, spetrunin commented on docs-website/src/pages/docs/architecture/wundergraph-conventions.md
> +import { WgEnv } from '@wundergraph/sdk'
maybe someone will want to use WG env vars but supply other defaults
also it serves like an additional documentation for the SDK

2022-09-13 13:35 UTC, spetrunin commented
@StarpTech 
```
When I run wunderctl server start --debug the server is not properly exited when I sent SIGINT. The process is still alive. See lsof -i tcp:9992 after exiting the process. I'd also expect a graceful shutdown because it's a production command.
```

this one is fixed

2022-09-13 14:06 UTC, spetrunin commented on docs/migrations/wunderctl-0.106.3-0.107.0.md
> +# Migration steps from wunderctl 0.106.3 to 0.107.0
@StarpTech should the file be called 0.107.0 -> 0.108.0?

2022-09-13 15:06 UTC, YuriBuerov commented on cli/helpers/process.go
> +	data, _ := ioutil.ReadFile(configJsonPath)
`ioutil` is deprecated, now it's `os.ReadFile`. Why are you ignoring an error? `data` could be `nil` and you will get a weird error: `unexpected end of JSON input` (line 25)

2022-09-13 15:09 UTC, YuriBuerov commented on cli/helpers/process.go
> +		if err != nil {
I didn't get it:
```
if err := cmd.Run(); err != nil {
		if err != nil {
```

2022-09-13 15:29 UTC, YuriBuerov commented on pkg/apihandler/apitransport.go
> +		primaryHost := fmt.Sprintf("%s:%d", t.api.Options.Listener.Host, t.api.Options.Listener.Port)
minor, just a suggestion. maybe it's worth it to create a helper, to avoid duplication (apihandler.go:594)

2022-09-13 15:58 UTC, YuriBuerov commented on pkg/engineconfigloader/engineconfigloader.go
> +	return strings.TrimSuffix(baseUrl, "/") + "/" + strings.TrimPrefix(path, "/")
maybe just a personal preference but I would use `fmt.Sprintf` or even strings builder for multiple concatenations

2022-09-13 16:24 UTC, StarpTech commented on cli/helpers/process.go
> +		if err != nil {
Double safe mode :smile:

2022-09-13 18:23 UTC, YuriBuerov commented on pkg/node/node.go
> +		err = nil
Maybe you can avoid using this hack if you remove `var err error` from the top of this method and change `err := n.server.Serve(l)` (line 392 or 395)

2022-09-13 18:24 UTC, YuriBuerov commented on pkg/node/node.go
> +			err = n.server.Serve(l)
`err := n.server.Serve(l)`

2022-09-13 23:30 UTC, StarpTech commented on docs-website/src/pages/docs/architecture/wundergraph-conventions.md
> +import { WgEnv } from '@wundergraph/sdk'
Alright

2022-09-14 19:08 UTC, StarpTech requested changes

2022-09-14 19:08 UTC, StarpTech commented on cli/commands/server.go
> +		if enableDebugMode {
In production, we never kill a running process. This can be an indication of a bad state.

2022-09-14 19:08 UTC, StarpTech commented on cli/commands/server.go
> +		if enableDebugMode {
We only kill in `wunderctl up`

2022-09-14 19:10 UTC, StarpTech commented
I can still reproduce the issue

```
// packages/default-testapp/.wundergraph/wundergraph.server.ts
	options: {
		listen: {
			port: '4000',
		},
	},
```

After regenerating the config there should be no `9992` in `packages/default-testapp/.wundergraph/generated/wundergraph.config.json`

2022-09-14 19:44 UTC, spetrunin commented
@StarpTech something is not in sync on your end

![image](https://user-images.githubusercontent.com/818351/190247628-12f9688e-5ee6-4cdf-948e-a788197e3819.png)

2022-09-14 20:46 UTC, StarpTech commented
Never mind, I forgot to bootstrap the whole monorepo :innocent: I will test tomorrow in depth.

2022-09-19 09:32 UTC, jensneuse commented on docs-website/README.md
> +Here's an example that directly adds a link, don't do it like this:
@spetrunin can you please fix the docs to comply with this rule?
It was not yet written down, sorry.

2022-09-19 09:33 UTC, jensneuse commented
@spetrunin I've tested this PR. Looks fine.
Please fix the merge conflicts and solve the docs issue (tagging).
After that, I'll have another look at the docs and we can release it.

2022-09-19 15:30 UTC, jensneuse commented
@spetrunin please update to master, I'll go through the docs this evening. If everything else is fine with @StarpTech, we can merge once I'm finished with the docs.

2022-09-19 15:54 UTC, StarpTech approved these changes
LGTM

2022-09-19 16:00 UTC, merged