feat(node): implement api config validation for cookie-based auth
wundergraph/wundergraph pull request #160
Opened 2022-09-02 14:00 UTC by jensneuse

This PR adds API config validation which detects wrong config for cookie-based auth configs.

2022-09-02 14:19 UTC, StarpTech requested changes

2022-09-02 14:19 UTC, StarpTech commented on packages/sdk/CHANGELOG.md
> -* implement userId for fromClaim directive ([#152](https://github.com/wundergraph/wundergraph/issues/152)) ([51df6e5](https://github.com/wundergraph/wundergraph/commit/51df6e50244bee9f5f8d579ff6f604e
Why is it changed? This is auto generated.

2022-09-02 14:19 UTC, StarpTech commented on pkg/node/node.go
> +			os.Exit(1)
or use `log.fatal`? I think this ensures that the log buffer is printed before the process dies.

2022-09-02 14:19 UTC, StarpTech commented on pkg/node/node.go
> +		valid, messages = validate.DefaultApiConfig(api, validate.ApiConfigValidationConfig{})
Why do we need to call the validator twice? This is confusing to me.

2022-09-02 14:19 UTC, StarpTech commented on pkg/validate/apiconfig.go
> +	api      *wgpb.Api
Is it really necessary that the validator has to know the `*wgpb.Api` object? The validator only needs to know: What is a valid value for a cookie secret / csrf.

```go
err := Validate(a.api.AuthenticationConfig.CookieBased.CsrfSecret, Validate.CookieCSRF)
err := Validate(a.api.AuthenticationConfig.CookieBased.BlockKey, Validate.CookieSecret)
```

I think this is easier to write and maintain.

2022-09-02 14:25 UTC, jensneuse commented on packages/sdk/CHANGELOG.md
> -* implement userId for fromClaim directive ([#152](https://github.com/wundergraph/wundergraph/issues/152)) ([51df6e5](https://github.com/wundergraph/wundergraph/commit/51df6e50244bee9f5f8d579ff6f604e
I don't know

2022-09-02 14:25 UTC, jensneuse commented on pkg/node/node.go
> +		valid, messages = validate.DefaultApiConfig(api, validate.ApiConfigValidationConfig{})
the comment says it

2022-09-02 14:28 UTC, jensneuse commented on pkg/validate/apiconfig.go
> +	api      *wgpb.Api
subjective

2022-09-02 17:00 UTC, jensneuse commented on pkg/validate/apiconfig.go
> +	api      *wgpb.Api
I've investigated a few other solutions. The issue remains that somewhere needs to sit the mapping.
I'll abandon the idea of improving the code at this point.
If you'd like to refactor it, ok.

2022-09-02 17:00 UTC, jensneuse commented on packages/sdk/CHANGELOG.md
> -* implement userId for fromClaim directive ([#152](https://github.com/wundergraph/wundergraph/issues/152)) ([51df6e5](https://github.com/wundergraph/wundergraph/commit/51df6e50244bee9f5f8d579ff6f604e
fixed

2022-09-03 10:47 UTC, StarpTech commented on pkg/validate/apiconfig.go
> +		// skip following tests if cookie auth is not enabled
If you put this here, we can only validate `AuthenticationConfig` settings, but `ApiConfig` is a place to validate the whole config.

2022-09-03 12:52 UTC, jensneuse commented on pkg/validate/apiconfig.go
> +		// skip following tests if cookie auth is not enabled
For each rule, we should call one function which can return early. Currently, with just one rule, it's fine.

2022-09-03 17:29 UTC, StarpTech commented on pkg/validate/apiconfig.go
> +		// skip following tests if cookie auth is not enabled
ok

2022-09-05 07:21 UTC, merged