docs: added MongoDB and FaunaDB Datasources
wundergraph/wundergraph pull request #165
Opened 2022-09-05 10:57 UTC by Slickstef11

#### Checklist

- [X] run `make test`
- [X] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-05 11:58 UTC, StarpTech requested changes

2022-09-05 11:58 UTC, StarpTech commented on docs-website/src/pages/docs/supported-data-sources/mongodb-atlas.md
> +### Injecting Claims
This part is already covered in auth section and isn't specific to mongodb.

2022-09-05 11:59 UTC, StarpTech commented on docs-website/src/pages/docs/supported-data-sources/mongodb-atlas.md
> +### Injecting Claims
In my opinion, this section should only inform about the compatibility and reference a full example.

2022-09-05 13:39 UTC, Slickstef11 commented on docs-website/src/pages/docs/supported-data-sources/mongodb-atlas.md
> +### Injecting Claims
@StarpTech Do we have a full example? I know we have a PR for one. Has it been reviewed?

2022-09-05 13:47 UTC, StarpTech commented on docs-website/src/pages/docs/supported-data-sources/mongodb-atlas.md
> +### Injecting Claims
Not yet :cry:

2022-09-06 17:56 UTC, jensneuse requested changes

2022-09-06 17:56 UTC, jensneuse commented on docs-website/src/pages/docs/supported-data-sources/mongodb-atlas.md
> +Combined with a SQLite Database, you're able to easily build Realtime Applications like a Chat.
if you do copy pasta, do it right :D

2022-09-08 21:25 UTC, closed without merging