feat: add golang client
wundergraph/wundergraph pull request #170
Opened 2022-09-07 12:58 UTC by jensneuse

2022-09-07 17:29 UTC, StarpTech requested changes

2022-09-07 17:29 UTC, StarpTech commented on packages/default-testapp/.wundergraph/wundergraph.server.ts
> +				/*onOriginResponse: {
Please enable it before merging.

2022-09-07 17:29 UTC, StarpTech commented on packages/default-testapp/.wundergraph/wundergraph.server.ts
> -						request.headers.set('X-Wundergraph-Test', 'test');
Please enable it before merging.

2022-09-07 17:29 UTC, StarpTech commented on packages/default-testapp/golang/client/client.go
> +type Queries struct {
Should we generate an interface for easier mocking?

2022-09-07 17:29 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +		console.error(e);
This can be quite annoying and confusing because most people arent go users. I would make it silent.

2022-09-07 17:29 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +const gofmt = (code: string) => {
Nice.

2022-09-07 17:29 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +		const formatter = execa.sync('gofmt', {
Can we make it part of the SDK? it would be great to have it consistent. This also validates the AST right?

2022-09-07 17:29 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +type GraphQLError struct {
Do we really need to put this here? Can't we import it as a static go file?

2022-09-07 17:29 UTC, StarpTech commented on packages/sdk/src/index.ts
> +export { visitJSONSchema } from './codegen/index';
I don't like the fact that we expose internals to the user. I'd love to have a separate export only intended for plugin development.

2022-09-07 17:46 UTC, jensneuse commented on packages/golang-client/src/index.ts
> +const gofmt = (code: string) => {
lol

2022-09-07 17:48 UTC, jensneuse commented on packages/sdk/src/index.ts
> +export { visitJSONSchema } from './codegen/index';
can you contribute a better solution?

2022-09-07 17:49 UTC, jensneuse commented on packages/golang-client/src/index.ts
> +type GraphQLError struct {
It's easier to maintain this way and I'm not expecting it to change.

2022-09-07 17:51 UTC, jensneuse commented on packages/golang-client/src/index.ts
> +		const formatter = execa.sync('gofmt', {
Do you think we're going to use it anywhere else?

2022-09-07 17:54 UTC, jensneuse commented on packages/default-testapp/golang/client/client.go
> +type Queries struct {
Isn't this a concern of the user?

2022-09-07 17:54 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +		const formatter = execa.sync('gofmt', {
Probably not, but also in the SDK we follow the approach to putting static code into code files to benefit from all language tools/validation etc...

2022-09-07 17:54 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +const gofmt = (code: string) => {
rofl

2022-09-07 17:56 UTC, jensneuse commented on packages/golang-client/src/index.ts
> +		console.error(e);
What exactly will be annoying? If you're not a go user, you don't add the go template to your code.
I can make it silent, but then we don't see why formatting failed. wdyt?

2022-09-07 18:35 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +		console.error(e);
You're right. Then I would throw a more meaningful error like: "Formatting failed. Did you install gofmt?"

2022-09-07 18:36 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +		console.error(e);
But it feels weird that the user has to install tooling to format code that he will never touch :smile:

2022-09-07 20:16 UTC, jensneuse commented on packages/golang-client/src/index.ts
> +		console.error(e);
Assuming you use go, because you're generating go code, you should have go installed, no? :D

2022-09-08 08:57 UTC, StarpTech commented on packages/default-testapp/golang/client/client.go
> +type Queries struct {
No, otherwise the user has to update its interface every time a new operation is added.

2022-09-08 08:58 UTC, StarpTech commented on packages/sdk/src/index.ts
> +export { visitJSONSchema } from './codegen/index';
Yes

2022-09-09 07:02 UTC, jensneuse commented on packages/golang-client/src/index.ts
> +		const formatter = execa.sync('gofmt', {
I've made it silent

2022-09-09 08:41 UTC, StarpTech approved these changes
LGTM

2022-09-09 09:51 UTC, merged