feat: make typescript client typesafe
wundergraph/wundergraph pull request #179
Opened 2022-09-13 14:39 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-14 13:53 UTC, Pagebakers commented
The pure TypeScript client now accepts an `Operation` type that defines all operations with input and data types to make all operation methods typesafe.

Adding `TypeScriptClientTemplate` to a project will generate the `Operation` types and a `createClient` function.

Added an example with Vite and SWR in `package/vite-testapp`

2022-09-14 16:16 UTC, StarpTech requested changes

2022-09-14 16:16 UTC, StarpTech commented on packages/nextjs-testapp/pages/authentication.tsx
> +					<p>{JSON.stringify(liveWeather.result.data.getCityByName?.coord)}</p>
Why is it still required to access `getCityByName` when there is only one prop in response?

2022-09-14 16:16 UTC, StarpTech commented on packages/vite-testapp/src/hooks/swr.ts
> +			const result = await client.mutate({
Here too: This doesn't look as designed.

2022-09-14 16:30 UTC, Pagebakers commented on packages/nextjs-testapp/pages/authentication.tsx
> +					<p>{JSON.stringify(liveWeather.result.data.getCityByName?.coord)}</p>
I didn't change the nextjs interface in this PR.

2022-09-14 16:30 UTC, Pagebakers commented on packages/nextjs-testapp/pages/authentication.tsx
> +					<p>{JSON.stringify(liveWeather.result.data.getCityByName?.coord)}</p>
I didn't change the nextjs interface in this PR.

2022-09-14 16:31 UTC, Pagebakers commented on packages/vite-testapp/src/hooks/swr.ts
> +			{ ...key, abortSignal: abort.signal } as unknown as SubscriptionProps<
Yeah if you have ideas, since these hooks are only used for testing and no official release I didn't want to spent any more time on it for now.

2022-09-14 16:33 UTC, Pagebakers commented on packages/sdk/src/codegen/templates/typescript/react.ts
> +// export const hasInjectedInput = (op: GraphQLOperation): boolean =>
Oh forgot this!

2022-09-14 16:34 UTC, Pagebakers commented on packages/vite-testapp/src/hooks/swr.ts
> +			if (result.status === 'ok') {
How should we handle that here? just throw the error?

2022-09-14 16:36 UTC, Pagebakers commented on packages/vite-testapp/src/hooks/swr.ts
> +			const result = await client.mutate({
Doesn't look as as designed?

2022-09-14 18:50 UTC, StarpTech requested changes

2022-09-14 18:50 UTC, StarpTech commented on packages/vite-testapp/src/App.tsx
> +					<h3>City: {liveWeather.data.getCityByName?.name}</h3>
No I mean 

```ts
const { data } = useSubscription()
data.name
```

2022-09-14 18:50 UTC, StarpTech commented on packages/vite-testapp/src/hooks/swr.ts
> +			const result = await client.mutate({
I mean this PR is about type safety, but this example has type conversions.

2022-09-14 18:50 UTC, StarpTech commented on packages/vite-testapp/src/hooks/swr.ts
> +			if (result.status === 'ok') {
Same semantics as in SWR.
```ts
const { data, error } = useMutation()
```

> The returned value will be passed as data, and if it throws, it will be caught as error.

2022-09-14 18:50 UTC, StarpTech commented on packages/vite-testapp/src/hooks/swr.ts
> +			if (result.status === 'ok') {
There should be no "partial" state

2022-09-14 18:50 UTC, StarpTech commented on packages/vite-testapp/src/hooks/swr.ts
> +			{ ...key, abortSignal: abort.signal } as unknown as SubscriptionProps<
If this PR isn't about type safety then I don't understand the scope of this PR. The example represents the final SWR client, isn't it?

2022-09-15 06:55 UTC, jensneuse commented on packages/vite-testapp/src/App.tsx
> +					<h3>City: {liveWeather.data.getCityByName?.name}</h3>
`getCityByName` is the root field of the Query, it cannot be omitted. An operation can have multiple root fields, therefore you must include them.

2022-09-15 08:59 UTC, StarpTech commented on packages/vite-testapp/src/App.tsx
> +					<h3>City: {liveWeather.data.getCityByName?.name}</h3>
ah, you're right! I had the operation -> single root field image in my mind :face_with_spiral_eyes:

2022-09-15 13:49 UTC, jensneuse approved these changes

2022-09-15 13:49 UTC, jensneuse commented on packages/vite-testapp/src/hooks/swr.ts
> +		if (isLiveQuery && enabled) {
Is it possible to move this outside of the effect and just use plain js?
Otherwise, all useQuery calls will have this effect, right?

2022-09-15 16:40 UTC, Pagebakers commented on packages/vite-testapp/src/hooks/swr.ts
> +		if (isLiveQuery && enabled) {
I thought about it, but otherwise we cannot cleanup the subscription if components get unmounted. Since it's a hook we cannot make the entire statement conditional.

the useEffect wont' do anything if it's not a liveQuery, so it does not add much overhead.

2022-09-16 08:35 UTC, StarpTech requested changes

2022-09-16 08:35 UTC, StarpTech commented on packages/sdk/src/client/index.ts
>  					cb(this.errorResult(response));
This currently swallows the original error. https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/client/index.ts#L314

The should be able to access the original error.

2022-09-16 09:11 UTC, StarpTech commented on packages/sdk/src/client/index.ts
>  					cb(this.errorResult(response));
This is a bit more complicated. `errorResult` is fine because it only executes for requests with statusCode != `200` so we are talking about gateway errors. The issue with this implementation is that the client maps statusCodes to gateway errors. We should just pass the gateway error to the client.

2022-09-16 11:32 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
>  					cb(this.errorResult(response));
This issue existed already in the client. I would say we create another issue to improve this, so we can ship the improved types.

2022-09-16 12:04 UTC, StarpTech commented on packages/sdk/src/client/index.ts
>  					cb(this.errorResult(response));
ok

2022-09-19 16:52 UTC, merged