chore: switch baseURL to be string
wundergraph/wundergraph pull request #187
Opened 2022-09-16 11:53 UTC by jensneuse

2022-09-16 12:04 UTC, StarpTech requested changes

2022-09-16 12:04 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +	baseUrl: string;
baseURL is required now?

2022-09-16 16:09 UTC, jensneuse commented on packages/protobuf/wgpb/wundernode_config.ts
> +	baseUrl: string;
No

2022-09-16 18:09 UTC, StarpTech approved these changes
LGTM

2022-09-17 11:59 UTC, jensneuse commented on packages/protobuf/wgpb/wundernode_config.ts
> +	baseUrl: string;
In the generated config, it can be empty string. In the user submitted config, it can be optional (undefined).

2022-09-17 12:38 UTC, merged