Feat/add post logout hook
wundergraph/wundergraph pull request #196
Opened 2022-09-20 13:50 UTC by jensneuse

This hook allows you to take actions, e.g. call APIs/DBs, when the user logged out.
Example use case: Use 3rd party API to end session.

2022-09-20 13:58 UTC, StarpTech requested changes
Looks good expect one minor thing.

2022-09-20 13:58 UTC, StarpTech commented on packages/sdk/src/middleware/plugins/hooks.ts
> +		reply.type('application/json').code(200);
This is incorrect. If the user is not set the endpoint can't be called. We should return non-2xx. E.g 400 (bad request and only 200 after postLogout). This would also make our metrics in the future wrong.

2022-09-20 13:59 UTC, jensneuse commented on packages/sdk/src/middleware/plugins/hooks.ts
> +		reply.type('application/json').code(200);
it's copy pasta from the other endpoints, are they wrong as well?

2022-09-20 14:19 UTC, YuriBuerov commented on pkg/authentication/authentication.go
> +	if !logoutOpenIDConnectProvider {
```
if !r.URL.Query().Has("logout_openid_connect_provider") {}
```

2022-09-20 14:22 UTC, jensneuse commented on pkg/authentication/authentication.go
> +	if !logoutOpenIDConnectProvider {
fails for "logout_openid_connect_provider=false"

2022-09-20 14:30 UTC, StarpTech commented on packages/sdk/src/middleware/plugins/hooks.ts
> +		reply.type('application/json').code(200);
This

```ts
	fastify.post('/authentication/postLogout', async (request, reply) => {
		if (!config.authentication?.postLogout || !request.ctx.user) {
			return reply.code(400)
		}
			try {
				const out = await config.authentication.postLogout(request.ctx);
				return reply.type('application/json').code(200).send({
					hook: 'mutatingPostAuthentication',
					response: out,
					setClientRequestHeaders: headersToObject(request.ctx.clientRequest.headers),
				})
			} catch (err) {
				request.log.error(err);
				return reply.code(500).send( { hook: 'mutatingPostAuthentication', error: err });
			}
	});
```

2022-09-20 14:39 UTC, YuriBuerov commented on pkg/authentication/authentication.go
> +	if !logoutOpenIDConnectProvider {
Btw, you can use existence for boolean parameter like ?logout_openid_connect_provider

like elasticsearch: `GET _cat/master?v` 

for example https://go.dev/play/p/wOysiK2j5gz

this way you don't need  param=true

2022-09-20 15:10 UTC, StarpTech commented on pkg/authentication/authentication.go
> +	if !logoutOpenIDConnectProvider {
But still ?x=false is interpreted as true.

2022-09-20 15:14 UTC, YuriBuerov commented on pkg/authentication/authentication.go
> +	if !logoutOpenIDConnectProvider {
yes, but the idea is to get rid of `?x=false` or `?x=true`  and have just `?x` which is valid URL param. if it's present - for us it's true, if not - false.

2022-09-20 15:16 UTC, YuriBuerov commented on pkg/authentication/authentication.go
> +	if !logoutOpenIDConnectProvider {
like in docs I linked above:
```
GET _cat/<operation_name>?h=<header_name_1>,<header_name_2>&v
Typically, for any operation you can find out what headers are available using the ?help parameter, and then use the ?h parameter to limit the output to only the headers that you care about.
```

2022-09-21 06:29 UTC, jensneuse commented on pkg/authentication/authentication.go
> +	if !logoutOpenIDConnectProvider {
I'm 100% sure that we always strip nullable args, so flag=false will not be the case anywhere. I think it's safe to make this change.

2022-09-21 06:51 UTC, jensneuse commented on packages/sdk/src/middleware/plugins/hooks.ts
> +		reply.type('application/json').code(200);
as we discussed, will be fixed in another PR

2022-09-21 07:22 UTC, merged