fix(sdk): add fastify route only if the hook is configured
wundergraph/wundergraph pull request #204
Opened 2022-09-21 18:24 UTC by JivusAyrus

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-21 18:26 UTC, jensneuse commented
Please always make sure to merge main into your PR branch.

2022-09-21 19:20 UTC, jensneuse commented
@JivusAyrus how can we verify that hooks still work? we should somehow test this. Ideas?

2022-09-21 20:03 UTC, JivusAyrus commented
Used postman to check if only the hooks which are used have the fastify routes and made sure that is the case.
To check if they are working appropriately, should we use the hooks in the test app and verify?

2022-09-21 20:10 UTC, StarpTech requested changes

2022-09-21 20:10 UTC, StarpTech commented on packages/sdk/src/middleware/plugins/hooks.ts
> +			reply.type('application/json');
This is set automatically when we return json.

2022-09-21 20:10 UTC, StarpTech commented on packages/sdk/src/middleware/plugins/hooks.ts
> +				reply.code(400);
I recommend the chained syntax

```ts
reply.code(400).send({ hook: 'mutatingPostAuthentication', error: "User context doesn't exist" })
```

2022-09-21 20:10 UTC, StarpTech commented on packages/sdk/src/middleware/plugins/hooks.ts
> +			if (request.ctx.user === undefined) {
To avoid repetition, we could move this part into a [pre-handler](https://www.fastify.io/docs/latest/Reference/Hooks/#prehandler). 

You could archive that very easy with fastify [encapsulation](https://www.fastify.io/docs/latest/Reference/Encapsulation/) concept:

```ts
childServer.register(async function grandchildContext (fastify) {
	fastify.addHook('preHandler', (request, reply, done) => {
 	 	// validate user
  		done()
	})

	// register the hooks routes
})
```

2022-09-21 20:16 UTC, StarpTech commented
> To check if they are working appropriately, should we use the hooks in the test app and verify?

Ideally, we set up a simple test with fastify inject feature. https://www.fastify.io/docs/latest/Guides/Testing/#testing-with-http-injection

We have already created a server factory for that https://github.com/wundergraph/wundergraph/blob/suvij/eng-402-dont-add-fastify-route-when-route-isnt/packages/sdk/src/middleware/server.ts#L126

2022-09-22 10:33 UTC, JivusAyrus commented on packages/sdk/src/middleware/plugins/hooks.ts
> +			reply.type('application/json');
Removed reply.type().

2022-09-22 10:34 UTC, JivusAyrus commented on packages/sdk/src/middleware/plugins/hooks.ts
> +			if (request.ctx.user === undefined) {
Used preHandler and fixed it in the latest commit.

2022-09-22 10:45 UTC, JivusAyrus commented on packages/sdk/src/middleware/plugins/hooks.ts
> +				reply.code(400);
Done. Used chained syntax

2022-09-23 09:53 UTC, JivusAyrus commented
> > To check if they are working appropriately, should we use the hooks in the test app and verify?
> 
> Ideally, we set up a simple test with fastify inject feature. https://www.fastify.io/docs/latest/Guides/Testing/#testing-with-http-injection
> 
> We have already created a server factory for that https://github.com/wundergraph/wundergraph/blob/suvij/eng-402-dont-add-fastify-route-when-route-isnt/packages/sdk/src/middleware/server.ts#L126

I wrote tests to verify the working of the routes, verify if the routes have user context check and verify if only the hooks used have the routes configured.

2022-09-26 11:59 UTC, StarpTech commented on packages/sdk/src/middleware/server.ts
> +		fastify.addHook<{ Body: FastifyRequestBody }>('preHandler', async (req, reply) => {
In the future, I'd like to keep this file very thin and move middleware, handlers into different files with a test file.

2022-09-26 12:01 UTC, StarpTech requested changes

2022-09-26 12:01 UTC, StarpTech commented on packages/sdk/src/middleware/plugins/hooks.test.ts
> +	expect(postLogoutResponse.statusCode).toEqual(200);
We should also expect the response payload.

2022-09-29 14:29 UTC, JivusAyrus commented
Have tested the hooks using the test apps(default and nextjs) manually.

2022-10-04 08:29 UTC, StarpTech approved these changes
LGTM

2022-10-05 08:26 UTC, merged