Sergey/eng 409 we need a way to configure the public
wundergraph/wundergraph pull request #207
Opened 2022-09-23 12:18 UTC by spetrunin

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-25 10:18 UTC, jensneuse approved these changes

2022-09-25 10:28 UTC, StarpTech requested changes

2022-09-25 10:28 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> -			nodeUrl = nodeUrl.endsWith('/') ? nodeUrl.slice(0, -1) : nodeUrl;
Could you put this in a helper fn?

2022-09-25 10:28 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +	const fallbackPublicNodeUrl = options?.listen?.port
Why is the `port` significant for the condition? I'd say the whole URL is relevant.

2022-09-26 16:15 UTC, StarpTech requested changes

2022-09-26 16:15 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +					new EnvironmentVariable(WgEnv.PublicNodeUrl, fallbackUrl(defaultNodePort, options?.listen)),
Shouldn't it be?

```ts
const nodeUrl = options?.nodeUrl || new EnvironmentVariable(WgEnv.NodeUrl, fallbackUrl(defaultNodePort, options?.listen))
const publicNodeUrl = options?.publicNodeUrl || nodeUrl,
```

2022-09-26 16:18 UTC, spetrunin commented on packages/sdk/src/configure/options.ts
> +					new EnvironmentVariable(WgEnv.PublicNodeUrl, fallbackUrl(defaultNodePort, options?.listen)),
than potentially it will share the same env var, which is not desired I believe

2022-09-26 16:19 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +					new EnvironmentVariable(WgEnv.PublicNodeUrl, fallbackUrl(defaultNodePort, options?.listen)),
Make sense, thanks.

2022-09-26 16:20 UTC, StarpTech approved these changes
LGTM

2022-09-26 16:22 UTC, merged

2022-09-26 16:22 UTC, StarpTech requested changes

2022-09-26 16:22 UTC, StarpTech commented on pkg/node/node.go
> +		abstractlogger.String("nodeUrl", nodeConfig.Api.Options.PublicNodeUrl),
Does it make sense to print here a URL that is not controlled by the node?