fix: remove invalid hasDotWunderGraphDirectory option
wundergraph/wundergraph pull request #211
Opened 2022-09-24 21:06 UTC by StarpTech

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-25 10:14 UTC, jensneuse commented
So, this code is correct and we could merge it.
However, I think that the real problem is that we don't know in which directory the user installed `.wundergraph`.
Is the WunderGraph dir in the root of a project, or are we in a monorepo and have some nesting?

For VSCode it's crucial that the `.graphqlconfig` sits at the root of the project. Otherwise, IntelliSense won't work.
Ideally, we could configure an absolute or relative path where the `.graphqlconfig` should be generated and updated.

2022-09-26 16:45 UTC, jensneuse requested changes

2022-09-26 16:45 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphqlconfig.md
> +This `.graphqlconfig` file is very important for WunderGraph to work.
Updated proposal:

This `.graphqlconfig` file is very important for an ideal developer experience.
IDEs like VSCode and Jetbrains recognise the file and use it to configure IntelliSense.
It's important to place it in the right directory.
E.g. in VSCode, it's important that you place it at the root of the project.
With the `.graphqlconfig` properly configured, your IDE helps you to define GraphQL Operations.

2022-09-26 19:25 UTC, StarpTech commented
> Ideally, we could configure an absolute or relative path where the .graphqlconfig should be generated and updated.

I tried this already, but it's not that easy to do because you user can only specify a relative path.

Example:

```ts
configureWunderGraphApplication({
  dotGraphQLConfig: {
    disable: true,
	path: '../../.graphqlconfig'
  },
})
```

How should we calculate the schema path? We would need to calculate the target directory and search for the nearest `.wundergraph` directory.

2022-10-05 09:04 UTC, jensneuse commented
@StarpTech update from main+merge or discard?

2022-10-28 15:42 UTC, bmcilw1 commented
> So, this code is correct and we could merge it. However, I think that the real problem is that we don't know in which directory the user installed `.wundergraph`. Is the WunderGraph dir in the root of a project, or are we in a monorepo and have some nesting?
> 
> For VSCode it's crucial that the `.graphqlconfig` sits at the root of the project. Otherwise, IntelliSense won't work. Ideally, we could configure an absolute or relative path where the `.graphqlconfig` should be generated and updated.

Can both of these challenges be addressed by setting an ENV var on the startup of the CLI? I believe both VSCode plugins and the running CLI process could reference an ENV var if set by something similar to #300

2023-01-18 08:11 UTC, jensneuse commented
@fiam what should we do with this? I think you were working on a similar issue.

2023-01-18 08:39 UTC, fiam commented
@jensneuse I think this one can be closed now, superseded by #537

2023-01-18 09:01 UTC, StarpTech commented
Yeah, let's close it.

2023-01-18 09:01 UTC, closed without merging