feat:  add graphql introspection middleware
wundergraph/wundergraph pull request #214
Opened 2022-09-26 17:32 UTC by spetrunin

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-26 17:42 UTC, jensneuse commented
Don't forget to update the docs

2022-09-27 12:28 UTC, StarpTech requested changes

2022-09-27 12:28 UTC, StarpTech commented on packages/sdk/src/definition/federation.ts
> +	if (requestMiddleware) {
I read the issue, but I'm still not convinced why we need to provide a middleware mechanism. Could you elaborate?

2022-09-27 12:28 UTC, StarpTech commented on packages/sdk/src/definition/index.ts
> +export type RequestMiddleware = (requestConfig: AxiosRequestConfig) => AxiosRequestConfig;
Axios is an implementation detail. In the future, we might switch the client. Don't expose the type to the user.

2022-09-27 13:01 UTC, spetrunin commented on packages/sdk/src/definition/index.ts
> +export type RequestMiddleware = (requestConfig: AxiosRequestConfig) => AxiosRequestConfig;
I need a detailed specification in this case - like what should be possible

2022-09-27 13:04 UTC, spetrunin commented on packages/sdk/src/definition/federation.ts
> +	if (requestMiddleware) {
At the moment there is only one way to authenticate an introspection request - add a StaticHeader 
but this means that such header will be used also for all requests

So we have a need in some way to provide various auth options for the introspection calls
open to any proposals

2022-09-27 13:04 UTC, jensneuse commented on packages/sdk/src/definition/index.ts
> +export type RequestMiddleware = (requestConfig: AxiosRequestConfig) => AxiosRequestConfig;
I actually think that at this moment, a function that takes the headers and allows us to override them should be enough.

2022-09-27 13:07 UTC, spetrunin commented on packages/sdk/src/definition/index.ts
> +export type RequestMiddleware = (requestConfig: AxiosRequestConfig) => AxiosRequestConfig;
could be there a basic auth?

2022-09-27 13:49 UTC, jensneuse commented on packages/sdk/src/definition/index.ts
> +export type RequestMiddleware = (requestConfig: AxiosRequestConfig) => AxiosRequestConfig;
yes, it's possible, but currently we don't have this use case
maybe you find a way to keep it flexible enough but keeping it simple?

2022-09-27 16:13 UTC, StarpTech commented on packages/sdk/src/definition/federation.ts
> +	if (requestMiddleware) {
What about?

```ts
const spacex = introspect.graphql({
	apiNamespace: 'spacex',
	url: 'https://api.spacex.land/graphql/',
	headers: (builder) => builder.addClientRequestHeader('X-Authorization', 'Authorization'),
	introspection: {
		headers: (builder) => builder.addClientRequestHeader('X-Authorization', 'Authorization'),
	}
});
```

My favorite API would look like this :smile: Exposing a builder or middleware is powerful but I see no reason to add this complexity here. It's also not simple to use.

```ts
const spacex = introspect.graphql({
	apiNamespace: 'spacex',
	url: 'https://api.spacex.land/graphql/',
	headers: [
		Headers.static('X-Authorization', 'Authorization'),
		Headers.client('X-Authorization', 'Authorization')],
	introspection: {
		headers: [
			Headers.static('X-Authorization', 'Authorization'),
			Headers.auth('username', 'password')],
	},
});
```

2022-09-29 07:49 UTC, jensneuse approved these changes
LGTM. I've only added a few minor changes in the docs.

2022-09-29 09:50 UTC, StarpTech requested changes

2022-09-29 09:50 UTC, StarpTech commented on docs-website/config/tags.js
> +		'/docs/wundergraph-config-ts-reference/configure-introspection#introspection-of-protected-graph-ql-ap-is',
`graph-ql`

2022-09-29 09:54 UTC, spetrunin commented on docs-website/config/tags.js
> +		'/docs/wundergraph-config-ts-reference/configure-introspection#introspection-of-protected-graph-ql-ap-is',
it is how nextjs generated an anchor from `## heading`

2022-09-29 09:55 UTC, spetrunin commented on docs-website/config/tags.js
> +		'/docs/wundergraph-config-ts-reference/configure-introspection#introspection-of-protected-graph-ql-ap-is',
https://github.com/wundergraph/wundergraph/pull/214/files#diff-a88d471cf72fc2ee1fffbe5d4cf67db38d8c45ffc3e5e702cfd9281a598361eeR81

header is here

2022-09-29 10:08 UTC, StarpTech approved these changes
Great work!

2022-09-29 10:29 UTC, merged