feat: sse subscriptions configuration
wundergraph/wundergraph pull request #217
Opened 2022-09-27 11:56 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-27 13:02 UTC, jensneuse requested changes

2022-09-27 13:02 UTC, jensneuse commented on packages/sdk/src/definition/index.ts
> +	useSSEForSubscription?: InputVariable;
as we've used the subscriptions prefix for URL, I'd suggest we call this `subscriptionsUseSSE`.

2022-09-27 13:02 UTC, jensneuse commented on packages/sdk/src/definition/index.ts
> +	useSSEForSubscription?: InputVariable;
this also means that you can use `true` instead of `"true"`.

2022-09-27 13:26 UTC, YuriBuerov commented on packages/sdk/src/definition/index.ts
> +	useSSEForSubscription?: InputVariable;
makes sense

2022-09-28 11:40 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +	useSSE: boolean;
nevermind, we use it :smile:

2022-09-29 06:22 UTC, jensneuse commented on packages/protobuf/wgpb/wundernode_config.ts
> +	useSSE: boolean;
https://www.youtube.com/watch?v=VnT7pT6zCcA

2022-09-29 06:27 UTC, jensneuse requested changes

2022-09-29 06:27 UTC, jensneuse commented on packages/sdk/src/definition/index.ts
> +	subscriptionUseSSE?: boolean;
should be plural ("subscriptions") because we're using plural for subscriptionsURL too

2022-09-29 06:27 UTC, jensneuse commented on pkg/apihandler/apitransport.go
> +	isStreamingRequest := request.Header.Get("Accept") == "text/event-stream"
we discussed that we don't have to check here, instead we set a config param on the transport when we create the "subscription" http client (see comment below)

2022-09-29 06:27 UTC, jensneuse commented on pkg/engineconfigloader/engineconfigloader.go
> +		Transport: transportFactory(baseTransport),
Here you should add a param to set this transport to "streaming" mode.
This way, you know in the transport without checking for the response headers (might vary) that the transport is used within the context of a streaming client.

2022-09-29 09:00 UTC, YuriBuerov commented on pkg/apihandler/apitransport.go
> +	isStreamingRequest := request.Header.Get("Accept") == "text/event-stream"
I do remember that we discussed it, but are there any other use cases for this config param apart from SSE? 
As for me, it looks consistent because this helper `isUpgradeRequest := websocket.IsWebSocketUpgrade(request)` also just checks headers. I'm ok if you want me to change this.

2022-09-29 10:10 UTC, StarpTech requested changes
LGTM, but I'm missing an example in the testapps and examples.

2022-09-29 10:29 UTC, YuriBuerov commented
@StarpTech  I'm going to add examples with docs for examples in the separate PR after release. Not sure about testapps though, I'm testing with the default test app,  do you want me to include it in this PR? (I'll need to add graphql servers, one for WS, and one for SSE respectively). All of this we will have in examples later.

2022-09-29 12:58 UTC, jensneuse approved these changes

2022-09-29 12:58 UTC, jensneuse commented
Changes LGTM.
Resolve conflicts an we can merge.

2022-09-29 13:23 UTC, merged

2022-09-30 07:20 UTC, StarpTech commented
@YuriBuerov is fine for me if we have at least one example to test it. @jensneuse please don't be so rushed with merging, I had open threads.