chore: examples, add subscription examples
wundergraph/wundergraph pull request #227
Opened 2022-09-30 17:03 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-09-30 18:02 UTC, StarpTech requested changes

2022-09-30 18:02 UTC, StarpTech commented on examples/graphql-sse-subscriptions/.wundergraph/wundergraph.config.ts
> +	subscriptionsUseSSE: true,
Wasnt it?

```ts
subscription: {
  useSSE: true
}
```

2022-09-30 18:02 UTC, StarpTech commented on examples/graphql-sse-subscriptions/.wundergraph/wundergraph.server.ts
> +	graphqlServers: [
Remove things that aren't necessary for the example. That makes our life easier to maintain it.

2022-09-30 18:08 UTC, YuriBuerov commented on examples/graphql-apollo-subscripptions/.wundergraph/wundergraph.config.ts
> +		enableGraphQLEndpoint: process.env.NODE_ENV !== 'production' || process.env.GITPOD_WORKSPACE_ID !== undefined,
yeah, missed it

2022-09-30 18:09 UTC, YuriBuerov commented on examples/graphql-sse-subscriptions/.wundergraph/wundergraph.config.ts
> +	subscriptionsUseSSE: true,
No, it wasn't. 
```
subscriptionsUseSSE
subscriptionsUrl
```

2022-10-07 19:16 UTC, StarpTech commented
Whats missing here?

2022-10-07 19:54 UTC, jensneuse commented
> Whats missing here?

non failing tests

2022-10-11 10:39 UTC, StarpTech commented
@YuriBuerov, how can we move forward?

2022-10-11 11:58 UTC, StarpTech approved these changes
LGTM

2022-10-11 12:01 UTC, merged