feat: add configurable per-source timeouts
wundergraph/wundergraph pull request #232
Opened 2022-10-05 07:44 UTC by fiam

- Add a new optional timeout field in HTTPUpstream
- Pass this new field to the node via FetchConfiguration, so it applies
  to all HTTP based sources
- In the server, create a dedicated http.Client with the specified
  timeout as needed

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-05 09:00 UTC, jensneuse commented
I think there should be a global default value we can pass to `configureWunderGraphApplication.options`.
Additionally, what's the behaviour for databases (Prisma).
We use an http client for prisma, too. We should also be able to configure timeouts there.

2022-10-07 08:07 UTC, StarpTech requested changes

2022-10-07 08:07 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
Can we call it `timeoutInMs`? Very often, I see "timeout" in libraries, and it's not obvious about the unit.

2022-10-07 08:07 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
Does `0` means unlimited?

2022-10-07 08:36 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
Definitely, that's a better idea. We have `pollingIntervalSeconds` somewhere else, though, so is `timeoutMilliseconds` better for consistency or would you prefer `timeoutMs` to save the user some typing?

2022-10-07 08:37 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
No, zero means the default, which can be specified globally per node, or left as the 10 seconds default.

2022-10-07 08:53 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
`timeoutMilliseconds` is good.

2022-10-07 08:53 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
Or why not use seconds too?

2022-10-07 08:55 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
That's confusing. I'd prefer `0` to be unlimited and the default is only used when no value has been set.

2022-10-07 10:06 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
I'd prefer to not have any means to set an unlimited timeout. Unlimited is an unintentional error 99% of the time, plus one can achieve the same result in practical (but quite explicit) terms setting it to a ridicuously high value.

2022-10-07 12:22 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
I have no strong opinion here. Both are fine to me. Setting a zero explicitly is an act but I also understand your point.

2022-10-07 14:08 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
I think I will change it to what you suggested. I feel a bit uneasy about not having a timeout, but maybe I'm being too paranoid. As you said, if they set it to zero manually without understanding the consequences, then it's their own fault.

2022-10-07 14:10 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
It's a timeout for all requests sent from the node when servicing that data source. We could introduce more granular timeouts (e.g. introspection, time to connect/first bytes, time for whole response), but it's non-trivial and a general timeout would probably work for most use cases.

2022-10-07 14:36 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
You have to explain why seconds are not granular enough :smile:

2022-10-07 14:47 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
Imagine this use case. Let's say I want to generate a response in less than 1 second (which is quite high already) and I have 2 data sources than can do the more or less the same thing, but one is richer than the other (e.g. gas prices on a given area: one gives me all stations, another one just one brand) but sometimes it takes too much time. If the richer source doesn't return any data in let's say 500ms, I'd rather query the other one and still present some data to the user. That's a use case that I think we should support, specially when it takes so little code on our side.

2022-10-07 14:52 UTC, StarpTech requested changes

2022-10-07 14:52 UTC, StarpTech commented on packages/sdk/src/definition/graphql-introspection.ts
> +					TimeoutMilliseconds: introspection.timeoutMilliseconds ?? -1,
What means `-1`?

2022-10-07 14:52 UTC, StarpTech commented on packages/sdk/src/definition/index.ts
> +	timeout?: number;
Why is it called "timeout" here?

2022-10-07 14:52 UTC, StarpTech commented on packages/sdk/src/definition/index.ts
> +	timeoutMilliseconds?: number;
I agree @jensneuse we should be clear about what this timeout means. What do you think about e.g.

```ts
const spacex = introspect.graphql({
	apiNamespace: 'spacex',
	url: 'https://api.spacex.land/graphql/',
    requestTimeoutMilliseconds: 5000
});
```

2022-10-07 14:55 UTC, fiam commented on packages/sdk/src/definition/graphql-introspection.ts
> +					TimeoutMilliseconds: introspection.timeoutMilliseconds ?? -1,
Any value <= 0 means "keep the default". That avoids having to represent a `null | undefined` on the Go side.

2022-10-07 14:55 UTC, fiam commented on packages/sdk/src/definition/index.ts
> +	timeout?: number;
Good catch. That's a leftover from the previous implementation. It's unused at this point and I need to delete it.

2022-10-07 15:04 UTC, fiam commented on packages/sdk/src/definition/index.ts
> +	timeoutMilliseconds?: number;
That definitely makes it more explicit, although a bit too long. I will change it.

2022-10-07 15:05 UTC, StarpTech commented on packages/sdk/src/definition/index.ts
> +	timeoutMilliseconds?: number;
or use a nested object but I have no idea about the name.

2022-10-07 15:09 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
But you can't ensure that your service will respond in exact 500ms. Everything can happen in between. From my experience, timeouts are chosen as generous.

2022-10-07 15:25 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
It depends on what your options are. If a timeout means all you can say is "Oooops, nothing for you to see here, please move along" then you will likely set it generously, because there's nothing else you can show if the upstream takes a long time. When you can have a fallback, you usually want to set it lower to still load your UI in a reasonable time.

2022-10-07 15:26 UTC, fiam commented on packages/sdk/src/definition/graphql-introspection.ts
> +					TimeoutMilliseconds: introspection.timeoutMilliseconds ?? -1,
I've reverted it

2022-10-07 15:26 UTC, fiam commented on packages/sdk/src/definition/index.ts
> +	timeoutMilliseconds?: number;
Changed to `requestTimeoutMilliseconds`

2022-10-07 15:34 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
There’s also a middle ground. We can make it take seconds and accept floats. The precision loss shouldn’t make any difference for this use case.

2022-10-07 16:10 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
We specifically talk about request timeout :smile:

2022-10-07 16:11 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
I just want to be consistent here. We have already "pollingIntervalSeconds" and I really don't see a reason to switch units.

2022-10-07 17:43 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
I agree that having different units is less than ideal, but I think the mistake is in `pollingIntervalSeconds` being an integer. A second is just not granular enough for a lot of things, that's why most tools/SDKs accept either milliseconds or decimal seconds. If you want us to use `requestTimeoutSeconds` with integers, we can do it, but let it be noted that I would strongly recommend against it.

2022-10-07 17:52 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
I don't understand your concern :smiley_cat:  Practically, polling an API isn't something where milliseconds matter. If you want to fetch every x second this is absolutely fine. The same goes for timeouts. There is no value in defining a request timeout with 2600ms instead 3s. It is an estimation of when a request is likely to be faulty.

2022-10-07 19:17 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
Seconds for timeouts and polling intervals is fine.

2022-10-07 20:01 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
I changed it to seconds in the last commit

2022-10-07 20:08 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-openapi-rest-data-source.md
> +  timeout: 10 * 1000, // in milliseconds, optional
:+1:

2022-10-07 21:18 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeoutMilliseconds: 10 * 1000, // optional
this needs an update

2022-10-07 21:19 UTC, StarpTech requested changes

2022-10-07 21:19 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphql-data-source.md
> +  timeoutMilliseconds: 10 * 1000, // optional
Should be "requestTimeoutSeconds"

2022-10-07 21:19 UTC, jensneuse requested changes
update readme

2022-10-07 21:23 UTC, jensneuse requested changes

2022-10-07 21:23 UTC, jensneuse commented on pkg/engineconfigloader/engineconfigloader.go
> +	if cfg != nil && cfg.MTLS != nil {
seems like config and mtls is checked twice

2022-10-07 21:23 UTC, jensneuse commented on pkg/engineconfigloader/engineconfigloader.go
> +			// XXX: Implement WithHTTPClient?
no

2022-10-07 21:45 UTC, StarpTech requested changes

2022-10-07 21:45 UTC, StarpTech commented on pkg/engineconfigloader/engineconfigloader.go
> +func (d *DefaultFactoryResolver) useCustomHTTPClient(ds *wgpb.DataSourceConfiguration, cfg *wgpb.FetchConfiguration) bool {
This can be a function and doesn't need to be a method. The prefix `use` doesn't really express a true/false return value.

2022-10-07 21:45 UTC, StarpTech commented on pkg/engineconfigloader/engineconfigloader.go
> +		if d.useCustomHTTPClient(ds, ds.CustomGraphql.Fetch) {
I think we can simplify this:

```go
// create a new client based on config etc...
client, err := d.newHTTPClient(ds, ds.CustomGraphql.Fetch)
if err != nil {
	return nil, err
}
d.graphql.HTTPClient = client
return d.graphql, nil
```

2022-10-07 21:47 UTC, StarpTech requested changes

2022-10-07 21:47 UTC, StarpTech commented on pkg/engineconfigloader/engineconfigloader.go
>  			return &graphql_datasource.Factory{
We forgot to pass all properties from the original factory to this one. My suggestion above will this is.

2022-10-08 20:20 UTC, fiam commented on pkg/engineconfigloader/engineconfigloader.go
> +func (d *DefaultFactoryResolver) useCustomHTTPClient(ds *wgpb.DataSourceConfiguration, cfg *wgpb.FetchConfiguration) bool {
I'd rather keep it as a method for namespacing. I had it named `shouldUseCustomHTTPClient` but then it felt a bit too Objective-C-y/Swift-y. I've changed it to `requiresCustomHTTPClient` which should convey the boolean nature of the function better.

2022-10-08 21:26 UTC, StarpTech commented on pkg/engineconfigloader/engineconfigloader.go
> +func (d *DefaultFactoryResolver) useCustomHTTPClient(ds *wgpb.DataSourceConfiguration, cfg *wgpb.FetchConfiguration) bool {
Sounds good. Thank you.

2022-10-10 13:26 UTC, fiam commented on pkg/engineconfigloader/engineconfigloader.go
> +	if cfg != nil && cfg.MTLS != nil {
I can't spot the other place where it gets checked. Could you please clarify where?

2022-10-10 13:28 UTC, fiam commented
> please update readme

I can't find any README files that mention timeouts. Could you please let me know which one specifically would you like me to update? Thanks!

2022-10-11 10:38 UTC, StarpTech commented
@fiam How did you test the implementation?

2022-10-11 10:40 UTC, fiam commented
> @fiam How did you test the implementation?

I configured sources from the test apps with 1ms timeouts and verified that the failed due to a deadline being exceeded. Then I did more or less the same for the global timeout.

2022-10-11 10:55 UTC, StarpTech commented
> I configured sources from the test apps with 1ms timeouts and verified that the failed due to a deadline being exceeded. Then I did more or less the same for the global timeout.

Thanks

2022-10-11 10:56 UTC, StarpTech requested changes

2022-10-11 10:56 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +	defaultRequestTimeoutSeconds: number;
Why is called here differently?

2022-10-11 20:29 UTC, fiam commented on packages/protobuf/wgpb/wundernode_config.ts
> +	defaultRequestTimeoutSeconds: number;
That one is the default for the whole node, for sources that don't have an explicit one.

2022-10-12 08:50 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +	defaultRequestTimeoutSeconds: number;
My point is why don't we call it `requestTimeoutSeconds` as well?

2022-10-12 09:49 UTC, fiam commented on packages/protobuf/wgpb/wundernode_config.ts
> +	defaultRequestTimeoutSeconds: number;
If you give them both the same name, I feel like it’s not immediately clear which one takes priority. Having one with the default prefix makes it more evident.

2022-10-12 13:02 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +	defaultRequestTimeoutSeconds: number;
Ah got it.

2022-10-13 06:36 UTC, jensneuse approved these changes

2022-10-13 06:36 UTC, jensneuse commented
amazing work!

2022-10-13 07:48 UTC, merged

2022-10-13 07:48 UTC, fiam commented
> amazing work!

Thanks to your and Dustin’s help!