chore: improve wunderctl build from Makefile
wundergraph/wundergraph pull request #233
Opened 2022-10-05 08:00 UTC by fiam

- Keep debug info, since it might be handy while developing
- Inject main.commit and main.date by spawing shell commands (they were
  previously set to empty variables)

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-06 09:04 UTC, StarpTech requested changes

2022-10-06 09:21 UTC, fiam commented on Makefile
> +	cd cmd/wunderctl && go build -o ../../wunderctl -ldflags "-X 'main.commit=$(shell git rev-parse --short HEAD)' -X 'main.builtBy=Makefile' -X 'main.version=dev' -X 'main.date=$(shell date)'" -trimpat
Are you sure about that? `$(shell <foo>)` is supposed to just call into whatever your `$SHELL` is, docs are here [Shell Function](https://www.gnu.org/software/make/manual/html_node/Shell-Function.html). We could make it work with variables, but we need to set them somewhere. Right now they're incorrectly typed (variables in make use `$(VAR)` rather than `$VAR` like the shell) as well as unset.

I also removed the arguments for stripping the debug info, because it can be helpful during development. What do you think about that?

2022-10-06 09:22 UTC, StarpTech commented on Makefile
> +	cd cmd/wunderctl && go build -o ../../wunderctl -ldflags "-X 'main.commit=$(shell git rev-parse --short HEAD)' -X 'main.builtBy=Makefile' -X 'main.version=dev' -X 'main.date=$(shell date)'" -trimpat
> ❯ shell git rev-parse --short HEAD
zsh: command not found: shell

2022-10-06 10:48 UTC, StarpTech commented on Makefile
> +	cd cmd/wunderctl && go build -o ../../wunderctl -ldflags "-X 'main.commit=$(shell git rev-parse --short HEAD)' -X 'main.builtBy=Makefile' -X 'main.version=dev' -X 'main.date=$(shell date)'" -trimpat
You're right. Works! I'd change `builtBy` to `ci`

2022-10-06 10:59 UTC, StarpTech commented on Makefile
> +	cd cmd/wunderctl && go build -o ../../wunderctl -ldflags "-X 'main.commit=$(shell git rev-parse --short HEAD)' -X 'main.builtBy=Makefile' -X 'main.version=dev' -X 'main.date=$(shell date)'" -trimpat
I'm okay with both `ci` ore `dev` but `makefile` was a bit weird.

2022-10-06 11:01 UTC, fiam commented on Makefile
> +	cd cmd/wunderctl && go build -o ../../wunderctl -ldflags "-X 'main.commit=$(shell git rev-parse --short HEAD)' -X 'main.builtBy=Makefile' -X 'main.version=dev' -X 'main.date=$(shell date)'" -trimpat
Perfect. Let's do `dev` instead, to tell it apart from actual CI builds.

2022-10-06 11:02 UTC, StarpTech commented on Makefile
> +	cd cmd/wunderctl && go build -o ../../wunderctl -ldflags "-X 'main.commit=$(shell git rev-parse --short HEAD)' -X 'main.builtBy=Makefile' -X 'main.version=dev' -X 'main.date=$(shell date)'" -trimpat
ok

2022-10-06 12:12 UTC, fiam commented
Pushed to trigger CI again, it seemed to have failed due to temporary network error.

2022-10-07 07:59 UTC, jensneuse commented
@fiam please trigger CI again

2022-10-07 10:53 UTC, jensneuse approved these changes

2022-10-07 10:53 UTC, merged