chore: add linux/arm64 support
wundergraph/wundergraph pull request #237
Opened 2022-10-05 14:07 UTC by fiam

- add support for linux/arm64 in binarypaths.js, so it downloads the correct binary
- add linux/arm64 wunderctl binaries to releases

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-06 09:05 UTC, StarpTech requested changes

2022-10-06 09:05 UTC, StarpTech commented on .github/goreleaser/.goreleaser-linux.yml
> +    id: linux_amd64
We used it in some other places. We should be consistent.

2022-10-06 09:33 UTC, fiam commented on .github/goreleaser/.goreleaser-linux.yml
> +    id: linux_amd64
I'm not sure what do you mean by that. Do you mean there are other places than use `x86_64` instead of `amd64`?

2022-10-06 11:01 UTC, jensneuse commented on .github/goreleaser/.goreleaser-linux.yml
> +    id: linux_amd64
we should use the same id across all places is what @StarpTech means I think
this id has no real meaning, it's just about making it consistent

2022-10-06 11:29 UTC, StarpTech commented on .github/goreleaser/.goreleaser-linux.yml
> +    id: linux_amd64
Yes

2022-10-07 08:37 UTC, jensneuse approved these changes

2022-10-07 08:39 UTC, StarpTech approved these changes
LGTM

2022-10-07 08:44 UTC, merged