feat: prioritize introspection cache, move out of generated
wundergraph/wundergraph pull request #238
Opened 2022-10-05 14:41 UTC by fiam

- feat: move introspection cache to .wundergraph/introspection/cache
- feat: prioritize cache during introspection

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-06 09:21 UTC, StarpTech requested changes

2022-10-06 09:21 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-introspection.md
> +The result is cached in the `.wundergraph/introspection/cache` directory.
When we introduce a global persistent cache dir, we should not call it "introspection" maybe `.wundergraph/cache` and put the introspection cache in `.wundergraph/cache/introspection`. In the future, we probably have other things to cache.

2022-10-06 09:21 UTC, StarpTech commented on packages/sdk/src/definition/introspection-cache.ts
> -		// fallback to old introspection result (only for development mode)
Why did you remove this? You have to differentiate between 

1. I run `wunderctl up`
2. I run `wunderctl generate`

Both commands should use the introspection cache but  `wunderctl up` calls it periodically. In case of an outage of one of the data sources, we want to fall back on the recent valid result. How do we ensure this now?

2022-10-06 09:21 UTC, StarpTech commented on packages/sdk/src/definition/introspection-cache.ts
>  	const cacheKey = objectHash(introspection);
I'd compute only when caching was enabled.

2022-10-06 09:21 UTC, StarpTech commented on packages/sdk/src/definition/introspection-cache.ts
> +		} catch (e) {}
Never swallow without at least a log entry :smile:

2022-10-06 09:21 UTC, StarpTech commented on cli/commands/up.go
> -			FirstRunEnv: append(os.Environ(),
Do I understand correctly that the introspection cache is now enabled by default?

2022-10-06 09:37 UTC, fiam commented on packages/sdk/src/definition/introspection-cache.ts
> +		} catch (e) {}
That block was just moved around, so I didn't question it that much, but you're right. I will add a log entry.

2022-10-06 09:44 UTC, fiam commented on packages/sdk/src/definition/introspection-cache.ts
>  	const cacheKey = objectHash(introspection);
`cacheKey` is also used when the source requires polling, even if the cache is disabled. We can initialise it lazily, but then we run into potential incorrect uses without initialisation. It think the hashing is cheap enough to perform it on function entry.

2022-10-06 09:44 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-introspection.md
> +The result is cached in the `.wundergraph/introspection/cache` directory.
I do agree that having `/cache/` at the first level is better than the at the last, but the initial issue specified exactly `.wundergraph/introspection/cache`. Should we change it or keep as initially requested?

2022-10-06 10:27 UTC, fiam commented
Made the requested changed and rebased

2022-10-06 10:38 UTC, StarpTech commented on cli/commands/up.go
> -			FirstRunEnv: append(os.Environ(),
No, sounds good.

2022-10-06 10:40 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-introspection.md
> +The result is cached in the `.wundergraph/introspection/cache` directory.
We should change it.

2022-10-06 10:42 UTC, StarpTech commented on packages/sdk/src/definition/introspection-cache.ts
> -		// fallback to old introspection result (only for development mode)
I mean, in case there is a cached introspection result, and the origin fails, the user should be able to continue with the cached result. Currently, the process will exit.

2022-10-06 10:43 UTC, StarpTech commented on packages/sdk/src/definition/introspection-cache.ts
>  	const cacheKey = objectHash(introspection);
ok

2022-10-06 10:52 UTC, fiam commented on packages/sdk/src/definition/introspection-cache.ts
> -		// fallback to old introspection result (only for development mode)
By the time execution reaches that point, either the cache doesn't have the entry or either it was explicitly disabled. Shouldn't we fail and exit?

2022-10-06 13:16 UTC, StarpTech requested changes

2022-10-06 13:18 UTC, fiam commented on cli/commands/root.go
> +			if err := os.Setenv("WG_ENABLE_INTROSPECTION_CACHE", "true"); err != nil {
Passing it individually to each command seems very error prone, at least a this stage. Unless we're expecting some commands will want to override the `--cache` flag in the near future, I think handling it globally is better.

2022-10-06 15:23 UTC, StarpTech requested changes

2022-10-06 15:23 UTC, StarpTech commented on cli/commands/generate.go
> +				fmt.Sprintf("WG_USE_INTROSPECTION_CACHE_EXCLUSIVELY=%t", !cacheFallback),
Can we simplify the flag? :smile: What means EXCLUSIVELY?

2022-10-06 15:26 UTC, StarpTech requested changes

2022-10-06 15:26 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableCache, "no-cache", false, "Enable cache")
You mean "disable cache" ?

2022-10-06 15:36 UTC, StarpTech commented on cli/commands/generate.go
> +				fmt.Sprintf("WG_USE_INTROSPECTION_CACHE_EXCLUSIVELY=%t", !cacheFallback),
`WG_ENABLE_INTROSPECTION_CACHE_FALLBACK` ?

2022-10-06 16:46 UTC, jensneuse requested changes

2022-10-06 16:46 UTC, jensneuse commented on cli/commands/up.go
> +		if introspectionCacheClearInterval > 0 {
The typescript sdk automatically polls (if configured properly) and refreshes the cache. No need to clear it from the go side.

2022-10-06 16:46 UTC, jensneuse commented on cli/commands/up.go
> -			FirstRunEnv: append(os.Environ(),
Is the switch from FirstRunEnv to ScriptEnv intentional?

2022-10-06 16:46 UTC, jensneuse commented on cli/commands/up.go
> +	upCmd.Flags().BoolVar(&keepIntrospectionCache, "keep-introspection-cache", false, "avoid clearing the introspection cache on startup")
this wasn't in the latest proposal we accepted

2022-10-06 16:46 UTC, jensneuse commented on cli/commands/up.go
> +	upCmd.Flags().IntVar(&introspectionCacheClearInterval, "cache-clear-interval", 5, "interval to clear the instrospection cache periodically, in seconds - 0 to disable")
clearing the cache from go does not make sense this way

2022-10-06 20:30 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableCache, "no-cache", false, "Enable cache")
Indeed! Thanks for the heads up. Fixed.

2022-10-06 20:34 UTC, fiam commented on cli/commands/generate.go
> +				fmt.Sprintf("WG_USE_INTROSPECTION_CACHE_EXCLUSIVELY=%t", !cacheFallback),
It's because "fallback" feels a bit weird as a name for this. When "cache" and "fallback" go together usually you hit the source of truth first (e.g. the remote server), then when that fails you query the cache. I'll see if I can come up with a better name.

2022-10-06 20:40 UTC, fiam commented on cli/commands/generate.go
> +				fmt.Sprintf("WG_USE_INTROSPECTION_CACHE_EXCLUSIVELY=%t", !cacheFallback),
Thinking more about this... Collins Dictionary says: "Exclusively is used to [refer](https://www.collinsdictionary.com/dictionary/english/refer) to situations or activities that involve only the thing or things [mentioned](https://www.collinsdictionary.com/dictionary/english/mention), and nothing else.", so maybe it's not that bad of a name.

2022-10-07 11:10 UTC, fiam commented on cli/commands/root.go
> +			if err := os.Setenv("WG_ENABLE_INTROSPECTION_CACHE", "true"); err != nil {
I've changed it to pass the variable individually to each command.

2022-10-07 14:34 UTC, StarpTech commented on cli/commands/up.go
> +	upCmd.Flags().BoolVar(&keepIntrospectionCache, "keep-introspection-cache", false, "avoid clearing the introspection cache on startup")
I'd not add it unless requested.

2022-10-07 14:46 UTC, jensneuse commented on cli/commands/up.go
> +	upCmd.Flags().BoolVar(&keepIntrospectionCache, "keep-introspection-cache", false, "avoid clearing the introspection cache on startup")
I would also suggest to just always clear on "up"

2022-10-07 14:48 UTC, fiam commented on cli/commands/up.go
> +	upCmd.Flags().BoolVar(&keepIntrospectionCache, "keep-introspection-cache", false, "avoid clearing the introspection cache on startup")
Deleting code? I can get behind that!

2022-10-07 14:53 UTC, fiam commented
> One thing I'd add is to set all "introspection" configs to automatically refresh each cache item every 5 seconds if not otherwise configured. So, by default, all introspections should be cached and refreshed after 5 seconds of waiting. This will give the most pleasent DX as it will be fast and (almost) always up to date if a datasource changes. @StarpTech opinion?

So basically making `pollingIntervalSeconds` default to 5 while running from `wunderctl up`?

2022-10-07 14:55 UTC, jensneuse commented
> > One thing I'd add is to set all "introspection" configs to automatically refresh each cache item every 5 seconds if not otherwise configured. So, by default, all introspections should be cached and refreshed after 5 seconds of waiting. This will give the most pleasent DX as it will be fast and (almost) always up to date if a datasource changes. @StarpTech opinion?
> 
> So basically making `pollingIntervalSeconds` default to 5 while running from `wunderctl up`?

It can always default to 5s, not just for "up", because when using "start", we don't introspect.

2022-10-07 14:58 UTC, StarpTech commented
Assumption: Most people integrate an existing API into the service. They don't need to refresh it so often. If so, they can configure it. For me it makes more sense to opt-in.

2022-10-07 15:00 UTC, jensneuse commented
> Assumption: Most people integrate an ready API into the service. They don't need to refresh it so often. If so, they can configure it. For me, it makes more sense to opt in.

ok, makes sense

2022-10-07 15:00 UTC, jensneuse approved these changes

2022-10-07 15:21 UTC, fiam commented
@StarpTech GH says there's one remaining change requested from you, but then it links to a resolved one. Can we dismiss it?

2022-10-07 18:12 UTC, jensneuse commented
> @StarpTech GH says there's one remaining change requested from you, but then it links to a resolved one. Can we dismiss it?

@StarpTech if you're ok, please approve

2022-10-07 18:17 UTC, StarpTech requested changes

2022-10-07 18:17 UTC, StarpTech commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&cacheFallback, "cache-fallback", false, "fallback to introspection if cache fails")
You mean "Fallback to introspection cache on error"?

2022-10-07 18:18 UTC, StarpTech commented
I'd like to test it once locally.

2022-10-07 18:20 UTC, fiam commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&cacheFallback, "cache-fallback", false, "fallback to introspection if cache fails")
No, it's the other way around. `generate` by default uses only the cache, if the entry is not in cache it will return an error. The option allows querying the network when the entry is not in cache.

2022-10-07 18:56 UTC, StarpTech commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&cacheFallback, "cache-fallback", false, "fallback to introspection if cache fails")
ok but still makes no sense to me. "cache fallback" means I use cache but you said it will skip the cache.
Maybe

```go
generateCmd.Flags().BoolVar(&cacheFallback, "force-introspection", false, "Refresh introspection if cache fails")
```

2022-10-07 19:09 UTC, jensneuse commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&cacheFallback, "cache-fallback", false, "fallback to introspection if cache fails")
> 

Sounds good, I'd extend it with:

3. `wunderctl generate --no-cache` will always make introspection call

This way, the user can decide between auto (default), online, or offline.

@StarpTech WDYT?

2022-10-07 19:12 UTC, StarpTech commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&cacheFallback, "cache-fallback", false, "fallback to introspection if cache fails")
I like.

2022-10-07 19:14 UTC, jensneuse commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&cacheFallback, "cache-fallback", false, "fallback to introspection if cache fails")
@fiam I think we have consensus if you agree on the 3 rules.

2022-10-07 20:18 UTC, fiam commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&cacheFallback, "cache-fallback", false, "fallback to introspection if cache fails")
That's exactly how most things that work with a cache and provide an offline switch works. Both on by default, provide flags to turn them off individually. If anything, I'm happier with this approach that the previous ones.

2022-10-07 21:24 UTC, jensneuse commented
Once the implementation is done, the docs need updates as well:
https://docs.wundergraph.com/docs/wundergraph-config-ts-reference/configure-introspection

2022-10-08 21:30 UTC, StarpTech requested changes

2022-10-08 21:30 UTC, StarpTech commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&offline, "offline", false, "offline mode, return an error instead of hitting the network")
I always try to understand this from the user's perspective. You didn't explain it. I'd try to simplify this:

> Offline mode enforces the use of the local introspection cache

2022-10-08 21:32 UTC, StarpTech requested changes

2022-10-08 21:32 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableCache, "no-cache", false, "Disable cache")
Here as well

> Disables the local introspection cache.

2022-10-08 21:40 UTC, StarpTech requested changes

2022-10-08 21:40 UTC, StarpTech commented on cli/commands/generate.go
>  // generateCmd represents the generate command
Could you also update the cmd text?

	Short: "Generate the production config.",
    Long: "Generate the production config to start the node and hook component. All files are stored to .wundergraph/generated. The local introspection cache has precedence. You can overwrite this behavior by passing --no-cache to the command"

2022-10-09 20:46 UTC, fiam commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&offline, "offline", false, "offline mode, return an error instead of hitting the network")
It probably needs a better help string, but I don't think we should mention anything regarding the cache in there, they're orthogonal concepts. The way that the failure is handled by the code managing the cache is an implementation detail.

What about "disables loading resources from the network"?

2022-10-09 20:50 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableCache, "no-cache", false, "Disable cache")
Right now we only have a cache for introspection, but I think not far from now we'll have caches for other things. It's rare to need to disable just some caches - most of the time you either enable them all (for speed) or disable them altogether (to e.g. ensure the changes are applied, refetching resources or ensuring a cold start works). Think of web browsers and how virtually none of them expose the different caches individually, they just allow clearing/disabling everything at once.

I would, however, change the help to 3rd person since I've been checking all available flags in wunderctl and while they're not 100% consistent, 3rd person seems more common than 1st. What about "disables local caches"?

2022-10-09 20:55 UTC, fiam commented on cli/commands/generate.go
>  // generateCmd represents the generate command
The long description seems a bit too verbose to me, mentioning where the cache is stored as well as to how to disable it (which can be seen via --help), but I guess it's fine.

2022-10-10 08:08 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableCache, "no-cache", false, "Disable cache")
I'm okay with it, but I thought it wouldn't hurt to be a bit more clear about what's the impact of this flag.

2022-10-10 10:43 UTC, StarpTech commented on cli/commands/generate.go
> +	generateCmd.Flags().BoolVar(&offline, "offline", false, "offline mode, return an error instead of hitting the network")
Fine for me as well.

2022-10-10 16:32 UTC, StarpTech commented
Let me test it locally and then we are good to go.

2022-10-11 10:36 UTC, StarpTech requested changes

2022-10-11 10:36 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-introspection.md
>  ## Clearing the Cache
Please add some docs about the different flags and use cases.
By default, we recommend not committing the cache directory unless you can't make introspection calls in your CI pipeline.

2022-10-11 14:34 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-introspection.md
>  ## Clearing the Cache
I've added some documentation about it, mentioning that it can be useful for CI. Please, let me know what you think. Thanks!

2022-10-11 15:53 UTC, merged