Sergey/eng 47 align logging format hooks server and
wundergraph/wundergraph pull request #240
Opened 2022-10-05 21:56 UTC by spetrunin

**Pretty**

![Screenshot 2022-10-06 at 00 50 05](https://user-images.githubusercontent.com/818351/194170952-9142a74a-7c75-4f3f-b45d-ee0475646c09.png)

**Json**
![Screenshot 2022-10-06 at 00 50 47](https://user-images.githubusercontent.com/818351/194171032-04d134ce-3fd2-4750-a77d-512d4fe32467.png)

**Open question:**
- zap produces time format with floating point, nevertheless, it should be int64
- for zap there is no way to format custom props away from JSON at the end of log message

2022-10-05 22:30 UTC, jensneuse commented
results look nice

2022-10-06 08:36 UTC, StarpTech commented
You can introduce a custom time encoder https://blog.sandipb.net/2018/05/03/using-zap-creating-custom-encoders/

2022-10-06 08:39 UTC, StarpTech commented
Pretty logging does not share the same format and style.

- In node, we log as a combination of text + JSON
- In node, we don't work with colors.

How did you ensure that we use the same log level between both components?

As @jensneuse suggest it would be nice if we have a different log prefix for each component

> { "component": "server" }

> INFO: SERVER: ...

2022-10-06 08:43 UTC, StarpTech requested changes

2022-10-06 08:45 UTC, StarpTech requested changes

2022-10-06 08:45 UTC, StarpTech commented on cli/commands/root.go
> +			// skip any setup for loadoperations to avoid logging anything
I don't get it. Could you explain why we need to do this?

2022-10-06 08:52 UTC, StarpTech requested changes

2022-10-06 08:52 UTC, StarpTech commented on packages/sdk/src/env/env.ts
> +export const WgEnvValue = (v: WgEnvironmentVariable): string | undefined => {
I suggest calling it `resolveWgEnv`

2022-10-06 08:52 UTC, StarpTech commented on packages/sdk/src/env/env.ts
> +	if (varName === 'UNKNOWN') {
Weird that this is not type safe :smile:

2022-10-06 08:52 UTC, StarpTech commented on types/protos/wundernode_config.proto
> +enum WgEnvironmentVariable {
Can we introduce the new way of handling env in a separate PR? Otherwise, we will have two ways until someone has refactored it.

2022-10-06 08:52 UTC, StarpTech commented on cli/commands/root.go
>  	rootCmd.PersistentFlags().BoolVar(&jsonEncodedLogging, "json-encoded-logging", false, "switches the logging to json encoded logging")
As with many other tools, JSON logging is always the default, and you have to set e.g. `--pretty-logger` to enable pretty print. I favor this because by default we should configure everything for production except for "wunderctl up".

2022-10-06 12:05 UTC, spetrunin commented on cli/commands/root.go
> +			// skip any setup for loadoperations to avoid logging anything
currently, loadoperations returns data through stdout via fmt.Println
in order to not break it, we should not log anything

2022-10-06 12:06 UTC, spetrunin commented on cli/commands/root.go
>  	rootCmd.PersistentFlags().BoolVar(&jsonEncodedLogging, "json-encoded-logging", false, "switches the logging to json encoded logging")
yeah, I agree with that

But before this it was opposite - so it will be a breaking change to a cli - which should be ok I belive

2022-10-06 12:10 UTC, spetrunin commented on types/protos/wundernode_config.proto
> +enum WgEnvironmentVariable {
sure, I will extract this into separate PR - so someone could also pick up it

2022-10-06 12:10 UTC, spetrunin commented on packages/sdk/src/env/env.ts
> +export const WgEnvValue = (v: WgEnvironmentVariable): string | undefined => {
ok

2022-10-06 12:20 UTC, spetrunin commented
> Pretty logging does not share the same format and style.

Yeah, with the current customization options of Pino and Zap
It is not possible to fully align this

> * In node, we log as a combination of text + JSON

that is one of the problems, as zap does not support logging additional keys in a different way at least with a standard console encoder
I believe we could solve it - by writing a custom log encoder - but this was out of the scope of this task

> * In node, we don't work with colors.

Partially do, the log level is colored
We could colorize output also, but I haven't added that

> How did you ensure that we use the same log level between both components?

We don't have to, it is the responsibility of the user to specify log level of WunderNode and WunderGraph Server via the options

But another breaking change - is that loglevel flag of CLI - should be responsible only for CLI log level, neither node nor server, as they use their own config


> As @jensneuse suggest it would be nice if we have a different log prefix for each component
> > { "component": "server" }

Yeah, agree, this will involve more work, I propose extracting it into a separate issue as well as environment variables refactoring

2022-10-07 13:37 UTC, StarpTech commented on cli/commands/root.go
>  	rootCmd.PersistentFlags().BoolVar(&jsonEncodedLogging, "json-encoded-logging", false, "switches the logging to json encoded logging")
It's fine :+1:

2022-10-07 18:10 UTC, jensneuse commented on cli/commands/root.go
> +			// skip any setup for loadoperations to avoid logging anything
Wouldn't it be better if we migrate loadoperation to output to a file?
Otherwise, as Dustin explained, add an explicit comment that we MUST NOT do any logging to not break this

2022-10-07 18:13 UTC, spetrunin commented on cli/commands/root.go
> +			// skip any setup for loadoperations to avoid logging anything
+1 to migrate to file

2022-10-07 20:44 UTC, StarpTech commented on cli/commands/root.go
> +			// skip any setup for loadoperations to avoid logging anything
or using "PersistentPreRunE" only for specific commands. I like both approaches.

2022-10-12 20:25 UTC, spetrunin commented on cli/commands/root.go
> +			// skip any setup for loadoperations to avoid logging anything
added a comment and todo, better to do optimization as a separate issue

2022-10-14 13:13 UTC, jensneuse approved these changes

2022-10-14 13:37 UTC, jensneuse approved these changes

2022-10-14 13:37 UTC, jensneuse commented
LGTM

2022-10-15 11:01 UTC, StarpTech commented
What's the status here? The PR has been open for too long.

2022-10-15 11:10 UTC, StarpTech requested changes

2022-10-15 11:10 UTC, StarpTech commented on cli/helpers/flags.go
> +type RootFlags struct {
Why did you put this here instead of in the root command?

2022-10-15 11:10 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +			console.log('gofmt is not installed. If you want to prettify the generated code, please install gofmt');
This should use the same logger as in the SDK, right? You can expose it in the SDK and use it here too.

2022-10-15 11:10 UTC, StarpTech commented on packages/sdk/src/codegen/index.ts
> +import { SdkLogger } from '../logger/logger';
Just naming but why did you prefix it with SDK? We are already in the SDK :smile:

2022-10-15 11:10 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +export type LoggerLevel =
This is confusing. The user will see "FATAL" and "fatal" in the IDE. I'd go with one way lowercase.

2022-10-15 11:10 UTC, StarpTech commented on pkg/node/node.go
>  	"github.com/jensneuse/abstractlogger"
Can we only use one logger for the node? I see no benefit in using abstactlogger and zap at the same time.

2022-10-17 08:07 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +			console.log('gofmt is not installed. If you want to prettify the generated code, please install gofmt');
Ideally, the logs are prefixed with the plugin name :smiley_cat:

2022-10-17 08:49 UTC, spetrunin commented on cli/helpers/flags.go
> +type RootFlags struct {
flag values used in CliEnv helper, so we will have to move both flags and env helper to commands pkg, to avoid circular references,
alternatively, we could add `cli/flags` pkg, to manage all flags of commands

2022-10-17 08:57 UTC, StarpTech commented on cli/helpers/flags.go
> +type RootFlags struct {
I see, fine for me.

2022-10-17 08:57 UTC, spetrunin commented on packages/golang-client/src/index.ts
> +			console.log('gofmt is not installed. If you want to prettify the generated code, please install gofmt');
it is confused me a bit, as seems it is part of SDK but sits outside of it

so SDK logger could be used here

yep, it could be smth like this
```
Logger.child("plugin", "golang-client")
```

But do we have any other plugins?

2022-10-17 09:00 UTC, spetrunin commented on pkg/node/node.go
>  	"github.com/jensneuse/abstractlogger"
we use a single logger already - it is zap, but it should be decorated with an abstract logger on a specific log level coming from the config

abstractlogger is not a logging backend - it is decorator for zap or logrus

2022-10-17 09:04 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +			console.log('gofmt is not installed. If you want to prettify the generated code, please install gofmt');
Yes, but not all logging something.

2022-10-17 09:38 UTC, StarpTech requested changes

2022-10-17 09:38 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +			Logger.child({ plugin: 'golang-client' }).error(
Could you define the logger at the top? In that case the next one doesn't make the mistake to log without the child.

```ts
const logger = Logger.child({ plugin: 'golang-client' })
```

2022-10-17 10:26 UTC, spetrunin commented on pkg/node/node.go
>  	"github.com/jensneuse/abstractlogger"
It is used in graphql-go-tools as logger abstraction, so it should be wrapped before passing to engine

we could handle it afterwords, but also we should be careful - currently zap starts with debug level and we filter reaching to zap via abstract logger

2022-10-18 07:46 UTC, StarpTech commented on pkg/node/node.go
>  	"github.com/jensneuse/abstractlogger"
Fine for me to use it as a wrapper for graphql-go-tools, but I'd not use it as a general abstraction for logs.

2022-10-18 07:47 UTC, StarpTech approved these changes
LGTM

2022-10-18 07:53 UTC, merged