fix: incorrect go code generated from JSON models
wundergraph/wundergraph pull request #249
Opened 2022-10-10 13:21 UTC by fiam

- fix: don't swallow gofmt errors, except gofmt being not present
- fix: go code generated from JSON mdel was missing a \n after slices

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-10 16:31 UTC, StarpTech requested changes

2022-10-10 16:31 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +		if (e instanceof Error && e.message.indexOf('ENOENT') >= 0) {
Swallowing was intentional because we can't expect that everyone has go installed.

2022-10-10 17:41 UTC, fiam commented on packages/golang-client/src/index.ts
> +		if (e instanceof Error && e.message.indexOf('ENOENT') >= 0) {
The problem was that it was also swallowing  other errors, like feeding gofmt invalid code. With this change, it will still swallow the exception when gofmt is not present (printing a warning), but it will fail when gofmt is installed but returns an error.

2022-10-10 18:13 UTC, jensneuse approved these changes

2022-10-10 22:32 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +		if (e instanceof Error && e.message.indexOf('ENOENT') >= 0) {
Thanks for the explanation. Makes sense.

2022-10-10 22:33 UTC, StarpTech approved these changes
LGTM

2022-10-11 08:32 UTC, fiam commented
I've changed the `packages-ci` workflow to also install Go, so we get a `gofmt` recent enough to support generics. Otherwise, CI would fail because our Go code generator does emit generics.

2022-10-11 08:32 UTC, merged