feat: allows node to sleep after an idle timeout
wundergraph/wundergraph pull request #256
Opened 2022-10-12 10:50 UTC by fiam

- feat: add httpidletimeout package
- feat: implement idle timeout in wunderctl start

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-12 11:30 UTC, spetrunin requested changes

2022-10-12 11:30 UTC, spetrunin commented on pkg/httpidletimeout/httpidletimeout.go
> +func (m *Middleware) C() <-chan struct{} {
maybe give it a longer name?

2022-10-12 11:30 UTC, spetrunin commented on pkg/httpidletimeout/httpidletimeout.go
> +	go func() {
new has a side effects and starts go routine immediately

2022-10-12 11:30 UTC, spetrunin commented on pkg/httpidletimeout/httpidletimeout.go
> +	LOOP:
it is possible to implement it without label?

2022-10-12 11:30 UTC, spetrunin commented on cli/commands/start.go
> +			err := StartWunderGraphNode(n, opts...)
I believe it should be implemented within StartWunderGraphNode

With the current approach we have this behavior only for `wunderctl start`

The goal of `start` is to launch node and server in exactly the same way how separate commands behaves

2022-10-12 11:30 UTC, spetrunin commented on pkg/httpidletimeout/httpidletimeout.go
> +// Package httpidletimeout implements an HTTP middleware that triggers
does it make sense to put it under `node` pkg? as it fully belongs to node?

2022-10-12 11:30 UTC, spetrunin commented on cli/commands/start.go
> +			defer middleware.Cancel()
Node could have an option `WithCleanupFunc()` - to run smth before node exits

we could have a more specific option `WithIdleTimeoutMiddleware`.

wdt?

2022-10-12 11:35 UTC, fiam commented on pkg/httpidletimeout/httpidletimeout.go
> +// Package httpidletimeout implements an HTTP middleware that triggers
I'd rather have it at the top level. As it stands, the package doesn't have any dependencies besides stdlib and we could use it to implement a separate proxy if we need it at some point in the future.

2022-10-12 11:36 UTC, fiam commented on pkg/httpidletimeout/httpidletimeout.go
> +func (m *Middleware) C() <-chan struct{} {
I think `C` is fine, it's what the `time` package uses (although it's a field instead of a function), but we can change it to something longer. What name would you prefer?

2022-10-12 11:36 UTC, fiam commented on pkg/httpidletimeout/httpidletimeout.go
> +	go func() {
Would you prefer an explicit `Start()` method?

2022-10-12 11:40 UTC, fiam commented on cli/commands/start.go
> +			defer middleware.Cancel()
I like the more specific option, something like `WithIdleTimeout` (if we make it opaque I see no reason to specify it's implemented as a middleware, that would become an implementation detail). In that case, at least for the time being, I wouldn't expose `WithCleanupFunc()` either, handling both the middleware and the cleanup internally.

2022-10-12 11:46 UTC, fiam commented on cli/commands/start.go
> +			err := StartWunderGraphNode(n, opts...)
The reason I went with that is because I didn't want to make the flag global. Let me check how cobra handles having multiple flags pointing to the same variable.

2022-10-12 11:48 UTC, spetrunin commented on pkg/httpidletimeout/httpidletimeout.go
> +func (m *Middleware) C() <-chan struct{} {
idk, it just unclear from name what it is

for example Trigger

2022-10-12 11:48 UTC, spetrunin commented on pkg/httpidletimeout/httpidletimeout.go
> +	go func() {
yep, smth like that

2022-10-12 11:50 UTC, spetrunin commented on cli/commands/start.go
> +			err := StartWunderGraphNode(n, opts...)
you could add same flag to both `start` and `node start`

2022-10-12 11:51 UTC, fiam commented on pkg/httpidletimeout/httpidletimeout.go
> +	if atomic.AddUint64(&m.counter, ^uint64(0)) == 0 {
There's no method to decrement it. I know it feels a bit weird the first time you see it, but it's explicitly documented in the atomic package.

2022-10-12 11:51 UTC, fiam commented on cli/commands/start.go
> +	startCmd.Flags().IntVar(&idleTimeout, "idle-timeout", 0, "exits after the given timeout has elapsed without any requests, in seconds")
Sure, I'll change it.

2022-10-12 11:51 UTC, fiam commented on cli/commands/start.go
> +	idleTimeout                int
I'll rename it as the flag.

2022-10-12 11:54 UTC, fiam commented on pkg/httpidletimeout/httpidletimeout.go
> +				case notifyCh <- struct{}{}:
I know, but if you close the channel then you can't send anything else once the timeout triggers once. I think at some point we might want to implement a more sophisticated logic, so I'd preferred a design that sent multiple notifications.

2022-10-12 11:57 UTC, fiam commented on pkg/node/node.go
> +func WithMiddleware(middleware func(http.Handler) http.Handler) Option {
I'll change it

2022-10-12 12:04 UTC, fiam commented on cli/commands/start.go
> +				<-middleware.C()
The channel gives you the most flexibility and it's more lightweight. You can receive or select on it, as you please. You can also chain it with a Context if you want. But we can  expose a blocking function if you prefer.

2022-10-12 12:05 UTC, fiam commented on pkg/httpidletimeout/httpidletimeout.go
> +					ctx, cancel = context.WithTimeout(parent, infiniteDuration)
Timer.Reset() is such a problematic API that I rarely reach for it for anything that requires a reset. I'll take a look and check how it would work with timers.

2022-10-12 14:43 UTC, StarpTech commented on pkg/httpidletimeout/httpidletimeout.go
> +func (m *Middleware) C() <-chan struct{} {
or `timedoutChan`

2022-10-12 14:44 UTC, fiam commented on pkg/httpidletimeout/httpidletimeout.go
> +func (m *Middleware) C() <-chan struct{} {
I've removed it in favour of a function/Context based API, as Jens requested

2022-10-12 14:52 UTC, fiam commented on cli/commands/start.go
> +			err := StartWunderGraphNode(n, opts...)
I've tested it and you're right. Having two flags with the same flag name and pointing the same variable is complete fine. I've moved it to StartWunderGraphNode().

2022-10-12 14:56 UTC, StarpTech commented
Sorry, I didn't see the tests. Looks pretty solid.

2022-10-12 15:01 UTC, fiam commented on cli/commands/node.go
> +			err := StartWunderGraphNode(n, stop)
It's the cancellation function for the parent `Context`. We need to pass it to the `Node` because now it handles the idle timeouts itself rather than exposing a middleware.

2022-10-12 15:03 UTC, StarpTech commented on cli/commands/node.go
> +			err := StartWunderGraphNode(n, stop)
ah its the cancel function.

2022-10-12 15:04 UTC, StarpTech requested changes

2022-10-12 15:04 UTC, StarpTech commented on cli/commands/node.go
> +func StartWunderGraphNode(n *node.Node, stop func()) error {
I'd expect that cancellation is communicated through the node context and that the registration of the middleware is part of the Node struct.

2022-10-12 15:09 UTC, fiam commented on cli/commands/node.go
> +func StartWunderGraphNode(n *node.Node, stop func()) error {
That's what I went for initially, but that requires quite a big refactor because `StartWunderGraphNode` blocks waiting for `Node.StartBlocking`, which only returns once the node has stopped.

2022-10-12 19:06 UTC, fiam commented on cli/commands/node.go
> +func StartWunderGraphNode(n *node.Node, stop func()) error {
Unless I'm mistaken, at that point the Context that Node receives is not guaranteed to be the one that sits at the top of hierarchy. Since we want to cancel everything and exit cleanly, I think it would be safer to handle it at the top level. That's why I'm passing the cancelation function from the top.

2022-10-13 08:36 UTC, StarpTech commented on cli/commands/node.go
> +func StartWunderGraphNode(n *node.Node, stop func()) error {
Could you give it another shoot? I can help you.

2022-10-13 09:23 UTC, fiam commented on cli/commands/node.go
> +func StartWunderGraphNode(n *node.Node, stop func()) error {
Sure! Maybe I'm misunderstanding what you have in mind. Let's have a chat to ensure we're both on the same page.

2022-10-18 07:18 UTC, jensneuse approved these changes
LGTM
@StarpTech please verify as well

2022-10-18 08:10 UTC, StarpTech requested changes

2022-10-18 08:10 UTC, StarpTech commented on pkg/node/node.go
> +		m := httpidletimeout.New(n.options.idleTimeout)
Could you use more meaningful names here?

2022-10-18 08:10 UTC, StarpTech commented on pkg/node/node.go
> +// has elapsed without any requests.
Could you also mention that the handler is called after idleTimeout?

2022-10-18 08:28 UTC, fiam commented on pkg/node/node.go
> +		m := httpidletimeout.New(n.options.idleTimeout)
Do you mean the `m`? We can call it `middleware`

2022-10-18 08:28 UTC, fiam commented on pkg/node/node.go
> +// has elapsed without any requests.
Sure, I'll add that.

2022-10-18 08:37 UTC, fiam commented on pkg/node/node.go
> +		m := httpidletimeout.New(n.options.idleTimeout)
Thanks for the clarification! I'll get it done.

2022-10-18 08:45 UTC, StarpTech requested changes

2022-10-18 08:45 UTC, StarpTech commented on cli/commands/start.go
> +	startCmd.Flags().IntVar(&exitAfterIdle, "exit-after-idle", 0, "exits after the given timeout has elapsed without any requests, in seconds")
"Shutdown the server after given seconds in idle when no requests have been served"

"exit" sounds hard, but we gracefully shut down the server. Maybe "idle-shutdown"?

2022-10-18 10:19 UTC, fiam commented on cli/commands/start.go
> +	startCmd.Flags().IntVar(&exitAfterIdle, "exit-after-idle", 0, "exits after the given timeout has elapsed without any requests, in seconds")
I went with all lowercase and 3rd person form, for consistency with the rest of the flags, but pretty much copied your suggestion verbatim otherwise

2022-10-18 11:13 UTC, StarpTech commented on cli/commands/start.go
> +	startCmd.Flags().IntVar(&exitAfterIdle, "exit-after-idle", 0, "exits after the given timeout has elapsed without any requests, in seconds")
thanks

2022-10-18 11:13 UTC, StarpTech approved these changes
LGTM

2022-10-18 14:59 UTC, spetrunin approved these changes

2022-10-18 15:07 UTC, merged