feat: subscriptions, operation hooks
wundergraph/wundergraph pull request #260
Opened 2022-10-14 20:03 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-18 07:28 UTC, jensneuse requested changes

2022-10-18 07:28 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-server-ts-reference/ws-transport-connection-init-hook.md
> +The `onConnectionInit` hook is called whenever the resolver needs to call a remote service.
The `onConnectionInit` hook is called when the engine is initiating a WebSocket connection with a GraphQL Server.

2022-10-18 07:28 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-server-ts-reference/ws-transport-connection-init-hook.md
> +                Authorization: request.headers.get('Authorization'),
This will not work. It needs to be clientRequest.
As per the introspect.graphql config, the "Upgrade" request will not contain an Authorization header.

2022-10-18 07:28 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			resp = r
error gets swallowed

2022-10-18 08:01 UTC, YuriBuerov commented on pkg/apihandler/apihandler.go
> +			resp = r
they are logged

2022-10-18 08:51 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			resp = r
ok, I didn't see.

2022-10-18 08:53 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-server-ts-reference/ws-transport-connection-init-hook.md
> +        onConnectionInit: {
I found a problem with this.
We can only have one single hook.
I think wsTransport should actually contain an array of objects, not just a single hook.

2022-10-18 13:06 UTC, jensneuse requested changes

2022-10-18 13:06 UTC, jensneuse commented on packages/sdk/src/codegen/templates/typescript/hooks.template.ts
> +	  dataSourceId: string;
This should not be string but using a generic which points to the configured id's for this hook.

2022-10-18 13:06 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-server-ts-reference/ws-transport-connection-init-hook.md
> +            if (dataSourceId === 'chat') {
currently, dataSourceId is a string, but it should actually be one of the strings passed to "enableForDataSources"

example how it could work:
https://github.com/microsoft/TypeScript/issues/28046#issuecomment-607145719

2022-10-20 09:36 UTC, jensneuse approved these changes

2022-10-20 09:44 UTC, merged