feat: improvements to "getting started" docs page
wundergraph/wundergraph pull request #261
Opened 2022-10-15 09:37 UTC by fiam

- fix: default output directory in wunderctl init is . - not .wundergraph
- feat: add wunderctl templates
- fix(devdocs): port for docs-website in development is 3005
- feat: minor improvements in getting-started page

2022-10-15 10:49 UTC, StarpTech requested changes

2022-10-15 10:49 UTC, StarpTech commented on docs-website/src/pages/getting-started.md
> +Wundergraph uses Node.js to manage and run your projects. Install it following their
> Wundergraph uses Node.js to manage and run your projects.

This is not accurate. WunderGraph uses Node.js to build the configuration and run the middleware server. The gateway is running with go.

2022-10-15 10:49 UTC, StarpTech commented on docs-website/src/pages/getting-started.md
> +[official instructions](https://nodejs.org).
Point to LTS. This is the only version we actively supported.

2022-10-15 10:49 UTC, StarpTech commented on cli/commands/templates.go
> +var templatesCmd = &cobra.Command{
We should not introduce more commands that will be removed soon. We would like to change how templates are managed. We no longer want to manage them with wunderctl. This has several reasons. There is no easy way to download wunderctl binary. The flow starts with npm. Therefore we should provide an npm package that manage the templates e.g `npx create-wundergraph-app@latest`

 A `npx create-wundergraph-app@latest -e nextjs` will checkout the example from a git repository. In that way, we don't need to prepare a release for every template change.

I'd also change templates to examples which I think is cleaner:

```
npx create-wundergraph-app list
npx create-wundergraph-app ---example nextjs
```

This is the same approach of https://nextjs.org/docs

2022-10-15 11:11 UTC, fiam commented on docs-website/src/pages/getting-started.md
> +Wundergraph uses Node.js to manage and run your projects. Install it following their
The motivation for that sentence is to explain why Node is needed. Maybe we can leave the "manage" part and remove the "run"?

2022-10-15 11:12 UTC, fiam commented on cli/commands/templates.go
> +var templatesCmd = &cobra.Command{
I wasn't aware of that. In that case, updating the project creation first and then updating the docs might be a better approach.

2022-10-15 11:14 UTC, StarpTech commented on cli/commands/templates.go
> +var templatesCmd = &cobra.Command{
My fault, we didn't document it.

2022-10-15 11:15 UTC, StarpTech commented on docs-website/src/pages/getting-started.md
> +Wundergraph uses Node.js to manage and run your projects. Install it following their
Yes, sounds good.

2022-10-17 14:42 UTC, fiam commented
Since we're now working on the tutorials, maybe changing this to link to the tutorials instead of the examples would be a good idea.

2022-10-18 07:42 UTC, StarpTech approved these changes
LGTM

2022-10-18 08:26 UTC, jensneuse approved these changes

2022-10-18 08:36 UTC, merged