docs: add Your First WunderGraph Application tutorial
wundergraph/wundergraph pull request #266
Opened 2022-10-17 14:40 UTC by fiam

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-18 07:11 UTC, jensneuse requested changes

2022-10-18 07:11 UTC, jensneuse commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +WunderGraph applications are just Node packages, so if you're already familiar with
I'm not sure I like the wording here.

2022-10-18 07:11 UTC, jensneuse commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +	--template application -o countries
I think if you're using the application template, you can omit `--template application`

2022-10-18 07:11 UTC, jensneuse commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +  apiNamespace: 'the_continents',
Why continents? it's the countries API?
I'd stay consistent and name the api "countries" as well as the namespace.
I'd also explain what a namespace is and why it's important. (At least briefly)

Also, please don't suggest namespaces like "the_xxx".
Namespaces should be [a-z].

2022-10-18 07:11 UTC, jensneuse commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +  cors: {
Actually, I'd suggest that you change the API here.
Can you make cors settings optional and just allow anything?
We can later use the CI to validate this config and warn the user if they use "allow all" in production.

2022-10-18 15:46 UTC, fiam commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +	--template application -o countries
You're right, let's drop that

2022-10-18 15:48 UTC, fiam commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +  apiNamespace: 'the_continents',
The idea was to make it distinct from the `continents` in the graphql API. Having `continents_continents` makes telling apart what's namespace and what comes from the API a bit confusing. What do you think about changing the namespace to `world`?

2022-10-18 15:49 UTC, fiam commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +  cors: {
I agree. PR for the API change is in https://github.com/wundergraph/wundergraph/pull/270 - I will rewrite the doc assuming we'll merge it.

2022-10-18 15:50 UTC, fiam commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +WunderGraph applications are just Node packages, so if you're already familiar with
What about...

- `At their heart, WunderGraph applications are Node packages`
- `WunderGraph applications are also Node packages`

2022-10-20 09:53 UTC, jensneuse commented on docs-website/src/pages/docs/tutorials/your-first-wundergraph-application.md
> +  apiNamespace: 'the_continents',
world is good

2022-10-20 09:56 UTC, jensneuse approved these changes

2022-10-20 10:22 UTC, fiam commented
@jensneuse This is running into the problem with `build_test` not triggering. Could you please override and merge? Thanks!

2022-10-20 10:58 UTC, merged