feat: healthcheck, node and hooks server
wundergraph/wundergraph pull request #274
Opened 2022-10-19 14:21 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-19 14:30 UTC, StarpTech requested changes

2022-10-19 14:30 UTC, StarpTech commented on packages/sdk/src/middleware/server.ts
> +		url: '/',
Let's call it "/health" to make it clear.

2022-10-19 14:30 UTC, StarpTech commented on pkg/node/node.go
>  	router.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
Here too call it "/health"

2022-10-19 14:30 UTC, StarpTech commented on pkg/node/node.go
> +		resp, err := http.DefaultClient.Get(serverUrl + "/")
Please ensure proper max timeouts.

2022-10-19 14:30 UTC, StarpTech commented on pkg/node/node.go
> +		_ = json.NewEncoder(w).Encode(health)
The endpoint has to return with a non-200 status code when the server is unhealthy.

2022-10-19 14:30 UTC, StarpTech commented on pkg/node/node.go
> +		resp, err := http.DefaultClient.Get(serverUrl + "/")
This check should only happen when wunderctl manage the server process "wunderctl start"

2022-10-19 18:21 UTC, StarpTech requested changes

2022-10-19 18:21 UTC, StarpTech commented on cli/commands/node.go
> +func StartWunderGraphNode(n *node.Node, stop func(), opts ...Option) error {
Could you convert "stop" also to an option?

2022-10-19 18:21 UTC, StarpTech commented on pkg/node/node.go
> +			c.Timeout = 30 * time.Second
I'd suggest creating a custom HTTP client outside of the handler.

2022-10-19 18:21 UTC, StarpTech commented on pkg/node/node.go
> +			resp, err := c.Get(serverUrl + "/health")
Use

```
url.JoinPath("http://host/foo", "bar/")
```

2022-10-19 18:21 UTC, StarpTech commented on pkg/node/node.go
> +			c.Timeout = 30 * time.Second
The default should come from the cli flag default value.

2022-10-19 18:21 UTC, StarpTech commented on cli/commands/start.go
> +	startCmd.Flags().IntVar(&healthCheckTimeout, "healthcheck-timeout", 0, "healthcheck timeout in seconds")
You can define a default here.

2022-10-20 07:59 UTC, spetrunin commented on pkg/node/node.go
> +			resp, err := c.Get(serverUrl + "/health")
It will require go 1.19

2022-10-20 08:06 UTC, StarpTech commented on pkg/node/node.go
> +			resp, err := c.Get(serverUrl + "/health")
:cry:

2022-10-20 10:40 UTC, StarpTech approved these changes
LGTM

2022-10-20 10:47 UTC, merged