feat: add flag for disabling environment loading from file
wundergraph/wundergraph pull request #291
Opened 2022-10-26 13:35 UTC by fiam

- Add --no-env, which disables the .env file
- Refactor the checks for environment files that do not exist and
report a failure if the environment file is set to something else than
the default, but does not exist.

2022-10-29 17:43 UTC, StarpTech requested changes

2022-10-29 17:43 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
Hi, did you check if existing env variables take precedence over variables with the same name in .env?

2022-10-29 17:43 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
I think we don't need this flag if we can ensure that environment variables passed by the user take precedence over variables in `.env`. In https://github.com/joho/godotenv you can read them to a map and implement this behavior.

2022-10-31 10:29 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
I've verified that environment variables take precedence over the `.env` file. `godotenv` handles it here https://github.com/joho/godotenv/blob/5c76d3e02c63f90a1bfae60738bbc24ba16f05c4/godotenv.go#L190

2022-10-31 11:19 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
Great, do you think it still makes sense to add this flag?

2022-10-31 11:24 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
While the flag is not entirely mandatory, it might make some sense if you want to be absolutely sure that nothing from an external file pollutes the environment. On the other hand, naming it properly is a bit annoying as we discussed: `--no-env` might seem like it ignores the  previous environment while naming it `--no-env-file` does not make it as obvious that's related to `--env`. I you think that's useful for cloud, I'd keep it. Otherwise we can drop it and if someone asks for it in the future we can revive the PR.

2022-11-03 10:39 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
I agree with renaming the flags, but only loading `.env` from `wunderctl up` seems like it could lead to some unpleasant surprises for users. I think we either load it by default in all cases or either we default `--env-file` to empty and only load it when the user provides a value for the flag.

2022-11-03 12:37 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
We should prevent users from making such mistakes. Using `.env` by default could encourage people to commit their secrets to git or disk. This is only reasonable for development. We can expose this flag, but it shouldn't be the default behavior for production commands like `wunderctl start` or `wunderctl node start` ...

2022-11-03 14:48 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
Those are orthogonal concepts. People that think committing secrets is not a problem will still find ways to do so, like adding a script to launch `wunderctl` with the secrets in it.

2022-11-03 14:52 UTC, fiam commented
I've changed it to define two flags, one for the root command and another one for `wunderctl up`, in the same way that it was done for `--pretty-logging`. First has an empty value by default, while the latter defaults to `.env`. Problem is cobra doesn't seem to support this. Notice the output of `wunderctl up -h`:

```
Start the WunderGraph application in development mode and watch for changes
 
Usage:
  wunderctl up [flags]

Flags:
  -h, --help   help for up

Global Flags:
      --clear-cache              clears local caches during startup
  -l, --cli-log-level string     sets the CLI log level (default "info")
      --debug                    enables the debug mode so that all requests and responses will be logged
  -e, --env-file string          allows you to set environment variables from an env file
      --no-cache                 disables local caches
      --no-env-file              disables loading environment variables from a file
      --pretty-logging           switches to human readable format
      --wundergraph-dir string   path to your .wundergraph directory (default ".wundergraph")
```
The root command definition is the one that prevails (notice it's shown only as global and with no default). Basically, what this ends up doing is overriding the default value if the command is `up` with no way for the user to discover that (other than trial and error).

2022-11-03 14:58 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
Let me describe it differently. Let's say you accidentally copy your .env file to your docker context. Your app will likely work and you're going crazy about why the wrong variables are used.

2022-11-03 15:04 UTC, StarpTech requested changes

2022-11-03 15:04 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().StringVarP(&dotEnvFile, "env-file", "e", "", "allows you to set environment variables from an env file")
`load` instead `set`?

2022-11-03 15:04 UTC, StarpTech commented on cli/commands/root.go
> +			dotEnvFile = upCmdEnvFile
Now, you're running into the same ugly workaround :smile:

2022-11-03 15:04 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env-file", false, "disables loading environment variables from a file")
Is it required to have `--no-env-file` and `--env-file`? Who not just `--env-file` and by default `wunderctl up` uses `.env` and all others empty string? WDYT?

2022-11-03 15:06 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env", false, "disables loading environment variables from a file")
Maybe we have different workflows in mind. Won’t the environment variables that are already defined take precedence in that case? If you forgot to define a secret I would assume you won’t use the same values in production and development and it will fail during startup.

2022-11-03 15:11 UTC, fiam commented on cli/commands/root.go
> +			dotEnvFile = upCmdEnvFile
In practical terms, I think we're better served by checking for `dotEnvFile == ""` and command being `up`, then overriding the value. The help for the subcommand seems to be ignored, and that way we avoid repeating its help text.

2022-11-03 15:13 UTC, fiam commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env-file", false, "disables loading environment variables from a file")
Now that we've changed it to default to an empty string, I think we can remove `--no-env-file`. What bothers me a bit is defaulting to `.env` for up. I'd be more comfortable with leaving it empty in all cases, then if it has a value and it fails to load we can report an error. Having two different defaults makes error handling a bit messy.

2022-11-03 15:17 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&disableEnvFile, "no-env-file", false, "disables loading environment variables from a file")
`.env` is very common for development exists since the early days of wundergraph. I'd not remove this default for up. Loading .env in development is best-effort.

2022-11-03 15:31 UTC, closed without merging