chore: rename X-Cache header to X-Wg-Cache
wundergraph/wundergraph pull request #298
Opened 2022-10-28 14:12 UTC by fiam

refactor the cache key to a constant to avoid repeating it

2022-10-28 16:11 UTC, bmcilw1 commented on pkg/apihandler/apihandler.go
> +	WG_CACHE_HEADER = "X-Wg-Cache"
Should this be 
```suggestion
	WG_CACHE_HEADER = `X-${WG_PREFIX}-Cache`
```

2022-10-31 14:22 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +	WG_CACHE_HEADER = "X-Wg-Cache"
no, but I'd suggest we make the key "X-WG-Cache" instead of "X-Wg-Cache" @fiam

2022-10-31 14:23 UTC, jensneuse requested changes
x

2022-10-31 14:39 UTC, fiam commented on pkg/apihandler/apihandler.go
> +	WG_CACHE_HEADER = "X-Wg-Cache"
`X-WG-Cache` is not in canonical form. While HTTP headers are case insensitive, some APIs/libraries delegate the canonicalisation to the user while others handle it internally (Go falls into the latter, see [CanonicalMimeHeaderKey](https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/net/textproto/reader.go;l=579;drc=e09bbaec69a8ff960110e13eabb3bef5331ecb0c;bpv=1;bpt=1)). To avoid having to handle this directly (e.g. writing to `resp.Header` instead of using `resp.Header.Set` and potentially causing issues for consumers, I'd rather go with `X-Wg-Cache`.

2022-10-31 14:44 UTC, bmcilw1 commented on pkg/apihandler/apihandler.go
> +	WG_CACHE_HEADER = "X-Wg-Cache"
Just for the heck of saying something, since that's true it could also be `X-${WG_PREFIX[0].toUpper() + WG_PREFIX.restOfStringAfter0().toLower()}-Cache`

That is if fully respecting the given prefix was a desired feature.

2022-10-31 17:48 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +	WG_CACHE_HEADER = "X-Wg-Cache"
Ok @fiam

2022-10-31 17:49 UTC, jensneuse approved these changes

2022-10-31 17:52 UTC, merged