feat: ensure wunderctl always call the same copy when calling itself
wundergraph/wundergraph pull request #300
Opened 2022-10-28 14:33 UTC by fiam

Introduce a WUNDERCTL_BINARY_PATH environment variable. This can
be set either by the user or either by wunderctl itself. On startup,
wunderctl checks if the variable is unset and if it is, then it
sets it to its own path. The TS side now checks for this new variable
and when it's non-empty, it overrides the path to the wunderctl binary.

2022-10-29 17:49 UTC, StarpTech requested changes

2022-10-29 17:49 UTC, StarpTech commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
I don't like it this way. The same reason why globals are evil. I prefer to set this variable explicitly in the process call of the "config runner" https://github.com/wundergraph/wundergraph/blob/main/cli/commands/up.go#L82.

2022-10-31 10:44 UTC, fiam commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
Reading an environment variable, moving it to a Go global, then passing it as the environment for each invocation is still using a global, just with more steps and hence more chances to mess it up (like we have right now with both `WG_ABS_DIR` and `WG_DIR_ABS`. If you want to set environment variables on a per-invocation basis we need to refactor all the environment variables to a centralised place. We have some of them handled in `helpers/env.go`, but others are still handled manually at each invocation.

2022-10-31 10:51 UTC, StarpTech commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
My point is: It's not clear that the runner requires this env to work. This is very error-prone.

2022-10-31 11:07 UTC, fiam commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
If the script requires a specific environment variable to work, we should wrap it in a function and require an explicit argument. Adding the environment variables explicitly to each invocation doesn't mean they're required, maybe they were required at some point in the past and someone forgot to remove them, because you have no way to know if they're actually used without looking at what the child (and its potential children) does. If you want to be absolutely sure that the child always receives a given set of environment variables, we should have the child validate its environment.

2022-10-31 11:49 UTC, StarpTech commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
:+1:

2022-10-31 14:17 UTC, jensneuse commented
Is this passed back to go when called from the wunderctl Node wrapper?

2022-10-31 14:20 UTC, jensneuse requested changes

2022-10-31 14:20 UTC, jensneuse commented on cli/commands/root.go
> +	for _, v := range os.Environ() {
Replace with idiomatic go:
https://golangbyexample.com/check-environment-variable-set-go/

2022-10-31 14:26 UTC, fiam commented on cli/commands/root.go
> +	for _, v := range os.Environ() {
Good idea. I wasn't aware of that.

2022-10-31 16:55 UTC, StarpTech commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
This env variable is only needed when generating the config. Could you pass the env variable as with the others? https://github.com/wundergraph/wundergraph/blob/main/cli/commands/up.go#L82

2022-10-31 16:58 UTC, fiam commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
What if we take the chance to refactor all that? We have variables duplicated in a couple of places and right now, with less than 10 variables, it shouldn't take long to organise them.

2022-10-31 17:05 UTC, StarpTech commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
Could you make an example of how that refactoring would look like? IMO I don't see much room for valuable refactoring.

2022-10-31 17:09 UTC, fiam commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
Move all variables passed to scripts to functions. e.g. `GeneratorEnvironment()`, `HooksServerEnviroment()`, etc.. and don't type any variables directly when creating the `ScriptRunner`. If we need to adjust those variables depending on something else, pass them as parameters to those functions.

2022-10-31 17:16 UTC, StarpTech commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
This would introduce another abstraction. We would still pass it like this right?

```go
configRunner := scriptrunner.NewScriptRunner(&scriptrunner.Config{
			Name:          "config-runner",
			Executable:    "node",
			AbsWorkingDir: wunderGraphDir,
			ScriptArgs:    []string{configOutFile},
			Logger:        log,
			ScriptEnv: HooksServerEnviroment(disableCache, .....)
		})
```

I'd just pass the wunderctlBinaryPathEnvKey to the runner for now.

2022-10-31 17:37 UTC, jensneuse commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
Agree. Just pass on the process env. Simple and clear.

2022-10-31 20:31 UTC, fiam commented on cli/commands/root.go
> +		os.Setenv(wunderctlBinaryPathEnvKey, exe)
I've refactored it to pass each the variable to each invocation individually

2022-10-31 20:55 UTC, StarpTech requested changes

2022-10-31 20:55 UTC, StarpTech commented on cli/commands/root.go
> +	wunderctlBinaryPath = value
Can we avoid working with a global here? Why not

```go
path, err := getBinaryPath()
fmt.Sprintf("%s=%s", wunderctlBinaryPathEnvKey, path),
```

2022-11-03 10:12 UTC, fiam commented on cli/commands/root.go
> +	wunderctlBinaryPath = value
There used to be a time when `os.Executable()` could get a bit fishy after starting up (if e.g. you `chdir()`'ed), but I checked its most recent source code and it should now work fine. I will remove the global variable.

2022-11-03 10:23 UTC, fiam commented on cli/commands/root.go
> +	wunderctlBinaryPath = value
Changed

2022-11-03 12:26 UTC, StarpTech requested changes

2022-11-03 12:26 UTC, StarpTech commented on packages/wunderctl/src/binarypath.ts
> +		return process.env.WUNDERCTL_BINARY_PATH;
Should we validate for a valid path? I could imagine the error message is not very helpful when the path does not point to a binary.

2022-11-03 12:31 UTC, fiam commented on packages/wunderctl/src/binarypath.ts
> +		return process.env.WUNDERCTL_BINARY_PATH;
At least for now, we're the only ones setting that variable. If someone is setting it manually before invocation I think letting it blow up makes it more evident than swallowing the error. There's also already a check in `wunderCtlFile()` which throws if the binary doesn't exist, so I'd say there's already enough validation.

2022-11-03 12:52 UTC, StarpTech commented on packages/wunderctl/src/binarypath.ts
> +		return process.env.WUNDERCTL_BINARY_PATH;
ok

2022-11-03 12:52 UTC, StarpTech approved these changes
LGTM

2022-11-04 11:11 UTC, jensneuse approved these changes

2022-11-04 11:11 UTC, jensneuse commented
LGTM

2022-11-04 11:12 UTC, merged