feat: sdk, support schema extension
wundergraph/wundergraph pull request #302
Opened 2022-10-28 17:20 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-10-31 18:38 UTC, YuriBuerov commented
I would like to have feedback before I update the docs

2022-11-02 10:37 UTC, jensneuse requested changes

2022-11-02 10:37 UTC, jensneuse commented on packages/sdk/src/transformations/shema.ts
> +		replaceJSONTypeFields?: ReplaceJSONTypeFieldConfiguration[] | undefined;
I think we agreed to go away from naming this JSON, right?

2022-11-02 10:37 UTC, jensneuse commented on packages/sdk/src/definition/index.ts
> +	replaceJSONTypeFields?: ReplaceJSONTypeFieldConfiguration[];
rename to "replaceCustomScalarTypeFields" (consistently across all data sources)

2022-11-02 10:37 UTC, jensneuse commented on packages/sdk/src/v2openapi/index.test.ts
> +				inputTypeReplacement: `ContactInput`,
Is this optional? Because it should. As you can see in this example, we're not using it.
I think for GraphQL and OpenAPI, we really only set responseTypeReplacement.

2022-11-04 09:52 UTC, jensneuse approved these changes

2022-11-04 09:55 UTC, merged