feat: SWR v2
wundergraph/wundergraph pull request #305
Opened 2022-10-31 15:10 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-07 15:35 UTC, Pagebakers commented on packages/swr/src/hooks.ts
> +			if (!startedAtRef.current && resetOnMount) {
Allow  to reset the cached data when the hook in mounted, so we don't have 'old' subscription values.

@StarpTech what do you think of the `resetOnMount` prop name?

2022-11-07 16:57 UTC, StarpTech requested changes

2022-11-07 16:57 UTC, StarpTech commented on packages/swr/src/hooks.ts
> +			if (!startedAtRef.current && resetOnMount) {
I like the name.

2022-11-07 16:57 UTC, StarpTech commented on packages/sdk/src/client/client.ts
>  		subscription: SubscriptionRequestOptions,
Don't forget to add tests for the types https://github.com/wundergraph/wundergraph/blob/main/packages/type-tests/test/swr.test-d.ts. It's a great place to understand the API of the new client.

2022-11-07 17:10 UTC, StarpTech requested changes

2022-11-07 17:10 UTC, StarpTech commented on packages/swr/src/hooks.ts
> +		const { mutate } = useSWRConfig();
Does that mean the user has to use `swr` context?

2022-11-07 17:10 UTC, StarpTech commented on packages/swr/src/hooks.ts
> +import useSWRMutation, { SWRMutationConfiguration } from 'swr/mutation';
Can we set up a minimal test suite? We could use swr tests as an inspiration.

2022-11-08 09:18 UTC, Pagebakers commented on packages/swr/src/hooks.ts
> +		const { mutate } = useSWRConfig();
No, SWR always fallback to global context by default.

2022-11-08 09:18 UTC, Pagebakers commented on packages/swr/src/hooks.ts
> +import useSWRMutation, { SWRMutationConfiguration } from 'swr/mutation';
Yes I think it's a good idea, will look into this today.

2022-11-08 12:21 UTC, StarpTech commented on packages/swr/src/hooks.ts
> +		const { mutate } = useSWRConfig();
ok

2022-11-08 15:57 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
>  		subscription: SubscriptionRequestOptions,
Fixed tests

2022-11-10 15:45 UTC, StarpTech requested changes

2022-11-10 15:45 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +				reject(new Error(`SSE connection error: ${subscription.operationName}`));
Can we log / enrich the original error? `(err)`

2022-11-10 15:45 UTC, StarpTech commented on packages/swr/package.json
>      "@wundergraph/sdk": ">=0.91.0",
Update it?

2022-11-10 15:45 UTC, StarpTech commented on packages/swr/src/hooks.test.tsx
> +		expect(hooks).toBeTruthy();
Can we validate here if `createHooks` returns the correct api?

2022-11-10 15:45 UTC, StarpTech commented on packages/swr/src/types.ts
> +export interface UseUserOptions<User> extends FetchUserRequestOptions, SWRConfiguration<User> {
`UseUserHookOptions` ?

2022-11-10 15:47 UTC, StarpTech commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> +			// .wundergraph/operations/Counter.graphql
Delete?

2022-11-10 15:48 UTC, StarpTech commented
Please rename the PR title to something more meaningful for the user e.g improve mutation support.

2022-11-10 15:59 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +				reject(new Error(`SSE connection error: ${subscription.operationName}`));
There was no valuable information available in the parameter, as it's just a generic event.

https://developer.mozilla.org/en-US/docs/Web/API/EventSource/error_event

2022-11-10 16:08 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +				reject(new Error(`SSE connection error: ${subscription.operationName}`));
ok

2022-11-10 16:09 UTC, StarpTech commented on packages/swr/src/hooks.test.tsx
> +		expect(hooks).toBeTruthy();
ok

2022-11-10 16:13 UTC, StarpTech approved these changes
LGTM

2022-11-10 16:16 UTC, merged