feat: add root path and UI
wundergraph/wundergraph pull request #308
Opened 2022-11-01 15:18 UTC by thisisnithin

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-01 15:58 UTC, StarpTech commented
Lovely. Only a minor thing: Could we use a different blue? It doesn't match so well with the pink. Maybe that blue from the "Why WunderGraph?" button from our landing?

2022-11-01 16:06 UTC, StarpTech requested changes

2022-11-01 16:06 UTC, StarpTech commented on pkg/node/nodetemplates/resources/index.gohtml
> +	<script src="https://cdn.tailwindcss.com"></script>
Are we able to enforce a version? I'm OK with it, but it could just break without notice.

2022-11-01 16:06 UTC, StarpTech commented on pkg/node/nodetemplates/template.go
> +		"/": "resources/index.gohtml",
Is `gohtml` a thing? I'd call it `.tpl`

2022-11-01 16:06 UTC, StarpTech commented on pkg/node/nodetemplates/resources/index.gohtml
> +		href="/api/main/graphql"
We can only show it if enabled, and we recommend disabling it in production. I'd point to the cloud dashboard.

2022-11-01 16:06 UTC, StarpTech commented on pkg/node/nodetemplates/resources/index.gohtml
> +	WunderGraph
Link it to our website.

2022-11-01 16:10 UTC, StarpTech requested changes

2022-11-01 16:41 UTC, jensneuse commented
The playground will only be available if activated in the config.

2022-11-01 16:42 UTC, jensneuse commented
Can you add a tooltip on the server and node status that explains what "SKIP" or the other status results mean?

2022-11-01 16:43 UTC, jensneuse commented
The commit could actually be a link to the commit.

2022-11-01 16:44 UTC, jensneuse commented
Can you make 2 sections? One for status, one for build info, to make it clear that these are two different things.

2022-11-02 07:24 UTC, thisisnithin commented on pkg/node/node.go
> +	rootPath            = "/"
Done

2022-11-02 07:24 UTC, thisisnithin commented on pkg/node/nodetemplates/resources/index.gohtml
> +	<script src="https://cdn.tailwindcss.com"></script>
We cant unfortunately.

2022-11-02 07:24 UTC, thisisnithin commented on pkg/node/nodetemplates/template.go
> +		"/": "resources/index.gohtml",
just named it html

2022-11-02 07:25 UTC, thisisnithin commented on pkg/node/nodetemplates/resources/index.gohtml
> +		href="/api/main/graphql"
the node endpoint may be public, removed the card altogether

2022-11-02 07:25 UTC, thisisnithin commented on pkg/node/nodetemplates/resources/index.gohtml
> +	WunderGraph
Done

2022-11-02 07:25 UTC, thisisnithin commented on pkg/node/nodetemplates/resources/index.gohtml
> +<div class="grid grid-cols-2 w-full gap-4 mt-12">
Done

2022-11-02 07:25 UTC, thisisnithin commented
> Can you make 2 sections? One for status, one for build info, to make it clear that these are two different things.

Done

2022-11-03 09:09 UTC, StarpTech commented
@thisisnithin I'll check this locally and merge it when everything looks good.

2022-11-03 09:21 UTC, StarpTech approved these changes
LGTM

2022-11-03 09:22 UTC, merged