feat: disable response caching when returning HTTP errors
wundergraph/wundergraph pull request #310
Opened 2022-11-02 22:03 UTC by fiam

- feat: add cachecontrol package
- refactor: use cachecontrol package to set headers
- feat: add httperror package
- feat: make all returned HTTP errors  use httperror package
- feat: add middleware to make all responses default to use no cache

2022-11-03 12:51 UTC, StarpTech requested changes

2022-11-03 12:51 UTC, StarpTech commented on pkg/authentication/authentication.go
> +	h.Private().MaxAge(0).StaleWhileRevalidate(60).Set(w)
Why setting SWR when the content is not cached at all?

2022-11-03 12:51 UTC, StarpTech commented on pkg/cachecontrol/cachecontrol.go
> +// PublicOrPrivate is a shorthand for calling Public() iff
"iff"

2022-11-03 12:51 UTC, StarpTech commented on pkg/cachecontrol/cachecontrol.go
> +func (h *Header) Disabled() *Header {
`Disabled` sounds unspecific. Maybe `DisableCache`, `NoCache` ?

2022-11-03 12:51 UTC, StarpTech commented on pkg/cachecontrol/cachecontrol.go
> +type Header struct {
Honestly, I don't see value in providing a header builder for just a few constants. Just use `fmt.Sprintf`.

2022-11-03 12:55 UTC, fiam commented on pkg/cachecontrol/cachecontrol.go
> +// PublicOrPrivate is a shorthand for calling Public() iff
https://www.merriam-webster.com/dictionary/iff

2022-11-03 12:58 UTC, jensneuse requested changes

2022-11-03 12:58 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			var cch cachecontrol.Header
Wouldn't it make sense to build the CC headers when the Handler is configured?
It looks like this config is static in regards of the request, so I think we can do it at configuration time instead of request time for each request.

2022-11-03 13:01 UTC, fiam commented on pkg/cachecontrol/cachecontrol.go
> +type Header struct {
Using `fmt.Sprintf` can lead to typos, copy pasting and repetition. See the headers that I replaced that were identical except for `public / private`. Also, if we want to make changes to the headers, having them defined in a central place makes it easier.

2022-11-03 13:09 UTC, StarpTech commented on pkg/cachecontrol/cachecontrol.go
> +type Header struct {
A builder only makes sense if we have something complex to "build". We could provide a simple function for 2 use cases and are done.

- No cache
- Cache

2022-11-03 13:09 UTC, fiam commented on pkg/authentication/authentication.go
> +	h.Private().MaxAge(0).StaleWhileRevalidate(60).Set(w)
It's actually cached. Basically, if the response is less than 60 seconds old, you're allowing the browser to reuse whatever cached response it has while at the same time asking it to refresh the cached data from the network in a non-blocking way.

2022-11-03 13:14 UTC, fiam commented on pkg/apihandler/apihandler.go
> +			var cch cachecontrol.Header
Good idea. We can set it up during startup and wrap the handler into the middleware. Error responses with explicit headers will override the header for responses that should not be cached.

2022-11-03 14:08 UTC, fiam commented on pkg/cachecontrol/cachecontrol.go
> +type Header struct {
Cache responses are determined based on what the user configures via the SDK, so we need to keep some state. For now we only have two configurable values, but expecting it to grow doesn't seem unreasonable to me. If fact, if we have a more robust way than handling them on the server side than manipulating string, we could allow more flexibility.

Regarding unit testing the cache values, what ends up happening with long strings is that people mistype/misremember the string in the code and then copy it into the test. Let's say you have `%s, max-age=%d, state-while-revalidate=%d`, then someone copies it into the test and checks that passing `(true, 10, 20)` ends up producing `public, max-age=10, state-while-revalidate=20` which will pass the test but end up with an invalid header.

On the other hand, having just 2 free functions to set the cache leaves the call sites quite ambiguous. If you see a call to `cachecontrol.EnableCache(true, 30, 30)` is not clear what it does.

With that said, if you want it with free functions I will change it to do so.

2022-11-03 14:26 UTC, fiam commented on pkg/apihandler/apihandler.go
> +			var cch cachecontrol.Header
Looking at it again, there are a lot of paths in that function and we don't have robust tests for it. Changing for a function based approach, there's no much to be gained from a performance perspective either. So I think I would leave the logic as-is.

2022-11-03 14:32 UTC, StarpTech commented on pkg/cachecontrol/cachecontrol.go
> +type Header struct {
Just go with a reasonable approach. I leave let it up to you to use just constants or functions.

2022-11-03 14:33 UTC, StarpTech commented on pkg/cachecontrol/cachecontrol.go
> +// PublicOrPrivate is a shorthand for calling Public() iff
Never heard :smile:

2022-11-03 14:43 UTC, StarpTech commented on pkg/authentication/authentication.go
> +	h.Private().MaxAge(0).StaleWhileRevalidate(60).Set(w)
No, SWR means you can work with stale data for a further 60s until the data is invalidated asynchronously, but we have never put the data into the cache. It makes no sense to me.

> stale-while-revalidate tells caches that they may continue to serve a response after it becomes stale for up to the specified number of seconds, provided that they work asynchronously in the background to fetch a new one.

2022-11-03 14:45 UTC, StarpTech commented on pkg/authentication/authentication.go
> +	h.Private().MaxAge(0).StaleWhileRevalidate(60).Set(w)
I'd even say for auth I'd disable cache.

2022-11-03 14:51 UTC, jensneuse commented on pkg/authentication/authentication.go
> +	h.Private().MaxAge(0).StaleWhileRevalidate(60).Set(w)
max-age=0 combined with stale-while-revalidate=60 will result in the following behavior:

After 0 seconds (max-age,immediately), the browser will read the user object from the HTTP cache for 60 seconds.
Each time the browser reads the cache, it also fires off a request to the server to revalidate the cache.
Combined with the ETag, the server will most likely return with a 304.

This means, we can efficiently revalidate if the user is still logged in on each browser focus event, while most of the time, the answer is just a 304 not modified.

Once we logout, we delete the in-memory cache of the browser client and fire off a get user request, which will invalidate the http cache.

I think this is the most efficient pattern to leverage the HTTP cache and keep the client in sync across tabs and windows.

2022-11-03 14:53 UTC, StarpTech commented on pkg/authentication/authentication.go
> +	h.Private().MaxAge(0).StaleWhileRevalidate(60).Set(w)
Thanks, both. Can we document this in the form of comment?

2022-11-03 14:55 UTC, StarpTech commented on pkg/authentication/authentication.go
> +	cachecontrol.EnableCache(w, false, 0, 60)
Sry, but this is hard to read with 4 arguments. Can we use a string here?

2022-11-03 15:47 UTC, fiam commented on pkg/authentication/authentication.go
> +	h.Private().MaxAge(0).StaleWhileRevalidate(60).Set(w)
I've linked Jens response in a comment

2022-11-07 18:44 UTC, fiam commented on pkg/authentication/authentication.go
> +	cachecontrol.EnableCache(w, false, 0, 60)
Changed to new function called `EnableForAuthentication()`, as discussed

2022-12-04 20:21 UTC, closed without merging