chore: improve error handling
wundergraph/wundergraph pull request #318
Opened 2022-11-07 15:06 UTC by jensneuse

This PR gracefully handles errors caused by canceled contexts when the client disconnects.

2022-11-07 15:09 UTC, fiam commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
Maybe checking `err` with `errors.Is` would be more robust and obviate the comment?

2022-11-07 15:10 UTC, StarpTech requested changes

2022-11-07 15:10 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
I think it's not correct to swallow the error from the request in case of context cancellation.

2022-11-07 15:11 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
There can be multiple causes that cancel the ctx. Contexts can be "stacked".
What matter is that the ctx was cancelled, which results in ctx.Err() not being nil.

2022-11-07 15:12 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
I think it is. The client disconnected. It's a regular operation that is "propagated" through context cancellation.
The purpose of the task was to get rid of false negatives in the logs. (Error logs that should be no logs at all, as it's caused by client disconnected)

2022-11-07 15:16 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
So, checking errors.Is is actually less robust as there will be many cases where it will not match.

2022-11-07 15:17 UTC, fiam commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
If you cancel the parent then all of the stack should be cancelled. Checking for something like `errors.Is(err, context.Canceled)` should work and help with self-documentation.

2022-11-07 15:17 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
I think you're misunderstanding this code. if ctx.Err() is not nil, something cancelled the operation (e.g. the client, a timeout, etc..) The operation by itself did not return any error, it was the http client cancellation by the ctx.

2022-11-07 15:18 UTC, fiam commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
I think early returning is fine in these. If we want to log client disconnects, we can do that at the top level in a single place (e.g. with middleware)

2022-11-07 15:22 UTC, YuriBuerov approved these changes

2022-11-07 15:31 UTC, StarpTech requested changes

2022-11-07 15:31 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
If the request fails, it is still an error. This is my proposal:

```go
if err != nil {
    h.log.Error("MutatingPostResolve mutation hook", abstractlogger.Error(err))
	http.Error(w, "MutatingPostResolve mutation hook failed", http.StatusInternalServerError)
   return
}
if ctx.Err() != nil {
    h.log.Debug("MutatingPostResolve mutation hook", abstractlogger.Error(ctx.Err()))
	http.Error(w, "MutatingPostResolve mutation hook failed", http.StatusInternalServerError)
    return
}
```

2022-11-07 17:58 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
I understand the intention, but this code will never reach `if ctx.Err()` because err is never nil if ctx.Err() is != nil

2022-11-07 19:08 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +			if ctx.Err() != nil {
Are you sure?. I thought someone could transport different errors through ctx and return value.

2022-11-08 12:26 UTC, StarpTech requested changes

2022-11-08 12:26 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +				// we've already flushed a header, so we simply return
Where did we already flush the header? Does it return 499 to the client?

2022-11-08 12:48 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +				// we've already flushed a header, so we simply return
In line 1077

2022-11-08 12:49 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +				// we've already flushed a header, so we simply return
You cannot return a header when we flushed it already.

2022-11-08 12:52 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +				// we've already flushed a header, so we simply return
ok

2022-11-08 12:52 UTC, StarpTech approved these changes
LGTM

2022-11-08 12:53 UTC, fiam approved these changes
LGTM

2022-11-08 13:02 UTC, merged