draft: implement withwundergraph ssr hoc for
wundergraph/wundergraph pull request #319
Opened 2022-11-07 15:28 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-09 11:03 UTC, Pagebakers commented
Fixes ENG-696

2022-11-10 13:48 UTC, Pagebakers commented
@StarpTech 

A few design considerations here.

There is the new `createWunderGraphNext` function that initializes the SWR hooks api for Nextjs.

```ts
import { createWunderGraphNext } from '@wundergraph/nextjs'
const { client, withWunderGraph, useQuery, useMutation, useSubscription, useUser, useAuth, useFileUpload } = createWunderGraphNext({
    client: new Client({baseURL: 'http://localhost:9991'}),
    ssr: true,
});
```

It will also be autogenerated, including the client. So you can do this.

```ts
import { withWunderGraph } from './generated/nextjs'

const App = ({ Component, pageProps }) => {
  return <Component {...pageProps />
}

export default withWunderGraph(App)
```

SSR can also be disabled per query.
```ts
export default function Home() {
  const weather = useQuery({ operationName: 'Weather', ssr: false })
}
```

1. Should SSR be enabled by default?
2. Should it be configurable as a parameter of `withWundergraph` or would setting it in  `createWunderGraphNext` good enough.
3. Any other api considerations?

2022-11-10 14:54 UTC, jensneuse commented
> @StarpTech
> 
> A few design considerations here.
> 
> There is the new `createWunderGraphNext` function that initializes the SWR hooks api for Nextjs.
> 
> ```ts
> import { createWunderGraphNext } from '@wundergraph/nextjs'
> const { withWunderGraph, useQuery, useMutation, useSubscription, useUser, useAuth, useFileUpload } = createWunderGraphNext({
>     client: new Client({baseURL: 'http://localhost:9991'}),
>     ssr: true,
> });
> ```
> 
> It will also be autogenerated, including the client. So you can do this.
> 
> ```ts
> import { withWunderGraph } from './generated/nextjs'
> 
> const App = ({ Component, pageProps }) => {
>   return <Component {...pageProps />
> }
> 
> export default withWunderGraph(App)
> ```
> 
> SSR can also be disabled per query.
> 
> ```ts
> export default function Home() {
>   const weather = useQuery({ operationName: 'Weather', ssr: false })
> }
> ```
> 
> 1. Should SSR be enabled by default?
> 2. Should it be configurable as a parameter of `withWundergraph` or would setting it in  `createWunderGraphNext` good enough.
> 3. Any other api considerations?

The API looks good to me.
1. Enabling SSR by default is ok if I can easily opt-out globally (possible?)
2. maybe make it an optional arg in `withWunderGraph` to disable it?
3. LGTM

2022-11-15 13:59 UTC, jensneuse approved these changes

2022-11-15 13:59 UTC, jensneuse commented on packages/nextjs/src/ssr-middleware.test.tsx
> +		applicationPath: 'app',
is this not deprecated?

2022-11-15 14:00 UTC, jensneuse requested changes
should this be updated to the new /app/main structure already?

2022-11-15 14:37 UTC, Pagebakers commented on packages/nextjs/src/ssr-middleware.test.tsx
> +		applicationPath: 'app',
applicationPath is deprecated, but not part of this PR.

2022-11-15 14:37 UTC, Pagebakers commented on packages/nextjs/src/ssr-middleware.test.tsx
> +		.get('/app/operations/' + operationName)
Idem

2022-11-15 14:47 UTC, fiam commented
> should this be updated to the new /app/main structure already?

I will take care of that in the other PR. We can merge this one first.

2022-11-15 14:47 UTC, fiam approved these changes
LGTM

2022-11-15 14:54 UTC, jensneuse approved these changes

2022-11-15 15:41 UTC, StarpTech requested changes
Overall very great only a few questions and possible improvements.

2022-11-15 15:41 UTC, StarpTech commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +SWR is a new peer dependency of `@wundergraph/nextjs`, add it to your project.
peerDep?

2022-11-15 15:41 UTC, StarpTech commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +useLiveQuery no longer exists, you can pass `liveQuery: true` to useQuery to turn it into a live query (if it is supported)
In what case, it is not supported?

2022-11-15 15:41 UTC, StarpTech commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +// response.data
Remove for consistency?

2022-11-15 15:41 UTC, StarpTech commented on packages/nextjs/src/types.ts
> +	 * @default wg_user
What is wg_user?

2022-11-15 15:41 UTC, StarpTech commented on packages/nextjs/src/with-wundergraph.tsx
> +					} catch (e) {}
Sure, that we don't want to log something e.g only in development?

2022-11-15 15:41 UTC, StarpTech commented on packages/nextjs/src/ssr-middleware.ts
> +			ssrCache[_key] = ssrFetcher(key).catch(() => {});
Same here. Log in development only?

2022-11-15 16:00 UTC, Pagebakers commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +SWR is a new peer dependency of `@wundergraph/nextjs`, add it to your project.
Moved it to peerDeps to make sure projects use 1 and the same version and prevent any unwanted issues with context. 

SWR 2 has these exports which a project might use.

```
import useSWRInfinite from 'swr/infinite'
import useSWRMutation from 'swr/mutation'
import useSWRImmutable from 'swr/immutable'
```

2022-11-15 16:01 UTC, Pagebakers commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +useLiveQuery no longer exists, you can pass `liveQuery: true` to useQuery to turn it into a live query (if it is supported)
Not sure what you mean? `useLiveQuery` hook is no longer exported and you need to use `useQuery` with `liveQuery: true` instead.

2022-11-15 16:26 UTC, StarpTech commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +SWR is a new peer dependency of `@wundergraph/nextjs`, add it to your project.
ok

2022-11-15 16:41 UTC, StarpTech commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +useLiveQuery no longer exists, you can pass `liveQuery: true` to useQuery to turn it into a live query (if it is supported)
> (if it is supported)

What do you mean by that?

2022-11-16 13:25 UTC, Pagebakers commented on packages/nextjs/src/ssr-middleware.ts
> +			ssrCache[_key] = ssrFetcher(key).catch(() => {});
This has been updated now.

2022-11-16 13:34 UTC, StarpTech commented on packages/nextjs/src/types.ts
> +	 * @default wg_user
ok

2022-11-16 13:34 UTC, StarpTech commented on docs/migrations/nextjs-0.3.0-0.4.0.md
> +// response.data
ok

2022-11-16 13:35 UTC, StarpTech commented on packages/nextjs/src/ssr-middleware.ts
> +			ssrCache[_key] = ssrFetcher(key).catch(() => {});
ok

2022-11-16 13:40 UTC, StarpTech approved these changes
LGTM

2022-11-16 13:57 UTC, merged