feat: add create-wundergraph-app command
wundergraph/wundergraph pull request #320
Opened 2022-11-07 18:25 UTC by JivusAyrus

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-07 18:32 UTC, jensneuse commented
@JivusAyrus I think you should add a README.md with info on usage, etc...

2022-11-08 11:20 UTC, jensneuse requested changes
Are you able to add at least some tests?

2022-11-08 11:20 UTC, jensneuse commented on packages/create-wundergraph-app/README.md
> +## Usage
can you put Usage above local usage?

2022-11-08 11:20 UTC, jensneuse commented on packages/create-wundergraph-app/src/helpers/getRepoInfo.ts
> +	// const repoContent = await got
remove? keep?

2022-11-08 11:28 UTC, Pagebakers requested changes

2022-11-08 11:28 UTC, Pagebakers commented on packages/create-wundergraph-app/src/helpers/getRepoInfo.ts
> +	// const repoContent = await got
Why is this commented out?

2022-11-08 11:28 UTC, Pagebakers commented on packages/create-wundergraph-app/src/index.ts
> +	.option('-L, --link [githubLink]', `Initialize a wundergraph app from the templates on GitHub`)
Can improve the descriptions a bit here.

`Initialize a WunderGraph app from the examples in the official WunderGraph repository`

`Initialize a WunderGraph app from a Github URL`

2022-11-08 11:53 UTC, JivusAyrus commented on packages/create-wundergraph-app/README.md
> +## Usage
Done

2022-11-08 11:53 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepoInfo.ts
> +	// const repoContent = await got
Removed

2022-11-08 11:53 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepoInfo.ts
> +	// const repoContent = await got
Removed

2022-11-08 11:54 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/index.ts
> +	.option('-L, --link [githubLink]', `Initialize a wundergraph app from the templates on GitHub`)
Done

2022-11-08 11:56 UTC, JivusAyrus commented
> Are you able to add at least some tests?

Nope. Will take a look at it

2022-11-08 13:06 UTC, StarpTech requested changes
Please add CI with a simple integration test.

2022-11-10 07:31 UTC, jensneuse commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		const currentDirectory = process.cwd();
I'd do this in temp:
https://www.geeksforgeeks.org/node-js-os-tmpdir-method/

2022-11-10 07:33 UTC, jensneuse approved these changes

2022-11-10 07:33 UTC, jensneuse commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		const currentDirectory = process.cwd();
I'd do this in temp:
https://www.geeksforgeeks.org/node-js-os-tmpdir-method/

2022-11-10 07:45 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		const currentDirectory = process.cwd();
As I am calling the same function, it will clone the repository in the same directory. In the test, I am accessing the current directory to delete it.

2022-11-10 07:46 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		const currentDirectory = process.cwd();
Should I create another function, which is the same as the original one, but uses the temp directory?

2022-11-10 07:47 UTC, jensneuse commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		const currentDirectory = process.cwd();
`getRepository ` could take another optional arg to set the working directory.

2022-11-10 07:49 UTC, jensneuse requested changes

2022-11-10 07:49 UTC, jensneuse commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		await fsp.access(currentDirectory);
Can you add a "real" check if we cloned something into the directory? e.g. it should contain a "package.json" or something else that all examples should have in common.

2022-11-10 09:53 UTC, fiam commented on packages/create-wundergraph-app/src/helpers/getRepository.ts
> +};
I would refactor this so we don't end up calling `downloadAndExtractRepo()` from 3 places. Split the resolution to a separate function, e.g.

```
const repo = resolveRepository(exampleName, githubLink);

const resolvedProjectPath = await createDirectory(projectName);
 	await retry(
 		() =>
 			downloadAndExtractRepo({
 				root: ...,
 				repoOwnerName:repo.owner,
 				repoName: repo.name,
 				branch: repo.branch,
 				filePath: repo.path,
 			}),
 		{
 			retries: 3,
 		}
 	);

2022-11-10 10:22 UTC, StarpTech requested changes

2022-11-10 10:22 UTC, StarpTech commented on packages/create-wundergraph-app/README.md
> +```shell
Could you try to explain the different commands in use cases? e.g

1. How to clone an example from the official WunderGraph Repository
2. How to clone an arbitrary WunderGraph Template Repository
3. ....

2022-11-10 10:22 UTC, StarpTech commented on packages/create-wundergraph-app/package.json
> +    "inquirer": "^8.0.0",
Deps required to run the application should be in `dependencies` not `devDependencies`

2022-11-10 10:22 UTC, StarpTech commented on packages/create-wundergraph-app/src/helpers/createDirectory.ts
> +			process.exit(1);
The process should not exit in a method except in the primary main method. Errors are propagated through throwing and catching. Rethrow the error here.

2022-11-10 10:22 UTC, StarpTech commented on packages/create-wundergraph-app/src/helpers/getRepoInfo.ts
> +		process.exit(1);
Same here.

2022-11-10 10:22 UTC, StarpTech commented on packages/create-wundergraph-app/src/helpers/getRepository.ts
> +			await retry(
:+1:

2022-11-10 16:30 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		const currentDirectory = process.cwd();
Done 👍

2022-11-10 16:30 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/tests/index.test.ts
> +		await fsp.access(currentDirectory);
Done

2022-11-10 16:31 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepository.ts
> +	try {
Removed console.log

2022-11-10 16:35 UTC, JivusAyrus commented on packages/create-wundergraph-app/package.json
> +    "inquirer": "^8.0.0",
Done

2022-11-10 16:36 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepoInfo.ts
> +		process.exit(1);
Done

2022-11-10 16:38 UTC, JivusAyrus commented on packages/create-wundergraph-app/README.md
> +```shell
Done

2022-11-10 17:34 UTC, StarpTech requested changes

2022-11-10 17:34 UTC, StarpTech commented on packages/create-wundergraph-app/src/helpers/getRepoInfo.ts
> +		throw 'The given link is not a github url';
always throw an error no string.

2022-11-10 20:52 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepository.ts
> +};
Done

2022-11-11 08:22 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/createDirectory.ts
> +			process.exit(1);
Done

2022-11-11 08:35 UTC, fiam approved these changes
LGTM

2022-11-11 10:37 UTC, StarpTech approved these changes
LGTM

2022-11-11 12:46 UTC, Pagebakers approved these changes

2022-11-11 12:51 UTC, merged