feat: logging, request id
wundergraph/wundergraph pull request #323
Opened 2022-11-08 08:43 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-08 12:14 UTC, YuriBuerov commented on cli/commands/generate.go
> -					abstractlogger.String("runnerName", "config-runner"),
correct

2022-11-08 12:48 UTC, StarpTech requested changes

2022-11-08 12:48 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +type requestIDKey struct{}
I'd favor `type requestIDKey string`

```
k := favContextKey("language")
ctx := context.WithValue(request.Context(), k, requestID)
```

2022-11-08 12:52 UTC, YuriBuerov commented on pkg/apihandler/apihandler.go
> +type requestIDKey struct{}
why? https://pkg.go.dev/context#WithValue

2022-11-08 12:56 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +type requestIDKey struct{}
Because it is more explicit and easier to debug. You use a unique struct as an identifier although a string is sufficient.  In the example of `WithValue` https://pkg.go.dev/context#WithValue they use the same approach.

2022-11-08 12:57 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +type requestIDKey struct{}
Check out the example. `type requestIDKey string` is not of type string.

2022-11-08 13:00 UTC, jensneuse requested changes
Nice and clean implementation of injecting the request ID into the context.

3 things I'd add:
1. inject the request ID into hook middleware requests
2. inject the request ID into internal requests (when a hook uses the internal client)
3. inject the request ID into origin requests via the transport (the ctx automatically injects the request ID into the transport, so we can pick it up in the transport and inject it into origin http requests)

2022-11-08 13:02 UTC, StarpTech commented on pkg/node/node.go
> +		With(zap.String("component", "@wundergraph/node"))
Yes. We call it `wundernode` in the cloud to differentiate between a node with a running hooks server and without.

2022-11-08 13:03 UTC, StarpTech approved these changes
LGTM

2022-11-09 17:23 UTC, StarpTech requested changes

2022-11-09 17:23 UTC, StarpTech commented on packages/sdk/src/middleware/server.ts
> +			return req.headers['x-request-id']?.toString() || uuidv4();
We don't need to fall back here because the hooks server can't be called alone.

2022-11-09 17:23 UTC, StarpTech commented on pkg/authentication/authentication.go
> +		if ctx.Err() != nil {
@jensneuse

2022-11-09 17:23 UTC, StarpTech commented on pkg/hooks/hooks.go
> +	if requestID := logging.RequestIDFromContext(ctx); requestID != "" {
It should never happen that we have no request id. I'd log a warning here.

2022-11-09 17:27 UTC, StarpTech requested changes

2022-11-09 17:27 UTC, StarpTech commented on pkg/apihandler/apitransport.go
> +	request.Header.Set("X-Request-Id", logging.RequestIDFromContext(request.Context()))
Missing `!= ""` check with warning log.

2022-11-09 17:27 UTC, StarpTech commented on pkg/scriptrunner/scriptrunner.go
> +					zap.Any("startTs", status.StartTs),
I think zap has a concrete type for this.

2022-11-09 18:10 UTC, YuriBuerov commented on packages/sdk/src/middleware/server.ts
> +			return req.headers['x-request-id']?.toString() || uuidv4();
`return req.headers['x-request-id']!.toString()` ?

2022-11-09 18:46 UTC, jensneuse commented on pkg/authentication/authentication.go
> +		if ctx.Err() != nil {
@YuriBuerov we should use the same pattern like here:
https://github.com/wundergraph/wundergraph/blob/68b34d7b5436dfe8d88c7e3a27e0975a263e5034/pkg/apihandler/apihandler.go#L2243

2022-11-09 18:49 UTC, YuriBuerov commented on pkg/authentication/authentication.go
> +		if ctx.Err() != nil {
thanks, I'll fix it, I didn't change it though

2022-11-09 18:51 UTC, jensneuse commented on pkg/authentication/authentication.go
> +		if ctx.Err() != nil {
Yes, I know. I forgot to change it.

2022-11-09 18:52 UTC, YuriBuerov commented on pkg/apihandler/apitransport.go
> +	request.Header.Set("X-Request-Id", logging.RequestIDFromContext(request.Context()))
@jensneuse  where should we place it? `logging` package?

2022-11-09 18:53 UTC, jensneuse commented on pkg/apihandler/apitransport.go
> +	request.Header.Set("X-Request-Id", logging.RequestIDFromContext(request.Context()))
sounds good

2022-11-09 18:54 UTC, YuriBuerov commented on pkg/apihandler/apitransport.go
> +	request.Header.Set("X-Request-Id", logging.RequestIDFromContext(request.Context()))
and what is our final decision regarding logging warning in case if req id is empty? (my comment above)

2022-11-09 18:57 UTC, jensneuse commented on pkg/apihandler/apitransport.go
> +	request.Header.Set("X-Request-Id", logging.RequestIDFromContext(request.Context()))
How about adding a test that ensures this behaviour is actually impossible? 
A test like this:
https://github.com/wundergraph/wundergraph/blob/ad02a27af5dddbcf8e1126e5bf32c949005630b2/pkg/node/node_test.go#L154

Create a mock origin. Send a request to the gateway (including request ID), expect request ID to be sent to mock origin.

2022-11-10 16:32 UTC, YuriBuerov commented
> @YuriBuerov did you test that the request-id is correctly propagated from Node -> hook -> another-hook -> onOriginResponse -> postHook ?

@StarpTech  yes

2022-11-10 16:34 UTC, StarpTech approved these changes
LGTM

2022-11-14 09:49 UTC, jensneuse approved these changes

2022-11-14 10:16 UTC, merged