feat: remove app/main from URL structure
wundergraph/wundergraph pull request #335
Opened 2022-11-11 15:32 UTC by fiam

Fixes ENG-701, ENG-703, ENG-704, ENG-705, ENG-706, ENG-730

- feat: remove /<app-name>/main prefix from router and pb definition
- chore(docs): update docs to reflect changes to WunderGraph protocol
- chore(docs): update docs to reflect changes to WunderGraph protocol
- fix: update code generation (#333)
- feat: update URLs in testapps for new style
- feat: remove /<app-name>/main prefix from router and pb definition
- fix: update code generation (#333)
- feat: drop Client applicationPath and associated properties
- fix: port apollo-federation example to new URL/API
- fix: update /auth0-oidc-authentication to new URL/API
- fix: update caching example to new URL/API
- fix: update cross-api-joins to new URL/API
- fix: update faunadb-nextjs to new URL/API
- fix: update fragments example to new URL/API
- fix: update golang-client example to new URL/API
- fix: update graphql-sse-subscriptions example to new URL/API
- fix: update graphql-subscriptions-hooks example to new URL/API
- fix: update graphql-ws-subscriptions example to new URL/API
- fix: update graphql-yoga-sse-subscriptions example to new URL/API
- fix: update hooks example to new URL/API
- fix: update inject-bearer example to new URL/API
- fix: update keycloak-oidc-authentication example to new URL/API
- fix: update migrate-from-apollo example to new URL/API
- fix: update nextjs example to new URL/API
- fix: update nextjs-postgres-prisma to new URL/API
- fix: update nextjs-swr example to new URL/API
- fix: update rbac example to new URL/API
- fix: upadte  schema-extension example to use new URL/API
- fix: update simple example to new URL/API
- fix: update webhooks example to new URL/API
- fix: update URLs in README files for new style
- fix: update publish-install-api to new URL/API
- fix: update graphql-hasura-subscriptions to new URL/API
- fix: permissions in graphql-apollo-subscriptions example
- fix: update graphql-apollo-subscriptions example to new URL/API
- fix: typo in graphql-apollo-subscriptions README
- fix: update postgres example to new URL/API
- fix: update nextjs-postgres-user-filters example to new URL/API
- docs: fix old-style URLs in a couple of pages
- feat: add redirect for old-style URLs

2022-11-14 11:42 UTC, jensneuse approved these changes
LGTM

2022-11-15 16:42 UTC, StarpTech requested changes

2022-11-15 16:42 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +	r.router.MatcherFunc(func(r *http.Request, rm *mux.RouteMatch) bool {
I thought, we won't do it?

2022-11-15 16:42 UTC, StarpTech commented
Did you also consider the wg templates in wunderctl?

2022-11-15 16:47 UTC, fiam commented on pkg/apihandler/apihandler.go
> +	r.router.MatcherFunc(func(r *http.Request, rm *mux.RouteMatch) bool {
We decided to add it for a few releases, to help users that might not read the release notes. If the old style URL is used, a warning is printed in the logs to give them a heads up.

2022-11-15 16:48 UTC, fiam commented
> Did you also consider the wg templates in wunderctl?

No, I didn't update those. I understand that those are going away as soon as the new create-wundergraph-app is merged.

2022-11-15 16:51 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +	r.router.MatcherFunc(func(r *http.Request, rm *mux.RouteMatch) bool {
ok

2022-11-15 16:52 UTC, StarpTech commented
> No, I didn't update those. I understand that those are going away as soon as the new create-wundergraph-app is merged.

Yes, but then you need to coordinate with @JivusAyrus and only merge it after that.

2022-11-15 17:02 UTC, fiam commented
> > No, I didn't update those. I understand that those are going away as soon as the new create-wundergraph-app is merged.
> 
> 
> 
> Yes, but then you need to coordinate with @JivusAyrus and only merge it after that.

No problem, I will wait for Suvij's PR to be merged.

2022-11-16 16:59 UTC, StarpTech approved these changes
LGTM, but please coordinate with @JivusAyrus before merge

2022-11-17 13:55 UTC, merged