feat: react query client
wundergraph/wundergraph pull request #340
Opened 2022-11-16 13:11 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-21 09:13 UTC, StarpTech approved these changes
Awesome work!

2022-11-21 10:13 UTC, StarpTech commented on packages/react-query/CHANGELOG.md
> +All notable changes to this project will be documented in this file.
ok, let's see

2022-11-21 10:22 UTC, thisisnithin approved these changes

2022-11-21 11:28 UTC, StarpTech requested changes
Any reason why you didn't add type tests?

2022-11-21 13:29 UTC, Pagebakers commented
> Any reason why you didn't add type tests?

No specific reason, I'll add them.

2022-11-21 15:34 UTC, Pagebakers commented
@StarpTech Updated tests and added type tests to the package.

2022-11-22 12:24 UTC, StarpTech approved these changes
LGTM

2022-11-22 12:40 UTC, merged