docs: advanced s3 spec
wundergraph/wundergraph pull request #344
Opened 2022-11-17 17:34 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-18 10:55 UTC, jensneuse requested changes

2022-11-18 10:55 UTC, jensneuse commented on specs/advanced-s3-support.md
> +      uploads: {
I'd call this uploadProfiles.

Btw. what happens if there's no upload profile at all?

2022-11-18 10:55 UTC, jensneuse commented on specs/advanced-s3-support.md
> +          meta: {
I'm not sure if this will work.
I think it would be easier to have something like zod to generate a JSON Schema, which can be used to generate the types for the wundergraph.server.ts.

2022-11-21 08:24 UTC, Pagebakers commented on specs/advanced-s3-support.md
> +      uploads: {
I like it.

When no profiles are configured, it will fallback to the default functionality as described.

2022-11-21 08:27 UTC, Pagebakers commented on specs/advanced-s3-support.md
> +          meta: {
I didn't want to make a hard dependency on Zod yet since that would be an RFC on itself I think, but I would love to see it. The current meta object in the spec is a JSON schema defined as a js object, so it can be typed.

2022-11-21 08:41 UTC, Pagebakers commented on specs/advanced-s3-support.md
> +          meta: {
We could create a helper for this that returns the JSON schema as a string. It could accept a simple object by default and it allows to use any other implementation like Zod.

```ts
meta: createMetaSchema({
  postId: 'string'
})
```

or we accept this as the default (I like the simplicity of this)

```ts
meta: {
   postId: 'string
}
```

And allow schema to be transformed from zod or other libs.

```ts
meta: metaSchemaFromZod(z.object({
  
}))
```

2022-11-24 07:44 UTC, jensneuse commented on specs/advanced-s3-support.md
> +          meta: {
ok, makes sense

2022-11-24 07:44 UTC, jensneuse approved these changes

2022-11-24 13:20 UTC, fiam approved these changes
LGTM. I like the recap of the problems at the end, good job.

2022-12-05 09:14 UTC, merged