feat: add WunderGraph testing library
wundergraph/wundergraph pull request #345
Opened 2022-11-17 17:40 UTC by fiam

- feat: add wunderctl node url subcommand
- feat: add wunderctlSubprocess
- feat: add initial testing framework
- feat: add tests to simple example

2022-12-07 16:34 UTC, Pagebakers requested changes
Really great work! A few small comments.

2022-12-07 16:34 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/testing.md
> +WunderGraph comes with builtin support for running tests against your APIs, using a our type-safe
I think we can drop type-safe no? Or rephrase.

`fully typesafe using our TypeScript client.`

2022-12-07 17:26 UTC, fiam commented on packages/sdk/src/codegen/templates/typescript/client.template.ts
> +export const createClient = (config?: ClientConfigInit) => {
Good idea, I've changed it.

2022-12-07 17:31 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +WunderGraph comes with builtin support for running tests against your APIs, using a our type-safe
I agree, I think it reads better if we drop `type-safe`

2022-12-07 17:45 UTC, StarpTech requested changes

2022-12-07 17:45 UTC, StarpTech commented on docs-website/src/pages/docs/guides/testing.md
> +You can create as many `Server` instances as you like, they will run in parallel without interfering
I should rephrase it. Right now, there is no reason to start more than one, and you have to create multiple if you want to split your tests into multiple files.

2022-12-07 17:45 UTC, StarpTech commented on packages/sdk/src/testing/index.ts
> +	private async beforeTest(): Promise<void> {
Just `start` and `stop`?

2022-12-07 21:39 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +Our testing library is framework agnostic, so you can use it coupled with your preferred test
Fixed

2022-12-07 21:40 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +  await wg.setupUp()
Fixed

2022-12-07 21:45 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +You can create as many `Server` instances as you like, they will run in parallel without interfering
I've rephrased it from a different angle, encouraging users to create as little instances as possible. Let me know what you think.

2022-12-07 21:48 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +  wg.test(async () => {
I agree, having a single way to do something is better than having two, it makes everything clearer.

Give me another day to think to try to get the automatic API right. The biggest problem right now is the ergonomics with testing frameworks that require test functions to accept an argument (like ava). If I can't find a suitable solution, 

If we can't find a way to use the automatic API with concurrent tests, we'll go with the "manual" one (using beforeAll/afterAll or equivalent)

2022-12-07 23:17 UTC, StarpTech commented on docs-website/src/pages/docs/guides/testing.md
> +## Headless testing
I've never heard the term headless in testing expect if it comes to frontend testing e.g with playwright. I'd go with integration which is a term.

2022-12-08 10:06 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +  wg.test(async () => {
Removed automatic API

2022-12-08 10:07 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +## Headless testing
Changed to `integration`

2022-12-08 10:18 UTC, Pagebakers approved these changes
awesome

2022-12-08 10:19 UTC, jensneuse requested changes

2022-12-08 10:24 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +const wg = new Server({ createClient })
I'll rename it

2022-12-08 10:26 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +const wg = new Server({ createClient })
This is a bit tricker because there's no fixed location for `client.ts`, we're relying on the user to provide the correct path in the import. Do you think we should generate a `tests.ts` file with a template that imports `Client`? Seems like a lot of work for a minor gain to me, but we can do it that way.

2022-12-08 10:43 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +const wg = new Server({ createClient })
Renamed

2022-12-08 12:52 UTC, fiam commented on docs-website/src/pages/docs/guides/testing.md
> +const wg = new Server({ createClient })
I've prototyped this with an additional `templates.typescript.testing` template and I'm linking it a lot. Not just for avoiding passing the `createClient`, but also as plumbing for additional testing boilerplate (e.g. mocks). I'll clean it up and push.

2022-12-08 14:05 UTC, StarpTech requested changes

2022-12-08 14:05 UTC, StarpTech commented on examples/simple/package.json
> +    "@types/node-fetch": "^2.6.2",
Should be in devDeps

2022-12-08 14:07 UTC, fiam commented on examples/simple/package.json
> +    "@types/node-fetch": "^2.6.2",
Good catch, fixed

2022-12-08 14:09 UTC, StarpTech requested changes

2022-12-08 14:09 UTC, StarpTech commented on packages/sdk/src/testing/index.ts
> +				if (maxWaitMs > 0 && new Date().getTime() - started > maxWaitMs) {
Please log the original error

2022-12-08 14:09 UTC, StarpTech commented on packages/sdk/src/testing/index.ts
> +				clearTimeout(id);
You should clean the timeout also in catch case.

2022-12-08 15:46 UTC, fiam commented on packages/sdk/src/testing/index.ts
> +				if (maxWaitMs > 0 && new Date().getTime() - started > maxWaitMs) {
We need to add more context, otherwise it's just going to say `fetch() failed` or something like that which might look like something else failed, right?

2022-12-08 15:57 UTC, fiam commented on packages/sdk/src/testing/index.ts
> +				clearTimeout(id);
Fixed, PTAL

2022-12-08 16:15 UTC, StarpTech commented on packages/sdk/src/testing/index.ts
> +				if (maxWaitMs > 0 && new Date().getTime() - started > maxWaitMs) {
This is the `start` method. I think you mixed it up.

2022-12-08 16:39 UTC, fiam commented on packages/sdk/src/testing/index.ts
> +				if (maxWaitMs > 0 && new Date().getTime() - started > maxWaitMs) {
No, I knew which method you were referring to. This loop is waiting for the server to come up, checking the health endpoint. The only errors we might get here are either fetch failing or a problem decoding/checking the JSON returned from the health endpoint. I think those need to be augmented with some context, otherwise the user will have no clue were they came from and might even think the problem is in their tests/code.

2022-12-08 20:06 UTC, StarpTech requested changes

2022-12-08 20:06 UTC, StarpTech commented on packages/sdk/src/testing/index.ts
> +		while (true) {
I'd use this lib to cover retry and max retries https://github.com/normartin/ts-retry-promise

2022-12-08 21:06 UTC, StarpTech reviewed
LGTM

2022-12-08 21:45 UTC, jensneuse approved these changes

2022-12-09 09:15 UTC, StarpTech requested changes

2022-12-09 09:15 UTC, StarpTech commented on packages/sdk/src/codegen/templates/typescript/testing.template.ts
> +import { ServerOptions, WunderGraphTestServer as WunderGraphTestServerInternal } from '@wundergraph/sdk/testing';
Code that is not tightly coupled to the type generation should always live in a codebase for maintainability reasons. It's great to have one single import, but the downsides are not worth it. There are two ways.

1. You put this code in the SDK and export only the class
2. You put everything in the SDK

2022-12-09 12:41 UTC, StarpTech approved these changes
LGTM

2022-12-09 12:41 UTC, merged