feat(create-wundergraph-app): download latest tag instead of main
wundergraph/wundergraph pull request #349
Opened 2022-11-18 12:58 UTC by fiam

Downloading from the main branch prevents us from making breaking
changes, since the examples would stop working until the next SDK with
the breaking changes is released.

When using the wundegraph repository as the example source, first
retrieve the tags and use the latest tag starting with @wundergraph/sdk

2022-11-21 08:29 UTC, JivusAyrus requested changes

2022-11-21 08:29 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepository.ts
> +				ref: 'main',
Shouldn't this be ' ref: ref || "main" '

2022-11-21 08:29 UTC, Pagebakers approved these changes
Nice one!

2022-11-22 15:39 UTC, fiam commented on packages/create-wundergraph-app/src/helpers/getRepository.ts
> +				ref: 'main',
You're right, good catch. I'll update it.

2022-11-22 16:02 UTC, fiam commented on packages/create-wundergraph-app/src/helpers/getRepository.ts
> +				ref: 'main',
Fixed, PTAL

2022-11-22 16:35 UTC, JivusAyrus approved these changes
LGTM

2022-11-22 20:46 UTC, merged