chore: some extra logging for CI
wundergraph/wundergraph pull request #365
Opened 2022-11-23 15:26 UTC by fiam

2022-11-24 07:40 UTC, jensneuse requested changes

2022-11-24 07:40 UTC, jensneuse commented on pkg/datasources/database/engine.go
> +	fmt.Println("ensurePrisma()", time.Now())
I'd rename this to "installing prisma dependencies"

2022-11-24 07:54 UTC, fiam commented on pkg/datasources/database/engine.go
> +	fmt.Println("ensurePrisma()", time.Now())
I don’t intend to merge this, at least for the time being. The messages are just for debugging where it gets stuck.

2022-12-12 19:16 UTC, jensneuse approved these changes
Amazing! Thank you.

2022-12-12 20:10 UTC, fiam commented
@jensneuse Wait a bit. I need to test on Windows.

2022-12-12 20:24 UTC, fiam commented
@jensneuse Changed `syscall.Kill()` to `os.Process.Kill()`, which provides a better implementation on Windows. Good to go! Thanks for the review 👍

2022-12-12 20:28 UTC, StarpTech requested changes

2022-12-12 20:28 UTC, StarpTech commented on pkg/datasources/database/engine.go
> +	exitCh := make(chan error, 1)
Why buffered?

2022-12-12 20:31 UTC, fiam commented on pkg/datasources/database/engine.go
> +	exitCh := make(chan error, 1)
The idea was to prevent the goroutine waiting for the exit to block, but it should be fine with an unbuffered channel because the select in the parent goroutine will be already waiting by that point.

2022-12-12 20:40 UTC, StarpTech commented on pkg/datasources/database/engine.go
> +	exitCh := make(chan error, 1)
If it is not needed we should remove it.

2022-12-12 20:42 UTC, fiam commented on pkg/datasources/database/engine.go
> +	exitCh := make(chan error, 1)
Changed 👍

2022-12-13 09:11 UTC, merged