feat: add wundergraph todo example app
wundergraph/wundergraph pull request #367
Opened 2022-11-24 10:14 UTC by kaleem68

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-11-24 10:37 UTC, Pagebakers requested changes
A few comments and needs some more work on the optimistic updates, but nice and clean code 👌

2022-11-24 10:37 UTC, Pagebakers commented on examples/nextjs-todos/.wundergraph/wundergraph.server.ts
> +			serverName: 'gql',
We can remove this.

2022-11-24 10:37 UTC, Pagebakers commented on examples/nextjs-todos/package.json
> +  "name": "wundergraph-nextjs-postgres-prisma",
change the name to `wundergraph-nextjs-todo`

2022-11-24 10:37 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +						getTodo: result.db_createOneTodo,
This one is a bit tricky, you should update and return `db_findManyTodo` here, format should be the same as the return value of the Todos query.

2022-11-24 10:37 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +							placeholder={'Add todo'}
Rather be consistent with string values and use double quotes everywhere, unless you use a string template 
{\`${var}\`}

2022-11-24 10:37 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +				if (todo.id === updatedCompleteTodoStatus.db_updateOneTodo.id) {
Nice one!

2022-11-26 00:41 UTC, kaleem68 commented on examples/nextjs-todos/.wundergraph/wundergraph.server.ts
> +			serverName: 'gql',
Removed.

2022-11-26 00:41 UTC, kaleem68 commented on examples/nextjs-todos/package.json
> +  "name": "wundergraph-nextjs-postgres-prisma",
Changed.

2022-11-26 00:41 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +						getTodo: result.db_createOneTodo,
This is updated, please review it.

2022-11-26 00:42 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +							placeholder={'Add todo'}
Done.

2022-11-26 00:47 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +				if (todo.id === updatedCompleteTodoStatus.db_updateOneTodo.id) {
Thanks :)

2022-11-26 10:00 UTC, Pagebakers approved these changes

2022-11-26 10:00 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +							placeholder={'Add todo'}
Are you sure, your changes are pushed? I don't see any difference.

2022-11-27 05:58 UTC, kaleem68 commented on examples/nextjs-todos/components/TodoItem.tsx
> +			{ revalidate: true, rollbackOnError: true }
Updated.

2022-11-27 05:58 UTC, kaleem68 commented on examples/nextjs-todos/components/TodoItem.tsx
> +			{ revalidate: true, rollbackOnError: true }
Updated.

2022-11-27 05:58 UTC, kaleem68 commented on examples/nextjs-todos/components/TodoItem.tsx
> +							${editMode ? `mb-1` : ``}
Added.

2022-11-28 15:57 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +							placeholder={'Add todo'}
It is added now, there is a `pre-commit `script that runs on each commit and converts the strings to `single quotes` so I'm using `--no-verify` to skip the `pre-commit` 

e.g.`git commit -m "<msg>" --no-verify`

2022-12-02 08:33 UTC, Pagebakers requested changes

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/.wundergraph/wundergraph.config.ts
> +			templates: [templates.typescript.client, new NextJsTemplate()],
templates.typescript.cleint should not be required anymore with the latest release

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/README.md
> +# WunderGraph Postgres Starter
Update the readme title and description.

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/components/TodoItem.tsx
> +		setCurrentTodo(initialCurrentTodo);
Not sure why you first use useMemo here and then useEffect to update the state variable. Why not directly access todo from props, and just have a state variable for the title field value?

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/interfaces.tsx
> +	updateTitle: (updateTodoTitle: EditTodoInput) => void;
instead of passing these as props, I'd create hooks for them, so they are portable.

```useUpdateTitleMutation()```
```useUpdateCompleteStatusMutation()```

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +	async function addTodo() {
I'd create a hook for each mutation, so you keep the page component lightweight, and contain the logic in re-usable hooks.

`useAddTodoMutation` for example.

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +								WunderGraph{" "}
Both {" "} seem redundant here.

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +					<div className={"mt-2"}>
Ok now I see why linting wasn't working correctly.

You need to use the double quotes directly instead of escaping them with {}
`<div className="mt-2">`

2022-12-02 08:33 UTC, Pagebakers commented on examples/nextjs-todos/pages/index.tsx
> +		await Promise.all(newOrder.map((item: TodoOrder) => updateTodoOrder.trigger(item)));
This works, but it'll be very inefficient when there are a lot of todos, since you loop over all of them and then update the order individual.

One solution could be something like this; 
Send the item id, newOrder, then on the server you can run these queries.
1. If the newOrder is less than the oldOrder, increase the order value of all items that are >= newOrder and < oldOrder.
2. If the newOrder is greater than the oldOrder, decrease the order value of all items that are <= newOrder and > oldOrder
3. Update the item order to newOrder.

2022-12-02 22:10 UTC, kaleem68 commented on examples/nextjs-todos/components/TodoItem.tsx
> +		setCurrentTodo(initialCurrentTodo);
removed `useEffect` and `useMemo`

2022-12-02 22:10 UTC, kaleem68 commented on examples/nextjs-todos/README.md
> +# WunderGraph Postgres Starter
Updated.

2022-12-02 22:10 UTC, kaleem68 commented on examples/nextjs-todos/.wundergraph/wundergraph.config.ts
> +			templates: [templates.typescript.client, new NextJsTemplate()],
Removed.

2022-12-02 22:12 UTC, kaleem68 commented on examples/nextjs-todos/interfaces.tsx
> +	updateTitle: (updateTodoTitle: EditTodoInput) => void;
Following hooks added `useAddTodoMutation`, `useDeleteTodoMutation`, `useUpdateCompleteStatusMutation`, `useUpdateTitleMutation`.

2022-12-02 22:13 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +	async function addTodo() {
Following hooks added `useAddTodoMutation`, `useDeleteTodoMutation`, `useUpdateCompleteStatusMutation`, `useUpdateTitleMutation`.

2022-12-02 22:13 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +								WunderGraph{" "}
Both removed.

2022-12-02 22:19 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +					<div className={"mt-2"}>
This is a bit tricky

this `<div className="mt-2">` indeed works 

but to use `clsx` we need to use `{}`  and if you use `{}` it replaces `""` to `''`

It will be as following
```diff
- className={clsx(["flex justify-between pt-4 pb-2 m-2 px-2 w-72 hover:bg-zinc-600 hover:rounded-md"])}
+ className={clsx(['flex justify-between pt-4 pb-2 m-2 px-2 w-72 hover:bg-zinc-600 hover:rounded-md'])}

```

2022-12-05 05:02 UTC, kaleem68 commented on examples/nextjs-todos/pages/index.tsx
> +		await Promise.all(newOrder.map((item: TodoOrder) => updateTodoOrder.trigger(item)));
I think I have added this "optimal" approach for the dnd reorder update in `useReorderTodoMutation` hook, the hook abstracts these 3 steps.

2022-12-05 13:43 UTC, Pagebakers requested changes
I'm running the app locally but running into issues.

- npm start, only starts postgress and migrations, it doesn't start the wundernode and app.
- client.ts is not generated, so the app doesn't run, make sure all packages are up to date.
- inline editing is opened when i start dragging.
- alignment of the add todo input and the items below still isn't correct.
- border of the items still looks off, there should be some space between the border and the background hover.
- when editing an item, the background should stay gray and the text should keep the same size and positioning.

2022-12-06 12:44 UTC, Pagebakers requested changes

2022-12-06 12:44 UTC, Pagebakers commented on examples/nextjs-todos/package.json
> +  "name": "wundergraph-nextjs-todo",
Fix typo the name is wundergraph-nextjs-todos

2022-12-07 13:38 UTC, kaleem68 commented on examples/nextjs-todos/.wundergraph/wundergraph.operations.ts
> +	operations: {
Could you elaborate a bit on "dropped the fields with default values" which fields?

2022-12-07 15:12 UTC, kaleem68 commented on examples/nextjs-todos/seed/seed.ts
> +seed();
Removed `seed` folder and `seed/seed.ts`

2022-12-07 15:34 UTC, kaleem68 commented on examples/nextjs-todos/.wundergraph/wundergraph.operations.ts
> +	operations: {
Which of the fields is the default, could you be a little specific?

2022-12-07 15:42 UTC, fiam commented on examples/nextjs-todos/.wundergraph/wundergraph.operations.ts
> +	operations: {
Sure, apologies for the lack of specificity. I wasn't sure which ones exactly could be dropped. I would only remove `custom: {}`, the rest are mandatory (for now). I will see if we can make at least some of the rest optional, that's a bit of boilerplate that we could take away.

2022-12-08 09:14 UTC, Pagebakers approved these changes

2022-12-08 09:19 UTC, Pagebakers commented
@kaleem68 pkg/wgpb/wundernode_config.pb.go is out of date, can you run `make` and check in the update file, then we can merge this.

2022-12-08 11:01 UTC, merged