feat: make detecting invalid operations easier, allow empty ones
wundergraph/wundergraph pull request #374
Opened 2022-11-25 12:58 UTC by fiam

- Allow .graphql files with zero operations, mark them as invalid. This
allows commenting them out
- When an operation is not valid, either by being empty or by producing
an error during parsing, generate a handler that just returns an error
for it.

2022-11-25 14:33 UTC, jensneuse requested changes

2022-11-25 14:33 UTC, jensneuse commented on pkg/loadoperations/loader.go
> +type infoError string
What's the purpose of this type alias?

2022-11-25 14:33 UTC, jensneuse commented on pkg/loadoperations/loader.go
> +	if len(doc.OperationDefinitions) > 1 {
This is actually wrong, although it looks correct.

You need to iterate through the doc.RootNodes and count the number of root nodes that are of kind OperationDefinition.

Counting the number of OperationDefinitions is correct most of the time, but not always.
E.g. we "delete" an OperationDefinition from an AST by deleting the reference in the RootNodes.
By deleting it, the Walker will no longer walk into the OperationDefinition, hence it "doesn't exist" anymore.

By directly using doc.OperationDefinitions, all you do is access pre-allocated space, that might or might not be correct.

2022-11-25 14:36 UTC, fiam commented on pkg/loadoperations/loader.go
> +type infoError string
It's used to report errors that should be passed to the TS side as `info` instead of `error`, see the type assertion on line 124 after calling `l.loadOperation()`

2022-11-25 14:36 UTC, fiam commented on pkg/apihandler/apihandler.go
> +		OperationName: name,
We can definitely log an error there. I'll add it.

2022-11-25 14:42 UTC, fiam commented on pkg/loadoperations/loader.go
> +	if len(doc.OperationDefinitions) > 1 {
I tested it locally with a few files and it seemed to work. I'll look into it and count the nodes as you suggest.

2022-11-25 14:43 UTC, jensneuse requested changes

2022-11-25 14:43 UTC, jensneuse commented on pkg/loadoperations/loader.go
> +			if ierr, ok := err.(infoError); ok && ierr.IsInfo() {
it would be a bit more idiomatic to just use `errors.Is(infoError,infoErrorType)`

2022-11-25 14:45 UTC, jensneuse commented on pkg/loadoperations/loader.go
> +	if len(doc.OperationDefinitions) > 1 {
It will always work unless someone manipulates the AST.
I only wanted to make you aware of the behaviour of the doc object as it might bite you when working with graphql-go-tools.
Right after parsing, the AST should be correct, no deletions happened.
So you can leave the code as is, but just keep it in mind.

2022-11-25 14:48 UTC, fiam commented on pkg/apihandler/apihandler.go
> +		OperationName: name,
Added

2022-11-25 15:40 UTC, fiam commented on pkg/loadoperations/loader.go
> +			if ierr, ok := err.(infoError); ok && ierr.IsInfo() {
`errors.Is` test against a given error value, not its type. I've changed the check to use `errors.As` which can be used to test its type

2022-11-25 15:40 UTC, fiam commented on pkg/loadoperations/loader.go
> +	if len(doc.OperationDefinitions) > 1 {
I've changed it to walk the AST and count OperationDefinitions nodes

2022-11-25 21:34 UTC, jensneuse approved these changes

2022-12-02 09:10 UTC, StarpTech commented
> Allow .graphql files with zero operations, mark them as invalid. This
allows commenting them out

Honestly, I don't like that approach. You can easily move the file to a different location. Next.js also didn't try to solve this "issue".

2022-12-02 12:51 UTC, fiam commented
> > Allow .graphql files with zero operations, mark them as invalid. This
> > allows commenting them out
> 
> Honestly, I don't like that approach. You can easily move the file to a different location. Next.js also didn't try to solve this "issue".

It feels a bit weird to me that an entirely commented file (or an empty one) is considered an error, but maybe that's more frequent in frameworks I don't have experience with. I've changed it so empty files are treated as files with errors. PTAL.

2022-12-02 13:27 UTC, StarpTech commented
> It feels a bit weird to me that an entirely commented file (or an empty one) is considered an error, but maybe that's more frequent in frameworks I don't have experience with. I've changed it so empty files are treated as files with errors. PTAL.

The more I think about it, the less I'm opinionated. I see it from this perspective: An empty string is not valid graphql and an operation contains just graphql. If we throw an error, we can ensure that everything that can be picked as an operation is a valid operation. The user is free to design their operations in a different directory if they can't provide the right query yet.

2022-12-02 14:11 UTC, fiam commented
> > It feels a bit weird to me that an entirely commented file (or an empty one) is considered an error, but maybe that's more frequent in frameworks I don't have experience with. I've changed it so empty files are treated as files with errors. PTAL.
> 
> The more I think about it, the less I'm opinionated. I see it from this perspective: An empty string is not valid graphql and an operation contains just graphql. If we throw an error, we can ensure that everything that can be picked as an operation is a valid operation. The user can design their operations in a different directory if they can't provide the right query yet.

Honestly, the more I think about it the better it seems to report them as errors.

I don’t think we should discuss wether an empty string is or is not valid GraphQL, that’s going down the realm of semantics. Instead, think of the practical implications.

The reason I wanted to make empty files acceptable is that commenting out a file is way faster than moving it (and simpler, since you don’t need to think where to move it). However, there’s a drawback: if you accidentally leave an empty file because you forgot to save its contents wunderctl generate will report a message but not stop with an error. For this reason, I think is better if we err on the side of correctness even if it comes with a cost in terms of convenience.

2022-12-05 10:02 UTC, StarpTech requested changes

2022-12-05 10:02 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +		zap.String("Help", "The Operation is not properly configured. This usually happens when there is a mismatch between GraphQL Schema and Operation. Please make sure, the Operation is valid. This can
The last phrase is not helpful. Can we point to some docs?

2022-12-05 11:22 UTC, fiam commented on packages/sdk/src/graphql/operations.ts
>  			throw new Error(out.errors[0]);
I did, it exists with 1 because of the thrown exception.

2022-12-05 11:23 UTC, fiam commented on pkg/apihandler/apihandler.go
> +		zap.String("Help", "The Operation is not properly configured. This usually happens when there is a mismatch between GraphQL Schema and Operation. Please make sure, the Operation is valid. This can
I agree with its lack of usefulness, but I also think in most cases it would be impossible to find the relevant doc. What if we direct them to check the logs, which will have the relevant error?

2022-12-05 11:44 UTC, fiam commented on pkg/apihandler/apihandler.go
> +		zap.String("Help", "The Operation is not properly configured. This usually happens when there is a mismatch between GraphQL Schema and Operation. Please make sure, the Operation is valid. This can
I've updated the message, PTAL

2022-12-05 13:34 UTC, merged