feat: add hasura live chat example
wundergraph/wundergraph pull request #376
Opened 2022-11-26 05:32 UTC by alasdairtran

Hi @jensneuse,

This is an example live chat app using Hasura as a data source for WunderGraph (adapted from [here](https://github.com/hasura/graphql-engine/tree/master/community/sample-apps/realtime-chat)). I'm marking this as draft as I mainly want to show a couple of corner cases that WunderGraph currently fails to handle.

### 1. Some queries with complex `where` clauses fail validation

Two examples are the `FetchNewMessages` query [here](https://github.com/mochilabs/wundergraph/blob/hasura-example/examples/graphql-hasura-live-chat/app/.wundergraph/operations/FetchNewMessages.graphql) and the `SubscribeToUserTyping` subscription [here](https://github.com/mochilabs/wundergraph/blob/hasura-example/examples/graphql-hasura-live-chat/app/.wundergraph/operations/SubscribeToUserTyping.graphql). They both give a fairly opaque `mismatched input value` error during validation when starting WunderGraph. In those two graphql files, I also provide in the comments simpler queries that pass validation.

### 2. Queries containing Boolean input pass validation but fails to return data

The `FetchAllMessages` query [here](https://github.com/mochilabs/wundergraph/blob/hasura-example/examples/graphql-hasura-live-chat/app/.wundergraph/operations/FetchAllMessages.graphql) passes validation (I believe thanks to https://github.com/wundergraph/graphql-go-tools/pull/447) *but* fails to return any data. I console.log the response [here](https://github.com/mochilabs/wundergraph/blob/hasura-example/examples/graphql-hasura-live-chat/app/components/chat/RenderMessages.tsx#L53) and it's always null.

Let me know if this PR is enough for you guys to reproduce, and if you'd like me to create separate issues to track them.

2022-11-26 07:07 UTC, jensneuse commented
Thank you @alasdairtran! We will have a look. @spetrunin can you try this out with the latest engine?

2022-12-16 00:47 UTC, alasdairtran commented
Hi @spetrunin, just wondering if you had the chance to reproduce these errors?

2022-12-20 09:02 UTC, spetrunin commented
Hi @alasdairtran
yep, we have reproduced it
currently working on a fix

2022-12-21 12:22 UTC, spetrunin requested changes

2022-12-21 12:22 UTC, spetrunin commented on examples/graphql-hasura-live-chat/app/package.json
> +    "@wundergraph/sdk": "^0.123.2",
next sdk release will include a fix to make this example work

2022-12-21 12:22 UTC, spetrunin commented on examples/graphql-hasura-live-chat/docker-compose.yml
> +    image: docker.io/bitnami/postgresql:14.4.0
could we use official postgres image instead to been able to launch examples on m1 mac?

2022-12-21 12:22 UTC, spetrunin commented on examples/graphql-hasura-live-chat/hasura/console.Dockerfile
> + && curl -L -o /usr/local/bin/hasura https://github.com/hasura/graphql-engine/releases/download/v2.15.0/cli-hasura-linux-amd64 \
could you add commented line with arm version also and add a note to readme about that?

2022-12-21 12:22 UTC, spetrunin commented on examples/graphql-hasura-live-chat/hasura/engine.Dockerfile
> +FROM hasura/graphql-engine:v2.15.0
hasura release `v2.15.0` was removed, nearest available version is `v2.15.2`

2022-12-21 12:23 UTC, spetrunin commented on examples/graphql-hasura-live-chat/app/package.json
> +    "@wundergraph/sdk": "^0.123.2",
@alasdairtran I will notify you once it is released

2022-12-29 10:34 UTC, spetrunin commented
@alasdairtran this release `@wundergraph/sdk@0.129.0` contains required fixes

we still have to do some work to properly integrate this example into our CI pipeline

please let us know in case you have any other problems
thanks again for your input!

2022-12-29 10:34 UTC, closed without merging