chore: fix fauna-db example
wundergraph/wundergraph pull request #380
Opened 2022-11-29 09:53 UTC by kaleem68

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-01 19:12 UTC, StarpTech approved these changes
LGTM

2022-12-02 07:48 UTC, jensneuse requested changes

2022-12-02 07:48 UTC, jensneuse commented on examples/faunadb-nextjs/pages/index.tsx
> +export default Home
why remove withWunderGraph? no SSR?

2022-12-02 08:24 UTC, kaleem68 commented on examples/faunadb-nextjs/pages/index.tsx
> +export default Home
TL;DR: `withWunderGraph` is not exported from `lib/wundergraph.ts`.

If we need `withWunderGraph` then it will be imported from a different file.

The changes will be as following:

```diff
+ import {withWunderGraph} from "../components/generated/nextjs";
  import { useQuery } from '../lib/wundergraph';
```
```diff
- export default Home
+ export default withWunderGraph(Home);
```

Do we want to do the above? 

I copied `lib/wundergraph.ts` from `examples/nextjs-swr` to make this example work and in the `examples/nextjs-swr` `withWunderGraph` is not exported.

2022-12-02 08:39 UTC, StarpTech commented on examples/faunadb-nextjs/pages/index.tsx
> +export default Home
I'd favor doing not more than showing that WG works with faunadb. For advanced next.js stuff, we have a dedicated example.

2022-12-02 08:43 UTC, jensneuse approved these changes

2022-12-02 08:45 UTC, jensneuse commented
I've just changed to "fix: ..." because "chore: fix..." feels wrong.

2022-12-02 08:59 UTC, kaleem68 commented on examples/faunadb-nextjs/pages/index.tsx
> +export default Home
@StarpTech Are you saying we are good with existing changes?

2022-12-02 12:59 UTC, merged