chore: upgrade-swr-to-rc3
wundergraph/wundergraph pull request #397
Opened 2022-12-05 12:21 UTC by kaleem68

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-05 12:29 UTC, Pagebakers requested changes

2022-12-05 12:29 UTC, Pagebakers commented on examples/vite-swr/package.json
> +    "swr": "^2.0.0-rc.0",
update to rc.3 and test if it works

2022-12-07 08:24 UTC, kaleem68 commented on examples/vite-swr/package.json
> +    "swr": "^2.0.0-rc.0",
vite-swr is working now but there is an issue with this example `nextjs-postgres-user-filters`

the issue seems to be in `uploadFiles`

`wundergraph/examples/nextjs-postgres-user-filters/components/generated/client.ts:95
                return super.uploadFiles(config);`

2022-12-07 14:41 UTC, Pagebakers approved these changes

2022-12-07 17:21 UTC, fiam approved these changes

2022-12-07 18:14 UTC, merged