refactor(hooks)!: refactor hooks interface
wundergraph/wundergraph pull request #40
Opened 2022-06-16 08:28 UTC by StarpTech

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-06-16 18:38 UTC, StarpTech commented on pkg/apihandler/internalapihandler.go
> +	clientRequest, _, _, _ := jsonparser.Get(body, "__wg", "clientRequest")
Move to function

2022-06-19 13:43 UTC, jensneuse requested changes

2022-06-19 13:43 UTC, jensneuse commented on pkg/templates/assets/templates/nextjs-starter/.wundergraph/wundergraph.server.ts
> +				mockResolve: async (hook) => {
Can we add the type of the hook "thing"?

2022-06-19 13:43 UTC, jensneuse commented on pkg/apihandler/internalapihandler.go
> +	request := r
maybe rename to "internalRequest"?

2022-06-19 13:43 UTC, jensneuse commented on pkg/apihandler/internalapihandler.go
> +		// create a new request from the client request
add comment why we're excluding the body

2022-06-19 13:43 UTC, jensneuse commented on packages/nextjs-testapp/.wundergraph/wundergraph.server.ts
> +				mockResolve: async (hook) => {
add type?

2022-06-19 13:43 UTC, jensneuse commented on packages/default-testapp/.wundergraph/wundergraph.server.ts
> +			postAuthentication: async (hook) => {},
add types for hook arg?

2022-06-19 14:46 UTC, StarpTech commented on pkg/apihandler/internalapihandler.go
> +	request := r
Good point.

2022-06-19 14:51 UTC, StarpTech commented on packages/nextjs-testapp/.wundergraph/wundergraph.server.ts
> +				mockResolve: async (hook) => {
This bloats the examples. Every code editor supports inline types and the user has type support anyway.

2022-06-19 14:56 UTC, StarpTech commented on packages/nextjs-testapp/.wundergraph/wundergraph.server.ts
> +				mockResolve: async (hook) => {
I added the types to the official examples but left them in our test apps.

2022-06-20 08:30 UTC, StarpTech commented on docs/migrations/sdk-0.92.5-0.93.md
> +    preResolve: async ({ user, log, clientRequest, setClientRequestHeader, internalClient, ...others }) => {};
Remove "setClientRequestHeader"

2022-06-20 18:50 UTC, merged