chore: add error handling rfc
wundergraph/wundergraph pull request #405
Opened 2022-12-07 10:20 UTC by jensneuse

2022-12-07 10:54 UTC, Pagebakers commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +  "Message": "Bad Request: Invalid input",
I'd make the keys lowercase, to make it consistent with our TypeScript coding standards.

2022-12-12 11:57 UTC, jensneuse commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +  "Message": "Bad Request: Invalid input",
done

2022-12-12 15:12 UTC, jensneuse commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +- 503 Service Unavailable (misconfigured Operation)
These are just current state, look below.

2022-12-12 15:15 UTC, jensneuse commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +  "message": "Bad Request: Invalid input",
what do you mean by code?

2022-12-12 15:16 UTC, fiam commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +  "message": "Bad Request: Invalid input",
A numeric code to tell apart the different types of errors

2022-12-12 15:18 UTC, jensneuse commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +  "message": "Bad Request: Invalid input",
400 will always only return validation errors

2022-12-12 16:50 UTC, StarpTech requested changes

2022-12-12 16:50 UTC, StarpTech commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +Responses that were executed successfully might still contain errors,
I also prefer to move to the REST world here because that is what we expose to the user. With functions and directory-based URLs, we will do REST with a GraphQL response schema. There is no reason to inherit GraphQL semantics at all.

A request that results in an error should not have a 2xx status code. This makes the client less complex because we don't need to parse the body to identify a failed request. It will also simplify caching and makes it easier to identify errors in observability tools.

2022-12-12 17:05 UTC, jensneuse commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +Responses that were executed successfully might still contain errors,
Keep in mind that a partial response (some root field resolved, some with errors) means that the client can show "some" data. So you have to parse the response anyways. The execution was successful.

2022-12-12 17:37 UTC, jensneuse commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +Responses that were executed successfully might still contain errors,
Although I'd set this to 206 (Partial Response) because the client then knows that the response will contain errors and data, which I think is quite convenient, no?

2022-12-12 17:40 UTC, StarpTech commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +Responses that were executed successfully might still contain errors,
It is used in combination with range requests.

2022-12-12 17:42 UTC, jensneuse commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +Responses that were executed successfully might still contain errors,
Yeah, that's what Mozilla says. I think it's the best alternative to distinguish between partial response and 200. Any better options?

2022-12-12 17:43 UTC, StarpTech commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +Responses that were executed successfully might still contain errors,
For correctness, I'd go with 200, and the client can check for errors optionally.

2022-12-12 18:30 UTC, StarpTech commented on rfc/error handling/[RFC] error handling - 001 - jensneuse.md
> +Responses that were executed successfully might still contain errors,
To be clear. If I define a schema where some types are optional, and an error happens during the execution. I'd treat the errors as meta information, not as response errors.

2023-01-19 10:38 UTC, Pagebakers commented
Closing this for now, will re-open this in the new rfcs repo.

2023-01-19 10:38 UTC, closed without merging