feat: better error messages when resolving undefined variables
wundergraph/wundergraph pull request #419
Opened 2022-12-08 11:28 UTC by fiam

Test before calling resolveVariable(), since by that point the information
has already been lost and it's too late to provide a more detailed message

2022-12-13 11:16 UTC, fiam commented on packages/sdk/src/definition/graphql-introspection.ts
> +			throw new Error('introspection mTLS key is not defined');
Good idea, I'll add it.

2022-12-13 13:51 UTC, fiam commented on packages/sdk/src/definition/graphql-introspection.ts
> +			throw new Error('introspection mTLS key is not defined');
Added API namespace to all error messages

2022-12-15 10:23 UTC, StarpTech requested changes

2022-12-15 10:23 UTC, StarpTech commented on packages/sdk/src/configure/variables.ts
> +		throw new Error('could not resolve undefined data variable');
Why did you remove the name from the err msg?

2022-12-15 10:26 UTC, StarpTech requested changes

2022-12-15 10:26 UTC, StarpTech commented on packages/sdk/src/definition/graphql-introspection.ts
> +			throw new Error(`introspection mTLS key is not defined in API ${introspection.apiNamespace}`);
It would be great to point the user with a path to the right config.

```ts
throw new Error(`The field mtls.key of your datasource ${introspection.apiNamespace} is not defined`);
```

2022-12-15 12:31 UTC, fiam commented on packages/sdk/src/configure/variables.ts
> +		throw new Error('could not resolve undefined data variable');
Notice the check right before, the variable is undefined at that point, so it will just show `could not resolve empty data variable: undefined`

2022-12-15 14:33 UTC, Pagebakers approved these changes
Nice!

2022-12-20 12:01 UTC, StarpTech approved these changes
LGTM

2022-12-20 13:39 UTC, merged