chore: remove version numbers from generated PB Go file
wundergraph/wundergraph pull request #420
Opened 2022-12-08 11:54 UTC by fiam

Although version numbers could provide some value to detect version
incompatibility, we're only using PB to generate schema definitions
for JSON files, so this is a minor concern. Additionally, we do not
have version numbers in the TS side (because the generator doesn't
write them down). On the other hand, including the version number
causes significant friction for contributors using slightly different
PB versions while checking that the generated files are up to date)

2022-12-09 08:58 UTC, StarpTech requested changes

2022-12-09 08:58 UTC, StarpTech commented on types/generate.sh
> +sed -i.bak '2,4d' ${outfile}
This thread convinced me. https://github.com/golang/protobuf/issues/1185

Your regex is a bit dangerous. Could you use this one:

```sh
sed -i -e '1h;2,$H;$!d;g' -re 's|// versions.+// source:|// source:|' pkg/wgpb/*.pb.go
```

2022-12-09 09:02 UTC, StarpTech commented on types/generate.sh
> +sed -i.bak '2,4d' ${outfile}
Whereby this is still valid https://github.com/golang/protobuf/issues/1185#issuecomment-1305074470

> Note that this does not apply semver; the promise is expressed in terms of a time window.

2022-12-09 13:35 UTC, StarpTech requested changes

2022-12-09 13:35 UTC, StarpTech commented on types/generate.sh
> +# Remove comments with version numbers
Could you add comment why we are doing this?

2022-12-09 14:40 UTC, fiam commented on types/generate.sh
> +sed -i.bak '2,4d' ${outfile}
Changed to grep

2022-12-09 14:45 UTC, fiam commented on types/generate.sh
> +# Remove comments with version numbers
I've added a comment explaining the rationale for dropping the version numbers as well as for choosing grep as the tool to do it. PTAL

2022-12-09 17:08 UTC, StarpTech approved these changes
LGTM

2022-12-12 08:40 UTC, jensneuse approved these changes

2022-12-12 10:56 UTC, merged