chore: enforce formatting of prettier-formatted files in CI
wundergraph/wundergraph pull request #421
Opened 2022-12-08 12:08 UTC by fiam

- Fix patterns in package.json, so prettier doesn't exit with an
error when some of the file patterns have no results
- Add generated PB files to .prettierignore
- Format files in CI before checking for dirty ones

2022-12-09 09:57 UTC, StarpTech requested changes

2022-12-09 09:57 UTC, StarpTech commented on .github/workflows/packages-ci.yaml
> +        run: pnpm format && pnpm format:examples
As discussed: Please only check for incorrectly formatted files and only files that were touched in the commit.

2022-12-12 11:03 UTC, Pagebakers approved these changes

2022-12-16 16:17 UTC, StarpTech approved these changes
LGTM

2022-12-19 14:30 UTC, merged