draft: add nextauth example
wundergraph/wundergraph pull request #423
Opened 2022-12-09 09:18 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-01-03 14:15 UTC, jensneuse requested changes

2023-01-03 14:15 UTC, jensneuse commented on pkg/authentication/authentication.go
> +	if user.FromCookie && u.HasRevalidateHook && r.URL.Query().Get("revalidate") == "true" {
We could also revalidate with a token I think. This would allow us to call the userInfo endpoint again.

2023-01-03 14:29 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/token-based-authentication-with-next-auth.md
> +    'http://127.0.0.1:9991'
Yes, sure, but for the sake of the example I didn't add any env variables. I'll add an extra not to clarify this.

2023-01-03 14:30 UTC, Pagebakers commented on pkg/authentication/authentication.go
> +	if user.FromCookie && u.HasRevalidateHook && r.URL.Query().Get("revalidate") == "true" {
Yeah but response caching is never enabled for token, since it doesn't have an ETag

2023-01-03 14:59 UTC, Pagebakers commented on pkg/authentication/authentication.go
> +	if user.FromCookie && u.HasRevalidateHook && r.URL.Query().Get("revalidate") == "true" {
So revalidate with token would then reset the internal userInfo cache?

2023-01-04 22:39 UTC, jensneuse commented on pkg/authentication/authentication.go
> +	if user.FromCookie && u.HasRevalidateHook && r.URL.Query().Get("revalidate") == "true" {
We cache the response of the token internally. So if the token doesn't change and we have a cache entry, we're not calling the userInfo endpoint again. In case of changing some user details, it would be nice if we could automatically revalidate the cache entry. So, by setting revalidate to true, we could skip the cache and refresh it.

2023-01-06 10:17 UTC, StarpTech commented on docs-website/src/pages/docs/guides/token-based-authentication-with-next-auth.md
> +    "generate": "wunderctl generate"
Let's use `build` as the script name. We use it now as default for all examples.

2023-01-06 10:33 UTC, StarpTech requested changes

2023-01-06 10:33 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +	private csrfEnabled: boolean = true;
Why should it be possible to disable it?

2023-01-06 10:33 UTC, StarpTech commented on testapps/nextauth/pages/api/auth/userInfo.ts
> +	const token = await getToken({ req });
According to the code, this is the only place where we verify the JWT. From a security perspective, it would make sense to verify the token when it arrives at our node to not make unauthenticated requests. Currently, we reuse the userInfoEndpoint to do both but we aren't in control of it from wundergraph perspective.

2023-01-06 10:38 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +	private csrfEnabled: boolean = true;
Because its now always enabled, even when no auth is enabled, or for server side requests

2023-01-06 10:44 UTC, StarpTech commented on testapps/nextauth/pages/api/auth/userInfo.ts
> +	const token = await getToken({ req });
We can go this way, but we should ensure that we don't make decisions at the node based on the authenticity of the token.

2023-01-06 11:17 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +	private csrfEnabled: boolean = true;
ok

2023-01-09 10:13 UTC, Pagebakers commented on testapps/nextauth/pages/api/auth/userInfo.ts
> +	const token = await getToken({ req });
As discussed in the standup. It's OK to leave the validation to the userInfo endpoint according to OIDC spec.

2023-01-09 11:14 UTC, Pagebakers commented on pkg/authentication/authentication.go
> +	if user.FromCookie && u.HasRevalidateHook && r.URL.Query().Get("revalidate") == "true" {
Add revalidate support for the userInfo cache

2023-01-09 17:25 UTC, StarpTech approved these changes
LGTM

2023-01-12 19:33 UTC, fiam approved these changes

2023-01-12 19:48 UTC, merged