feat: implement telemetry
wundergraph/wundergraph pull request #424
Opened 2022-12-09 10:31 UTC by StarpTech

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-09 14:57 UTC, jensneuse requested changes

2022-12-09 14:57 UTC, jensneuse commented on cli/commands/root.go
> +				go func() {
Is it intentional to do this async? This might have the effect that it doesn't complete if the actual action is faster.
Should you not make sure that the process doesn't exit before sending the telemetry data is complete?

2022-12-09 14:57 UTC, jensneuse commented on cli/commands/root.go
> +					TelemetryClient.Duration(metricDurationName)
Can you rename the functions to give them more meaning?
From looking at the code, I don't understand it.
Also, `TelemetryClient.Duration(metricDurationName)` makes no sense to me.
Maybe it's the lack of verbs. I don't understand what happens here.

2022-12-09 14:57 UTC, jensneuse commented on cli/commands/root.go
> +					TelemetryClient.Duration(metricDurationName)
This is an example that is easier to understand for me:

https://github.com/open-telemetry/opentelemetry-go/blob/4e763472eee5ef03b97274694d2d1b07f0b3cd11/example/jaeger/main.go#L85

2022-12-09 15:03 UTC, StarpTech commented on cli/commands/root.go
> +				go func() {
I don't want to block the actual usage. Wunderctl should work offline, and it could block for a noticeable time.

2022-12-09 15:07 UTC, StarpTech commented on cli/commands/root.go
> +					TelemetryClient.Duration(metricDurationName)
Please check

2022-12-09 15:08 UTC, StarpTech commented on cli/commands/root.go
> +				go func() {
> Should you not make sure that the process doesn't exit before sending the telemetry data is complete?

I do https://github.com/wundergraph/wundergraph/pull/424/files#diff-6cef6e709aaccb651a756f23bbae52a22cbe8f82fbe90258831d7c189b42915aR172

2022-12-09 15:22 UTC, StarpTech commented on cli/commands/root.go
> +				go func() {
If the process is exited before aster the data is sent to the client the data is also flushed on exit. See link.

2022-12-09 15:24 UTC, StarpTech commented on cli/commands/root.go
> +				go func() {
But there is another flaw. I do count too late. The duration should start immediately not after the first metric was sent.

2022-12-09 17:48 UTC, StarpTech commented on cli/commands/root.go
> +				go func() {
Please check

2022-12-09 18:48 UTC, jensneuse requested changes

2022-12-09 18:48 UTC, jensneuse commented on cli/commands/root.go
> +			TelemetryClient = telemetry.NewClient(
Does it make sense to init the client when the telemetry annotation is not true?

2022-12-09 18:48 UTC, jensneuse commented on cli/commands/root.go
> +				// which is done after the command is finished
how? using `FlushTelemetry()` in the Execute func?

2022-12-09 18:48 UTC, jensneuse commented on cli/commands/root.go
> +		flusher := TelemetryClient.PrepareBatch()
Can you explain why we create a batch here and in line 144 as well?

2022-12-10 16:55 UTC, StarpTech commented on cli/commands/root.go
> +				// which is done after the command is finished
yes

2022-12-12 08:39 UTC, jensneuse requested changes

2022-12-12 08:39 UTC, jensneuse commented on cli/commands/root.go
> +			if cmd.Annotations["telemetry"] == "true" {
doesn't have to be 2 nested if, can be just one

2022-12-12 08:39 UTC, jensneuse commented on pkg/config/config.go
> +	if !viper.InConfig("anonymousID") {
Should we disable this if "WG_TELEMETRY_DISABLED" env var is true?

2022-12-12 08:39 UTC, jensneuse commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&rootFlags.Telemetry, "telemetry", os.Getenv("WG_TELEMETRY_DISABLED") == "", "enables telemetry. Telemetry allows us to accurately gauge WunderGraph feature usage,
rename to "WG_DISABLE_TELEMETRY"?

2022-12-12 08:39 UTC, jensneuse commented on pkg/telemetry/client.go
> +	if resp.StatusCode != 200 {
you should also check if the response contains the root field errors

2022-12-12 10:20 UTC, StarpTech commented on cli/commands/root.go
> +	rootCmd.PersistentFlags().BoolVar(&rootFlags.Telemetry, "telemetry", os.Getenv("WG_TELEMETRY_DISABLED") == "", "enables telemetry. Telemetry allows us to accurately gauge WunderGraph feature usage,
Why?

2022-12-12 10:20 UTC, StarpTech commented on pkg/config/config.go
> +	if !viper.InConfig("anonymousID") {
Yes, good point.

2022-12-12 11:53 UTC, StarpTech commented on pkg/telemetry/client.go
> +	if resp.StatusCode != 200 {
Good catch

2022-12-12 12:23 UTC, fiam requested changes

2022-12-12 12:23 UTC, fiam commented on cli/commands/root.go
> +	"time"
Sort these impors with `make golang-ci-fix`please

2022-12-12 12:23 UTC, fiam commented on testapps/default/.wundergraph/wundergraph.server.ts
> +			postAuthentication: async ({ user, internalClient }) => {},
This seems to be added accidentally

2022-12-12 12:24 UTC, StarpTech commented on cli/commands/root.go
> +	"time"
Can we run it as part of the recommit hook?

2022-12-12 12:25 UTC, StarpTech commented on testapps/default/.wundergraph/wundergraph.server.ts
> +			postAuthentication: async ({ user, internalClient }) => {},
Yes, will delete it

2022-12-12 12:26 UTC, fiam commented
> During the implementation, I also removed the hub code that is no longer used because the way how we want to enable users to share and consume API as packages have significantly changed. That allowed me to clean up several places.

Please, try to avoid that in the future. It makes the review more complicated (hence more likely for reviewers to miss something). Also, if we want to bring back the code at some point in the future we can no longer git-revert.

2022-12-12 12:36 UTC, fiam commented on cli/commands/root.go
> +	"time"
We can add a check to enforce the formatting, but I don't think that changing the code automatically is a good idea.

2022-12-12 12:47 UTC, jensneuse commented on pkg/telemetry/client.go
> +	if resp.StatusCode != 200 {
so?

2022-12-12 13:24 UTC, StarpTech commented on testapps/default/.wundergraph/wundergraph.server.ts
> +			postAuthentication: async ({ user, internalClient }) => {},
Done

2022-12-12 13:25 UTC, StarpTech commented
> Please, try to avoid that in the future. It makes the review more complicated (hence more likely for reviewers to miss something). Also, if we want to bring back the code at some point in the future we can no longer git-revert.

I see your point, and I agree, but in this case, we agreed on it.

2022-12-12 13:43 UTC, fiam approved these changes

2022-12-12 14:18 UTC, StarpTech commented on pkg/telemetry/client.go
> +	if resp.StatusCode != 200 {
Adressed

2022-12-12 14:21 UTC, jensneuse approved these changes

2022-12-12 15:59 UTC, merged