chore(RFC): functions
wundergraph/wundergraph pull request #426
Opened 2022-12-09 13:35 UTC by jensneuse

2022-12-10 16:28 UTC, StarpTech requested changes
Great proposal.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +│   ├── users
It should also be possible to add a folder to implement REST-like versioning e.g. `/v1/users/create`. This is very powerful.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +const out = await client.mutate({
How is DELETE, and PUT request methods mapped? Or do we ignore them in wundergraph RPC protocol?

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
I prefer to manage functions in a different directory. It might be confusing from the user perspective that only GraphQL operations can have hooks. If a function is never the same as a regular GraphQL operation, we should not mix them. I like to have a functions directory.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  type: 'mutation',
I prefer to have different methods for queries and mutations `createMutationOperation`. This makes it a bit more convenient.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +import { createContext } from '@wundergraph/sdk/functions';
IMO this is a premature optimization. The user can do whatever he wants in the handler. Creating a TCP connection on every cold start could result in very bad performance.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
It should be possible to work with typed errors that are part of the output type definition. Similar to GraphQL unions.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
What's the expected response when an error is thrown?

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
We could provide an onError hook where the user can decide how and when to communicate an error to the client.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +We'd extend the existing folder structure by adding a `create.hooks.ts` file:
I think this has nothing to do with functions. I'd handle it in a separate RFC.

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  handler: async ({ input, context }) => {
It should be possible to call other functions through the context `context.internalClient`

2022-12-10 16:28 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  input: createUser,
I'd put validation in an object

```ts
{
  validation:  {  input, output }
}
```

2022-12-11 20:00 UTC, StarpTech requested changes

2022-12-11 20:00 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +const user = z.object({
Some other points:
- We need to figure out how and when to generate the JSON schema from the functions.
- The more functions we create, the slower the cold start because all files are loaded synchronously. Ideally, we can lazy load it or we bundle all functions into a single bundle.

2022-12-12 10:19 UTC, Pagebakers commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
When we throw a regular Error or anything else we parse it to `{error: 'message'}`, but it should also be possible to throw built-in error objects like `throw new GraphqlError()` so you can communicate more info in the error.

2022-12-12 10:20 UTC, Pagebakers commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  handler: async ({ input, context }) => {
Since we define them as operations this is possible.

2022-12-12 10:43 UTC, Pagebakers commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
I think they are 2 distinct things, there's some overlap technically.

1. Functional (custom) operations.
I think this is a very natural and powerful pattern, you write your operation resolvers directly in TS, instead of graphql (later, this hooks in perfectly with the ts ORM) and can continue using the WG client (query/mutate) like you would normally. From a DX perspective it is very similar to writing resolvers and like other frameworks like trpc. They also have a more opiniated API with input validation for example.

2. Generic functions
These are more like lambda (or edge / nextjs api) functions, very similar to webhooks.

2022-12-12 10:45 UTC, Pagebakers commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +We'd extend the existing folder structure by adding a `create.hooks.ts` file:
I like the idea, because the current hooks setup is not ideal. It could be handled in a separate RFC, but it's a good moment to think about the design.

2022-12-12 10:48 UTC, Pagebakers commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  input: createUser,
Passing the schema directly to input like this makes zod a hard dependency, we'd also want to support other validation libraries.

2022-12-12 10:57 UTC, Pagebakers commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +import { createContext } from '@wundergraph/sdk/functions';
Having access directly to prisma via context is productive, but depending on the application it might add unneeded extra load to all operations.

2022-12-12 11:29 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +│   ├── users
you can do this already with this RFC

2022-12-12 11:32 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +const out = await client.mutate({
We could later on add different HTTP Verbs, although this wouldn't affect the generated clients as the HTTP method is an internal detail. Currently, I'd not try to solve this problem.

2022-12-12 11:33 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
I think it needs to be in the same folder as GraphQL Operations, because in the end, both are just operations. Putting them in different directories would cause conflicts. We also don't yet know how this will be used. I'd just release it as is and see how people react.. Everything else is assumptions.

2022-12-12 11:33 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  type: 'mutation',
Yes, good idea.

2022-12-12 11:34 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +import { createContext } from '@wundergraph/sdk/functions';
We can actually add this feature later.

2022-12-12 11:34 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
I agree

2022-12-12 11:35 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +We'd extend the existing folder structure by adding a `create.hooks.ts` file:
Yes, can be done in a separate RFC/Implementation.

2022-12-12 11:35 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  handler: async ({ input, context }) => {
context/ctx should be the ctx like in all other hooks, so yes, we'd inject the internal client

2022-12-12 11:37 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +const user = z.object({
JSON Schema should be generated during development (up) or build step (generate).

2022-12-12 14:25 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  input: createUser,
It's just another fixed field. I don't understand how it will cause issues or make it "a lot more" verbose.

2022-12-12 14:27 UTC, StarpTech requested changes

2022-12-12 14:30 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +To sum up the problems:
I think they solve quite different use cases.
A WebHook is more or less an HTTP handler.
An Operation Handler is a statically typed event handler, with a typed input and output.
Operation handlers can define all things for Operations, like Authentication, etc...
There's actually less overlap than one might think.
I think it's best to keep them separate.

2022-12-12 14:31 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
It will be possible to configure function operations in "wundergraph.operation.ts" correct?

2022-12-12 14:31 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +const out = await client.mutate({
ok

2022-12-12 14:32 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +│   ├── users
ok, so empty directories aren't ignored, and the total file path is mapped to the operation name.

2022-12-12 14:32 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  input: createUser,
At the same time, it's not clear how this is really different then the original idea.
Keep in mind that it's more than just validation.
The input and output definition is responsible to infer the types for the handler function as well as for the generation of the JSON Schema for the clients AND input validation, but not just validation by itself.

2022-12-12 14:34 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
As a user, I don't really want to know anything about GraphQL.
I think there should be a way to return a public error, which will then be returned in the errors object.
For internal errors we could allow to Throw.

2022-12-12 14:35 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
What do you mean by "configure"? In theory yes, but the function could configure itself, e.g. caching. There's no need to add configuration in multiple places.

2022-12-12 15:41 UTC, fiam commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +To sum up the problems:
I would also keep them separate

2022-12-12 15:44 UTC, fiam commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
I agree with Eelco here. I would implement both  “typescript operations” (these are analog to graphql operations and we should be able to translate a graphql operation to a typescript one automatically) and “functions” (which take the raw request and produce a response)

2022-12-12 15:45 UTC, fiam commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +We'd extend the existing folder structure by adding a `create.hooks.ts` file:
Separate RFC and PR, but we can discuss it here. And let it be notes that I like this design.

2022-12-12 15:49 UTC, fiam commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
Throwing an error should be never reported to the client, otherwise it's very easy to leak information on unintentional errors. They should be logged and shown in the dashboard, though. If the intent is to return an error, we should have some mechanism for that.

2022-12-12 18:48 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +  input: createUser,
Even so, I'd wish to have better names for it. Lets take fastify as an example

```ts
const schema = {
  body: bodyJsonSchema,
  querystring: queryStringJsonSchema,
  params: paramsJsonSchema,
  headers: headersJsonSchema
}

fastify.post('/the/url', { schema }, handler)
```

Maybe we call it `schema`?

2022-12-12 18:52 UTC, StarpTech commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +To sum up the problems:
Good points, but to make webhooks more convenient, we also need to consider type safety and validation.

2022-12-13 11:40 UTC, JivusAyrus commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
Even I agree with Eelco. When I heard functions, I thought it would be like the second point Eelco mentioned.
But I like the approach. Does this mean we will remove the support for .graphql files when .ts files can do everything the graphql files can? Or will we have support for both?

2022-12-13 12:10 UTC, jensneuse commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +The following endpoints will be created:
No, we will not remove support for GraphQL. You can use both.

2022-12-13 14:23 UTC, YuriBuerov commented on rfc/functions/[RFC] functions - 001 - jensneuse.md
> +      throw new Error('User not found');
@fiam  100% true

2023-01-10 20:24 UTC, closed without merging