feat(ci): add CI workflow for examples
wundergraph/wundergraph pull request #428
Opened 2022-12-09 15:15 UTC by fiam

2022-12-12 21:25 UTC, StarpTech requested changes

2022-12-12 21:25 UTC, StarpTech commented on scripts/test-example.sh
> +usage()
Awesome work! But we can drastically simplify it by using https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations

In that way, we can have one workflow that runs all examples in parallel with propert action integration (status, logging....)

2022-12-13 19:54 UTC, StarpTech commented on scripts/test-example.sh
> +usage()
Why you can't use one job per example? In that way, you don't need to set up stuff that only one example required of 5. We can have up to 256 parallel jobs :smile:

2022-12-14 09:26 UTC, StarpTech commented on scripts/test-example.sh
> +usage()
Done

2022-12-14 15:42 UTC, YuriBuerov approved these changes

2022-12-15 16:38 UTC, StarpTech approved these changes
LGTM

2022-12-16 21:25 UTC, merged