chore: add usage docs
wundergraph/wundergraph pull request #430
Opened 2022-12-10 04:26 UTC by Slickstef11

Added usage docs

#### Checklist

- [X] run `make test`
- [X] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-10 12:37 UTC, jensneuse requested changes
Please remove the package-lock.json from the commit.

2022-12-12 08:44 UTC, jensneuse requested changes

2022-12-12 08:44 UTC, jensneuse commented on docs-website/src/pages/usage-information.md
> +We take your privacy and our security very seriously. WunderGraph telemetry falls under the security disclosure policy.
"our security"?

2022-12-12 09:46 UTC, StarpTech commented on docs-website/src/pages/usage-information.md
> +We take your privacy and our security very seriously. WunderGraph telemetry falls under the security disclosure policy.
Could you suggest something?

2022-12-12 11:22 UTC, Pagebakers commented on docs-website/src/pages/usage-information.md
> +We take your privacy and our security very seriously. WunderGraph telemetry falls under the security disclosure policy.
`and the security of our platform`

2022-12-12 11:22 UTC, Pagebakers approved these changes
LGTM after improving the security line.

2022-12-12 21:52 UTC, StarpTech commented on docs-website/src/pages/usage-information.md
> +We take your privacy and our security very seriously. WunderGraph telemetry falls under the security disclosure policy.
thx, done.

2022-12-12 21:53 UTC, StarpTech approved these changes
LGTM

2022-12-12 21:53 UTC, jensneuse approved these changes

2022-12-12 21:53 UTC, merged