draft: [RFC] typesafe secrets
wundergraph/wundergraph pull request #441
Opened 2022-12-12 13:56 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-12 14:09 UTC, jensneuse commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +	NODE_ENV: z.enum(['development', 'test', 'production']),
It would be nice if we could also add meta data, like a description, which can be used in WunderGraph cloud so the user can better understand the purpose of the variable.

2022-12-12 14:09 UTC, jensneuse commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +new EnvironmentVariable(env.WG_SERVER_PORT, '9992');
I have an idea of how we improve the DX of this.
We should force the user to use `env.XXX` in `wundergraph.config.ts` instead of allowing strings.
Now, when running inside `wundergraph.config.ts` using an `env.XXX` variable will resolve to what before was `new EnvironmentVariable`.
When using `env.XXX` in the fastify server, it will resolve to the actual value. WDYT?
@StarpTech is this possible (technically)

2022-12-12 14:09 UTC, jensneuse commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +	NODE_ENV: z.enum(['development', 'test', 'production']),
It should also be possible to create a default value.
E.g.:

```typescript
const schema = createSchema({
  OAUTH_CLIENT_ID: {
    schema: z.string.optional(),
    default: "foo",
    description: "This is the Auth99 client ID"
  }
});
```

2022-12-12 14:09 UTC, jensneuse commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +	NODE_ENV: z.enum(['development', 'test', 'production']),
Maybe this is a bit verbose and we can improve it?

2022-12-12 15:17 UTC, jensneuse commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
>  });
It looks perfect!

2022-12-12 15:18 UTC, jensneuse commented
@Pagebakers great work!

2022-12-12 19:24 UTC, StarpTech requested changes

2022-12-12 19:24 UTC, StarpTech commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +import env from '.wundergraph/wundergraph.env';
I don't like the fact that we workaround from using process.env which is very natural. IMO we only need to ensure that the env schema is correct at build and runtime. Why should we provide a different way to access them?

2022-12-12 19:24 UTC, StarpTech commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +const schema = z.object({
How can we distinguish between build and runtime env variables? We need that separation so the node doesn't throw for things that aren't needed at runtime.

2022-12-13 14:02 UTC, fiam commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +const schema = z.object({
I like the idea of a type-safe environment a lot, but I'm wondering: doesn't TypeScript type's system allow us to express 90% of the required use cases? For example, this specific environment could be defined as:

```typescript
interface Env {
    NODE_ENV: "development" | "test" | "production";
   OAUTH_CLIENT_ID: string;
   SQLITE_DB?: string;
}

2022-12-13 14:05 UTC, jensneuse commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +const schema = z.object({
what about default values? what about adding a description for the UI to explain the variable?

2022-12-13 15:41 UTC, Pagebakers commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +const schema = z.object({
that way we can't have runtime errors for missing variables, but also don't get the benefit of reading the schema in the cloud and prefil the environment form in the UI (nice DX).

2022-12-13 15:41 UTC, Pagebakers commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +
They are already accessible to the user, and they can find them using the `wgEnv` variable exported from the SDK.

This would just add them to the type definition, so they are available in `env.`

2022-12-13 16:48 UTC, StarpTech commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +new EnvironmentVariable(env.WG_SERVER_PORT, '9992');
That sounds to me like a magical thing. You want to parse `.env` usages and create the equivalent `new EnvironmentVariable` to the file? I'd try to keep it boring. We have one file where the user can specify build and runtime environment variables. We generate a file to access the actual value. This file is imported where needed, exactly as in your example.

```ts
import { configureEnv, z } from '@wundergraph/sdk';

// 1. Define you variables with validation and when they are needed (by all are required for all stages)
export default configureEnv({
  COOKIE_SECRET: z.requiredForRun().string().describe('Cookie secret'),
  DATABASE_URL: z.required().string().describe('Database URL')
});

// 2. Access it like a regular import

import { DATABASE_URL } from './generated/env';

// 3. From the wundernode perspective
// The node will validates only COOKIE_SECRET because it is required to run the server
```

2022-12-13 16:48 UTC, StarpTech commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +import env from '.wundergraph/wundergraph.env';
I think the approach to using just process.env is too limited. What if we want to support coercion? string to int. It would be odd if process.env is not a string. Your argument regarding collision is also valid though.

2022-12-13 18:41 UTC, fiam commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +const schema = z.object({
You can use tsdoc comments to give them human-friendly names as well as specifying default values. The tsdoc parser is open source. This way developers don’t need to learn a new syntax, which removes a lot of friction.

2022-12-13 18:43 UTC, fiam commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +
My point is, does the app code need to care about those variables?  Users can set them to configure their app, but there’s not much that they can do with them at runtime.

2022-12-13 21:21 UTC, jensneuse commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +new EnvironmentVariable(env.WG_SERVER_PORT, '9992');
not too bad

2022-12-15 09:09 UTC, Pagebakers commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +import env from '.wundergraph/wundergraph.env';
Yeah I prefer having a custom env object for typesafe access. Coercion is a nice extra that way as well indeed. 

But then i'm not sure what you mean with `I don't like the fact that we workaround from using process.env `, your comments seem contradicting.

2022-12-15 14:36 UTC, Pagebakers commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +
Either way they are available in process.env no?

2022-12-15 14:54 UTC, StarpTech commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +new EnvironmentVariable(env.WG_SERVER_PORT, '9992');
Decision: There is only one set of env variables (no separation between build and runtime), and we need to ensure that defaults are loaded into ENV before validation.

2022-12-15 14:56 UTC, Pagebakers commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md 
> +new EnvironmentVariable(env.WG_SERVER_PORT, '9992');
I rather not add proprietary functionality on top of zod.

If we make sure WG defaults are loaded into process.env is set before the validation is run we don't need to worry between runtime/buildtime required variables, we can just use one set.

2022-12-15 16:33 UTC, StarpTech approved these changes
LGTM

2022-12-15 16:34 UTC, StarpTech requested changes

2022-12-15 16:34 UTC, StarpTech commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +declare global {
Why should we generate it if we the user can import them directly?

2022-12-15 16:36 UTC, StarpTech requested changes

2022-12-15 16:36 UTC, StarpTech commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +declare global {
Or do you mean for the type of `new EnvironmentVariable`?

2022-12-15 16:58 UTC, Pagebakers commented on rfc/typesafe-env-vars/[RFC] typesafe env vars - 001 - Pagebakers.md
> +declare global {
Yes that's for the first arg of EnvironmentVariable('this is typed')

2022-12-15 17:01 UTC, StarpTech approved these changes
LGTM

2022-12-29 17:20 UTC, jensneuse approved these changes

2022-12-30 11:05 UTC, Pagebakers commented
@jensneuse Can you merge this, the build_test doesn't run

2022-12-30 11:06 UTC, merged