chore(RFC): wunderbase
wundergraph/wundergraph pull request #442
Opened 2022-12-12 14:26 UTC by jensneuse

2022-12-13 10:57 UTC, Pagebakers requested changes

2022-12-13 10:57 UTC, Pagebakers commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +export default configureWunderBase({
Why a separate file and not define it in wundergraph.config.ts?

2022-12-13 10:57 UTC, Pagebakers commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +    └── app
I thought we got rid of `app`. One wunderbase per project and one per environment seems OK for the use case no?

2022-12-13 11:34 UTC, jensneuse commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +    └── app
Why not have multiple databases? E.g. an SQLite for user data and PostgreSQL for analytics

2022-12-13 11:54 UTC, YuriBuerov commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +export default configureWunderBase({
I agree with @Pagebakers, `wundergraph.config.ts` is not so huge, as for me it's more convenient to have configurations in one single place.

2022-12-13 12:02 UTC, YuriBuerov commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +    └── app
having multiple databases sounds reasonable.  And one more thing - `.wundergraph` is optional now (which I don't like, but the decision was made), and it's not well documented. For example, the WG project could look like this: https://github.com/bmcilw1/turbo-wunder-svelte/tree/main/apps/api. So when we use it in docs, and RFC, it could be confusing.

2022-12-13 12:54 UTC, Pagebakers commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +export default configureWunderBase({
Not that big of an issue here yet. Since wundergraph.config.ts is just a typescript file, you can stil split up datasource configs in a separate folder if needed and then import them in the main config..

2022-12-13 13:00 UTC, Pagebakers commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +    └── app
Right, you want to be able to define multiple prisma schema in wunderbase? not only for sqlite?

2022-12-13 13:17 UTC, jensneuse commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +    └── app
exactly
in this case, what's the convention to put these prisma schemas?
why not just wunderbase and the convention makes it clear and the user doesn't have to think about file paths, etc...

2022-12-13 13:34 UTC, fiam commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +export default configureWunderBase({
I'd go with a `wunderbase.config.ts` file inside `.wundergraph` instead. We can make `configureWunderBase()` take an array of configuration objects explicitly linking to the schema e.g.

```configureWunderBase([
     {
          namespace: 'app',
          schema: './prisma.schema',
          ...
          <future-configuration-options e.g. for cloud automatic backups<
     }
])
```

This supports multiple databases and allows users to organize the files as they see fit

2022-12-13 13:38 UTC, fiam commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +}
Do we really need so much information? I'd think that namespace and schema path should be enough, the rest can be read from the files.

2022-12-13 13:47 UTC, jensneuse commented on rfc/wunderbase/[RFC]wunderbase-001-jensneuse.md
> +}
yes, it's needed

2023-01-19 10:39 UTC, Pagebakers commented
Closing this for now, if you continue working on this, re-open it in the rfcs repo

2023-01-19 10:39 UTC, closed without merging