test: add tests for graphql-apollo-subscriptions example
wundergraph/wundergraph pull request #443
Opened 2022-12-12 21:05 UTC by fiam

2022-12-12 21:36 UTC, jensneuse requested changes

2022-12-13 14:06 UTC, fiam commented on examples/graphql-apollo-subscriptions/test/index.test.ts
> +				subscribeOnce: true,
Just because we could doesn't mean that we should. We don't have any API for canceling the subscription, so the only escape hatch is using a custom fetch and aborting. I recommend we add a test that subscribes, sends a message by POST'ing to the chat server, and finally stops listening; but only after we have some means for cancellation.

2022-12-13 14:23 UTC, fiam commented on examples/graphql-apollo-subscriptions/test/index.test.ts
> +				subscribeOnce: true,
If you're positive you want it at this point, I'll add it.

2022-12-13 16:19 UTC, jensneuse commented on examples/graphql-apollo-subscriptions/test/index.test.ts
> +				subscribeOnce: true,
Let's try if the effort is reasonable. Otherwise we can do it later.

2022-12-13 19:46 UTC, fiam commented on examples/graphql-apollo-subscriptions/test/index.test.ts
> +				subscribeOnce: true,
Added test for multiple subscriptions

2022-12-13 21:19 UTC, jensneuse approved these changes
Amazing!

2022-12-13 21:24 UTC, fiam commented
Thanks! Hopefully we can add a cancellation API at some point. Although stopping a subscription might be a bit of an edge case, it requires too much ceremony right now.

2022-12-13 21:25 UTC, jensneuse commented
> Thanks! Hopefully we can add a cancellation API at some point. Although stopping a subscription might be a bit of an edge case, it requires too much ceremony right now.

What do you mean by cancellation? Calling cancel on the abortcontroller will cancel the subscription. What's missing?

2022-12-13 21:26 UTC, fiam commented
> > Thanks! Hopefully we can add a cancellation API at some point. Although stopping a subscription might be a bit of an edge case, it requires too much ceremony right now.
> 
> What do you mean by cancellation? Calling cancel on the abortcontroller will cancel the subscription. What's missing?

Not having to use the AbortController explicitly would be nicer, IMHO.

2022-12-13 21:29 UTC, jensneuse commented
> > > Thanks! Hopefully we can add a cancellation API at some point. Although stopping a subscription might be a bit of an edge case, it requires too much ceremony right now.
> > 
> > 
> > What do you mean by cancellation? Calling cancel on the abortcontroller will cancel the subscription. What's missing?
> 
> Not having to use the AbortController explicitly would be nicer, IMHO.

extend the subscription with a stop() func and make it implicit
but not sure how much value is in it
most clients, e.g. SWR and React Query hide this completely from the user

2022-12-14 12:40 UTC, fiam commented
@jensneuse Something I forgot to mention: this test only runs on Node 18 because we do not support subscriptions with earlier Node versions, but it can be added. Thing is: is it worth it or should we just tell users that subscriptions in Node require version 18+?

2022-12-14 12:42 UTC, jensneuse commented
> @jensneuse Something I forgot to mention: this test only runs on Node 18 because we do not support subscriptions with earlier Node versions, but it can be added. Thing is: is it worth it or should we just tell users that subscriptions in Node require version 18+?

I'd say go with the easier option.

2022-12-14 14:02 UTC, fiam commented
> > @jensneuse Something I forgot to mention: this test only runs on Node 18 because we do not support subscriptions with earlier Node versions, but it can be added. Thing is: is it worth it or should we just tell users that subscriptions in Node require version 18+?
> 
> I'd say go with the easier option.

Node 18+ only is definitely the easier, no code required.

2022-12-14 15:20 UTC, YuriBuerov approved these changes

2022-12-14 15:35 UTC, merged