fix: csrf and authenticated uploads
wundergraph/wundergraph pull request #456
Opened 2022-12-15 19:01 UTC by thisisnithin

Will add example after merge as a separate PR

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-15 19:51 UTC, StarpTech approved these changes
Good work.

2022-12-15 21:15 UTC, fiam requested changes

2022-12-15 21:15 UTC, fiam commented on pkg/authentication/authentication.go
> +			domain := removeSubdomain(sanitizeDomain(r.Host))
This seems incorrect to me. This middleware is applied unconditionally [here](https://github.com/wundergraph/wundergraph/blob/737bc30682068a1f8af9c7e75ec6e88dbab284c2/pkg/apihandler/apihandler.go#L1693), so the effect is that all handlers will require CSRF protection.

Right now, CSRF is coupled with authentication, but if we're going to support it for unauthenticated users we need some means to signal the handlers that should be CSRF protected.

2022-12-16 09:36 UTC, StarpTech requested changes

2022-12-16 09:36 UTC, StarpTech commented on pkg/authentication/authentication.go
> -			if user := UserFromContext(r.Context()); user != nil && user.FromCookie {
As discussed in the daily. We misunderstood the situation. A CSRF should only be required when the User is authenticated. The generated client should not issue a CSRF request when the operation doesn't require auth.

2022-12-16 10:35 UTC, thisisnithin commented on pkg/authentication/authentication.go
> +			domain := removeSubdomain(sanitizeDomain(r.Host))
Reverted

2022-12-16 10:35 UTC, thisisnithin commented on pkg/authentication/authentication.go
> -			if user := UserFromContext(r.Context()); user != nil && user.FromCookie {
Reverted and added a check on the client

2022-12-16 11:19 UTC, StarpTech requested changes

2022-12-16 11:19 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +		const isAuthenticated = await this.isAuthenticatedByCookie();
I think that can be improved. Right now, we need auth for uploads. It would be enough to throw an error when the crsf endpoint does not return 200

```ts
throw new Error('You must be authenticated in order to upload files')
```

2022-12-16 11:27 UTC, StarpTech requested changes

2022-12-16 11:27 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +		const isAuthenticated = await this.isAuthenticatedByCookie();
The upload endpoint will already throw an unauthentication error.

2022-12-16 11:33 UTC, thisisnithin commented on packages/sdk/src/client/client.ts
> +		const isAuthenticated = await this.isAuthenticatedByCookie();
There is no change to be done at all then on the client, making the route require auth on the server should be enough. CSRF function already throws the error, the point is to not make that request at all right?

2022-12-16 13:09 UTC, thisisnithin commented on packages/sdk/src/client/client.ts
> +		const isAuthenticated = await this.isAuthenticatedByCookie();
Done

2022-12-16 13:23 UTC, StarpTech approved these changes
LGTM

2022-12-16 13:37 UTC, fiam approved these changes
LGTM

2022-12-16 13:47 UTC, merged