chore: add e2e texts to Next.js example
wundergraph/wundergraph pull request #460
Opened 2022-12-16 22:23 UTC by fiam

2022-12-18 11:48 UTC, StarpTech requested changes

2022-12-18 11:48 UTC, StarpTech commented on scripts/test-examples/single.sh
> +if test -f playwright.config.ts; then
I refactored that in https://github.com/wundergraph/wundergraph/pull/461. We should not guess actions based on a file. We should use npm scripts with conventions. You can run the e2e tests as part of the `test` script with `run-p`

2022-12-18 11:48 UTC, StarpTech commented on examples/nextjs/playwright.config.ts
> +		// {
Remove. Let's try to work with the simplest config file here because we have to duplicate it in every example.

2022-12-18 11:48 UTC, StarpTech commented on examples/nextjs/playwright.config.ts
> +// require('dotenv').config();
Enable it. This is compatible with the new approach in https://github.com/wundergraph/wundergraph/pull/461 where we load env from .env

2022-12-18 11:48 UTC, StarpTech commented on examples/nextjs-react-query/playwright.config.ts
> +		command: 'npm run start',
I think this will collide. `start` was not introduced for CI, only for local development. This is great for local testing only. For CI, it should work because `start:services` and `wait-on:services` ensure that the env is bootstrapped.

2022-12-18 11:48 UTC, StarpTech commented on examples/nextjs-react-query/pages/index.tsx
> +								<ul id="result">
`data-test-id` attributes are used for those markers. Playwright has native support for it.

2022-12-18 17:11 UTC, fiam commented on examples/nextjs/playwright.config.ts
> +// require('dotenv').config();
We don't need `.env` because we're calling `npm start` which ends up calling `wunderctl up` and setting dummy secrets. Keep in mind that end to end tests might also need to run the Next.js server.

2022-12-18 17:53 UTC, fiam commented on examples/nextjs-react-query/playwright.config.ts
> +		command: 'npm run start',
`start` works fine for CI.  Playwright kills all the children and doesn't leave any orphans.

2022-12-18 17:57 UTC, fiam commented on examples/nextjs-react-query/pages/index.tsx
> +								<ul id="result">
Changed to `data-testid`

2022-12-18 18:00 UTC, fiam commented on examples/nextjs/playwright.config.ts
> +		// {
Do you mean we should remove all comments?

2022-12-18 19:28 UTC, StarpTech commented on examples/nextjs/playwright.config.ts
> +		// {
I think the comments are good, but we should only have the props we need for the example to work.

2022-12-18 19:29 UTC, StarpTech commented on examples/nextjs/playwright.config.ts
> +// require('dotenv').config();
I thought it could be a quick win whenever you need to reference an ENV in your e2e tests you would be able to use .env.

2022-12-18 19:30 UTC, StarpTech commented on examples/nextjs-react-query/playwright.config.ts
> +		command: 'npm run start',
Then why don't we just use `start` for the CI?

2022-12-19 15:03 UTC, StarpTech commented on examples/nextjs/playwright.config.ts
> +// require('dotenv').config();
Delete it.

2022-12-20 11:26 UTC, fiam commented on examples/nextjs/playwright.config.ts
> +		// {
Deleted

2022-12-20 11:27 UTC, fiam commented on examples/nextjs-react-query/playwright.config.ts
> +		command: 'npm run start',
Changed the script to run `start` once, then run both integration and end-to-end tests before stopping the server

2022-12-20 11:27 UTC, fiam commented on scripts/test-examples/single.sh
> +if test -f playwright.config.ts; then
Changed to package script

2023-01-13 10:50 UTC, StarpTech requested changes

2023-01-13 10:50 UTC, StarpTech commented on scripts/test-examples/single.sh
> +while ! test -f .wundergraph/generated/wundergraph.schema.graphql; do
What happens when it errors? Forever loop?

2023-01-13 10:50 UTC, StarpTech commented on scripts/test-examples/single.sh
> +while ! test -f .wundergraph/generated/wundergraph.schema.graphql; do
Or does will it always fail before on any error?

2023-01-13 11:30 UTC, fiam commented on scripts/test-examples/single.sh
> +while ! test -f .wundergraph/generated/wundergraph.schema.graphql; do
There's a `set -e` after the initial checks, so any command that fails will abort the script with a non-zero exit code

2023-01-13 14:08 UTC, StarpTech commented on scripts/test-examples/single.sh
> +while ! test -f .wundergraph/generated/wundergraph.schema.graphql; do
ok

2023-01-13 14:08 UTC, StarpTech approved these changes
LGTM

2023-01-13 17:18 UTC, fiam commented on scripts/test-examples/single.sh
> +while ! test -f .wundergraph/generated/wundergraph.schema.graphql; do
> There's a `set -e` after the initial checks, so any command that fails will abort the script with a non-zero exit code

Replying to myself: this ended up to not be correct for background commands. Added a check while waiting for code generation to complete.

2023-01-18 09:29 UTC, Aenimus approved these changes

2023-01-18 09:29 UTC, Aenimus requested changes
start:serverCI test is failing

2023-01-24 09:10 UTC, Aenimus approved these changes

2023-01-24 10:00 UTC, merged