feat: setup a default .env file before start, improve tests
wundergraph/wundergraph pull request #461
Opened 2022-12-17 13:02 UTC by StarpTech

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-17 14:32 UTC, jensneuse approved these changes

2022-12-17 21:59 UTC, jensneuse approved these changes

2022-12-17 22:26 UTC, fiam requested changes

2022-12-17 22:26 UTC, fiam commented on scripts/test-examples/single.sh
> -if test ! -z ${services_pid}; then
This needs to stay. Otherwise examples like that run servers (e.g. graphql-apollo-subscriptions/package.json) will leave processes around.

2022-12-18 11:27 UTC, StarpTech commented on scripts/test-examples/single.sh
> -if test ! -z ${services_pid}; then
I kill it in the cleanup step.

2022-12-18 16:54 UTC, fiam commented on examples/openapi-mocking/package.json
> -    "test": "ava"
Please, leave this example with ava tests. We want to have at least one as an example and also ensures our test library works with testing suites that run tests in parallel.

2022-12-18 16:56 UTC, fiam commented on examples/graphql-apollo-subscriptions/package.json
> +    "cleanup": "kill-port 8085",
I don't think this is a good idea. We'd be replacing 4 lines in an sh script with a line that needs to be maintained for every current and future example as well an extra dependency (which also requires the full lsof on Linux - so it doesn't work in e.g. Alpine)

2022-12-18 17:00 UTC, fiam commented on examples/hooks/.env.example
> +WUNDERGRAPH_SECURE_COOKIE_HASH_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
This is not the right solution, since it requires managing and `.env` file in the repository just for development and adding an extra package script to every example that uses auth. If we think that setting these in `beforeAll()` is too verbose, there are other 2 solutions that we might apply that require no user intervention, either:

- If these variables are empty during the testing library startup, set them before calling `wunderctl start`.
- Alternatively, add a `--dev-mode` flag to `wunderctl start` and use it when starting the server.

2022-12-18 19:42 UTC, StarpTech commented on examples/hooks/.env.example
> +WUNDERGRAPH_SECURE_COOKIE_HASH_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> If these variables are empty during the testing library startup, set them before calling wunderctl start

How?

> Alternatively, add a --dev-mode flag to wunderctl start and use it when starting the server.

This will only work for values with a known default value.

2022-12-18 19:47 UTC, StarpTech commented on examples/hooks/.env.example
> +WUNDERGRAPH_SECURE_COOKIE_HASH_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> This is not the right solution, since it requires managing and .env file in the repository just for development and adding an extra package script to every example that uses auth

I don't understand this. I rename `.env.example` to `.env` on the `postinstall` hook. At this point, the user can work with the defaults. Having a local `.env` is the best practice.

2022-12-18 19:54 UTC, StarpTech commented on examples/openapi-mocking/package.json
> -    "test": "ava"
It doesn't work. I got an error regarding `new` with classes.

2022-12-18 20:00 UTC, StarpTech commented on examples/graphql-apollo-subscriptions/package.json
> +    "cleanup": "kill-port 8085",
I tried to restore your kill procedure, but it didn't work. Feel free to re-add it but for now, I move forward with the cleanup hook.

2022-12-18 20:48 UTC, fiam commented on examples/openapi-mocking/package.json
> -    "test": "ava"
It works in my machine and in CI. Please, check your local setup.

2022-12-18 20:48 UTC, fiam commented on examples/graphql-apollo-subscriptions/package.json
> +    "cleanup": "kill-port 8085",
Again, works in my machine and in CI

2022-12-18 21:38 UTC, StarpTech commented on examples/graphql-apollo-subscriptions/package.json
> +    "cleanup": "kill-port 8085",
I reverted it. It was due to pnpm. I had to use npm. PNPM always results in "ELIFECYCLE  Command failed" even on success.

2022-12-18 21:40 UTC, StarpTech commented on examples/openapi-mocking/package.json
> -    "test": "ava"
Even if it works now, mixing test frameworks randomly is confusing. If we want to show ava, we should provide a dedicated example. Let's go with jest as a default test runner.

2022-12-19 07:44 UTC, jensneuse commented on examples/hooks/.env.example
> +WUNDERGRAPH_SECURE_COOKIE_HASH_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
I actually think it's perfect as it allows the user to run `wunderctl start` in the project without needing to figure out how to set the environment variables. It's not just about the tests but also about running the app in production. By adding this env file, they can draw the connection between `new EnvironmentVariable('SECRET')` and the `.env` file.

Alternatively, we could "omit" the secrets altogether if we run `wunderctl start --insecure`, which would override the secrets with a default but static value.

2022-12-19 08:43 UTC, StarpTech commented on examples/hooks/.env.example
> +WUNDERGRAPH_SECURE_COOKIE_HASH_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
I'd not say alternatively, because as you said it is not just for default values also for configuration in general https://github.com/wundergraph/wundergraph/pull/461#discussion_r1051654954

2022-12-19 09:33 UTC, fiam approved these changes
Pending dropping references to ava from `testing.md`

2022-12-19 10:49 UTC, merged