fix: use github token for getTags API to increase the rate limit
wundergraph/wundergraph pull request #467
Opened 2022-12-19 13:53 UTC by JivusAyrus

#### Checklist

- [ ] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-19 14:06 UTC, fiam approved these changes
LGTM

2022-12-19 14:27 UTC, StarpTech requested changes

2022-12-19 14:27 UTC, StarpTech commented on packages/create-wundergraph-app/src/helpers/getRepoTags.ts
> +dotenv.config();
We should document that we support .env

2022-12-19 18:22 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepoTags.ts
> +dotenv.config();
Added an example.env file.
Should I mention it in the README?

2022-12-19 18:52 UTC, StarpTech commented on packages/create-wundergraph-app/src/helpers/getRepoTags.ts
> +dotenv.config();
Yes, a simple sentence.

2022-12-20 10:50 UTC, JivusAyrus commented on packages/create-wundergraph-app/src/helpers/getRepoTags.ts
> +dotenv.config();
Done 👍

2022-12-20 11:17 UTC, jensneuse approved these changes

2022-12-20 11:46 UTC, StarpTech approved these changes
LGTM

2022-12-21 11:53 UTC, merged