chore: docs, update cloud deployment doc
wundergraph/wundergraph pull request #475
Opened 2022-12-20 17:27 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-20 18:53 UTC, StarpTech requested changes

2022-12-20 18:53 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +If the repository meets these requirements, the WunderGraph Cloud will check for a build command in the root `package.json` file
Will it always look for the build script?

2022-12-20 18:53 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +If your repository is set as a `turborepo`, no additional steps are required for deployment.
How do I set a repository as turborepo?

2022-12-20 18:53 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +To test this feature, you can fork the [turborepo example repository](https://github.com/wundergraph/turbo-wunder-svelte/fork).
Could we create a dedicated one e.g `cloud-starter-turbo` ?

2022-12-20 20:38 UTC, jensneuse requested changes

2022-12-20 20:38 UTC, jensneuse commented on docs-website/src/pages/docs/cloud/deployments.md
> +The WunderGraph Cloud officially supports the `turborepo`, which is a type of monorepo that allows for faster and more efficient builds.
supports {remove "the"} `turborepo`

2022-12-20 20:38 UTC, jensneuse commented on docs-website/src/pages/docs/cloud/deployments.md
> +If the repository meets these requirements, the WunderGraph Cloud will check for a build command in the root `package.json` file
requirements, {remove "the"} WunderGraph Cloud

2022-12-21 09:11 UTC, YuriBuerov commented on docs-website/src/pages/docs/cloud/deployments.md
> +If your repository is set as a `turborepo`, no additional steps are required for deployment.
Is it a part of our documentation?

2022-12-21 09:11 UTC, YuriBuerov commented on docs-website/src/pages/docs/cloud/deployments.md
> +If the repository meets these requirements, the WunderGraph Cloud will check for a build command in the root `package.json` file
we are in monorepo deployment section, so in this case - yes

2022-12-21 10:03 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +If your repository is set as a `turborepo`, no additional steps are required for deployment.
It was more of a question. I don't understand this section. How can a Use set a repository as `turborepo`?

2022-12-21 10:44 UTC, YuriBuerov commented on docs-website/src/pages/docs/cloud/deployments.md
> +If your repository is set as a `turborepo`, no additional steps are required for deployment.
what would you suggest?

2022-12-21 19:25 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +If your repository is set as a `turborepo`, no additional steps are required for deployment.
Maybe 

> If you have a `turbo.json` at the root of your repository, no additional steps are required for the deployment. We will build the repository with `turbo run build`.

2023-01-10 20:32 UTC, StarpTech commented
@YuriBuerov What about this PR?

2023-01-18 11:24 UTC, closed without merging