feat: add upload profiles for S3 providers
wundergraph/wundergraph pull request #476
Opened 2022-12-21 08:08 UTC by fiam

2023-01-16 14:43 UTC, Pagebakers requested changes
Did you update the docs in another PR?

Something that needs to be documented as well is using paths in your fileKeys to create folders.

eg 
```
{
  fileKey: `${user.id}/${fileHash}.${file.extension}`
}
```

2023-01-16 14:43 UTC, Pagebakers commented on examples/nextjs-file-upload/.wundergraph/wundergraph.server.ts
> +						//						return {fileKey: file.name}
Why so many tabs :D

2023-01-16 14:43 UTC, Pagebakers commented on examples/nextjs-file-upload/.wundergraph/wundergraph.server.ts
> +	graphqlServers: [
Remove this, we shouldn't be including this in examples any longer.

2023-01-16 14:43 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +			headers['X-Upload-Profile'] = (config as any).profile ?? ('' as string);
Do we need to cast config to any here?

`('' as string);` could be just `''` too in this case?

2023-01-16 14:43 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +			headers['X-Metadata'] = (config as any).meta ? JSON.stringify((config as any).meta) : '';
Idem

2023-01-16 14:43 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +			throw new Error(`uploading ${config.files.length} exceeds the maximum allowed (${validation.maxAllowedFiles})`);
Now we have a new InputValidationError error type, I think having a UploadValidationError makes sense as well. We can add additional information to make it easier to display relevant error messages to users.

Actually now I think about it, this should've been part of the spec.

There's much more to it, eg I would like an error object for all files and their validation errors.

Let's do this in v2, I'll open an issue for it.

2023-01-16 15:24 UTC, fiam commented on examples/nextjs-file-upload/.wundergraph/wundergraph.server.ts
> +	graphqlServers: [
Removed

2023-01-16 15:28 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +import { z } from 'zod';
Good idea, changed

2023-01-16 15:28 UTC, fiam commented on examples/nextjs-file-upload/.wundergraph/wundergraph.server.ts
> +						//						return {fileKey: file.name}
Commented via keyboard shortcut, it kept all the indentation. Fixed.

2023-01-16 15:51 UTC, fiam commented on packages/sdk/src/client/client.ts
> +			headers['X-Metadata'] = (config as any).meta ? JSON.stringify((config as any).meta) : '';
As discussed, we found no cleaner way to do this

2023-01-18 11:33 UTC, fiam commented on packages/sdk/src/client/client.ts
> +			headers['X-Upload-Profile'] = (config as any).profile ?? ('' as string);
Fixed

2023-01-18 11:33 UTC, fiam commented
> Did you update the docs in another PR?
> 
> Something that needs to be documented as well is using paths in your fileKeys to create folders.
> 
> eg
> 
> ```
> {
>   fileKey: `${user.id}/${fileHash}.${file.extension}`
> }
> ```

Where should we document this?

2023-01-18 11:33 UTC, fiam commented
@jensneuse Merge conflicts fixed, PTAL

2023-01-18 13:54 UTC, Pagebakers commented
> > Did you update the docs in another PR?
> > Something that needs to be documented as well is using paths in your fileKeys to create folders.
> > eg
> > ```
> > {
> >   fileKey: `${user.id}/${fileHash}.${file.extension}`
> > }
> > ```
> 
> Where should we document this?

In the uploads documentation I'd say.

More importantly, does it work already? (I believe it should by default, but I can't confirm)

2023-01-18 18:58 UTC, YuriBuerov commented on pkg/apihandler/apihandler.go
> +				AllowedMimeTypes:      append([]string(nil), profile.AllowedMimeTypes...),
could `profile.AllowedMimeTypes` be nil? (possible runtime error)

2023-01-18 19:15 UTC, YuriBuerov commented on pkg/s3uploadclient/s3uploadclient.go
> +						continue
should we continue if `err != nil`? 
```
re, err := regexp.Compile(strings.ReplaceAll(normalized, "*", ".*"))
if err != nil {
    if s3Options.Logger != nil {
	s3Options.Logger.Warn("error compiling mimetype wildcard", zap.String("mimetype", normalized), zap.Error(err))
    }
    continue
}
```

Could you also explain in what cases we want `s3Options.Logger` to be nil, and why?

2023-01-18 19:16 UTC, YuriBuerov commented on pkg/s3uploadclient/s3uploadclient.go
> +						continue
I would also put normalization into the separate helper

2023-01-18 19:33 UTC, YuriBuerov requested changes
just a few comments

2023-01-18 19:58 UTC, fiam commented on pkg/apihandler/apihandler.go
> +			if profiles == nil {
I'll change it to preallocate the map with the required size. If there are no profiles we waste 48 bytes, but if there are profiles it will end up using less memory and being faster.

2023-01-18 20:06 UTC, fiam commented on pkg/s3uploadclient/s3uploadclient.go
> +						continue
I wouldn't expect that error to ever happen in a real scenario, but I'd rather log it just in case I got it wrong. Notice that the code handles having nils in allowedMimeTypesRegexps because not all mimetypes get compiled as a regular expression.

2023-01-19 10:03 UTC, Pagebakers approved these changes
LGTM, let's get this in the hands of developers.

Can you open an issue to allow for anonymous uploads? We can use the same api as functions `authenticationRequired: true/false` in the uploadProfile

2023-01-19 10:12 UTC, fiam commented
> LGTM, let's get this in the hands of developers.
> 
> Can you open an issue to allow for anonymous uploads? We can use the same api as functions `authenticationRequired: true/false` in the uploadProfile

Thanks! I’ll open an issue so we can get the ball rolling.

2023-01-19 10:23 UTC, jensneuse approved these changes

2023-01-19 16:12 UTC, fiam commented
@YuriBuerov can you please take another look? Thanks!

2023-01-20 08:24 UTC, YuriBuerov approved these changes

2023-01-20 13:45 UTC, merged