fix(node): listening only on tcp4
wundergraph/wundergraph pull request #493
Opened 2022-12-26 16:25 UTC by StarpTech

Listening to tcp4 and tcp6 has produced network issues on a platform like fly.io.
The initial idea to support both was an alignment with fastify. Fastify server will listen on the address(es) resolved by localhost (which could be ipv4 + ipv6) when no specific host is provided. 

The best default for the wundernode is to listen on ipv4 only.

Go has an issue https://github.com/golang/go/issues/17615 For those reasons, we must create a `tcp4` listener explicitly.

In the future, when the demand is there we could use a syntax like `tcp4/0.0.0.0` `tcp6/[::]` to distinguish between different IP stacks. See https://github.com/caddyserver/caddy/search?q=tcp4

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-27 08:05 UTC, jensneuse requested changes

2022-12-27 08:05 UTC, jensneuse commented on pkg/node/node.go
> +	if host == "0.0.0.0" {
I would do this instead as I think it's pretty accurate and will work for all kinds of local IP addresses: https://stackoverflow.com/a/48519490/20693155

```go
func IsIPv4(address string) bool {
    return strings.Count(address, ":") < 2
}
```

2022-12-27 08:05 UTC, jensneuse commented on pkg/node/node.go
> +	if host == "0.0.0.0" {
So, we only listen ipv4 when the user explicitly wants to listen to an ipv6 address. WDYT?

2022-12-27 08:43 UTC, fiam commented on Makefile
> +	cd cmd/wunderctl && CGO_ENABLED=0 go install
Please, don’t force this here. We can set it during the build as needed. Keep in mind that CGO_ENABLED=0 is not an Alpine requirement, it’s instead a requirement when you compile in a system with glibc with the intention to run the binary on a musl based system.

2022-12-27 11:00 UTC, StarpTech commented on pkg/node/node.go
> +	if host == "0.0.0.0" {
Great, I think this will work.

2022-12-27 11:08 UTC, StarpTech commented on Makefile
> +	cd cmd/wunderctl && CGO_ENABLED=0 go install
My intention here is that I don't need to set this flag manually when producing a test binary for the builder. Since we also have no cgo dependencies, we can set it without any issues.

> Keep in mind that CGO_ENABLED=0 is not an Alpine requirement, it’s instead a requirement when you compile in a system with glibc with the intention to run the binary on a musl based system.

Yes, I mean, in the case of alpine it is required because the binary was linked differently. In order to produce a cross-compatible image we have to set CGO_ENABLED=0 therefore disables native builds. That's everything I want to do here.

2022-12-27 12:26 UTC, StarpTech commented on pkg/node/node.go
> +	if host == "0.0.0.0" {
Done.

2022-12-27 15:33 UTC, jensneuse approved these changes

2022-12-28 07:28 UTC, fiam approved these changes

2022-12-28 09:58 UTC, merged