chore: update react-query example
wundergraph/wundergraph pull request #494
Opened 2022-12-27 10:41 UTC by Pagebakers

Updated the example to @wundergraph/react-query@0.2.0
Removed secrets configuration.

2022-12-27 10:44 UTC, JivusAyrus commented on examples/nextjs-react-query/.wundergraph/wundergraph.config.ts
> -			secureCookieHashKey: new EnvironmentVariable('WUNDERGRAPH_SECURE_COOKIE_HASH_KEY'), // must be of length 32
We need this for the tests

2022-12-27 10:47 UTC, JivusAyrus requested changes
Can we change the name in the package.json?  I forgot to do it last time

2022-12-27 10:50 UTC, Pagebakers commented on examples/nextjs-react-query/.wundergraph/wundergraph.config.ts
> -			secureCookieHashKey: new EnvironmentVariable('WUNDERGRAPH_SECURE_COOKIE_HASH_KEY'), // must be of length 32
This is included in all examples now?

2022-12-27 10:51 UTC, JivusAyrus commented on examples/nextjs-react-query/.wundergraph/wundergraph.config.ts
> -			secureCookieHashKey: new EnvironmentVariable('WUNDERGRAPH_SECURE_COOKIE_HASH_KEY'), // must be of length 32
All examples which use authentication

2022-12-27 10:55 UTC, JivusAyrus approved these changes

2022-12-27 10:55 UTC, Pagebakers commented on examples/nextjs-react-query/.wundergraph/wundergraph.config.ts
> -			secureCookieHashKey: new EnvironmentVariable('WUNDERGRAPH_SECURE_COOKIE_HASH_KEY'), // must be of length 32
Ok I thought it was some leftover code from copying another example. This one doesn't use auth. But I'll leave it in for now then.

2022-12-29 14:26 UTC, fiam approved these changes

2022-12-29 17:16 UTC, merged