feat(node)!: restructure server imports
wundergraph/wundergraph pull request #497
Opened 2022-12-27 20:25 UTC by StarpTech

This PR will restructure the import paths for the server component. In that way, the server does not require more modules and paths as needed. This has improved the cold start by multiple seconds. 

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-12-28 10:30 UTC, jensneuse approved these changes

2022-12-28 10:40 UTC, Pagebakers requested changes
Great improvement! Only thing I see it the webhook example isn't updated (only the testapp)

Actually we need to update all examples and docs :)

2022-12-28 11:24 UTC, StarpTech commented
> Great improvement! Only thing I see it the webhook example isn't updated (only the testapp)
Actually we need to update all examples and docs :)

Thanks! Yes, I'm going to update all testapps in this PR, but examples after the release.

2022-12-29 11:49 UTC, Pagebakers approved these changes
LGTM

2022-12-29 12:02 UTC, jensneuse approved these changes

2022-12-29 18:20 UTC, merged