chore: wip implement functions
wundergraph/wundergraph pull request #515
Opened 2023-01-04 23:21 UTC by jensneuse

2023-01-16 15:50 UTC, jensneuse commented
Tests are failing because we first need to make a binary release.

2023-01-17 09:38 UTC, StarpTech requested changes

2023-01-17 09:38 UTC, StarpTech commented on packages/sdk/src/operations/operations.ts
> +import type { User } from '../client';
Are you sure this is the client user? I'd assume since this the server you should use `WunderGraphUser`

```ts
BaseRequestContext<User, IC> & AuthenticationRequestContext<User>;
```

2023-01-17 09:38 UTC, StarpTech commented on packages/sdk/src/operations/operations.ts
> +import { z } from 'zod';
Please put everything to `/src/server`. This is the export for all server components.

2023-01-17 09:38 UTC, StarpTech commented on packages/sdk/src/server/plugins/functions.ts
> +								reply.hijack();
I'd call this before `subscriptionHandler` so the code in the catch handler can hijack also when `subscriptionHandler` throws.

2023-01-17 09:38 UTC, StarpTech commented on packages/sdk/src/server/plugins/functions.ts
> +								while (true) {
This is blocking the event loop all the time. For/Loop iterates until all values have been consumed. E.g.

```ts
let generator = generateSequence();

for await (let value of generator) {
     
}
```

2023-01-17 10:24 UTC, jensneuse commented on Dockerfile-Cloud-Starter
> +CMD ["/bin/sh","-c","node .wundergraph/generated/bundle/server.js & wunderctl start --exclude-server --pretty-logging=false --shutdown-after-idle=10 --wundergraph-dir=.wundergraph"]
this is only meant for testing fly machines, just ignore it

2023-01-17 10:24 UTC, jensneuse commented on Dockerfile-Cloud-Starter
> +FROM golang:1.18 as build
this is only meant for testing fly machines, just ignore it

2023-01-17 10:26 UTC, jensneuse commented on packages/sdk/src/operations/operations.ts
> +import { z } from 'zod';
Can you explain? Does this belong to server? It's about operations/functions?

2023-01-17 10:31 UTC, StarpTech commented on packages/sdk/src/operations/operations.ts
> +import { z } from 'zod';
To separate the server from the sdk we have introduced `@wundergraph/sdk/server` as the primary entry point for everything server related. Functions similar to webhooks are running on the server so I'd suggest to put it there as well.

2023-01-17 10:36 UTC, StarpTech commented on Dockerfile-Cloud-Starter
> +CMD ["/bin/sh","-c","node .wundergraph/generated/bundle/server.js & wunderctl start --exclude-server --pretty-logging=false --shutdown-after-idle=10 --wundergraph-dir=.wundergraph"]
ok, but I'd not put it at the root because it might confuse users.

2023-01-17 10:39 UTC, Pagebakers requested changes
With folder based operations, what does this mean to .graphql operations?

/users/get.graphql translate to `operationName: 'users/get'` now as well?

In that case it's a breaking change, because we have some customers/users that group operations in sub folders. (Tripadvisor?)

Add migration instructions, and inform developers.

2023-01-17 10:39 UTC, Pagebakers commented on fly-machine-test.sh
> +fly apps destroy "$FLY_APP_NAME" --yes
Same as the Dockerfile-Cloud-Starter, don't think this should be here

2023-01-17 10:39 UTC, Pagebakers commented on packages/sdk/src/server/plugins/functions.ts
> +					} catch (e) {
Does this implement input validation errors?

```
{
	propertyPath: string;
	message: string;
	invalidValue: any;
}[]
```

2023-01-17 10:42 UTC, jensneuse commented on Dockerfile-Cloud-Starter
> +CMD ["/bin/sh","-c","node .wundergraph/generated/bundle/server.js & wunderctl start --exclude-server --pretty-logging=false --shutdown-after-idle=10 --wundergraph-dir=.wundergraph"]
moved into test app

2023-01-17 10:48 UTC, jensneuse commented on packages/sdk/src/operations/operations.ts
> +import type { User } from '../client';
changed

2023-01-17 12:57 UTC, StarpTech approved these changes
LGTM

2023-01-17 15:31 UTC, jensneuse commented on packages/sdk/src/server/plugins/functions.ts
> +					} catch (e) {
it's handled in go by the gateway already

2023-01-17 15:31 UTC, jensneuse commented on fly-machine-test.sh
> +fly apps destroy "$FLY_APP_NAME" --yes
moved

2023-01-17 15:32 UTC, jensneuse commented
> With folder based operations, what does this mean to .graphql operations?
> 
> /users/get.graphql translate to `operationName: 'users/get'` now as well?
> 
> In that case it's a breaking change, because we have some customers/users that group operations in sub folders. (Tripadvisor?)
> 
> Add migration instructions, and inform developers.

yup

2023-01-17 16:03 UTC, merged