fix: json scalar types rendering not supported for graphql api
wundergraph/wundergraph pull request #516
Opened 2023-01-05 12:28 UTC by spetrunin

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-01-08 12:20 UTC, StarpTech requested changes
Looks great, I only made a couple of suggestions for the testapp.

2023-01-08 12:20 UTC, StarpTech commented on testapps/simple/README.md
> +npm install && npm start
In our workspace, we use pnpm

2023-01-08 12:20 UTC, StarpTech commented on testapps/simple/tsconfig.json
> +  "compilerOptions": {
Inherit from the shared tsconfig at the root.

2023-01-08 12:20 UTC, StarpTech commented on testapps/simple/.wundergraph/wundergraph.operations.ts
> +export default configureWunderGraphOperations<OperationsConfiguration>({
Is that everything needed to be a simple example?

2023-01-08 12:20 UTC, StarpTech commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +		enableGraphQLEndpoint: process.env.NODE_ENV !== 'production' || process.env.GITPOD_WORKSPACE_ID !== undefined,
GITPOD_WORKSPACE_ID not needed

2023-01-08 12:20 UTC, StarpTech commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +import { configureWunderGraphApplication, cors, EnvironmentVariable, introspect, templates } from '@wundergraph/sdk';
Why do we need another testapp?

2023-01-09 12:06 UTC, spetrunin commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +import { configureWunderGraphApplication, cors, EnvironmentVariable, introspect, templates } from '@wundergraph/sdk';
yep, it is basically empty starter in context of the workspace

maybe better name will be `debug` or smth like that

it is purpose to been able to debug some issues inside sdk without any additional api

default test app is too huge, contains a lot of features from wundergraph

2023-01-09 12:29 UTC, spetrunin commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +		enableGraphQLEndpoint: process.env.NODE_ENV !== 'production' || process.env.GITPOD_WORKSPACE_ID !== undefined,
removed

2023-01-09 12:30 UTC, spetrunin commented on testapps/simple/README.md
> +npm install && npm start
removed readme

2023-01-10 09:15 UTC, StarpTech commented on testapps/simple/tsconfig.json
> +  "compilerOptions": {
ok, its fine :+1:

2023-01-10 09:16 UTC, StarpTech commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +import { configureWunderGraphApplication, cors, EnvironmentVariable, introspect, templates } from '@wundergraph/sdk';
ok, but we should have a structure for which testapps are used for what cases.

2023-01-10 15:29 UTC, spetrunin commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +import { configureWunderGraphApplication, cors, EnvironmentVariable, introspect, templates } from '@wundergraph/sdk';
I have added a draft readme

2023-01-10 18:56 UTC, StarpTech commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +import { configureWunderGraphApplication, cors, EnvironmentVariable, introspect, templates } from '@wundergraph/sdk';
Thank you

2023-01-10 18:56 UTC, StarpTech approved these changes
LGTM

2023-01-11 08:33 UTC, jensneuse requested changes

2023-01-11 08:33 UTC, jensneuse commented on packages/sdk/src/graphql/configuration.ts
> +	scalars.push(...jsonScalars);
does it make sense to do this for each field? could it be done e.g. at the top of visitSchema?

2023-01-11 08:48 UTC, spetrunin commented on packages/sdk/src/graphql/configuration.ts
> +	scalars.push(...jsonScalars);
yep, updated

2023-01-11 09:34 UTC, jensneuse approved these changes

2023-01-11 09:34 UTC, merged

2023-01-12 14:52 UTC, acdn-sglanzer commented
Would it be possible to publish a new release including this?

2023-01-18 09:27 UTC, spetrunin commented
`@wundergraph/sdk@0.131.0` was released with this fix

2023-01-20 05:57 UTC, greemo commented
@spetrunin  as commented on the original issue #448 , this fix breaks the logic for returning json strings