alberto/eng 1014 fix listening on with
wundergraph/wundergraph pull request #517
Opened 2023-01-06 21:29 UTC by fiam

- fix: when WG_NODE_HOST is a hostname resolve and listen in all addresses
- chore: dummy commit to trigger examples CI, UNDO BEFORE MERGE

2023-01-07 22:09 UTC, StarpTech requested changes

2023-01-07 22:09 UTC, StarpTech commented on examples/simple/README.md
> +dummy
Revert

2023-01-07 22:09 UTC, StarpTech commented on pkg/node/node.go
> +	if net.ParseIP(host) == nil {
localhost is special. We should not inherit it for all names. This can be a pitfall. We only now that localhost is safe.

2023-01-08 10:21 UTC, fiam commented on pkg/node/node.go
> +		listener, err := cfg.Listen(context.Background(), bindProto, toListen)
Changed

2023-01-08 10:23 UTC, fiam commented on pkg/node/node.go
> +			panic(fmt.Errorf("%s doesn't look like an IPv4 nor an IPv6", addr))
This is one of the cases where one should panic, because it's a programming error. The panic is to mark the section as unreachable (e.g. like `__builtin_unreachable()` GCC's builtin). However, I've just realized we can rewrite that to not need 3 branches and then we can remove the panic entirely.

2023-01-08 10:27 UTC, fiam commented on examples/simple/README.md
> +dummy
I'll leave it in until we get the PR ready to be merged, so CI continues to trigger

2023-01-08 10:34 UTC, fiam commented on pkg/node/node.go
> +	if net.ParseIP(host) == nil {
There are more ways to specify a valid hostname that might make sense. `something.local` or even a public DNS name. I've also realized we should not manually decide when something is an IP or it's not. We can always resolve it and look at the returned values.

2023-01-08 10:50 UTC, StarpTech commented on examples/simple/README.md
> +dummy
ok

2023-01-08 10:50 UTC, StarpTech commented on pkg/node/node.go
> +			panic(fmt.Errorf("%s doesn't look like an IPv4 nor an IPv6", addr))
Great

2023-01-10 10:38 UTC, StarpTech commented
I think I found another issue related to Ipv6. When the node only listen to ipv6 but the server on both I get 

```
2023-01-10T11:32:24+01:00 INFO: Server listening at http://[::1]:9992 {"component":"@wundergraph/server"}
2023-01-10T11:32:24+01:00 INFO: Server listening at http://127.0.0.1:9992 {"component":"@wundergraph/server"}


2023-01-10T11:29:01+01:00 ERROR: connect ECONNREFUSED ::1:9991 {"component":"@wundergraph/server","reqId":"2913d5a2-1a18-108e-df27-c716eb4c560c"}
    err: {
      "message": "connect ECONNREFUSED ::1:9991",
      "stack":
          Error: connect ECONNREFUSED ::1:9991

```

Are you able to reproduce?

2023-01-11 10:29 UTC, StarpTech approved these changes
LGTM

2023-01-11 11:04 UTC, fiam commented on pkg/node/node.go
> +			if err := n.server.Serve(l); err != nil {
If you do it that way then you can't use the shorter "if with assignment"

2023-01-11 11:55 UTC, Aenimus approved these changes

2023-01-11 12:04 UTC, merged