feat: add support for disconnecting from Auth0
wundergraph/wundergraph pull request #525
Opened 2023-01-09 15:37 UTC by fiam

Auth0 doesn't implement OIDC's end_session_endpoint, requiring a custom
API instead. Add machinery to support this kind of APIs and implement
a provider type to handle this.

Also, update the auth0-oidc-authentication example to use port 3000
and add some extra setup instructions

Fixes ENG-1016
Fixes ENG-968

2023-01-11 19:01 UTC, jensneuse approved these changes

2023-01-11 19:01 UTC, jensneuse requested changes
see comments

2023-01-11 19:10 UTC, fiam commented on pkg/authentication/oidc.go
> +	m  map[string]*OpenIDConnectProvider
You're not missing anything, it's not required. I added it before I went through the rest of the code handling OIDC providers. I'll remove it.

2023-01-11 19:13 UTC, fiam commented on examples/auth0-oidc-authentication/.wundergraph/wundergraph.config.ts
> +				authProviders.auth0({
That's correct, that's why we made `create-wundergraph-app` download from the last stable tag instead of fetching from main (otherwise we can't ever make breaking changes). But you've made a good point, because we totally forgot to do the same for the cloud templates.

2023-01-11 19:33 UTC, fiam commented on packages/sdk/src/client/types.ts
> +	redirect?: (url: string) => Promise<boolean>;
Good idea. I’ll add it.

2023-01-11 20:15 UTC, fiam commented
@jensneuse PR updated, PTAL. Thanks!

2023-01-11 21:49 UTC, jensneuse requested changes

2023-01-11 21:49 UTC, jensneuse commented on pkg/authentication/oidc.go
> +		if provider.config.Issuer == issuer {
If we have 2 OIDC providers with a different id, but the same issue, we'd select the first, which might be wrong.
How about using the user object and selecting the provider by id? This way, you could also use the map actually.

2023-01-12 08:50 UTC, fiam commented on pkg/authentication/oidc.go
> +		if provider.config.Issuer == issuer {
I like that better. I though we were using the issuer URL because there might be circumstances where `User.ProviderID` is not set, but I guess I was wrong. I'll update it.

2023-01-12 10:30 UTC, fiam commented on pkg/authentication/oidc.go
> +		if provider.config.Issuer == issuer {
Updated, PTAL

2023-01-12 11:03 UTC, jensneuse commented on pkg/authentication/oidc.go
> +	provider := s.m[id]
you can do `provider,exists := s.m[id]`
btw, can m have a real name, like providers? =)

2023-01-12 11:03 UTC, jensneuse approved these changes

2023-01-12 11:08 UTC, jensneuse approved these changes

2023-01-12 11:08 UTC, jensneuse commented
good work!

2023-01-12 11:08 UTC, fiam commented
> good work!

Thanks!

2023-01-13 10:23 UTC, StarpTech requested changes

2023-01-13 10:23 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +		if (response.headers.get('Content-Type') === 'application/json') {
From my experience with https://github.com/StarpTech/apollo-datasource-http I know that content negotiation like this is error prone.

I recommend doing it like this https://github.com/StarpTech/apollo-datasource-http/blob/main/src/http-data-source.ts#L344

2023-01-13 10:23 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +				} else {
This only works on the browser. Is it intended to run this function on the server? At least, I'd check for the existence of the window object.

2023-01-13 10:25 UTC, fiam commented on packages/sdk/src/client/client.ts
> +				} else {
It's the same approach we use with `fetch`, we let it blow up in the server. I will add a check, but what should we do when not in a browser? Throw an error asking the user to pass the redirect function?

2023-01-13 10:26 UTC, fiam commented on packages/sdk/src/client/client.ts
> +		if (response.headers.get('Content-Type') === 'application/json') {
That's definitely more robust, I'll change it.

2023-01-13 10:29 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +				} else {
I'd do nothing. The user can already do something after logout with `after`. The redirect is async anyway.

2023-01-13 10:33 UTC, fiam commented on packages/sdk/src/client/client.ts
> +				} else {
The redirect is required for disconnecting from the auth provider and completing the log out when `logoutOpenidConnectProvider` is true, we need to keep it.

2023-01-13 10:38 UTC, fiam commented on packages/sdk/src/client/client.ts
> +				} else {
I've noticed we don't support `login()` and `logout()` in the server side. `login()` already has a check for it, I'll add the same in `logout()`

2023-01-13 10:42 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +				} else {
That's sad because you could issue a logout on the server and redirect yourself.

2023-01-13 10:47 UTC, StarpTech approved these changes
LGTM

2023-01-13 10:50 UTC, merged