fix: prevent swallowing of input validation errors
wundergraph/wundergraph pull request #529
Opened 2023-01-11 16:15 UTC by Aenimus

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-01-12 13:57 UTC, Aenimus commented on testapps/default/.wundergraph/wundergraph.config.ts
> +				: ['http://localhost:3000', 'http://localhost:9991'],
I will revert this.

2023-01-12 17:28 UTC, fiam approved these changes
LGTM. Excited to get better error messages!

2023-01-13 09:26 UTC, Pagebakers requested changes
Looks great!

One thing though. In our SWR and React Query clients we use GraphqlResponseError as the error type. I believe we should rewrite this to ClientResponseError instead. So useQuery and useMutation return the correct error type.

2023-01-13 10:59 UTC, spetrunin commented on packages/react-query/src/types.ts
> +import { ClientResponseError } from '@wundergraph/sdk/dist/client/ClientResponseError';
I believe import should not be from dist, but from package itself

```
@wundergraph/sdk/client/ClientResponseError'
```

maybe you will need to export it ether from client to been able to to this
```
import { ClientResponseError } from '@wundergraph/sdk/dist/client';
```

2023-01-13 18:15 UTC, Pagebakers approved these changes
Nice work!

2023-01-16 09:28 UTC, merged