chore: add support for extra telemetry fields
wundergraph/wundergraph pull request #541
Opened 2023-01-13 17:15 UTC by fiam

2023-01-14 05:52 UTC, Slickstef11 approved these changes

2023-01-18 08:36 UTC, jensneuse requested changes

2023-01-18 08:36 UTC, jensneuse commented on cli/commands/root.go
> +								return nil, err
As a rule of thumb, I always try to have at max 2 levels of (if|else|switch) nesting. In very very rare cases 3 levels might be an escape hatch. 8 levels are absolutely unmaintainable. Please give this code some structure.

2023-01-18 08:36 UTC, jensneuse commented on pkg/telemetry/client.go
> +// Equal returns true iff both Metric instances contain the same data
typo: iff -> if

2023-01-18 08:36 UTC, jensneuse commented on cli/commands/root.go
> +					if err != nil {
Do you want to return an error when the datasource is not supported? I'm not sure if the err check makes sense in this case.

2023-01-18 08:53 UTC, StarpTech requested changes

2023-01-18 08:53 UTC, StarpTech commented on pkg/telemetry/client.go
> +func (m *Metric) Equal(other *Metric) bool {
Please add tests for both functions.

2023-01-18 08:53 UTC, StarpTech commented on pkg/telemetry/client.go
> +		invalidChars       = ";!^="
This should be validated on the cloud. In the cloud, we can sanitize invalid tags. In wunderctl, we are in control of every metric. I see no value in adding it here.

2023-01-18 08:53 UTC, StarpTech commented on cli/commands/root.go
> +func dataSourcesTelemetryMetrics(info *telemetry.MetricClientInfo) ([]*telemetry.Metric, error) {
Please put this in a package. The root file contains already a lot of stuff.

2023-01-18 08:53 UTC, StarpTech commented on cli/helpers/telemetry.go
> +	TelemetryAnnotationCommand TelemetryAnnotation = 1 << iota
What should that mean? Can we be more explicit e.g. `EnableTelemetry` I'd also suggest using string instead int which is easier to grasp.

2023-01-18 11:11 UTC, fiam commented on cli/commands/root.go
> +					if err != nil {
The idea was to make it evident for future developers, but an error might be too harsh. Would you prefer a warning message in the logs while handling the known data source types?

2023-01-18 11:34 UTC, fiam commented on pkg/telemetry/client.go
> +// Equal returns true iff both Metric instances contain the same data
https://en.wikipedia.org/wiki/If_and_only_if

2023-01-18 11:36 UTC, fiam commented on cli/commands/root.go
> +					urlVariable = ds.CustomDatabase.GetDatabaseURL()
It's resolved here https://github.com/wundergraph/wundergraph/pull/541/files#diff-6cef6e709aaccb651a756f23bbae52a22cbe8f82fbe90258831d7c189b42915aR279 - Using that same function

2023-01-18 11:40 UTC, fiam commented on cli/helpers/telemetry.go
> +	TelemetryAnnotationCommand TelemetryAnnotation = 1 << iota
It means that the command usage/duration should be reported via telemetry. `cmd.Annotations` is a map[string]string, but I introduced constants on top to avoid errors due to mistyped strings.

2023-01-18 11:41 UTC, fiam commented on pkg/telemetry/client.go
> +		invalidChars       = ";!^="
I would validate it in both places. Otherwise, the failure report is too disconnected from the error and becomes difficult to diagnose when someone runs into it.

2023-01-18 13:19 UTC, fiam commented on cli/commands/root.go
> +func dataSourcesTelemetryMetrics(info *telemetry.MetricClientInfo) ([]*telemetry.Metric, error) {
Moved it to `pkg/telemetry`, PTAL

2023-01-18 14:06 UTC, fiam commented on cli/commands/root.go
> +									if err := metric.AddTag("localhost", "true"); err != nil {
Updated to detect all private IPs, PTAL

2023-01-18 14:06 UTC, fiam commented on pkg/telemetry/client.go
> +func (m *Metric) Equal(other *Metric) bool {
Added

2023-01-18 14:06 UTC, fiam commented on cli/helpers/telemetry.go
> +	TelemetryAnnotationCommand TelemetryAnnotation = 1 << iota
Refactored this into a simpler approach

2023-01-18 16:55 UTC, YuriBuerov commented on pkg/telemetry/client.go
> +				c.log.Debug("error retrieving gitRepoURLHash: %w", zap.Error(err))
why is it needed to use wrap (`%w`) for the log message?

2023-01-18 17:04 UTC, YuriBuerov commented on pkg/telemetry/client.go
> +	if m.Name == other.Name && m.Value == other.Value && len(m.Tags) == len(other.Tags) {
I would simplify it.
Two options:

1) using reflect, something like:
```
func (m *Metric) Equal(other *Metric) bool {
    if m.Name == other.Name && m.Value == other.Value {
        return reflect.DeepEqual(m.Tags, other.Tags)
    }
    return false
}
```

2)  with comparison func:
```
func (t MetricTag) Equal(other MetricTag) bool {
    return t.Name == other.Name && t.Value == other.Value
}

func (m *Metric) Equal(other *Metric) bool {
    if m.Name == other.Name && m.Value == other.Value && len(m.Tags) == len(other.Tags) {
        for i := range m.Tags {
            if !m.Tags[i].Equal(other.Tags[i]) {
                return false
            }
        }
        return true
    }
    return false
}
```

2023-01-18 17:10 UTC, fiam commented on pkg/telemetry/client.go
> +				c.log.Debug("error retrieving gitRepoURLHash: %w", zap.Error(err))
Good catch. It was an error return at first. I’ll amend it.

2023-01-18 17:16 UTC, fiam commented on pkg/telemetry/client.go
> +	if m.Name == other.Name && m.Value == other.Value && len(m.Tags) == len(other.Tags) {
I'd rather not use reflect unless we strictly need it, I'll refactor the MetricTag comparison to a method.

2023-01-18 17:20 UTC, fiam commented on pkg/telemetry/client.go
> +	if m.Name == other.Name && m.Value == other.Value && len(m.Tags) == len(other.Tags) {
I've just realized that reflect.DeepEqual wouldn't work because multiple Metric instances with the same tags but in different order should still be equal.

2023-01-18 17:23 UTC, fiam commented on pkg/telemetry/client.go
> +				c.log.Debug("error retrieving gitRepoURLHash: %w", zap.Error(err))
Updated, PTAL

2023-01-18 17:23 UTC, fiam commented on pkg/telemetry/client.go
> +	if m.Name == other.Name && m.Value == other.Value && len(m.Tags) == len(other.Tags) {
Updated, PTAL

2023-01-18 18:00 UTC, YuriBuerov commented on pkg/telemetry/client.go
> +	if m.Name == other.Name && m.Value == other.Value && len(m.Tags) == len(other.Tags) {
why not get rid of found -> break,  and just return like in my example?

2023-01-18 18:02 UTC, fiam commented on pkg/telemetry/client.go
> +	if m.Name == other.Name && m.Value == other.Value && len(m.Tags) == len(other.Tags) {
Your example requires the tag order to match, but we want to ignore the order (because once these make their way into graphite, they're unordered)

2023-01-18 18:05 UTC, YuriBuerov commented on pkg/telemetry/client.go
> +	if name[0] == invalidInitialChar[0] {
I would use `regexp` this way it will be more readable and even faster than `string.ContainsAny` below
like:

```
var invalidCharsRegex = regexp.MustCompile(`[;!^=]`)
var invalidInitialCharRegex = regexp.MustCompile(`^[~]`)
```

or alternatively `strings.IndexAny`

2023-01-18 18:10 UTC, fiam commented on pkg/telemetry/client.go
> +	if name[0] == invalidInitialChar[0] {
Regexp makes the check less readable and the performance difference for the string lengths we're using has to be negligible

2023-01-18 18:34 UTC, YuriBuerov requested changes

2023-01-18 18:34 UTC, YuriBuerov commented on pkg/telemetry/client_test.go
> +	testCases := []struct {
```
testCases := []struct {
		name string
		a    *Metric
		b    *Metric
		want bool
}{
	{name: "equal", a: m1, b: m1, want: true},
	{name: "not equal", a: m1, b: m2, want: false},
	{name: "not equal", a: m1, b: m3, want: false},
	{name: "not equal", a: m1, b: m4, want: false},
	{name: "equal", a: m1, b: m5, want: true},
}

for _, tc := range testCases {
	t.Run(tc.name, func(t *testing.T) {
		assert.Equal(t, tc.want, tc.a.Equal(tc.b))
		assert.Equal(t, tc.want, tc.b.Equal(tc.a))
	})
}
```

2023-01-18 18:34 UTC, YuriBuerov commented on pkg/telemetry/client.go
> +	if name[0] == invalidInitialChar[0] {
I would not agree with less readable, but ok, it works for me

2023-01-18 18:34 UTC, YuriBuerov commented on pkg/telemetry/client_test.go
> +	assert.NotNil(t, m.AddTag("", tagValue), "should fail to add empty tag")
I would use `assert.Error`

2023-01-18 18:34 UTC, YuriBuerov commented on pkg/telemetry/client_test.go
> +	for _, ch := range ";!^=" {
it would better to reuse const here, so in test and implementation you will always have same values

2023-01-18 18:34 UTC, YuriBuerov commented on pkg/telemetry/client_test.go
> +	assert.Equal(t, 1, len(m.Tags), "should have one tag")
`assert.Len`

2023-01-18 19:32 UTC, fiam commented on pkg/telemetry/client.go
> +	if name[0] == invalidInitialChar[0] {
> I would not agree with less readable, but ok, it works for me

I didn't know you enjoyed Perl 😁

2023-01-18 19:37 UTC, fiam commented on pkg/telemetry/client_test.go
> +	for _, ch := range ";!^=" {
Good idea, I'll move the constants outside the method and reference them from the test

2023-01-18 19:41 UTC, fiam commented on pkg/telemetry/client_test.go
> +	testCases := []struct {
I'd rather use the struct dump as the test name, I feel it's easier to spot what's actually being tested, but I'll rename the boolean field.

2023-01-19 09:05 UTC, fiam commented on pkg/telemetry/client.go
> +		invalidChars       = ";!^="
Added validation to cloud

2023-01-19 10:25 UTC, jensneuse approved these changes
amazing work!

2023-01-19 14:04 UTC, StarpTech approved these changes
LGTM

2023-01-20 11:45 UTC, fiam commented
@YuriBuerov PTAL

2023-01-22 18:34 UTC, StarpTech requested changes

2023-01-22 18:34 UTC, StarpTech commented on cli/commands/root.go
> +				dataSourcesMetrics, err := telemetry.DataSourceMetrics(wunderGraphDir)
Loading and parsing the whole file twice on every start may make our cold start slower. Is there any room for improvement? Otherwise, I'd go with it and measure the impact.

2023-01-22 20:56 UTC, jensneuse commented on cli/commands/root.go
> +				dataSourcesMetrics, err := telemetry.DataSourceMetrics(wunderGraphDir)
How about this: send a signal when WunderNode is listening. Then do things that are not required for serving requests.

2023-01-23 21:48 UTC, fiam commented on cli/commands/root.go
> +				dataSourcesMetrics, err := telemetry.DataSourceMetrics(wunderGraphDir)
We're only sending the data source metrics in `wunderctl up`, so it shouldn't have any impact in production. We can add some means for the Node to emit an event when the configuration is parsed, thought, that might come in handy for eventually allowing the testing SDK to modify the config on the fly.

2023-01-23 22:20 UTC, jensneuse approved these changes

2023-01-24 11:08 UTC, StarpTech commented on cli/commands/root.go
> +				dataSourcesMetrics, err := telemetry.DataSourceMetrics(wunderGraphDir)
Sounds great.

2023-01-24 11:09 UTC, StarpTech approved these changes
LGTM

2023-01-25 09:20 UTC, merged