fix: avoid double escaping special characters in JSON
wundergraph/wundergraph pull request #567
Opened 2023-01-19 16:09 UTC by fiam

Apply jsonparser.EachKey() returns escaped keys, so we need to unescape
them

Fixes #377

2023-01-19 16:15 UTC, Aenimus commented on pkg/customhttpclient/customhttpclient.go
> +		if len(parameterName) != 0 && len(parameterValue) != 0 {
Are we able to unnest this?

2023-01-19 16:17 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +		if len(parameterName) != 0 && len(parameterValue) != 0 {
I don't think so, `jsonparser.EachKey` uses a callback

2023-01-19 16:19 UTC, Aenimus commented on pkg/customhttpclient/customhttpclient.go
> +		if len(parameterName) != 0 && len(parameterValue) != 0 {
I just mean `if len(parameterName) != 0 && len(parameterValue) != 0 {`, which is within `jsonparser.ArrayEach`

2023-01-19 16:19 UTC, Aenimus commented on pkg/customhttpclient/customhttpclient.go
> +		if len(parameterName) != 0 && len(parameterValue) != 0 {
could we pass or return or otherwise do nothing and un-nest the if else?

2023-01-19 16:20 UTC, jensneuse requested changes

2023-01-19 16:23 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +				query.Add(string(parameterName), string(parameterValue))
We can use unsafe string conversions because those strings are temporary until `encodeQueryParams()` returns. I'll update it.

2023-01-19 16:27 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +				query.Add(string(parameterName), string(parameterValue))
Changed to `unsafebytes.BytesToString()`

2023-01-19 16:28 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +	unescaped, err := jsonparser.Unescape(in, nil)
That should be fine because at the end of `encodeQueryParams()` we encode the whole query string

2023-01-19 20:54 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +		if len(parameterName) != 0 && len(parameterValue) != 0 {
I've changed it to an early return

2023-01-19 21:29 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +	unescaped, err := jsonparser.Unescape(in, nil)
I don't think we can use a pool effectively here. The number of keys is variable and we would need the buffers inside the `jsonparser` callbacks, so we need to allocate to keep track of the buffers that we need to put back. On the other hand, I've realized that the JSON we receive at that point is double encoded, which means we can safely unescape it into itself, hence avoiding any allocations. PTAL

2023-01-20 08:07 UTC, jensneuse requested changes
I suggest 2 small changes, then we're good.

2023-01-20 08:07 UTC, jensneuse commented on pkg/customhttpclient/customhttpclient.go
> +		rawQuery, err := encodeQueryParams(queryParams)
If you're using unsafe inside encodeQueryParams, we have to get a buffer from the pool, copy the original queryParams into the buffer, encode it, and defer release the buffer. Otherwise we're messing up "requestInput", which is the source of queryParams. requestInput can be passed to many Load functions, re-using resources. We're not allowed to directly "touch" it. If we want to manipulate it, we either make a copy with unsafe OR we use a string, which implicitly makes a copy (string is an immutable byte slice). I've ran into this issue before with the Load function. So, either we use string, or we have to explicitly make a copy and keep the buffer around as long as we're using the bytes we've touched with unsafe.

2023-01-20 08:07 UTC, jensneuse commented on pkg/customhttpclient/customhttpclient.go
> +	return jsonparser.Unescape(in, in)
I'm not sure if this is correct. Why not just create another buffer outside this function (in Load) from a buffer pool, pass it to this func as out buffer, and release it with defer in Load. This should work fine and will be less error prone.

2023-01-20 10:50 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +	return jsonparser.Unescape(in, in)
Added a local copy of queryParams with a pooled buffer, PTAL

2023-01-20 10:51 UTC, fiam commented on pkg/customhttpclient/customhttpclient.go
> +		rawQuery, err := encodeQueryParams(queryParams)
Added a local copy, as requested. PTAL

2023-01-20 12:02 UTC, jensneuse approved these changes

2023-01-22 12:19 UTC, jensneuse approved these changes

2023-01-22 16:32 UTC, StarpTech approved these changes
lgtm

2023-01-22 16:40 UTC, merged