fix: handler, return graphql errors
wundergraph/wundergraph pull request #575
Opened 2023-01-20 14:00 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-01-20 15:25 UTC, spetrunin approved these changes

2023-01-20 19:50 UTC, jensneuse requested changes
Can you add a test to cover this behavior? I think the easiest way would be to add it to `node_test.go`
https://github.com/wundergraph/wundergraph/blob/main/pkg/node/node_test.go

2023-01-23 07:18 UTC, fiam commented
Except for the missing test, LGTM. I’ll approve as soon as the test is added.

2023-01-23 13:25 UTC, fiam approved these changes
LGTM

2023-01-23 17:59 UTC, jensneuse approved these changes

2023-01-23 18:10 UTC, merged