feat: federation, support extend keyword
wundergraph/wundergraph pull request #578
Opened 2023-01-20 18:10 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-01-20 18:41 UTC, spetrunin approved these changes

2023-01-20 18:41 UTC, spetrunin commented
LGTM

2023-01-20 19:47 UTC, jensneuse requested changes
can you add a test?

2023-01-23 18:15 UTC, jensneuse approved these changes

2023-01-24 09:19 UTC, merged