feat: add JWKS tests and update MicahParks/keyfunc
wundergraph/wundergraph pull request #580
Opened 2023-01-21 09:29 UTC by fiam

- feat: add testapp for JWKS
- chore: update keyfunc and add 100% backwards compatible options
- Remove 100% backwards compatible keyfunc options
- chore: update MicahParks/keyfunc to v1.9.0

2023-01-21 10:12 UTC, fiam commented
@MicahParks Thaks for your contribution! I've pulled your commits from #294 and I've also added some tests for JWKS on top.

2023-01-23 07:55 UTC, jensneuse approved these changes

2023-01-23 07:55 UTC, jensneuse commented on testapps/jwks/test/index.test.ts
> +		client.setExtraHeaders({
Can we add a method on the client e.g. named `client.setAuthorizationToken`.
Extra headers is quite low level. I think setAuthorizationToken give a user better ergonomics.

2023-01-23 07:55 UTC, jensneuse commented on testapps/jwks/test/index.test.ts
> +	const token = await new jose.SignJWT({})
great way to test!

2023-01-23 07:55 UTC, jensneuse commented on testapps/jwks/test/index.test.ts
> +	process.env['JWKS_JSON'] = JSON.stringify(jwksKeys);
so smart!

2023-01-23 09:49 UTC, Pagebakers approved these changes

2023-01-23 15:59 UTC, fiam commented on testapps/jwks/test/index.test.ts
> +		client.setExtraHeaders({
Sure

2023-01-23 16:08 UTC, fiam commented on testapps/jwks/test/index.test.ts
> +	process.env['JWKS_JSON'] = JSON.stringify(jwksKeys);
Thank you!

2023-01-23 17:55 UTC, jensneuse requested changes

2023-01-23 17:55 UTC, jensneuse commented on testapps/jwks/test/index.test.ts
> +		client.setAuthorizationToken('');
I don't want to annoy you, but wouldn't it make sense to also add client.unsetAuthorizationToken which removes the Authorization header from the extra headers if it existed? setAuthorizationToken with empty string will still send "Authorization: Bearer "

2023-01-23 21:46 UTC, fiam commented on testapps/jwks/test/index.test.ts
> +		client.setAuthorizationToken('');
No worries, I think it's a good idea. I've added `Client.removeAuthorization()` with the idea of eventually using it for both tokens and cookies. PTAL

2023-01-23 22:21 UTC, jensneuse approved these changes

2023-01-23 22:21 UTC, jensneuse commented on testapps/jwks/test/index.test.ts
> +		client.setAuthorizationToken('');
LGTM

2023-01-23 22:21 UTC, jensneuse commented on testapps/jwks/test/index.test.ts
> +		client.setExtraHeaders({
LGTM

2023-01-24 06:27 UTC, merged