chore: wip improve functions
wundergraph/wundergraph pull request #595
Opened 2023-01-24 15:31 UTC by jensneuse

2023-01-28 22:18 UTC, jensneuse commented
TODO: @Pagebakers please fix the errors in the client test

2023-01-30 15:52 UTC, fiam commented
I've run this against all the test in examples locally and they pass

2023-01-30 15:57 UTC, Pagebakers requested changes
Overall nice improvement, but I'm not sure why we couldn't re-use the Typescript client here with simply setting a custom baseURL.

2023-01-30 15:57 UTC, Pagebakers commented on packages/sdk/src/operations/operations.ts
> +	<IC extends InternalClient, UserRole extends string, Queries, Mutations, Subscriptions>() =>
I'd prefer to see Queries/Mutations and Subscriptions be merged into one generic `Operations`, cleaner and consistent with all frontend clients.

2023-01-30 15:57 UTC, Pagebakers commented on packages/sdk/src/server/operations-client.ts
> +				const res = await fetch(url, {
fetch in nodejs is still experimental

2023-01-30 16:20 UTC, fiam commented on packages/sdk/src/operations/operations.ts
> +	<IC extends InternalClient, UserRole extends string, Queries, Mutations, Subscriptions>() =>
It can't be merged into one generic `Operations` because otherwise then we can't constrain on them as template parameters (not exactly in this spot, but somewhere else along the chain).

You can constrain a generic as `<..., TQueries extends Operations, TMutations extends Operations, TSubscriptions extends Operations>` and then replace then with subtypes.

On the other hand, if you use `<... Operations extends Operations<Operation, Operation, Operation>` then `Operations<TQueries, Mutation, TSubscription>` doesn't extend `Operations<Operation, Operation, Operation>`

2023-01-30 16:28 UTC, fiam commented on packages/sdk/src/server/operations-client.ts
> +				const res = await fetch(url, {
I've added support for using a custom fetch function. PTAL

2023-01-30 17:33 UTC, Pagebakers requested changes

2023-01-30 17:33 UTC, Pagebakers commented on packages/sdk/src/server/operations-client.ts
> +	customFetch?: (input: URL | RequestInfo, init?: RequestInit) => Promise<globalThis.Response>;
Sorry but we have to revert this, this will still result in a broken state if fetch is not enabled in node (and older node versions). There is no way to configure a custom fetch anywhere, the operations client is initiated in the fastify server.

https://github.com/wundergraph/wundergraph/pull/595/files#diff-2f9c5d63c84e8681f889caeb22b494c16f93545d9368d37cf2d15829be1db0b5R38

I'd suggest to use axios like in the internalClient for now, so we don't need to introduce new dependencies and we can replace it once node fetch is GA.

2023-01-30 20:33 UTC, fiam commented on packages/sdk/src/server/operations-client.ts
> +	customFetch?: (input: URL | RequestInfo, init?: RequestInit) => Promise<globalThis.Response>;
Thanks for pointing it out. As discussed, we've used `cross-fetch` instead for easier forwards compatibility

2023-01-31 11:09 UTC, Pagebakers approved these changes

2023-01-31 14:41 UTC, StarpTech requested changes

2023-01-31 14:41 UTC, StarpTech commented on packages/sdk/src/server/operations-client.ts
> +			try {
How does error handling work when try has no catch?

2023-01-31 15:12 UTC, fiam commented on packages/sdk/src/server/operations-client.ts
> +			try {
I think this `try` is only for the `finally` on line 128

2023-01-31 18:15 UTC, StarpTech requested changes

2023-01-31 18:15 UTC, StarpTech commented on packages/sdk/src/server/operations-client.ts
> +				abort.abort();
@fiam I mean, in my opinion, the error must be rethrown here, so the user can react and log errors.

2023-02-01 10:08 UTC, StarpTech commented on packages/sdk/src/server/operations-client.ts
> +				abort.abort();
Nice, thank you.

2023-02-01 10:09 UTC, StarpTech approved these changes
LGTM

2023-02-01 11:08 UTC, fiam approved these changes

2023-02-01 11:12 UTC, merged