fix: examples, simple
wundergraph/wundergraph pull request #604
Opened 2023-01-26 18:22 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-01-26 18:34 UTC, jensneuse commented
> Upstream issue.
> 

Is the problem with the origin? Is it not possible to fix it in the engine?

2023-01-26 18:35 UTC, YuriBuerov commented
> > Upstream issue.
> 
> Is the problem with the origin? Is it not possible to fix it in the engine?

correct

2023-01-26 19:45 UTC, jensneuse requested changes

2023-01-26 19:45 UTC, jensneuse commented on examples/simple/.wundergraph/operations/Countries.graphql
> +query Countries($filter: countries_CountryFilterInput) @removeNullVariables {
Can we just switch it to `countries_country(code: "US")`?
It might be confusing if you have to use such a directive in the first example.

2023-01-26 21:19 UTC, fiam commented on examples/simple/.wundergraph/operations/Countries.graphql
> +query Countries($filter: countries_CountryFilterInput) @removeNullVariables {
I agree, I think it would be better if we could avoid introducing `@removeNullVariables` in an example called `simple`. What about giving the filter a default value of `{code:{ne:""}`?

2023-01-27 08:54 UTC, YuriBuerov commented on examples/simple/.wundergraph/operations/Countries.graphql
> +query Countries($filter: countries_CountryFilterInput) @removeNullVariables {
for me, it looks even more unclear.

2023-01-27 11:26 UTC, fiam commented on examples/simple/README.md
>  #### Get Andorra
This subtitle needs to be updated too

2023-01-27 11:36 UTC, jensneuse approved these changes

2023-01-27 11:38 UTC, fiam approved these changes
LGTM

2023-01-27 12:02 UTC, merged