chore: typecheck examples during CI
wundergraph/wundergraph pull request #618
Opened 2023-01-31 10:48 UTC by fiam

Don't just execute them, always validate the types

2023-02-01 12:38 UTC, StarpTech requested changes

2023-02-01 12:38 UTC, StarpTech commented on scripts/test-examples/single.sh
> +elif grep -q '"check"' package.json; then
`check` should be part of the build script. We should split it.

2023-02-01 12:52 UTC, fiam commented on scripts/test-examples/single.sh
> +elif grep -q '"check"' package.json; then
All examples have `build` call `wunderctl generate`, while `check` calls `tsc --noEmit`. We've had that for both examples and testapps for quite long. Are you suggesting we change all those `package.json` to make `build` also call `check?

2023-02-01 17:58 UTC, fiam commented on scripts/test-examples/single.sh
> +elif grep -q '"check"' package.json; then
I was not aware of those plans. So should use the following commands in `package.json`: `"generate": "wunderctl generate"`, `"build": "npm run generate && npm run check"`?

2023-02-01 18:21 UTC, fiam commented on scripts/test-examples/single.sh
> +elif grep -q '"check"' package.json; then
I was not aware of those plans. So should we add `"build:wundergraph": "wunderctl generate"` and `"build": "build:wundergraph && npm run check`

2023-02-01 18:23 UTC, fiam commented on scripts/test-examples/single.sh
> +elif grep -q '"check"' package.json; then
No idea how the double comment happened, apologies for the inconvenience!

2023-02-01 19:49 UTC, StarpTech commented on scripts/test-examples/single.sh
> +elif grep -q '"check"' package.json; then
Not set in stone. I'd make tsc check part of `build`.

2023-02-02 10:53 UTC, fiam commented on scripts/test-examples/single.sh
> +elif grep -q '"check"' package.json; then
As discussed, we're splitting that into a separate issue. Let's concentrate on fixing type-checking in the examples for this one. PTAL.

2023-02-02 21:21 UTC, StarpTech approved these changes
LGTM

2023-02-03 11:16 UTC, Aenimus approved these changes

2023-02-03 11:26 UTC, merged