docs: add documentation for Prisma data source
wundergraph/wundergraph pull request #619
Opened 2023-01-31 16:31 UTC by fiam

2023-02-01 09:31 UTC, Pagebakers requested changes

2023-02-01 09:31 UTC, Pagebakers commented on docs-website/src/pages/docs/supported-data-sources/prisma.md
> +description:
where is the description? title could be better to Prisma Datasource

2023-02-01 09:31 UTC, Pagebakers commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-prisma-datasource.md
> +description:
description

2023-02-01 10:54 UTC, fiam commented on docs-website/src/pages/docs/supported-data-sources/prisma.md
> +description:
Added, PTAL

2023-02-01 10:54 UTC, fiam commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-prisma-datasource.md
> +description:
Added, PTAL

2023-02-02 16:45 UTC, StarpTech approved these changes
LGTM

2023-02-07 12:12 UTC, Pagebakers approved these changes

2023-02-08 10:16 UTC, merged