chore: examples, remove lock files
wundergraph/wundergraph pull request #620
Opened 2023-01-31 18:13 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-01-31 18:27 UTC, StarpTech approved these changes
LGTM

2023-01-31 19:00 UTC, thisisnithin approved these changes

2023-01-31 19:53 UTC, Pagebakers requested changes
the lockfiles shouldn't be in .gitignore of individual examples, but in the root of repo

```
# example lock files
examples/*/package-lock.json
examples/*/yarn.lock
examples/*/pnpm-lock.yaml
```

2023-02-01 10:19 UTC, Pagebakers approved these changes

2023-02-01 10:21 UTC, fiam approved these changes
LGTM

2023-02-01 10:21 UTC, merged