feat: new open api introspection
wundergraph/wundergraph pull request #621
Opened 2023-01-31 18:28 UTC by spetrunin

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-02-01 17:37 UTC, Aenimus commented on packages/sdk/src/rest2graphql/introspection.ts
> +		if (!introspection.id.match(/^[_\-0-9a-zA-z]+$/)) {
I believe it should be`^[a-zA-Z_][a-zA-Z0-9_]+$`

Also, your second `z` is lowercase.

2023-02-01 19:35 UTC, jensneuse requested changes
Looks great. My only concern is that we're generated GraphQL engines for all OAS files at startup, which will affect cold starts. One consideration I'd make is to lazy load the schemas on the fastify server. E.g. create handlers for all schemas, etc. but only initialize the schema when the first request hits this particular endpoint. E.g. you can create a factory that returns a promise. The first request will trigger the promise to resolve the executable schema. All subsequent requests will also wait for this promise. Once it's resolved, the promise will immediately return the schema. This way, we're only really initializing the GraphQL JS Engine/Executable Schema when it's needed.

2023-02-01 19:35 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +				custom.Fetch.baseUrl.staticVariableContent.includes('<SERVER_URL>')
Can you add a comment to explain this behavior?

2023-02-01 19:35 UTC, jensneuse commented on packages/sdk/src/rest2graphql/execution.ts
> +export const createExecutableSchema = async (specName: string): Promise<GraphQLSchema> => {
what is a specName?

2023-02-01 19:35 UTC, jensneuse commented on packages/sdk/src/rest2graphql/execution.ts
> +			ctx.wundergraph?.log?.info(`created headers ${JSON.stringify(headers)}`);
debug log?

2023-02-01 19:35 UTC, jensneuse commented on packages/sdk/src/rest2graphql/introspection.ts
> +		baseUrl: '<SERVER_URL>',
What is `<SERVER_URL>`?

2023-02-01 20:14 UTC, spetrunin commented on packages/sdk/src/rest2graphql/introspection.ts
> +		baseUrl: '<SERVER_URL>',
It is a server url placeholder

We know what it is only at configure stage, but the introspection promise is prepared earlier

So once introspection is resolved we are replacing this placeholder at configure stage

open to ideas on how to do it better

2023-02-01 20:17 UTC, spetrunin commented on packages/sdk/src/rest2graphql/execution.ts
> +export const createExecutableSchema = async (specName: string): Promise<GraphQLSchema> => {
it is a name of a file in `generated/openapi` folder

2023-02-01 20:18 UTC, spetrunin commented on packages/sdk/src/configure/index.ts
> +				custom.Fetch.baseUrl.staticVariableContent.includes('<SERVER_URL>')
explained it in other comment

as this is a POC - this behaviour could be changed

2023-02-01 20:19 UTC, spetrunin commented on packages/sdk/src/rest2graphql/execution.ts
> +			ctx.wundergraph?.log?.info(`created headers ${JSON.stringify(headers)}`);
yeah, in case anyone wants to play with POC - we will see that headers are picked up properly

2023-02-01 20:23 UTC, spetrunin commented on packages/sdk/src/rest2graphql/introspection.ts
> +	writeApiInfo(apiID, spec, introspection);
it could be a problem, cause server didn't know what is actual version of a cached spec

And we will rewrite a file each time id or hash is changed, so we could have a couple of files in this case
And server will load each file as an api

For the POC - this OAS data source becomes just graphql API, so we don't have any additional information about it, cause engine don't need that info and for our api class Api<T> - T is only related to datasources

2023-02-01 20:23 UTC, spetrunin commented on testapps/simple/.wundergraph/wundergraph.config.ts
> +const stripe = introspect.openApiV2({
this is temp code, as stripe spec is very big and should not be stored in the repo

2023-02-01 20:29 UTC, spetrunin commented on packages/sdk/src/server/plugins/graphql.ts
> +			const headers = Object.entries(request.headers).reduce((acc, [key, value]) => {
not so clean solution, open to any suggestion how to do it better

2023-02-01 20:31 UTC, spetrunin commented on packages/sdk/src/rest2graphql/execution.ts
> +	return headersBuilder.build().map((value) => value.key.toLowerCase());
header name converted to lowercase, seems in fastify headers are always lowercased

2023-02-01 20:34 UTC, spetrunin commented on packages/sdk/src/rest2graphql/introspection.ts
> +		headers: introspection.headers,
How headers works:

Headers builder is used by graphql datasource and datasource will process headers and forward proper headers from request to wundergraph server, the only thing that we need is to read these headers instead of client request headers and add them to graphql context

2023-02-08 13:27 UTC, Pagebakers commented on packages/sdk/src/rest2graphql/execution.ts
> +			ctx.wundergraph?.log?.info(`created headers ${JSON.stringify(headers)}`);
Not very safe, we would output secrets in info now.

2023-02-09 11:14 UTC, Pagebakers commented
It's actually pretty fast on my dev environment using the stripe.yaml spec.

There are some quirky field names though. Why does it append 2 after these queries?
Why do some have v1 and others not.

![Screenshot 2023-02-09 at 12 10 32](https://user-images.githubusercontent.com/32583/217797231-8742a7ef-9fcf-48d8-a88e-0a1b4600cbcb.png)
![Screenshot 2023-02-09 at 12 10 11](https://user-images.githubusercontent.com/32583/217797223-cc7c4272-04c0-4f1b-bd5b-9c13c12f2b4c.png)

2023-02-09 13:04 UTC, Pagebakers commented
Introspection keycloak works as well out of the box.

![Screenshot 2023-02-09 at 14 03 40](https://user-images.githubusercontent.com/32583/217820546-89fb86b0-abfb-49c1-b963-0c66f425ff6f.png)

2023-02-09 15:47 UTC, StarpTech requested changes

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/rest2graphql/execution.ts
> +			ctx.wundergraph?.log?.info(`created headers ${JSON.stringify(headers)}`);
Good point, don't log all headers by default.

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/rest2graphql/execution.ts
> +	fs.mkdir(specsFolderPath, { recursive: true }, (err) => {
Use async variant.

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/rest2graphql/execution.ts
> +	fs.writeFileSync(filePath, JSON.stringify(item, null, 2));
Here too

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/rest2graphql/introspection.ts
> +		throw new Error('cannot read OAS');
embed the original error

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/server/plugins/graphql.ts
> +			pluginLogger.info(`GraphQL request  ${JSON.stringify(request)}`);
I think it was for debugging purpose. Fastify already logs requests.

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/server/plugins/graphql.ts
> +			const headers = Object.entries(request.headers).reduce((acc, [key, value]) => {
Why is it necessary at all? Can't we pass the object as it is?

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +			fs.readdirSync(openApisSpecsPath).forEach((file) => {
Use async versions

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +				fastify.log.info('GraphQL plugin registered');
Registering plugins is not sync. You need to put the logs in after `fastify.after(() => )`

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +				fastify.register(require('./plugins/graphql') as FastifyPluginAsync<LazyGraphQLServerConfig>, {
`require` once before the loop. It is cached but will still make several calls under the hood.

2023-02-09 15:47 UTC, StarpTech commented on packages/sdk/src/rest2graphql/execution.ts
> +			spec.headers.reduce((acc, header: string) => {
I think this can be simplified to 

```ts
	const headers = {};
		for (const [key, value] of req.body.__wg.clientRequest?.headers.entries()) {
			headers[key] = value;
		}
```

2023-02-09 16:16 UTC, StarpTech requested changes

2023-02-09 16:16 UTC, StarpTech commented on packages/sdk/src/server/plugins/graphql.ts
> +				schema = await lazyLoadSchema(config.schema);
Just for completeness. This will still introduce cold starts when the user uses this endpoint. The good thing is will not affect others.

2023-02-09 16:16 UTC, StarpTech commented on packages/sdk/src/rest2graphql/execution.ts
> +	fs.writeFileSync(filePath, JSON.stringify(item, null, 2));
Can't we generate the schema at build time and load it from disk as JSON? I saw some libraries that serialize the schema to and from JSON.

2023-02-09 16:16 UTC, StarpTech commented on packages/sdk/src/rest2graphql/execution.ts
> +	const { schema } = await createGraphQLSchema(spec.content, {
Can't we get rid of creating the schema at runtime by serializing the final schema to JSON or GraphQL at build time?
https://www.apollographql.com/blog/backend/schema-design/three-ways-to-represent-your-graphql-schema/

2023-02-09 22:35 UTC, StarpTech commented on packages/sdk/src/rest2graphql/execution.ts
> +	fs.writeFileSync(filePath, JSON.stringify(item, null, 2));
Nvm. openapi-to-graphql do much more. It implements the resolver. I forgot it.

2023-02-10 19:07 UTC, Aenimus commented on packages/sdk/src/server/plugins/graphql.ts
> +			const headers = Object.entries(request.headers).reduce((acc, [key, value]) => {
Can't we do this? Or am I missing something?

`ts
const headers = Object.entries(request.headers).reduce((acc, [key, value]) => {
    if (value !== undefined) {
        acc[key] = value.toString();
    }
    return acc;
    }, {} as Record<string, string>);`

2023-02-10 19:19 UTC, spetrunin commented on packages/sdk/src/server/plugins/graphql.ts
> +			const headers = Object.entries(request.headers).reduce((acc, [key, value]) => {
@Aenimus yes we could do that

2023-02-10 19:22 UTC, spetrunin commented on packages/sdk/src/rest2graphql/execution.ts
> +			spec.headers.reduce((acc, header: string) => {
I need headers which was forwarded by wundernode

2023-02-10 19:32 UTC, spetrunin commented
I consider it more or less ready, cleaned up as much as I can

@StarpTech please play with headers, maybe you will get how to simplify it

Important things:
- I need headers coming from node to server (not client request headers)
- at the end, they should be just an object string:string

2023-02-10 21:42 UTC, StarpTech requested changes

2023-02-10 21:42 UTC, StarpTech commented on packages/sdk/src/definition/index.ts
> +		return async (): Promise<PrismaApi> => {
Remove `async` here it's not needed. It creates another promise.

2023-02-10 21:51 UTC, StarpTech commented
> I consider it more or less ready, cleaned up as much as I can

@spetrunin were you able to identify a degradation of the server start in general?

2023-02-12 08:42 UTC, Pagebakers commented on packages/sdk/src/server/plugins/graphql.ts
> +				schema = await lazyLoadSchema(config.schema);
Yep the load time is postponed. We have a few solutions in mind to speed it up. But good enough for now.

2023-02-12 16:49 UTC, spetrunin commented on packages/sdk/src/definition/index.ts
> +		return async (): Promise<PrismaApi> => {
done

2023-02-12 17:04 UTC, spetrunin commented
> > I consider it more or less ready, cleaned up as much as I can
> 
> @spetrunin were you able to identify a degradation of the server start in general?

for simple test app:
in main with custom graphql server: `29ms`
in this branch with custom graphql server and stripe api: `49ms`

2023-02-12 17:56 UTC, StarpTech commented
This is negligible. Looks good!

2023-02-13 12:52 UTC, Pagebakers requested changes
A lot to digest, found some minor textual changes

2023-02-13 12:52 UTC, Pagebakers commented on packages/sdk/src/server/server.ts
> +						fastify.log.info(`OpenAPi Graphql server '${apiName}' listening at ${routeUrl}`);
OpenAPI, GraphQL

2023-02-14 10:53 UTC, Pagebakers approved these changes

2023-02-14 11:25 UTC, jensneuse approved these changes

2023-02-14 14:25 UTC, merged