feat: add support for uploads from anonymous users
wundergraph/wundergraph pull request #632
Opened 2023-02-02 10:38 UTC by fiam

- Add a new per-profile field, which defaults to requiring authentication
- Add end to end tests to nodejs-file-upload example, which also validates
that the upload hooks run.

2023-02-02 10:42 UTC, Pagebakers requested changes
I think the parameter name we use with functions is `requiresAuthentication` let's make sure we use the same (I couldn't find it in the docs btw, please verify)

I've checked the source code, that's the parameter name. I'll update it.

2023-02-02 10:48 UTC, fiam commented
CI should pass once this is rebased on top of #631

2023-02-02 11:19 UTC, fiam commented
> I think the parameter name we use with functions is `requiresAuthentication` let's make sure we use the same (I couldn't find it in the docs btw, please verify)
> 
> I've checked the source code, that's the parameter name. I'll update it.

Changed, PTAL

2023-02-02 12:10 UTC, YuriBuerov approved these changes

2023-02-02 14:56 UTC, StarpTech requested changes

2023-02-02 14:56 UTC, StarpTech commented on pkg/s3uploadclient/s3uploadclient.go
> +	// Wether the profile requires authentication to upload a file
Typo

2023-02-02 14:56 UTC, StarpTech commented on pkg/s3uploadclient/s3uploadclient.go
> +	if (profile == nil || profile.RequiresAuthentication) && authentication.UserFromContext(r.Context()) == nil {
That contains many error cases. I prefer to handle each of them individually with some logs.

2023-02-02 15:27 UTC, fiam commented on pkg/s3uploadclient/s3uploadclient.go
> +	// Wether the profile requires authentication to upload a file
Thanks, fixed

2023-02-02 15:44 UTC, fiam commented on pkg/s3uploadclient/s3uploadclient.go
> +	if (profile == nil || profile.RequiresAuthentication) && authentication.UserFromContext(r.Context()) == nil {
I've separated it into two checks and added a log message. PTAL

2023-02-02 21:12 UTC, StarpTech requested changes

2023-02-02 21:12 UTC, StarpTech commented on pkg/s3uploadclient/s3uploadclient.go
> +				s.logger.Info("refusing upload from anonymous user", zap.String("provider", s.name), zap.String("profile", profileName))
I'd prefer debug.

2023-02-02 21:26 UTC, fiam commented on pkg/s3uploadclient/s3uploadclient.go
> +				s.logger.Info("refusing upload from anonymous user", zap.String("provider", s.name), zap.String("profile", profileName))
Changed to Debug

2023-02-03 09:04 UTC, Pagebakers approved these changes

2023-02-03 11:01 UTC, StarpTech approved these changes
LGTM

2023-02-03 11:09 UTC, merged