fix: avoid feeding paths into applicationHash calculation
wundergraph/wundergraph pull request #636
Opened 2023-02-02 14:29 UTC by fiam

Store ResolveApplicationConfig in a field in CodeGenerationConfig
rather than extending it. This allows us to safely hash ResolveApplicationConfig
without including the paths in CodeGenerationConfig.

2023-02-02 14:53 UTC, StarpTech requested changes

2023-02-02 14:53 UTC, StarpTech commented on packages/golang-client/src/index.ts
> +import { CodeGenerationConfig } from '@wundergraph/sdk/dist/configure';
Why point to dist? if is not exported, please do it.

2023-02-02 14:53 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> -export interface CodeGenerationConfig extends ResolvedWunderGraphConfig {
Could you explain why it makes a difference for hashing?

2023-02-02 15:18 UTC, Pagebakers commented on packages/golang-client/src/index.ts
> +import { CodeGenerationConfig } from '@wundergraph/sdk/dist/configure';
Yep /dist was for backwards compat, we should remove it at some point

2023-02-02 15:38 UTC, fiam commented on packages/golang-client/src/index.ts
> +import { CodeGenerationConfig } from '@wundergraph/sdk/dist/configure';
It was not exported. The editor filled the import automatically and I didn't think about it. I'll update it.

2023-02-02 15:44 UTC, fiam commented on packages/sdk/src/configure/index.ts
> -export interface CodeGenerationConfig extends ResolvedWunderGraphConfig {
I've added comments in `CodeGenerationConfig` and `ResolvedWunderGraphConfig`, PTAL

2023-02-02 16:46 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> -export interface CodeGenerationConfig extends ResolvedWunderGraphConfig {
ah now, I got it. Great fix

2023-02-02 16:46 UTC, StarpTech approved these changes
LGTM

2023-02-03 08:13 UTC, thisisnithin approved these changes

2023-02-03 08:14 UTC, merged