document how the build pipeline works
wundergraph/wundergraph pull request #638
Opened 2023-02-02 20:14 UTC by YuriBuerov

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-02-02 20:22 UTC, StarpTech requested changes
Awesome :+1:

2023-02-02 20:22 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +As you can see, we have a `build` script, which is executed during the deployment process.
`during build`

2023-02-02 20:22 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +    "build": "wunderctl generate --debug --pretty-logging=true --wundergraph-dir ."
Point to the `.` at h the end of the command.

2023-02-02 20:22 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +WunderGraph Cloud will automatically detect the path to the wundergraph dir, execute `wunderctl generate` command by default.
Should we mention the exact command here?

2023-02-03 08:30 UTC, fiam commented on docs-website/src/pages/docs/cloud/deployments.md
> +- Make changes to the `main` branch, e.g. change the query in `.wundergraph/operations/`.
`change the query` `change a query`?

2023-02-03 11:03 UTC, YuriBuerov commented on docs-website/src/pages/docs/cloud/deployments.md
> +    "build": "wunderctl generate --debug --pretty-logging=true --wundergraph-dir ."
what do you mean? in this case, it's correct: https://github.com/wundergraph/cloud-starter-turbo/blob/main/apps/api/package.json#L7

2023-02-03 11:07 UTC, fiam approved these changes
LGTM

2023-02-03 12:51 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +WunderGraph Cloud will automatically detect the path to the wundergraph dir, execute `wunderctl generate` command by default.
ok

2023-02-03 12:51 UTC, StarpTech commented on docs-website/src/pages/docs/cloud/deployments.md
> +    "build": "wunderctl generate --debug --pretty-logging=true --wundergraph-dir ."
I mean, the dot can be easily missed. I'd add a comment.

2023-02-03 13:29 UTC, merged