feat: initial (and incomplete) support for custom claims
wundergraph/wundergraph pull request #648
Opened 2023-02-06 21:20 UTC by fiam

2023-02-07 17:06 UTC, fiam commented
Docs are missing, but code should be ready for review

2023-02-07 18:35 UTC, jensneuse requested changes
only minor change requests
fantastic work!

2023-02-07 18:35 UTC, jensneuse commented on packages/sdk/src/definition/merge.ts
> +enum Claim {
I'd rename this to WG_WELL_KNOWN_CLAIM

2023-02-07 18:35 UTC, jensneuse commented on packages/sdk/src/definition/merge.ts
> +}
As you're touching this already, do you like to add the missing claims?

2023-02-07 18:35 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +		case jsonparser.String:
can we move the mapper somewhere else to keep the for loop readable?

2023-02-07 21:51 UTC, fiam commented on packages/sdk/src/definition/merge.ts
> +enum Claim {
Sure, will do

2023-02-07 21:51 UTC, fiam commented on packages/sdk/src/definition/merge.ts
> +}
```enum WellKnownClaim {
	EMAIL = 0; // email
	EMAIL_VERIFIED = 1; // emailVerified
	NAME = 2; // name
	NICKNAME = 3; // nickName
	LOCATION = 4; // location
	PROVIDER = 5; // providerId - notice this is usually set by us, not from claims
	USERID = 6; // userId
	FIRST_NAME = 7; // firstName
	LAST_NAME = 8; // lastName 
	DESCRIPTION = 9; // description
	AVATAR_URL = 10; // avatarUrl ```

Anything else that comes to mind?

2023-02-08 14:32 UTC, fiam commented on packages/sdk/src/definition/merge.ts
> +enum Claim {
Done

2023-02-08 14:32 UTC, fiam commented on packages/sdk/src/definition/merge.ts
> +}
Done

2023-02-09 12:44 UTC, StarpTech requested changes
Awesome work!

2023-02-09 12:44 UTC, StarpTech commented on docs-website/src/pages/docs/directives-reference/from-custom-claim-directive.md
> +				type: ValueType.INT, // Must be an integer
Can we adapt here the same zod schema as in function, or is it too much effort?

2023-02-09 12:44 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +		value := lookupJsonPath(user.CustomClaims, claim.Claim.JsonPathComponents, 0)
You can use `gjson` https://github.com/tidwall/gjson#path-syntax which we already use.

2023-02-09 12:44 UTC, StarpTech commented on testapps/auth/test/index.test.ts
> +import { afterAll, beforeAll, describe, expect, it, test } from '@jest/globals';
Great tests but a bit odd to have them in the testapps we will see as a toy playground. I think we also don't run them on go code change. It would be great if we were able to write similar tests in the go codebase.

2023-02-09 12:44 UTC, StarpTech commented on docs-website/src/pages/docs/directives-reference/from-custom-claim-directive.md
> +				type: ValueType.INT, // Must be an integer
- Can we use string types instead enums?
- Should we summarize Float, Int to `Number` ?
- Can a claim be optional? E.g. in Auth0 you add custom claims conditionally.

2023-02-09 13:00 UTC, fiam commented on testapps/auth/test/index.test.ts
> +import { afterAll, beforeAll, describe, expect, it, test } from '@jest/globals';
There's no other way to write a comprehensive test that validates both the TS and Go sides, as well as their interaction. We can add unit tests for the each side, but they're more code to maintain and the integration tests make the unit test almost redundant.

2023-02-09 13:05 UTC, fiam commented on pkg/apihandler/apihandler.go
> +		value := lookupJsonPath(user.CustomClaims, claim.Claim.JsonPathComponents, 0)
That's what the first iteration of the code did, but using `jsonparser` (which we also use). The problem with that is we would need to turn the custom claims into JSON on every call to `injectCustomClaims()`, which allocates. This way we avoid allocations at the cost of implementing the path lookup ourselves.

2023-02-09 13:08 UTC, fiam commented on pkg/apihandler/apihandler.go
> +		value := lookupJsonPath(user.CustomClaims, claim.Claim.JsonPathComponents, 0)
One way I considered to get around the allocation and still use a JSON parser for the lookup is to keep the custom claims as a `json.RawMessage`, but the API around that is such a pain in the Go side that I decided to not go for it.

2023-02-09 13:15 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/from-custom-claim-directive.md
> +				type: ValueType.INT, // Must be an integer
Zod is a bit too much for this because we don't support objects, just plain values. I think the confusion it could introduce is not worth the familiarity it brings.

2023-02-09 13:21 UTC, fiam commented on docs-website/config/tags.js
> +	'@fromCustomClaim': '/docs/directives-reference/from-custom-claim-directive',
We can handle it as a single directive, but it was requested as a separate one. We're still in time to change that, let's discuss it and decide.

2023-02-09 13:31 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/from-custom-claim-directive.md
> +				type: ValueType.INT, // Must be an integer
Sorry, what do you mean by a string type? `"string|int|float"`? We could do that and make the enum internal for communicating between the TS and Go sides. I wouldn't group together integer and float as number, otherwise it becomes quite the chore to validate it in every operation. As for validating for a specific pattern, we can add support for matching it to a regular expression. Claims are optional using `required: false`, it's documented in the last paragraph of the document.

2023-02-09 15:09 UTC, StarpTech commented on docs-website/src/pages/docs/directives-reference/from-custom-claim-directive.md
> +				type: ValueType.INT, // Must be an integer
ok

2023-02-09 15:10 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +		value := lookupJsonPath(user.CustomClaims, claim.Claim.JsonPathComponents, 0)
ok, but please document the syntax in the docs. Also whats, not possible e.g arrays etc.

2023-02-09 15:11 UTC, StarpTech commented on testapps/auth/test/index.test.ts
> +import { afterAll, beforeAll, describe, expect, it, test } from '@jest/globals';
How do we ensure that the tests are running on code change?

2023-02-09 15:14 UTC, StarpTech commented on docs-website/src/pages/docs/directives-reference/from-custom-claim-directive.md
> +				type: ValueType.INT, // Must be an integer
> Sorry, what do you mean by a string type? "string|int|float"? We could do that and make the enum internal for communicating between the TS and Go sides. I wouldn't group together integer and float as number, ....

Looks good. Can we support String, Int, Float, and Boolean? Then we are compliant with GraphQL base types.

> Claims are optional using required: false, it's documented in the last paragraph of the document.

Great.

2023-02-09 15:16 UTC, StarpTech commented on docs-website/config/tags.js
> +	'@fromCustomClaim': '/docs/directives-reference/from-custom-claim-directive',
I'm in favor of covering it with a single directive.

2023-02-09 15:19 UTC, fiam commented on testapps/auth/test/index.test.ts
> +import { afterAll, beforeAll, describe, expect, it, test } from '@jest/globals';
The NPM CI workflow runs `pnpm test` in these directories and they have a `package.json` that runs `jest`. Any PR that changes the SDK will have to pass these tests.

2023-02-09 15:19 UTC, fiam commented on pkg/apihandler/apihandler.go
> +		value := lookupJsonPath(user.CustomClaims, claim.Claim.JsonPathComponents, 0)
Good idea, I'll document it.

2023-02-09 16:26 UTC, StarpTech commented on docs-website/src/pages/docs/directives-reference/from-custom-claim-directive.md
> +				type: ValueType.INT, // Must be an integer
Thanks

2023-02-10 08:41 UTC, jensneuse approved these changes
fantastic work!

2023-02-10 10:30 UTC, merged