chore: add vercel integration docs
wundergraph/wundergraph pull request #657
Opened 2023-02-08 10:33 UTC by Pagebakers

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-02-08 10:41 UTC, fiam commented
LGTM

2023-02-08 10:47 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +The WunderGraph Vercel integration allows you sync your WunderGraph project settings with your Vercel projects.
allows you sync -> allows you to sync

2023-02-08 10:51 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Head over to your Vercel dashboard and click on the `Integrations` tab. Go to `Browse Marketplace` and Search for `WunderGraph` and click on the `Add integration` button.
Go to `Browse Marketplace` and Search for `WunderGraph` and -> Go to Go to `Browse Marketplace`, search for `WunderGraph`, and

2023-02-08 10:52 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Select the Vercel Account that you want to add the integration to and click `Continue.`. Choose All Project and select individual project that you want to give WunderGraph access to and continue.
Select the Vercel Account that you want to add the integration to and click -> Select the Vercel Account to which you wish to add integration and click

2023-02-08 10:52 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Select the Vercel Account that you want to add the integration to and click `Continue.`. Choose All Project and select individual project that you want to give WunderGraph access to and continue.
Choose All Project -> Choose `All Projects`

2023-02-08 10:54 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Now you can verify the permissions that are given to WunderGraph and click `Add integration`, a popup opens that will redirect to WunderGraph.
and click `Add integration`, a popup opens that will redirect to WunderGraph. -> and click `Add Integration`. A popup will open that will redirect to WunderGraph.

2023-02-08 10:55 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Log in if you're not logged in yet.
Log in if you're not logged in yet. -> Log in if you're not already logged in.

2023-02-08 10:55 UTC, Aenimus requested changes
Just some copywriting

2023-02-09 10:41 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Head over to your Vercel dashboard and click on the `Integrations` tab. Go to `Browse Marketplace`, Search for `WunderGraph` and click on the `Add integration` button.
Not enough to say "no" but capital s for Search?

2023-02-09 10:41 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Head over to your Vercel dashboard and click on the `Integrations` tab. Go to `Browse Marketplace`, Search for `WunderGraph` and click on the `Add integration` button.
and no Oxford comma ;D

2023-02-09 10:42 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Select the Vercel Account to which you wish to integrate and click `Continue.`. Choose all Project and select individual project that you want to give WunderGraph access to and click `Continue`.
Should All Project be capitalised, be in backticks and be plural? `All Projects`?

2023-02-09 10:43 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Select the Vercel Account to which you wish to integrate and click `Continue.`. Choose all Project and select individual project that you want to give WunderGraph access to and click `Continue`.
and select THE individual project to which you want/wish to give WunderGraph access and click `Continue`

2023-02-09 10:44 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Now you can verify the permissions that are given to WunderGraph and click `Add integration`, a popup will open that will redirect to WunderGraph.
Period and capital A.

2023-02-09 10:45 UTC, Aenimus commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Now you can select the Vercel project that you want to connect to your WunderGraph project and click `Connect Projects`. You will be redirected back to Vercel and the integration is now installed. 🥳
Vercel, and the (comma)

2023-02-09 10:47 UTC, Pagebakers commented on docs-website/src/pages/docs/cloud/integrations/vercel.md
> +Now you can select the Vercel project that you want to connect to your WunderGraph project and click `Connect Projects`. You will be redirected back to Vercel and the integration is now installed. 🥳
, and? either , or and. Or is that only Dutch rules?

2023-02-09 11:14 UTC, Aenimus approved these changes

2023-02-09 12:16 UTC, merged