fix: modify build scripts
wundergraph/wundergraph pull request #660
Opened 2023-02-09 09:07 UTC by JivusAyrus

#### Checklist

- [ ] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-02-09 16:25 UTC, StarpTech requested changes

2023-02-09 16:25 UTC, StarpTech commented on examples/vite-swr/.wundergraph/wundergraph.config.ts
> +		allowedOrigins: process.env.NODE_ENV === 'production' ? ['https://*'] : ['http://*'],
That's confusing. Does it work without specifying `allowedOrigins` at all?

2023-02-09 16:59 UTC, JivusAyrus commented on examples/vite-swr/.wundergraph/wundergraph.config.ts
> +		allowedOrigins: process.env.NODE_ENV === 'production' ? ['https://*'] : ['http://*'],
no, allowedOrigins is a required attribute

2023-02-09 18:17 UTC, StarpTech commented on examples/vite-swr/.wundergraph/wundergraph.config.ts
> +		allowedOrigins: process.env.NODE_ENV === 'production' ? ['https://*'] : ['http://*'],
So using `	...cors.allowAll,` alone does not allow all? :smile:

2023-02-09 18:38 UTC, StarpTech approved these changes
LGTM

2023-02-10 10:44 UTC, jensneuse approved these changes

2023-02-10 11:34 UTC, StarpTech requested changes

2023-02-10 11:34 UTC, StarpTech commented on packages/sdk/src/cors/index.ts
> +	allowedOrigins: ['http://*', 'https://*'],
You mean `["*"]`?

2023-02-10 11:42 UTC, JivusAyrus commented on packages/sdk/src/cors/index.ts
> +	allowedOrigins: ['http://*', 'https://*'],
That doesnt work.

2023-02-10 12:05 UTC, fiam approved these changes
LGTM

2023-02-10 14:35 UTC, StarpTech approved these changes
LGTM

2023-02-10 15:22 UTC, merged