chore: work in progress
wundergraph/wundergraph pull request #666
Opened 2023-02-11 18:02 UTC by Aenimus

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-02-13 17:55 UTC, Aenimus commented on pkg/apihandler/api.go
> +	validSecretCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
Are other characters valid?

2023-02-13 17:57 UTC, Aenimus commented on pkg/apihandler/api.go
> +	CookieBasedSecrets    *CookieBasedSecrets
Should I move CookieBasedSecrets into AuthenticationConfig > CookieBased? Or leave it as a top level field?

2023-02-13 20:11 UTC, jensneuse requested changes
A few minor issues.
One thing I was missing is that my understanding was that in dev mode (wunderctl up) we always want to set the same static value. Am I missing this?

2023-02-13 20:11 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +			/** @deprecated: Not used anymore */
Add links to docs for replacement/alternative?

2023-02-13 20:11 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +			/** @deprecated: Not used anymore */
same

2023-02-13 20:11 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +			/** @deprecated: Not used anymore */
same

2023-02-13 20:11 UTC, jensneuse commented on pkg/apihandler/api.go
> +	validSecretCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
I'm not sure. I think anything is valid?

2023-02-13 21:52 UTC, Aenimus commented on pkg/apihandler/api.go
> +	validSecretCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
Let me rephrase. What would be reasonable to include?

2023-02-14 10:11 UTC, StarpTech requested changes

2023-02-14 10:11 UTC, StarpTech commented on pkg/apihandler/api.go
> +func generateRandomStringOfLength(length int) []byte {
`rand.Intn` should not be used for security-senstive stuff. 

> This package's outputs might be easily predictable regardless of how it's seeded. For random numbers suitable for security-sensitive work, see the crypto/rand package.
https://pkg.go.dev/math/rand

Use this

```go
// GenerateRandomBytes returns securely generated random bytes.
// It will return an error if the system's secure random
// number generator fails to function correctly, in which
// case the caller should not continue.
func GenerateRandomBytes(n int) ([]byte, error) {
	b := make([]byte, n)
	_, err := rand.Read(b)
	// Note that err == nil only if we read len(b) bytes.
	if err != nil {
		return nil, err
	}

	return b, nil
}

// GenerateRandomString generated a random string with the length as the first argument
func GenerateRandomString(n int) (string, error) {
	b, err := GenerateRandomBytes(n)
	return base64.URLEncoding.EncodeToString(b), err
}
```

2023-02-14 10:11 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> -  hashKey: ConfigurationVariable | undefined;
Why do we remove this? IMO the user should still be able to configure it. The only difference is that we generate the value. This will also be a breaking change.

2023-02-14 10:17 UTC, StarpTech requested changes

2023-02-14 10:17 UTC, StarpTech commented on pkg/apihandler/api.go
> +		bytes[i] = validSecretCharacters[rand.Intn(len(validSecretCharacters))]
`rand.Intn` should not be used for security-sensitive work. Please use crypto rand e.g.

```go
func GenerateRandomString(n int) (string, error) {
	const letters = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-"
	ret := make([]byte, n)
	for i := 0; i < n; i++ {
		num, err := rand.Int(rand.Reader, big.NewInt(int64(len(letters))))
		if err != nil {
			return "", err
		}
		ret[i] = letters[num.Int64()]
	}

	return string(ret), nil
}
```

2023-02-14 10:23 UTC, Aenimus commented on packages/protobuf/wgpb/wundernode_config.ts
> -  hashKey: ConfigurationVariable | undefined;
My mistake. I didn't intend to remove from interfaces.

2023-02-14 14:54 UTC, Aenimus commented on packages/protobuf/wgpb/wundernode_config.ts
> -  hashKey: ConfigurationVariable | undefined;
This file is generated from proto, and I removed the proto values, so that's why they're gone here.

Is this definitely a breaking change?

2023-02-14 15:39 UTC, jensneuse approved these changes

2023-02-14 16:48 UTC, StarpTech requested changes

2023-02-14 16:50 UTC, StarpTech requested changes

2023-02-14 16:50 UTC, StarpTech commented on docs-website/src/pages/docs/self-hosted/security.md
> +WunderGraph uses three secrets to secure your deployment.
The secrets are only about authentication, nothing more.

2023-02-14 16:50 UTC, StarpTech commented on docs-website/src/pages/docs/self-hosted/security.md
> +Although values will be generated for you in the case that they have not been supplied, these secrets are your
We should mention that in case of you don't use fix values, we regenerate them and you users will be logged out after every restart

2023-02-15 16:34 UTC, StarpTech requested changes

2023-02-15 16:34 UTC, StarpTech commented on pkg/apihandler/api.go
> +	if isDevMode {
I'd handle this condition outside of this method, so the only responsibility of this method is to generate "new" ones.

2023-02-15 16:34 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +	} else if fallBackValue := r.api.CookieBasedSecrets.HashKey; fallBackValue != nil {
I'll try :smile: in IT it is called `fallback`

2023-02-16 17:48 UTC, StarpTech requested changes

2023-02-16 17:48 UTC, StarpTech commented on pkg/validate/apiconfig_test.go
> +		assert.Equal(t, "the required environment variable WUNDERGRAPH_SECURE_COOKIE_BLOCK_KEY must have a length of 32", messages[0])
Let's go with `WG_*` for consistency.

2023-02-16 17:48 UTC, StarpTech commented on pkg/validate/apiconfig.go
> +	requiredCsrfLength := 11
Where did you implement the logic for the cloud?

2023-02-17 11:57 UTC, StarpTech commented on pkg/validate/apiconfig.go
> +	requiredCsrfLength := 11
Clarified

2023-02-22 09:00 UTC, StarpTech approved these changes
LGTM

2023-02-28 17:37 UTC, merged