fix: ensure all hooks are called for live queries
wundergraph/wundergraph pull request #67
Opened 2022-07-05 17:24 UTC by StarpTech

- Call all hooks for live queries
- Ensure that hooks are called before the content is hashed
- Ensure that a hook error aborts the hook lifecycle
- Add maximum 10s graceful shutdown period for `up` command
- Fix a type issue with S3Provider in nextjs package. 
- Add a live-queries example

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-07-05 18:33 UTC, jensneuse requested changes

2022-07-05 18:33 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +	hookBuf := pool.GetBytesBuffer()
can you create this buf in handleLiveQuery? Otherwise, you'll have to pass the hookBuf back and forth into the pool for each handleLiveQueryEvent invocation

I guess it would be simpler to create one hookBuf per handleLiveQuery and pass it to the event handler, resetting it for each event.

2022-07-05 18:33 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			return nil, fmt.Errorf("LiveQueryHandler.mutatingPostResolve hook failed: %w", err)
typo (mutatingPreResolve)

2022-07-05 18:33 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			h.log.Error("LiveQueryHandler.MutatingPostResolve queries hook response is empty")
typo (preResolve)

2022-07-05 18:33 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +			// only send the response if the content has changed
should this be configurable for some reason?

2022-07-05 18:33 UTC, jensneuse commented on packages/nextjs/src/handlebar.template.ts
> +export const useWunderGraph = hooks.useWunderGraph<Role,AuthProvider,keyof S3Provider>(WunderGraphContext);
does this work when S3Provider has no keys?

2022-07-05 18:33 UTC, jensneuse commented on examples/subscriptions-live-queries/.wundergraph/wundergraph.server.ts
> +			Country: {},
this looks wrong

2022-07-05 18:33 UTC, jensneuse commented on cli/commands/up.go
> +		log.Info("Shutting down WunderNode with graceful period of 10s ...")
why graceful shutdown in up mode? I'd suggest to kill it immediately, e.g. if the user wants to start a new process after killing this one. Might lead to weird side effects or unexpected behaviour.

2022-07-05 18:33 UTC, jensneuse commented on cli/commands/start.go
> +		log.Info("Shutting down WunderNode with graceful period of 10s ...")
should we make the grace period configurable with a flag?

2022-07-05 19:48 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +	hookBuf := pool.GetBytesBuffer()
Good point.

2022-07-05 19:50 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +			// only send the response if the content has changed
Maybe, let's wait for feedback.

2022-07-05 19:51 UTC, StarpTech commented on packages/nextjs/src/handlebar.template.ts
> +export const useWunderGraph = hooks.useWunderGraph<Role,AuthProvider,keyof S3Provider>(WunderGraphContext);
Yes, it tested it with his case.

2022-07-05 19:51 UTC, StarpTech commented on examples/subscriptions-live-queries/.wundergraph/wundergraph.server.ts
> +			Country: {},
Not wrong just empty, Will remove it.

2022-07-05 19:59 UTC, StarpTech commented on cli/commands/up.go
> +		log.Info("Shutting down WunderNode with graceful period of 10s ...")
Good point

2022-07-05 20:11 UTC, StarpTech commented on cli/commands/start.go
> +		log.Info("Shutting down WunderNode with graceful period of 10s ...")
Added!

2022-07-05 20:23 UTC, jensneuse approved these changes

2022-07-05 20:23 UTC, jensneuse commented on pkg/apihandler/apihandler.go
> +func (h *QueryHandler) handleLiveQueryEvent(ctx *resolve.Context, r *http.Request, buf *bytes.Buffer, hookBuf *bytes.Buffer) ([]byte, error) {
I'd write requestBuf, hooksBuf *bytes.Buffer

2022-07-05 21:53 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +func (h *QueryHandler) handleLiveQueryEvent(ctx *resolve.Context, r *http.Request, buf *bytes.Buffer, hookBuf *bytes.Buffer) ([]byte, error) {
Done

2022-07-06 08:39 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +			http.Error(w, "LiveQueryHandler hook failed", http.StatusInternalServerError)
Return an error with SSE event

2022-07-06 11:14 UTC, merged