feat: add support for injecting claims into nested paths
wundergraph/wundergraph pull request #678
Opened 2023-02-15 14:54 UTC by fiam

Add a second optional argument to @fromClaim, which allows setting
the JSON path for the variable injection. Add a test in the auth
testapp to ensure its tested by CI.

2023-02-16 21:43 UTC, fiam commented
Pending docs update

2023-02-21 08:58 UTC, Pagebakers requested changes
Good stuff, I'd like to clarify the documentation a bit.

It seems that the directives are now 'repeatable' but I'm not sure, if so please add some examples to the docs as well to make it clear to the dev.

2023-02-21 08:58 UTC, Pagebakers commented on docs-website/src/pages/docs/directives-reference/from-claim-directive.md
> +```
Will input.filter.code be available in the generated client? or is it removed just like regular claims?

What happens when I use a non existing field name in `on`? Some more explanation would be great.

2023-02-21 08:58 UTC, Pagebakers commented on docs-website/src/pages/docs/directives-reference/inject-current-datetime-directive.md
> +mutation ($input: createUserInput! @injectCurrentDateTime(on: "createdAt")) {
Can I inject multiple values into the input?

For example?
```
$input: createUserInput! @injectCurrentDateTime(on: "createdAt") @injectEnvironmentVariable(name: "ID", on: "shopId")
```

2023-02-21 08:58 UTC, Pagebakers commented on docs-website/src/pages/docs/directives-reference/json-schema-directive.md
> +mutation ($input: createUserInput! @jsonSchema(pattern: "[0-9]+", on: "id")) {
Nice! Like my previous comment, can I add patterns to multiple fields in $input?

2023-02-21 10:04 UTC, jensneuse commented on docs-website/src/pages/docs/directives-reference/json-schema-directive.md
> +mutation ($input: createUserInput! @jsonSchema(pattern: "[0-9]+", on: "id")) {
This was the intended design, but we need to ask @fiam for clarification.

2023-02-22 07:48 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/json-schema-directive.md
> +mutation ($input: createUserInput! @jsonSchema(pattern: "[0-9]+", on: "id")) {
All these directives can be used multiple times, targeting different fields. I'll update the documentation to explain that better.

2023-02-22 07:51 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/from-claim-directive.md
> +```
Targeting an invalid field in the on argument will throw an error during generation, but not a very obvious one. I'll update it to provide a better error message.

Injected paths are removed from the operation input's schema, but I have not tested how that affects the generate client. I'll check it.

2023-02-22 21:12 UTC, spetrunin commented
seems at the moment prevent infinite recursive calls logic somehow is not working

so recursive hooks tests are commented out in the main branch
https://github.com/wundergraph/wundergraph/blob/main/testapps/hooks/test/index.test.ts#L10

2023-02-27 10:27 UTC, fiam commented
> seems at the moment prevent infinite recursive calls logic somehow is not working
> 
> so recursive hooks tests are commented out in the main branch [`main`/testapps/hooks/test/index.test.ts#L10](https://github.com/wundergraph/wundergraph/blob/main/testapps/hooks/test/index.test.ts?rgh-link-date=2023-02-22T21%3A12%3A16Z#L10)

That's weird, they were working for me and they still are. I'll submit a PR.

2023-02-27 11:03 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/json-schema-directive.md
> +mutation ($input: createUserInput! @jsonSchema(pattern: "[0-9]+", on: "id")) {
I've updated the docs to clarify that all these directives can be used multiple times and combined.

2023-02-27 11:04 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/inject-current-datetime-directive.md
> +mutation ($input: createUserInput! @injectCurrentDateTime(on: "createdAt")) {
Docs updated to reflect that you can

2023-02-27 13:32 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/from-claim-directive.md
> +```
Injected values are removed from the generated client inputs, but we're not removing them from the internal operations yet (tracked in ENG-1350). I've added a better error message when a referenced field doesn't exist.

![image](https://user-images.githubusercontent.com/41529/221576555-839f2e95-02b4-43a6-bb33-caef2b02d8e7.png)

2023-02-27 13:35 UTC, Pagebakers approved these changes

2023-03-01 14:49 UTC, devsergiy approved these changes

2023-03-01 15:46 UTC, merged