feat: svelte query client
wundergraph/wundergraph pull request #683
Opened 2023-02-18 17:57 UTC by DaniAkash

This PR is a draft of my initial implementation of [Wundergraph Client for sveltekit](https://github.com/DaniAkash/wundergraph-svelte-query), created to collect feedback from the maintainers of this project. There's still few pending items I need to address before this PR can be ready:
- [ ] figure out how to create subscription utilities in svelte
- [ ] setup tests for the svelte query client utilities

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-02-21 09:27 UTC, Pagebakers commented
Great work! is there anything you need help with?

2023-02-21 11:01 UTC, DaniAkash commented
> Great work! is there anything you need help with?

The subscription test cases are failing. Might need some help with it.

2023-02-21 11:07 UTC, DaniAkash commented
Since I'm new to svelte, I might have made some mistakes in the readable store implementation. Will try to figure out the issue tonight

2023-02-22 09:12 UTC, Pagebakers commented
Thanks, I will try it out once I have the time.

2023-02-22 11:36 UTC, DaniAkash commented
> Thanks, I will try it out once I have the time.

It is fixed now. All tests are passing 🎉

2023-02-23 12:50 UTC, Pagebakers requested changes
Great! Left some comments for improvements.

Will you also add a svelte/sveltekit example?

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/README.md
> +	import { createQuery } from '../lib/svelteQueryUtils';
I'd call it `lib/wundergraph` to make it consistent with the other query libs.

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/README.md
> +  createQueryUtils<Operations>(client);
Calling this Utils is a Svelte convention? I'm not sure.

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/package.json
> +  "main": "./dist/index.js",
We should release this as a dual bundle with exports (commonjs/esm), you can copy the tsup script and exports + main/module/types fields from the react-query package.

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/src/createQueryUtils.ts
> +	 * const { user, error, isLoading } = getUser()
`const { data`

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/src/createQueryUtils.ts
> +				subscriptionState,
deconstruct this into the return value. 

```
return {
  ...result,
   ...subscriptionState
}

const { isSubscribed, isLoading } = useQuery()
```

I'm not sure how reactivity works with svelte but for Solid we had to use `mergeProps` to keep the reactivity.

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/src/createQueryUtils.ts
> +			subscriptionState,
Same as livequery deconstruct this into the return value.

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/tsconfig.json
> +    "jsx": "react",
This doesn't seem correct I think?

2023-02-23 12:50 UTC, Pagebakers commented on packages/svelte-query/tsconfig.build.json
> +  "include": ["src/**/*"]
For the build config I suggest we use the same setup as tanstack svelte-query

2023-02-24 04:54 UTC, DaniAkash commented on packages/svelte-query/README.md
> +  createQueryUtils<Operations>(client);
no, couldn't find any common name like hooks in react

2023-02-24 04:56 UTC, DaniAkash commented on packages/svelte-query/package.json
> +  "main": "./dist/index.js",
Pretty much all svelte setups (vite / sveltekit) support ESM so conventionally svelte packages don't export UMD or CJS builds 

Refer: 
https://github.com/TanStack/query/discussions/5006
https://github.com/TanStack/query/pull/4768#issuecomment-1374622732

2023-02-24 04:56 UTC, DaniAkash commented on packages/svelte-query/src/createQueryUtils.ts
> +				subscriptionState,
Will figure out some way to preserve reactivity

2023-02-24 04:57 UTC, DaniAkash commented on packages/svelte-query/tsconfig.json
> +    "jsx": "react",
I think JSX is not needed, I'll change the tsconfig to svelte query's config

2023-02-24 04:58 UTC, DaniAkash commented on packages/svelte-query/README.md
> +	import { createQuery } from '../lib/svelteQueryUtils';
> Great overall! Left some comments for improvements.
> 
> Will you also add a svelte/sveltekit example?

I'd like to add, just waiting for the package to be published to npm

2023-02-27 14:16 UTC, Pagebakers commented on packages/svelte-query/README.md
> +	import { createQuery } from '../lib/svelteQueryUtils';
Good point

2023-02-27 14:22 UTC, Pagebakers commented on packages/svelte-query/README.md
> +  createQueryUtils<Operations>(client);
How about `createSvelteClient`

2023-02-27 14:26 UTC, Pagebakers requested changes

2023-02-27 14:26 UTC, Pagebakers commented on packages/svelte-query/package.json
> +  "main": "./dist/index.js",
Cool, in that case the package type needs to be module. And I'd still use ts-up for the build, but than only output esm, as well as using exports in package.json

2023-02-28 06:18 UTC, DaniAkash commented on packages/svelte-query/README.md
> +  createQueryUtils<Operations>(client);
this sounds much better. will refactor 👍

2023-02-28 10:37 UTC, DaniAkash commented on packages/svelte-query/tsconfig.json
> +    "jsx": "react",
have updated the config based on svelte query

2023-02-28 10:39 UTC, DaniAkash commented on packages/svelte-query/package.json
> +  "main": "./dist/index.js",
Sveltekit docs recommended using [svelte-package](https://kit.svelte.dev/docs/packaging) for building packages, Tanstack svelte-query also used the same build tool, so changed the build config as per the svelte-package docs

2023-03-02 09:35 UTC, DaniAkash commented on packages/svelte-query/src/createQueryUtils.ts
> +				subscriptionState,
@Pagebakers have use derived to merge the queryResult & subscription state, will look for ways to improve the typings on the derived state. But everything looks good for now

2023-03-02 10:16 UTC, DaniAkash commented
> Great overall! Left some comments for improvements.
> 
> Will you also add a svelte/sveltekit example?

@Pagebakers would like your review on the derived state implementation. If it looks good, I'll work on improving the types

2023-03-06 21:12 UTC, Pagebakers commented on packages/svelte-query/src/lib/createSvelteClient.ts
> +			const queryWithSubscriptionState: Readable<
Looks good @DaniAkash!

I'm thinking we could re-use this derived code and turn it into to a helper.

For example:
```
return withSubscriptionState(result, subscriptionState)
```

2023-03-14 07:06 UTC, DaniAkash commented on packages/svelte-query/src/lib/createSvelteClient.ts
> +			const queryWithSubscriptionState: Readable<
Have created the helper along with the correct types

2023-03-21 14:17 UTC, Pagebakers commented
Code looks good, but I'm unable to run the tests locally. (with CI it's expected not to work)

```
 FAIL  tests/queryUtils.test.ts (8.807 s)
  Svelte Query - createSvelteClient
    ✓ should be able to init utility functions (1 ms)
    ✕ should return data (1035 ms)
    ✓ should be disabled (182 ms)
  Svelte Query - createMutation
    ✓ should trigger mutation with auth (17 ms)
    ✓ should trigger mutation (8 ms)
    ✕ should invalidate query (1010 ms)
  Svelte Query - createSubscription
    ✕ should subscribe (5006 ms)
  Svelte Query - getUser
    ✕ should return user (1021 ms)
    ```

2023-03-30 14:58 UTC, Pagebakers approved these changes

2023-03-31 07:31 UTC, merged