fix: operation name normalization on Windows
wundergraph/wundergraph pull request #703
Opened 2023-02-28 14:16 UTC by fiam

Code for loading .graphql operations was different than for .ts operations.
Unify loading for both types of operations and fix Unix-isms. Fix also a
couple of typos in user visible log messages.

2023-02-28 14:23 UTC, Aenimus approved these changes

2023-02-28 15:25 UTC, devsergiy requested changes

2023-02-28 15:25 UTC, devsergiy commented on pkg/loadoperations/loader.go
> +		return "", "", false
could we extend the test to include the case of conflicting names between ts and graphql operations

2023-02-28 15:31 UTC, fiam commented on pkg/loadoperations/loader.go
> +		return "", "", false
It's checked just below this: [line 173](https://github.com/wundergraph/wundergraph/pull/703/files#diff-e12ef71dec9cf88b0a4001dc6b3004a5ab5058f4bd5bdf190936a614893d920bR173) and [line 181](https://github.com/wundergraph/wundergraph/pull/703/files#diff-e12ef71dec9cf88b0a4001dc6b3004a5ab5058f4bd5bdf190936a614893d920bR181)

2023-02-28 17:49 UTC, jensneuse commented
@fiam I think we load the path from the json and use it to load the modules, e.g. to generate custom config
Will this work as well with your changes? I have never tried it on windows?

2023-02-28 18:53 UTC, fiam commented
> @fiam I think we load the path from the json and use it to load the modules, e.g. to generate custom config
> Will this work as well with your changes? I have never tried it on windows?

That part was fixed in #607, but we missed that its GraphQL counterpart had a similar problem. This PR unifies the code for loading operations regardless of their type, so a problem in there should be easier to catch moving forward (we have nested TS operations in the examples CI). I'll trigger examples CI just to be safe.

2023-02-28 20:42 UTC, fiam commented
@jensneuse @StarpTech NPM CI is failing because we’ve been enforcing alphanumeric operation names, but only for GraphQL operations, and we also have operations in the nextjs testapp that use underscores (e.g. users/subscribe_no_input.ts) - I think we need to be consistent in this, we either allow underscores/dashes in all types or in none. Question is, should we rename the operations in the nextjs testapp or change the accepted operation names to allow dashes and underscores?

2023-02-28 21:58 UTC, jensneuse commented
> @jensneuse @StarpTech NPM CI is failing because we’ve been enforcing alphanumeric operation names, but only for GraphQL operations, and we also have operations in the nextjs testapp that use underscores (e.g. users/subscribe_no_input.ts) - I think we need to be consistent in this, we either allow underscores/dashes in all types or in none. Question is, should we rename the operations in the nextjs testapp or change the accepted operation names to allow dashes and underscores?

I think it's fine to allow it.

2023-03-01 06:52 UTC, fiam commented
> I think it's fine to allow it.

Wouldn't that be problematic if we expose those operations to GraphQL?

2023-03-01 07:49 UTC, fiam commented
> > I think it's fine to allow it.
> 
> Wouldn't that be problematic if we expose those operations to GraphQL?
> 
> 

Now that I think about it, underscores should be fine. Dashes would be the problematic ones.

2023-03-01 09:42 UTC, fiam commented
@devsergiy PTAL - Thanks!

2023-03-01 14:45 UTC, devsergiy commented on pkg/loadoperations/loader.go
> +		return "", "", false
yeah, but under extend test I mean add a test case here https://github.com/wundergraph/wundergraph/blob/main/pkg/loadoperations/loader_test.go

2023-03-01 15:03 UTC, fiam commented on pkg/loadoperations/loader.go
> +		return "", "", false
I've added a conflicting `.ts` operation to the test and updated the golden file

2023-03-01 15:27 UTC, devsergiy approved these changes

2023-03-01 15:40 UTC, merged