feat: add support for declaring a list of public claims
wundergraph/wundergraph pull request #706
Opened 2023-02-28 19:47 UTC by fiam

If non-empty, all other claims are hidden from the frontend.

- Add PublicCustomClaims type, which picks fields from CustomClaims
- Declare a PublicUser type in client.ts, which optionally picks the
selected fields.
- Add required machinery in the Go side to handle these fields
- Validate the selected claims during code generation

2023-02-28 20:31 UTC, jensneuse requested changes

2023-02-28 20:31 UTC, jensneuse commented on pkg/authentication/authentication.go
> +	PublicClaims      []string
We don't need to do this. We have this information in the API configuration. Cookie space is limited.

2023-02-28 20:39 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		publicClaims?: string[];
We can't generate an enum for that, since the user needs to write a `WunderGraphConfigApplicationConfig` and call `configureWunderGraphApplication()` (where that input field is) before code generation is run. However, the strings that are provided there are currently validated at generation time, causing a failure if any of them is incorrect. Validation is [here](https://github.com/wundergraph/wundergraph/pull/706/files#diff-944359769ce5d07540eab5d54fc4358ff90dd67b5223918bed68053b8edce9b7R312)

2023-02-28 20:49 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		publicClaims?: string[];
Something that we can do is create a type and provide predefined values for the well known claims, so the list can look like `publicClaims: [WellKnownClaim.EMAIL, CustomClaim('shopID')]`. That gives us type safety at "typing time" for the well known claims (as well as allowing us to move some logic to there), but I don't think there's much else we can do.

2023-02-28 22:11 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +		publicClaims?: string[];
I think it should be possible. The well-known claims are known ahead of time. There should be a way to infer names of the custom claims and combine both into a list of possible names. Not sure if this is exactly the solution, but it might be close: https://stackoverflow.com/a/66723158/20693155

2023-02-28 22:11 UTC, jensneuse commented on pkg/authentication/authentication.go
> +	PublicClaims      []string
ok

2023-03-01 14:36 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		publicClaims?: string[];
Turns out this was possible, but I had to use a different approach because I couldn't use `this` in that context. PTAL

2023-03-02 12:37 UTC, jensneuse approved these changes

2023-03-02 17:19 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +		let customClaim = config.authentication?.customClaims?.[claim];
Why `let`?

2023-03-02 17:20 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +		if (jsonPathComponents.length == 0) {
If you want to coerce, `!jsonPathComponents.length`, otherwise `===`

2023-03-02 17:21 UTC, Aenimus commented on packages/sdk/src/definition/merge.ts
> +	const wellKnownClaims = Object.keys(docs).map((key) => `"""${docs[key as WellKnownClaim]}"""\n${key}`);
Entries

2023-03-02 17:22 UTC, Aenimus commented on packages/sdk/src/definition/merge.ts
> +	const wellKnownClaims = Object.keys(docs).map((key) => `"""${docs[key as WellKnownClaim]}"""\n${key}`);
I think this would allow you to remove the `as`

2023-03-02 17:24 UTC, Aenimus commented on packages/sdk/src/graphql/operations.ts
>  	if (name in claims) {
Just curious, is this O(1)?

2023-03-02 17:26 UTC, Aenimus commented on pkg/authentication/authentication.go
> +		if !cpy.copyWellKnownClaim(claim, u) {
I prefer
```go
if cpy.copyWellKnownClaim(claim, u) {
    continue
}
...```

2023-03-02 17:26 UTC, Aenimus commented on pkg/authentication/authentication.go
> +func (*CSRFTokenHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
Huh?

2023-03-02 17:27 UTC, Aenimus commented on pkg/authentication/oidc.go
> +// isCustomClaim true if claim represents a token claim that we're not explicitly
lol

2023-03-02 17:29 UTC, Aenimus commented on pkg/jsonpath/jsonpath.go
> +	if keyIndex < len(keys) {
Invert the logic to reduce nesting? :'(

2023-03-02 17:30 UTC, Aenimus commented on pkg/jsonpath/jsonpath.go
> +	if keyIndex < len(jsonKeys) {
Same here

2023-03-02 17:30 UTC, Aenimus requested changes
Comments for changes

2023-03-02 19:04 UTC, fiam commented on pkg/authentication/authentication.go
> +func (*CSRFTokenHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
Receiver is not used, so it should be omitted

2023-03-02 19:09 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		let customClaim = config.authentication?.customClaims?.[claim];
Oversight, I'll change it

2023-03-02 19:10 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		if (jsonPathComponents.length == 0) {
`jsonPathComponents` can't be null nor undefined at that point, but I'll change it to `===`

2023-03-02 19:14 UTC, fiam commented on packages/sdk/src/graphql/operations.ts
>  	if (name in claims) {
`Object.keys()` is O(n) but `claims` has a fixed size

2023-03-02 19:22 UTC, fiam commented on pkg/jsonpath/jsonpath.go
> +	if keyIndex < len(keys) {
I've moved the length check to the callers, since it only makes a difference when the keys slice is empty. This way we remove a level of indirection as well as making it slightly faster.

2023-03-02 19:24 UTC, fiam commented on packages/sdk/src/codegen/templates/typescript/claims.ts
> +			const claim = claims[key];
Changed to Object.entries

2023-03-02 19:24 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		let customClaim = config.authentication?.customClaims?.[claim];
Changed

2023-03-02 19:24 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		if (jsonPathComponents.length == 0) {
Changed

2023-03-02 19:24 UTC, Aenimus commented on packages/sdk/src/graphql/operations.ts
>  	if (name in claims) {
No, I mean "in" for the records.

2023-03-02 19:24 UTC, Aenimus commented on pkg/authentication/authentication.go
> +func (*CSRFTokenHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
I didn't know you could just not have a ref

2023-03-02 19:24 UTC, fiam commented on pkg/jsonpath/jsonpath.go
> +	if keyIndex < len(jsonKeys) {
Moved the check to the caller

2023-03-02 19:25 UTC, fiam commented
> Comments for changes

Thanks for the review. I think I've addressed all requested changes. PTAL

2023-03-02 19:28 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +	let publicClaims: string[] = [];
Should be a const.

2023-03-02 19:30 UTC, Aenimus commented on pkg/authentication/authentication.go
> +// but it might be not validated if we have no key functions
might not be

2023-03-02 21:16 UTC, fiam commented on pkg/authentication/authentication.go
> +// but it might be not validated if we have no key functions
Thanks! Reworded.

2023-03-02 21:58 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +	let publicClaims: string[] = [];
Will you address this @fiam

2023-03-02 22:37 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	let publicClaims: string[] = [];
Sorry, I missed this one. It should be good now.

2023-03-02 22:39 UTC, Aenimus approved these changes

2023-03-02 22:42 UTC, fiam commented
Thanks for the thorough review @Aenimus 👍

2023-03-02 22:44 UTC, fiam commented
I've just realized we're missing some docs for this feature. Moving into draft to prevent merge.

2023-03-03 11:38 UTC, fiam commented
Docs added

2023-03-03 11:55 UTC, merged