fix: split user and id token due to size, add auth0 example
wundergraph/wundergraph pull request #71
Opened 2022-07-11 20:11 UTC by jensneuse

2022-07-11 20:45 UTC, StarpTech requested changes

2022-07-11 20:45 UTC, StarpTech commented on examples/auth0-oidc-authentication/example.env
> +FAUNADB_TOKEN="Bearer <replace-with-your-token>"
delete

2022-07-11 20:45 UTC, StarpTech commented on examples/auth0-oidc-authentication/next.config.js
> +module.exports = {
I think this file can be deleted as well.

2022-07-11 20:45 UTC, StarpTech commented on examples/auth0-oidc-authentication/package.json
> +  "name": "wundergraph-inject-bearer",
rename to `wundergraph-oidc`

2022-07-11 20:45 UTC, StarpTech commented on examples/auth0-oidc-authentication/pages/index.tsx
> +					FaunaDB & Next.js
Update title

2022-07-11 20:45 UTC, StarpTech commented on pkg/authentication/authentication.go
> +	http.SetCookie(w, userCookie)
Could you move the "reset" cookie logic into a function?

2022-07-12 08:28 UTC, StarpTech commented on examples/auth0-oidc-authentication/package.json
> +    "open": "wait-on -d 500 http://localhost:9991 && open-cli http://localhost:3003",
All demos starting with 3000? should we slign?

2022-07-12 08:39 UTC, jensneuse commented on examples/auth0-oidc-authentication/package.json
> +    "open": "wait-on -d 500 http://localhost:9991 && open-cli http://localhost:3003",
I'd actually give every example an incremented port so you can run multiple demos concurrently.

2022-07-12 08:40 UTC, StarpTech approved these changes

2022-07-12 09:35 UTC, merged