feat: otel, add tracer
wundergraph/wundergraph pull request #712
Opened 2023-03-01 17:48 UTC by YuriBuerov

## Motivation and Context

Open Telemetry instrumentation for WunderGraph node, and hooks server

## Marketing Changelog

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-03-03 19:15 UTC, StarpTech requested changes

2023-03-03 19:15 UTC, StarpTech commented on pkg/telemetry/otel/trace/trace.go
> +	otel.SetTracerProvider(p)
This will override the global provider. We should only work with local ones.

2023-03-03 19:15 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +	defer span.End()
With this approach how do we track errors? I think it is very cumbersome to call `span.RecordError` on all possible places. I think we need another abstraction (middleware?) to start, end, and record errors in a request/response lifecycle.

2023-03-03 19:15 UTC, StarpTech commented on pkg/hooks/hooks.go
> +	httpClient.HTTPClient.Transport = trace.HTTPClientTransporter(httpClient.HTTPClient.Transport)
- Remember that this does not replace hotel instrumentation in Node.js.
- Did you already think of how can instrument calls to the origins?

2023-03-25 09:43 UTC, StarpTech requested changes

2023-03-25 09:43 UTC, StarpTech commented on pkg/telemetry/otel/trace/trace.go
> +		client := otlptracehttp.NewClient(
This must be configurable. In prod, we will use the secure variant.

2023-03-25 09:43 UTC, StarpTech commented on pkg/telemetry/otel/trace/trace.go
> +	case config.JaegerEndpoint != "":
Can we make it configurable with a proper options API?
E.g `NewTracerProvider(withJaeger(...))` In that way, you can also validate if the right fields are set.

2023-03-25 09:43 UTC, StarpTech commented on pkg/telemetry/otel/trace/middleware.go
> +func getRRW(writer http.ResponseWriter) *recordingResponseWriter {
What means RRW?

2023-03-25 09:43 UTC, StarpTech commented on pkg/telemetry/otel/trace/middleware.go
> +	span.SetName(fmt.Sprintf("HTTP %s %s", r.Method, r.URL.Path))
Please ensure that the span name does not change per request. It's more used as a category like operationName, RPC call. See https://opentelemetry.io/docs/reference/specification/trace/api/#span

2023-03-25 09:43 UTC, StarpTech commented on pkg/telemetry/otel/trace/middleware_test.go
> +	assert.True(t, called)
You tested that the handler is called, not that tracer worked adequately.

2023-03-25 09:43 UTC, StarpTech commented on pkg/apihandler/internalapihandler.go
> +			"operation":     h.operation.Name,
We manage a namespace for our attributes. E.g.

- wg.operation.name
- wg.webhook.name
- wg.subscription (bool)

Check cloud shared/otel. We should follow them as closely as possible.

2023-04-03 15:58 UTC, StarpTech requested changes
Great work! Few questions:

1. Did you ensure that OTEL can be enforced in cloud?
2. I think you forgot to instrument the OperationClient https://github.com/wundergraph/wundergraph/blob/yuri/eng-1434-add-otel-opentelemetry-to-wundernode/packages/sdk/src/server/operations-client.ts

2023-04-03 15:58 UTC, StarpTech commented on packages/sdk/src/server/plugins/hooks.ts
> +			const { span } = request.telemetry();
Put this in a pre-handler hook or middleware. You also forgot to instrument auth hooks.

2023-04-03 15:58 UTC, StarpTech commented on packages/sdk/src/server/trace.ts
> +// import { diag, DiagConsoleLogger, DiagLogLevel } from "@opentelemetry/api";
Delete or good for debugging? If so, make a comment

2023-04-03 15:58 UTC, StarpTech commented on types/protos/wundernode_config.proto
> +	ConfigurationVariable otelEnabled = 1;
JWT secret is missing.

2023-04-04 11:11 UTC, jensneuse requested changes

2023-04-04 11:11 UTC, jensneuse commented on docs-website/src/pages/docs/examples/open-telemetry.md
> +configureWunderGraphApplication({
How about this alternative configuration:


```typescript
configureWunderGraphApplication({
  apis: [spacex],
  options: {
    openTelemetry: {
      enable: true,
      exporterHTTPEndpoint: '',
      exporterJaegerEndpoint: 'http://localhost:14268/api/traces',
    },
  },
  // ...
});
```

2023-04-04 11:11 UTC, jensneuse commented on docs-website/src/pages/docs/examples/open-telemetry.md
> +configureWunderGraphApplication({
Besides, what happens if I configure both endpoints? This should be documented.

2023-04-04 11:11 UTC, jensneuse commented on docs-website/src/pages/docs/examples/open-telemetry.md
> +curl -H "traceparent: 00-80e1afed08e019fc1110464cfa66635c-7a085853722dc6d2-01" http://localhost:9991/operations/Dragons
Explain this header in the docs.
Also explain what happens if we omit this header.

2023-04-04 11:11 UTC, jensneuse commented on docs-website/src/pages/docs/examples/open-telemetry.md
> +If you don't provide a traceparent header, a new trace id will be generated automatically.
You can add a reference to WG cloud that we do this automatically.

2023-04-04 11:11 UTC, jensneuse commented on pkg/telemetry/otel/trace/trace.go
> +			otlptracehttp.WithInsecure(),
There needs to be an option to set the JWT for auth against the public otel collector.

2023-04-06 07:44 UTC, StarpTech commented on docs-website/src/pages/docs/examples/open-telemetry.md
> +  WG_OTEL_JWT_TOKEN='' # production mode
Just `WG_OTEL_JWT`?

2023-04-06 07:46 UTC, StarpTech commented on docs-website/src/pages/docs/examples/open-telemetry.md
> +  WG_OTEL_EXPORTER_HTTP_ENDPOINT=''
This could be `http://localhost:4318`

2023-04-06 07:48 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +    openTelemetry: {
OpenTelemetry is an implementation detail. Let's call it `telemetry`.

2023-04-06 07:49 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +Configuration priority: `otelExporterHttpEndpoint` > `exporterJaegerEndpoint` > `Stdout`.
I'd throw an error when both are set.

2023-04-06 07:57 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.ts
> +		contextMap.delete(req);
What was the answer here?

2023-04-06 10:04 UTC, ggeijteman-wg commented on docs-website/src/pages/docs/examples/open-telemetry.md
> +      exporterJaegerEndpoint: '', // 'http://localhost:14268/api/traces' we recommed to use it for development
nit: recommend :)

2023-04-06 10:57 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +    openTelemetry: {
ok

2023-04-06 11:13 UTC, jensneuse requested changes

2023-04-06 11:13 UTC, jensneuse commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +Configuration priority: `otelExporterHttpEndpoint` > `exporterJaegerEndpoint` > `Stdout`.
Good idea

2023-04-11 08:02 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +Configuration priority: `otelExporterHttpEndpoint` > `exporterJaegerEndpoint` > `Stdout`.
@YuriBuerov thoughts?

2023-04-11 08:16 UTC, StarpTech requested changes

2023-04-11 08:16 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +If `authToken` / `WG_OTEL_JWT` is set, the exporter will add the `Authorization` header to the request:
`Authorization Bearer` header

2023-04-11 08:16 UTC, StarpTech commented on packages/sdk/src/server/trace.ts
> +			const [authHeader, hasAuthHeader] = getAuthHeader(config);
This looks wrong. The header must be in format `Authorization Bearer`. Please test against the public hotel collector.

2023-04-11 09:03 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +If `authToken` / `WG_OTEL_JWT` is set, the exporter will add the `Authorization` header to the request:
Clarified

2023-04-11 13:53 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-open-telemetry.md
> +Configuration priority: `otelExporterHttpEndpoint` > `exporterJaegerEndpoint` > `Stdout`.
The configuration interface is fine. The reason for throwing an error is to catch misconfiguration. If the user can't run both, it makes no sense to allow both. It has a false positive impression.

2023-04-12 14:27 UTC, StarpTech requested changes

2023-04-12 14:27 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			app.post('/operation/Image/postResolve', async (req, resp) => {
Could you make it clear in the path that this endpoint should error?

2023-04-12 14:27 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +		it('should add telemetry data to request object', async () => {
You mean, "It should add telemetry request decorator..."?

2023-04-12 14:27 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			await app.close();
You can just return app.Close

2023-04-12 14:27 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			expect(span.setAttributes).toBeCalledWith({
Where are the wg attributes?

2023-04-12 14:27 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			jest.spyOn(span, 'end');
Instead of spying, we should use **InMmeorySpanExporter** https://github.com/open-telemetry/opentelemetry-js/blob/93285585ce816a30df8db2b4bdd6d39fd78da806/experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts#L68 and call ` const spans = memoryExporter.getFinishedSpans();` at the end of each test. This gives us more confidence and is easier to handle.

2023-04-12 14:27 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> +		map[string]string{
This is repeated. Can we build a function to enforce that structure e.g `GetOperationSpanTags`

2023-04-12 15:50 UTC, YuriBuerov commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			jest.spyOn(span, 'end');
Could you explain how exactly it will improve these tests? We test the order of calls, returned values, and passed attributes. What additionally could be tested using `InMemoryExporter`?

2023-04-12 15:53 UTC, YuriBuerov commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			await app.close();
what's wrong with the `afterAll` hook? I'm not sure I understand your suggestion.

2023-04-12 15:56 UTC, YuriBuerov commented on pkg/apihandler/apihandler.go
> +		map[string]string{
This is repeated until we have clear requirements on what unique attributes we need in each particular case

2023-04-12 15:59 UTC, YuriBuerov commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			jest.spyOn(span, 'end');
Looking into the test you mentioned, I see no difference. It checks how many spans were created, attributes, and span names.

2023-04-12 17:17 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			await app.close();
Just to simplify it to `afterAll(() => app.close())`

2023-04-12 17:18 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			app.post('/operation/Image/postResolve', async (req, resp) => {
It's just about readability. It's just a suggestion. I have no strong opinion.

2023-04-12 17:19 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			expect(span.setAttributes).toBeCalledWith({
Then I misunderstood the test, and we need to add tests for our actual implementation.

2023-04-12 17:20 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			jest.spyOn(span, 'end');
It's more of a best practice. Spy relies on the actual implementation of the tracer. With the inMemoryExporter you could just test the result.

2023-04-12 17:26 UTC, StarpTech commented on packages/sdk/src/server/trace.ts
> +		throw new Error('cannot configure both OTLP and Jaeger exporters');
Better would be `Cannot configure both OTLP and Jaeger endpoints` ?

2023-04-12 17:58 UTC, YuriBuerov commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			expect(span.setAttributes).toBeCalledWith({
What do you mean by: for our actual implementation? We check that we register plugin successfully, this plugin contains the main logic, it propagates the span and the context everywhere. We check that request was decorated. We check what attributes we pass, the error we log, and when we end it. We don't check only custom attributes we pass in each particular hook, using this plugin.

2023-04-12 18:00 UTC, YuriBuerov commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			jest.spyOn(span, 'end');
The result created span, and passed attributes? I'm ok if it's a personal preference. But it won't be delivered forever this way

2023-04-12 18:02 UTC, YuriBuerov commented on packages/sdk/src/server/trace.ts
> +		throw new Error('cannot configure both OTLP and Jaeger exporters');
But we configure exporters not endpoints which is a configuration parameter passed by user?

2023-04-13 08:28 UTC, StarpTech commented on packages/sdk/src/server/plugins/telemetry.test.ts
> +			expect(span.setAttributes).toBeCalledWith({
Here we have no tests for those places:

- https://github.com/wundergraph/wundergraph/pull/712/files#diff-2f9c5d63c84e8681f889caeb22b494c16f93545d9368d37cf2d15829be1db0b5R43
- https://github.com/wundergraph/wundergraph/pull/712/files#diff-107fe1c4d7590a60a471913fa23ac45ea5111116a722b7609f5b37c6dc22feadR62
- https://github.com/wundergraph/wundergraph/pull/712/files#diff-107fe1c4d7590a60a471913fa23ac45ea5111116a722b7609f5b37c6dc22feadR153

Go

- https://github.com/wundergraph/wundergraph/pull/712/files#diff-1a96a1da77525d4d78f508c5047d48be421b0da7ade77b887a69232107d31546R1258
- https://github.com/wundergraph/wundergraph/pull/712/files#diff-f070476f0b264aae4526fb1388c89665f28ec45309b13381fe38521512ebcb33R260
- https://github.com/wundergraph/wundergraph/pull/712/files#diff-f070476f0b264aae4526fb1388c89665f28ec45309b13381fe38521512ebcb33R352

We also don't test if the trace is properly passed to the internal client.

2023-04-13 08:29 UTC, StarpTech commented on packages/sdk/src/server/trace.ts
> +		throw new Error('cannot configure both OTLP and Jaeger exporters');
My concern is: Does the user has enough context to fix the error when he reads this message?

2023-04-19 15:48 UTC, YuriBuerov commented
@StarpTech feel free to take it over. I improved tests, but it would be great to add tests to the functions, I was not sure how to do it properly. I resolved conflicts and adapted the changes which were made to the internal client.  I tested it, but it would be reasonable to double-check it. Apart from that, I think it's ready to be merged.

2023-05-27 12:12 UTC, StarpTech commented
Closed in favor of https://github.com/wundergraph/wundergraph/pull/1004

2023-05-27 12:12 UTC, closed without merging