chore: enable race detector in Go CI
wundergraph/wundergraph pull request #714
Opened 2023-03-01 21:35 UTC by fiam

2023-03-01 22:12 UTC, StarpTech requested changes

2023-03-01 22:12 UTC, StarpTech commented on .github/workflows/examples-ci.yaml
> +      - uses: ./.github/actions/wunderctl
Could you add a name or description? e.g. `Build with race and make wundectl available`

2023-03-02 10:19 UTC, StarpTech approved these changes
LGTM

2023-03-03 13:03 UTC, devsergiy approved these changes

2023-03-07 15:45 UTC, merged