alberto/eng 1448 add support for openapi generation for
wundergraph/wundergraph pull request #716
Opened 2023-03-02 13:50 UTC by fiam

- feat: initial support for OpenAPI generation
- fix: lazily initialize definitions during op input schema generation
- fix: typo in user visible string in postman collection

2023-03-03 12:24 UTC, Aenimus commented on docs-website/src/pages/docs/features/openapi-postman.md
> +After running `wunderctl generate`, (usually via `npm build` or `npm build:wundergraph`) both an OpenAPI
Parenthetical statement before the comma. Alternatively, remove the parentheses and replace the closing one with another comma.

2023-03-03 12:25 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +	let contents: string[] = ['import type { ExtractResponse } from "@wundergraph/sdk/operations";'];
Const

2023-03-03 12:25 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +		} catch {}
Empty catch?

2023-03-03 12:25 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +	let schemas: Record<string, JSONSchema> = {};
const

2023-03-03 12:26 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +	let generator = TJS.buildGenerator(program, settings);
const

2023-03-03 12:26 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +		let schema = generator!.getSchemaForSymbol(responseTypeName(op));
const

2023-03-03 12:27 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		} catch {}
That's right. If the cache loading fails (maybe the file ended up corrupted somehow), we'd rather fail silently and try to regenerate everything as if there was no cache entry.

2023-03-03 12:29 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +	} catch {}
empty catch?

2023-03-03 12:33 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +	if (loadedOperations.typescript_operation_files) {
Could invert the if an return early. It would mean you have two identical returns, but it would reduce the huge nested block. Your call.

2023-03-03 12:34 UTC, Aenimus commented on packages/sdk/src/graphql/operations.ts
> +							if (!root.definitions) {
Why can't we set this where it's declared?

2023-03-03 12:34 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	if (loadedOperations.typescript_operation_files) {
Let's move the nested block to a function

2023-03-03 12:35 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	} catch {}
I guess we can log a warning in this one. After all, if the cache can't be written to there's probably something wrong in the user's setup.

2023-03-03 12:35 UTC, devsergiy commented on packages/sdk/src/configure/index.ts
> +		} catch {}
@fiam put this explanation as a comment please

2023-03-03 12:39 UTC, Aenimus commented on packages/sdk/src/openapibuilder/operations.ts
> +	if (obj.type === 'array') {
why typeof above and `.type` here?

And on line 30 you coerce obj.type. Shouldn't this be the first thing you check?

2023-03-03 12:40 UTC, fiam commented on packages/sdk/src/graphql/operations.ts
> +							if (!root.definitions) {
That is eventually serialized into the OpenAPI spec. If we always initialize it as `{}` then it clutters the generated schema when it's empty. Lazily initializing it removes it from the output when it has no entries.

2023-03-03 12:45 UTC, devsergiy commented on packages/sdk/src/openapibuilder/__snapshots__/index.test.ts.snap
> +                "schema": undefined,
is it correct that schema is undefined?

2023-03-03 12:47 UTC, StarpTech requested changes
Great stuff!

2023-03-03 12:47 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	const cachePath = path.join('cache', `ts.operationTypes.${objectHash(contents)}.json`);
We want to get rid of the current cache in the next cycle. Is it so slow, or can we remove this?

2023-03-03 12:47 UTC, StarpTech commented on packages/sdk/src/openapibuilder/index.test.ts
> +test('OpenAPI Builder', async () => {
Can we have some sort of table tests to understand what each fixture should represent? I can imagine this place here will grow with different use cases.

2023-03-03 12:50 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	const cachePath = path.join('cache', `ts.operationTypes.${objectHash(contents)}.json`);
This works kinda separately from the rest of the cache, the only shared detail is that they use the same directory. `objectHash` should also be quite fast here, since we're hashing just an array of strings. Generating the schemas for the default testapp from scratch takes around 4s in my machine, so I think a cache is a nice improvement for this feature. Once we get rid of the one for introspection, we can decide if we keep this or if we refactor it into something else.

2023-03-03 12:51 UTC, fiam commented on packages/sdk/src/openapibuilder/index.test.ts
> +test('OpenAPI Builder', async () => {
I'll add more fine grained tests

2023-03-03 12:53 UTC, fiam commented on packages/sdk/src/openapibuilder/__snapshots__/index.test.ts.snap
> +                "schema": undefined,
It is, the operation for the test has no response schema. For real operations, we copy the field as is so this ends up as undefined in the test.

2023-03-03 12:54 UTC, fiam commented on packages/sdk/src/openapibuilder/index.ts
> +interface OpenAPIInfo {
I took a look at a couple of types for OAS and they seemed to bring way more problems than they fixed, because we only support a small subset instead of the whole thing. I'll take a look at this one.

2023-03-03 12:56 UTC, devsergiy commented on packages/sdk/src/openapibuilder/index.ts
> +interface OpenAPIInfo {
this is types only, no processing

2023-03-03 12:57 UTC, devsergiy commented on packages/sdk/src/openapibuilder/index.ts
> +		let spec: OpenAPISpec = {
I propose to also validate the resulting object

https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-schema-validator

maybe it will be enough to do that in tests

2023-03-03 13:01 UTC, Aenimus commented on packages/sdk/src/graphql/operations.ts
> +							if (!root.definitions) {
I don't think I understand. If it's falsy, you set it to an empty object. If it's truthy, it's already some form of object. Is the schema already generated before this? If so, what's the point of setting it at all? I'm really confused.

2023-03-03 15:13 UTC, fiam commented on packages/sdk/src/openapibuilder/index.ts
> +interface OpenAPIInfo {
These types are incomplete, [SchemaObject is missing $ref](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-types/index.ts#L143)

2023-03-03 15:26 UTC, fiam commented on packages/sdk/src/openapibuilder/index.ts
> +		let spec: OpenAPISpec = {
This validator doesn't support `$ref` in schemas nor `additionalProperties: false`

2023-03-03 16:23 UTC, fiam commented on packages/sdk/src/openapibuilder/index.test.ts
> +test('OpenAPI Builder', async () => {
I've added a couple of tests to check a few more properties. They're not very extensive for now because we're not doing that much in this department yet, it's basically a dump of the operations list.

2023-03-03 18:44 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	const cachePath = path.join('cache', `ts.operationTypes.${objectHash(contents)}.json`);
ok

2023-03-03 18:54 UTC, StarpTech requested changes

2023-03-03 18:54 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	openAPI?: {
I'd prefer `openApi`. Uppercase words are not a thing in javascript.

2023-03-03 18:54 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	const contents: string[] = ['import type { ExtractResponse } from "@wundergraph/sdk/operations";'];
For code generation, we have typescript templates `packages/sdk/src/codegen`

2023-03-03 18:54 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	const basePath = path.join(process.env.WG_DIR_ABS!, 'generated');
Reference to environment variables in functions is an anti-pattern. The path should be part of the interface, so it is easier to test and reason about.

2023-03-03 18:54 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	const filePath = path.join(process.env.WG_DIR_ABS!, file.module_path);
Same here.

2023-03-03 18:54 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	const warn = console.warn;
Could you call it `orginalWarn`?

2023-03-03 18:54 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +		logger.debug(`error storing cache entry: ${e}`);
I think this is an error worth it.

2023-03-03 18:57 UTC, StarpTech requested changes

2023-03-03 18:57 UTC, StarpTech commented on docs-website/src/pages/docs/features/openapi-postman.md
> +specification and a Postman collection will be produced inside `.wundergraph/generated`.
How can the user get access to the openAPI spec file? I'd name the concrete paths.

2023-03-03 20:11 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	const contents: string[] = ['import type { ExtractResponse } from "@wundergraph/sdk/operations";'];
We cannot route this through `GenerateCode()`, because retrieving the schemas for the TS operation responses requires code generation to run first.

2023-03-03 20:14 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	openAPI?: {
Renamed, but I don't think that topic is settled https://github.com/airbnb/javascript#naming--Acronyms-and-Initialisms 😅

2023-03-03 20:15 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +		logger.debug(`error storing cache entry: ${e}`);
Changed

2023-03-03 20:15 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	const warn = console.warn;
Renamed

2023-03-03 20:21 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	const basePath = path.join(process.env.WG_DIR_ABS!, 'generated');
I just moved that around, but I'll refactor it to read the environment variable once in `configureWunderGraphApplication()` and then pass it around

2023-03-03 20:27 UTC, fiam commented on docs-website/src/pages/docs/features/openapi-postman.md
> +specification and a Postman collection will be produced inside `.wundergraph/generated`.
Good idea, I've added the exact filenames to the doc

2023-03-03 20:28 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	const basePath = path.join(process.env.WG_DIR_ABS!, 'generated');
Changed

2023-03-03 20:28 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	const filePath = path.join(process.env.WG_DIR_ABS!, file.module_path);
Refactored into an argument

2023-03-04 18:38 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	openAPI?: {
This is a styleguide from airbnb. Most modules don't follow it, at least from my experience.

2023-03-04 18:41 UTC, StarpTech requested changes

2023-03-04 18:41 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> -const loadAndApplyNodeJsOperationOverrides = async (operation: GraphQLOperation): Promise<GraphQLOperation> => {
Could you add some comments what the methods are doing? With few tests its hard to understand the implementation. A short description how we convert to openapi would also helpful.

2023-03-04 18:43 UTC, StarpTech requested changes

2023-03-04 18:43 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +import * as TJS from 'typescript-json-schema';
Please differentiate between type and imports. `*` should be avoided if possible.

2023-03-04 19:55 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +	const contents: string[] = ['import type { ExtractResponse } from "@wundergraph/sdk/operations";'];
Alright :+1:

2023-03-06 11:10 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +import * as TJS from 'typescript-json-schema';
Thanks for the heads up. I copied the import from the repo README and then I didn't think of it again. I've updated it to import only the two functions we need.

2023-03-06 11:15 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +	openAPI?: {
I also found other JS style guides that suggested using the naming convention you mention, like Google's. Just wanted to point out that there are popular guides (AirBnB's has like 130k stars) that suggest something else, so I think we should explicitly pick one to follow and document it.

2023-03-06 11:17 UTC, StarpTech approved these changes
LGTM

2023-03-06 13:32 UTC, Pagebakers commented on packages/sdk/src/configure/index.ts
> +	// XXX: There's no way to silence warnings from TJS, override console.warn
🤦‍♂️

2023-03-06 13:34 UTC, Pagebakers approved these changes

2023-03-06 14:24 UTC, devsergiy approved these changes

2023-03-06 15:05 UTC, merged