feat: extract typescript client from nextjs
wundergraph/wundergraph pull request #72
Opened 2022-07-12 13:24 UTC by Pagebakers

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2022-07-12 15:07 UTC, Pagebakers commented
Will move the client in the sdk package as discussed with Dustin.

2022-07-13 11:23 UTC, Pagebakers commented
This is ready for review now.

The client can be imported from `@wundergraph/sdk/client`. The SDK doesn't export the client directly yet, since there are some conflicting types with the internal client.

2022-07-13 17:33 UTC, StarpTech requested changes

2022-07-13 17:34 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +import hash from 'object-hash';
Oh you're right! I forgot to copy this over.

2022-07-14 07:25 UTC, Pagebakers commented
Added and update the Readme.

`typesVersions` seems to fix the type issues with exports. Imports from 'sdk/dist/...' work still as well.

@StarpTech  I'd recommend you try this branch as well, to see if the new exports work on your machine too.

2022-07-14 08:02 UTC, StarpTech commented
Great, I'll try it out.

2022-07-18 11:26 UTC, Pagebakers commented
@jensneuse I've added types to the exports to make sure the ts compiler can find them.

Running make won't fail anymore, since the nextjs-testapp has been removed from the build script.

But.. after a fresh clone and running make, trying to build the nextjs-testapp will fail, complaining about not being able to find the client types. Once you run `pnpm i` inside the testapp, it does work as expected. To me this seems more like an issue with the nextjs-testapp in the monorepo then the types not being exported correctly from the sdk.

2022-07-18 12:52 UTC, Pagebakers commented
@jensneuse 

It's working fine from NPM, I used a local verdaccio server to publish @wundergraph/nextjs and @wundergraph/sdk and installed it in the nextjs starter without any issues.

If the types and response handling refactoring is OK, we are good to go.

2022-07-19 09:14 UTC, jensneuse requested changes

2022-07-19 09:14 UTC, jensneuse commented on packages/sdk/src/client/README.md
> +    requiresAuthentication: false,
we don't actually make use of "requiresAuthentication" in the pure ts client
I think we should remove it from the config and also the docs, it seems confusing
I've just checked the code, we don't do anything with it, it's only used by the nextjs package

2022-07-19 09:28 UTC, Pagebakers commented on packages/sdk/src/client/README.md
> +    requiresAuthentication: false,
Makes sense! Since 'operationName' is the only param in this case. We can change the client to
```client.query('Hello', {input: { hello: 'world' }})```

Like my proposal in https://github.com/wundergraph/wundergraph/discussions/80

2022-07-19 15:38 UTC, Pagebakers commented on packages/sdk/src/client/README.md
> +    requiresAuthentication: false,
Removed requiresAuthentication and moved isLiveQuery to InternalSubscriptionArgs.

I kept the client api the same, as it would introduce too many changes and I'd need to rewrite a lot of the Next.js api, which makes no sense, since I will be creating a new pure React hook client anyway.

2022-07-20 07:03 UTC, jensneuse requested changes

2022-07-20 07:03 UTC, jensneuse commented on packages/sdk/src/client/README.md
> +const result = await client.subscribe(
I think this is wrong. It's not returning a result. Also, it needs a callback when a message comes back, right?

2022-07-20 07:03 UTC, jensneuse commented on packages/sdk/src/client/README.md
> +const result = await client.subscribe(
I think this is the same problem as with the live query.

2022-08-01 12:10 UTC, StarpTech requested changes

2022-08-01 12:10 UTC, StarpTech commented on packages/sdk/src/client/README.md
> +# Wundergraph TypeScript Client
This client is built for Web and Server correct? It would be good to mention that here.

2022-08-01 12:10 UTC, StarpTech commented on packages/sdk/src/client/README.md
> +## Getting Started
Could you also add an example to pass a custom fetch implementation? Ideally Web and Server example.

2022-08-01 12:10 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +					if (done) break;
I think as a consumer it is valuable to know when the stream ends. Should we pass an object `{ value, done }` to the callback?

2022-08-01 12:10 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +						cb(this.jsonToSubscriptionResult(responseJSON));
By convention, the first argument of a callback is the error.  We should work with one object `{ value, done, error }` or passing it as two arguments `(err, { value, done }) =>`

2022-08-01 12:10 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +			}
As a consumer, I'd expect to get an error rather than nothing. Let's return the response or some information for debugging?

2022-08-01 12:10 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +		window.location.assign(`${this.baseURL}/${this.applicationPath}/auth/cookie/authorize/${authProviderID}${query}`);
This will throw on the server right? We should check the existence.

2022-08-01 12:10 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +			// @ts-ignore
Can you get rid of this?

2022-08-01 12:15 UTC, StarpTech commented
How / did you test the whole implementation?

2022-08-01 12:35 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +		cb: (response: SubscriptionResult<Data>) => void,
I considered this, but I didn't want to introduce breaking changes in this PR.

2022-08-01 14:54 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +						cb(this.jsonToSubscriptionResult(responseJSON));
This is more like an event handler, so I don't feel like this pattern applies here.

2022-08-01 14:59 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +					if (done) break;
I don't think we should add this to the callback parameters, as this is the result object, rather keep it consistent with all other methods.

Perhaps we can bind it to the scope of the function.

```ts
function callback() {
  console.log(this.state) // done // streaming // initializing?
}
```

But perhaps subscribe

2022-08-01 15:18 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +			}
I suppose we should throw an error in this case. But this brings the next question, should we throw every where instead of returning a result with the error message.

2022-08-01 15:22 UTC, Pagebakers commented
> How / did you test the whole implementation? (Upload, Subscribe, ...)

I tested all functionality (except subscriptions) using the nextjs-testapp

2022-08-01 15:24 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +						cb(this.jsonToSubscriptionResult(responseJSON));
After reading it a second time, I think you're right. However, I forget we use the same response shape as for graphql errors.

2022-08-01 15:30 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +		cb: (response: SubscriptionResult<Data>) => void,
As far as I see, the consumer does not use the WunderGraph Client directly in the Next.js package. You can easily swap the parameter order.

2022-08-01 15:35 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +			// @ts-ignore
Done

2022-08-01 15:37 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +			}
Generally, yes. But for now, I'd try to do it only for low-level methods like the client and handle it in the same way as now in the consumer packages (next.js, react ...). So if someone uses this client package, he has full control over handling an error.

2022-08-01 15:47 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +			}
Introducing this will break a thing or two in the next.js client. I wanted to prevent that in this PR. And only introduce  any breaking changes in the new React package.

2022-08-01 15:56 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +			}
Could you point me to the relevant places?

2022-08-01 16:02 UTC, StarpTech commented on pnpm-lock.yaml
> +      '@wundergraph/client': link:packages/client
Do you need to rerun `pnpm i`?

2022-08-01 16:04 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +			}
https://github.com/wundergraph/wundergraph/blob/main/packages/nextjs/src/index.ts#L797

This is also mentioned in a blog post somewhere, so that should be updated too if we change this.

But.. it already catches any error errors in this code, perhaps the change is as easy as `setUser(null)` in the catch, in case the call fails.

2022-08-01 16:12 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +			}
Blog post is irrelevant. We can't update it after every change :smile: 

> But.. it already catches any error errors in this code, perhaps the change is as easy as setUser(null) in the catch, in case the call fails.

Yes, that should do the trick.

2022-08-02 11:01 UTC, Pagebakers commented on pnpm-lock.yaml
> +      '@wundergraph/client': link:packages/client
Yeah because we added @wundergraph/client

I also had to resolve a type issue because there are multiple versions of @types/react installed.

2022-08-02 15:18 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +					if (done) break;
Let's keep this as is for now, and open a new issue once there is a need for having access to a 'done' event.

2022-08-02 16:02 UTC, StarpTech approved these changes
LGTM

2022-08-03 07:43 UTC, jensneuse approved these changes

2022-08-03 07:46 UTC, merged