feat: new local cache implementation
wundergraph/wundergraph pull request #727
Opened 2023-03-08 20:31 UTC by fiam

- feat: initial new cache implementation
- chore: avoid hashing files bigger than 4K

2023-03-10 16:42 UTC, StarpTech requested changes

2023-03-10 16:42 UTC, StarpTech commented on cli/helpers/cache.go
> +func LocalWunderGraphCacheDir(wgDir string) (string, error) {
The `.cache` folder is always placed on the root node_modules of a repository. So e.g. in an npm workspace the cache folder is at the root not at the wundergraph dir. Ideally, this path is configurable. similar to https://docs.astro.build/en/guides/integrations-guide/image/#configcachedir
![image](https://user-images.githubusercontent.com/1764424/224371852-e71c8bac-a765-4049-b043-6505d9f812c7.png)

2023-03-10 16:42 UTC, StarpTech commented on cli/helpers/cache.go
> +func LocalWunderGraphCacheDir(wgDir string) (string, error) {
This might also be useful. https://github.com/withastro/astro/blob/c44aa15534007c3ac320fa6e632c760ddb2ce2f3/packages/astro/src/core/create-vite.ts#L101

I'd checkout astro and turborepo and checkout how they cache behave with pnpm,npm and monorepo setups.

2023-03-10 18:18 UTC, jensneuse commented
@fiam can you add a description of the cache behaviour, edge cases, etc.. to the code so that it's clear how caching works without reading all the code?

2023-03-11 19:06 UTC, fiam commented on cli/helpers/cache.go
> +func LocalWunderGraphCacheDir(wgDir string) (string, error) {
Thanks for the clarification, I was not aware of that behavior. I've changed it to use the topmost `node_modules` instead of the first one found. Do you think we also need to make it configurable at this point?

2023-03-11 19:31 UTC, fiam commented
> @fiam can you add a description of the cache behaviour, edge cases, etc.. to the code so that it's clear how caching works without reading all the code?


I've added a few comments explaining the principles behind this implementation. PTAL and let me know if there's something else we can improve. Thanks!

2023-03-11 20:29 UTC, StarpTech commented on cli/helpers/cache.go
> +func LocalWunderGraphCacheDir(wgDir string) (string, error) {
> Do you think we also need to make it configurable at this point?

No, we can ship the first version without.

2023-03-20 13:19 UTC, jensneuse requested changes
I have a few minor comments.

One thing I'd like to as is about the caching behavior of GraphQL APIs.
I think the "default" behavior should be the following:

- when we run "up" for the first time, introspect the origin directly, don't use the cache, only as fallback, e.g. after 10s of timeout
- during subsequent "reconfigure" runs, always use the cache AND keep the cache updated via polling every 5s (by default)

I think this is the perfect tradeoff between keeping the cache fresh, and reconfigure fast. WDYT?

2023-03-20 20:55 UTC, fiam commented on cli/commands/up.go
> +			ScriptEnv: append(append(helpers.CliEnv(rootFlags), commonScriptEnv(wunderGraphDir)...),
Refactored into a helper function

2023-03-20 20:56 UTC, fiam commented on packages/sdk/src/definition/introspection-cache.ts
> + * There are some API types (like OpenAPI) where all we use for introspection comes from the local filesystem.
Almost. The derived cache key depends on the contents of the file, so we generate a different key when the file changes.

2023-03-20 20:58 UTC, fiam commented on cli/helpers/cache.go
> +	const nodeModulesDirName = "node_modules"
It should be fine. The SDK side is written to work without a cache directory, acting as if there's no cache.

2023-03-20 20:58 UTC, fiam commented on cli/commands/generate.go
> +			ScriptEnv: append(append(
Refactored into a function

2023-03-20 20:59 UTC, fiam commented on packages/sdk/src/definition/database-introspection.ts
> +export const introspectPostgresql = introspectDatabaseWithCache(
I tried passing the constructor to `introspectDatabaseWithCache`, but it became `undefined` at runtime. I'll see if I can find another approach.

2023-03-20 21:14 UTC, fiam commented on packages/sdk/src/definition/database-introspection.ts
> +export const introspectPostgresql = introspectDatabaseWithCache(
Fixed, PTAL

2023-03-20 21:45 UTC, StarpTech commented
@fiam lets have a chat in the morning. I'd like to understand the new behavior and how can use it in our builder.

2023-03-22 08:47 UTC, StarpTech requested changes

2023-03-22 08:47 UTC, StarpTech commented on cli/helpers/cache.go
The logic is not deterministic. Based on cwd a different cache folder can be found. The cache folder should look at the wundergraph application. Therefore, the top "node_modules" can be next to the wundergraph.config.ts or on repo root (, depending on the package manager.) or even worse, outside of the repository if the user hasn't installed the app but use a global wunderctl version. We need a consistent approach.

2023-03-22 12:25 UTC, fiam commented on cli/helpers/cache.go
Changed it to use the local `node_modules`, as requested.

2023-03-22 12:39 UTC, jensneuse approved these changes

2023-03-22 13:08 UTC, StarpTech requested changes

2023-03-22 13:08 UTC, StarpTech commented on cli/commands/up.go
> +	upCmd.PersistentFlags().BoolVar(&clearCache, "clear-cache", false, "clears local caches during startup")
`before startup`?

2023-03-22 13:10 UTC, StarpTech requested changes

2023-03-22 13:13 UTC, StarpTech commented on cli/helpers/cache.go
> +func LocalWunderGraphCacheDir(wgDir string) (string, error) {
The nearest package.json starting from the wundergraph.config.ts is the directory level of the node_modules.

2023-03-22 15:49 UTC, fiam commented on cli/commands/up.go
> +	upCmd.PersistentFlags().BoolVar(&clearCache, "clear-cache", false, "clears local caches during startup")
Fixed, thanks!

2023-03-22 17:29 UTC, StarpTech approved these changes
LGTM

2023-03-22 18:29 UTC, fiam commented
Thanks for the reviews and suggestions!

2023-03-22 18:31 UTC, merged