fix: nextjs client fails hard when a page misses "withWunderGraph"
wundergraph/wundergraph pull request #73
Opened 2022-07-12 14:13 UTC by Pagebakers

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

I think we should still throw an error when the WunderGraph context is missing, otherwise developers might not realise what's going on.

This PR will make sure the Nextjs client throws an error when the client in the WunderGraphContext is undefined with a clear message to instruct the developer how to fix the problem.

![Screenshot 2022-07-12 at 16 06 42](https://user-images.githubusercontent.com/32583/178510310-d17791dc-f60d-4fa7-a0e8-8cfe48d9d9e1.png)

2022-07-13 06:49 UTC, jensneuse requested changes

2022-07-13 06:49 UTC, jensneuse commented on packages/nextjs/src/index.ts
> +		name = 'useQuery',
should it be useQuery by default? Should there be a default value? Or would it not make more sense to force the user of useWunderGraphContext to set a name?

2022-07-13 06:49 UTC, jensneuse commented on packages/nextjs/src/index.ts
> +		errorMessage = `${name} 'client' is undefined. Did you forget to wrap your app or page with 'withWunderGraph'?`,
Is this message accurate? Is the main problem that client is undefined  or the missing Context?

2022-07-13 07:16 UTC, Pagebakers commented on packages/nextjs/src/index.ts
> +		name = 'useQuery',
`useWunderGraph` would be a better default, since that is the most basic context consumer. I don't think we need to force this.

2022-07-13 07:18 UTC, Pagebakers commented on packages/nextjs/src/index.ts
> +		errorMessage = `${name} 'client' is undefined. Did you forget to wrap your app or page with 'withWunderGraph'?`,
The main problem is that the ContextProvider is missing. The context has a default value, so the best way to check if the the app/page is wrapped with withWundreGraph or WunderGraphProvider (for React apps) is by checking if the client has been set.

2022-07-14 07:29 UTC, Pagebakers commented
The default name is `useWunderGraph` now.

2022-08-02 12:49 UTC, Pagebakers commented
@jensneuse this can be merged

2022-08-02 14:47 UTC, StarpTech commented
There is a failing job.

2022-08-02 15:55 UTC, Pagebakers commented
> There is a failing job.

Hm i had this locally too in the other branch, because there are multiple @types/react versions installed.

2022-08-03 07:50 UTC, StarpTech commented
Are you able to fix it?

2022-08-03 07:57 UTC, Pagebakers commented
> Are you able to fix it?

Yep it was fixed in the other PR,  fixed now with the merge

2022-08-03 08:19 UTC, jensneuse approved these changes

2022-08-03 08:20 UTC, merged