feat: add docs for neon integration
wundergraph/wundergraph pull request #768
Opened 2023-03-28 11:31 UTC by JivusAyrus

#### Checklist

- [ ] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-03-28 13:21 UTC, fiam commented on docs-website/src/pages/docs/cloud/integrations/neon.md
> +2. WunderGraph will be setting a environment variable called `NEON_DATABASE_URL`. Please use this env wherever you need the database url.
`use this env` => `use this variable`

2023-03-28 14:36 UTC, Pagebakers requested changes

2023-03-28 14:36 UTC, Pagebakers commented on docs-website/src/pages/docs/cloud/integrations/neon.md
> +This integration sets the connection string of your neon database allowing the wundernode to perform operations on it. Do note that any changes made to the connection string on the neon dashboard are
Neon (capital)

2023-03-28 14:36 UTC, Pagebakers commented on docs-website/src/pages/docs/cloud/integrations/neon.md
> +This integration sets the connection string of your neon database allowing the wundernode to perform operations on it. Do note that any changes made to the connection string on the neon dashboard are
Mention that this will create a new `wundergraph_...` role and it should not be reset or deleted.

2023-03-28 14:36 UTC, Pagebakers commented on docs-website/src/pages/docs/cloud/integrations/neon.md
> +2. WunderGraph will be setting a environment variable called `NEON_DATABASE_URL`. Please use this env wherever you need the database url.
WunderGraph configures a new environment variable

2023-03-28 15:56 UTC, JivusAyrus commented on docs-website/src/pages/docs/cloud/integrations/neon.md
> +This integration sets the connection string of your neon database allowing the wundernode to perform operations on it. Do note that any changes made to the connection string on the neon dashboard are
Have put that under Important instructions. Should I mention it here also?

2023-03-28 15:57 UTC, JivusAyrus commented on docs-website/src/pages/docs/cloud/integrations/neon.md
> +2. WunderGraph will be setting a environment variable called `NEON_DATABASE_URL`. Please use this env wherever you need the database url.
Done

2023-03-29 08:21 UTC, thisisnithin approved these changes

2023-03-29 08:21 UTC, fiam approved these changes
LGTM

2023-03-29 11:12 UTC, Pagebakers requested changes

2023-03-29 11:17 UTC, JivusAyrus commented on docs-website/src/pages/docs/cloud/integrations/neon.md
> +This integration sets the connection string of your Neon database allowing the wundernode to perform operations on it. Do note that any changes made to the connection string on the neon dashboard are
Done

2023-03-29 11:17 UTC, Pagebakers approved these changes

2023-03-29 11:36 UTC, merged