Sergiy/eng 1701 add beta omnigraph backed open api data
wundergraph/wundergraph pull request #771
Opened 2023-03-28 19:50 UTC by devsergiy

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-03-30 16:25 UTC, Pagebakers requested changes

2023-03-30 16:25 UTC, Pagebakers commented on packages/sdk/src/definition/index.ts
> +import { openApi, OpenAPIIntrospectionNew, openApiNew } from './openapi-introspection';
Can we make this openApiV2?

2023-03-30 16:29 UTC, Pagebakers commented on packages/sdk/src/definition/index.ts
> +import { openApi, OpenAPIIntrospectionNew, openApiNew } from './openapi-introspection';
One other issue i found is that `id` is not required but it will throw an error if no id is supplied to the introspection.

2023-03-30 17:55 UTC, devsergiy commented on packages/sdk/src/definition/index.ts
> +import { openApi, OpenAPIIntrospectionNew, openApiNew } from './openapi-introspection';
I have made an ID required and renamed to v2

2023-03-31 07:50 UTC, StarpTech approved these changes
LGTM

2023-03-31 07:58 UTC, jensneuse approved these changes

2023-03-31 08:12 UTC, merged