fix: graphql-hasura-subscriptions example
wundergraph/wundergraph pull request #772
Opened 2023-03-28 20:13 UTC by fiam

- Check that the example does work
- Change token configuration approach to use the environment, update
README
- Add tests

2023-03-28 20:26 UTC, Aenimus approved these changes

2023-03-29 08:13 UTC, Pagebakers approved these changes

2023-03-30 06:03 UTC, fiam commented
Awaiting a cleaner fix for vite example, switching to draft in the meantime

2023-03-31 08:20 UTC, jensneuse requested changes

2023-03-31 08:20 UTC, jensneuse commented on examples/graphql-hasura-subscriptions/.wundergraph/wundergraph.config.ts
> +	headers: (builder) => builder.addStaticHeader('Authorization', `Bearer ${process.env.HASURA_BEARER_TOKEN}`),
This should be `new EnvironmentVariable('HASURA_BEARER_TOKEN ')` with `Bearer token_xxx` in the env var

2023-03-31 08:20 UTC, jensneuse commented on examples/graphql-hasura-subscriptions/README.md
> +- Set your token as HASURA_BEARER_TOKEN=your_token
update this to `Bearer token_xxx` and don't forget to update the token in CI

2023-03-31 08:47 UTC, fiam commented on examples/graphql-hasura-subscriptions/README.md
> +- Set your token as HASURA_BEARER_TOKEN=your_token
Updated, PTAL

2023-03-31 08:47 UTC, fiam commented on examples/graphql-hasura-subscriptions/.wundergraph/wundergraph.config.ts
> +	headers: (builder) => builder.addStaticHeader('Authorization', `Bearer ${process.env.HASURA_BEARER_TOKEN}`),
Thanks for the heads up. I've changed it to use `EnvironmentVariable` and I've also renamed the variable to `HASURA_AUTH_TOKEN`

2023-03-31 08:53 UTC, jensneuse approved these changes

2023-03-31 09:52 UTC, merged