feat: replace the legacy client with the new implementation
wundergraph/wundergraph pull request #78
Opened 2022-07-13 15:47 UTC by Pagebakers

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

## What's new

The legacy client now uses the new client internally and is backwards compatible, so this should not introduce breaking changes.

## Tested methods

- [x] useQuery
- [x] useMutation
- [x] useLiveQuery
- [ ] useSubscription
- [x] uploadFiles
- [x] login
- [x] logout
- [x] fetchUser

This pr is still based of #72 , I can also open a new PR once 72 is merged into main.

2022-07-14 06:43 UTC, jensneuse requested changes
@Pagebakers do you think we can make the client code less repetitive in terms of handling response status codes? Currently, we're doing it multiple times in slightly different ways, but similar for queries and subscriptions as well as uploads. Maybe we can have a generic Response Object with enums for the different states, like error, partial, unauthorized, etc... The generic type will contain content that's specific to the operation. It would be slightly breaking, but I think it's worth cleaning this up. WDYT? cc @StarpTech

2022-07-14 06:51 UTC, Pagebakers commented
> @Pagebakers do you think we can make the client code less repetitive in terms of handling response status codes? Currently, we're doing it multiple times in slightly different ways, but similar for queries and subscriptions as well as uploads. Maybe we can have a generic Response Object with enums for the different states, like error, partial, unauthorized, etc... The generic type will contain content that's specific to the operation. It would be slightly breaking, but I think it's worth cleaning this up. WDYT? cc @StarpTech

We could have a base interface with all shared statuscodes that query/mutate/subscribe extend with their own properties. This wont break anything.

The response handling in the pr is to not break the legacy client, eg translating the new result to the old response type. But this will be deprecated and replaced with a new client with the new Result structure.

2022-07-14 08:12 UTC, StarpTech commented
I'm always for simplifying things :smile: @Pagebakers If you can do it without breaking that would be nice. Maybe just create a proposal and show us in zoom?

2022-07-15 12:15 UTC, StarpTech commented
I can't run `make` it looks like `nextjs-testapp` can't find the client.

```
│ Failed to compile.
│ .wundergraph/generated/wundergraph.client.ts:27:8
│ Type error: Cannot find module '@wundergraph/sdk/client' or its corresponding type declarations.
│   25 |        MutationResult,
│   26 |        SubscriptionResult,
│ > 27 | } from "@wundergraph/sdk/client";
│      |        ^
│   28 | 
│   29 | export const WUNDERGRAPH_S3_ENABLED = true;
│   30 | export const WUNDERGRAPH_AUTH_ENABLED = true;
└─ Failed in 4.6s

```

2022-07-18 10:25 UTC, Pagebakers commented
> Running into this error now too.
> 
> ```shell
> uncaught exception, origin: uncaughtException, error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/codegen/templates/typescript/web.client' is not defined by "exports" in /Users/eelco/Development/wundergraph/wundergraph/packages/nextjs-testapp/node_modules/@wundergraph/sdk/package.json
> node:internal/modules/cjs/loader:488
>       throw e;
>       ^
> ```
> 
> I was expecting this would happen when introduction `exports` in the package.json. You can no longer import from `@wundergraph/sdk/dist...` which I suspect might break a few things.

Added /dist/* to exports to resolve this.

2022-08-01 16:05 UTC, StarpTech requested changes

2022-08-01 16:05 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +export class WunderGraphClient<Role> {
This is the same implementation as in PR #72 ?

2022-08-02 14:40 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +export class WunderGraphClient<Role> {
This PR is based of #72

2022-08-02 14:41 UTC, Pagebakers commented
Fully up to date with #72 now

2022-08-02 14:49 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +// export interface QueryProps<Input, Args = QueryArgs> {
Any reason to stay it here?

2022-08-03 07:47 UTC, StarpTech approved these changes
LGTM

2022-08-03 07:47 UTC, StarpTech commented on packages/sdk/src/client/index.ts
> +// export interface QueryProps<Input, Args = QueryArgs> {
Any reason to keep it?

2022-08-03 07:48 UTC, Pagebakers commented on packages/sdk/src/client/index.ts
> +// export interface QueryProps<Input, Args = QueryArgs> {
I actually dreamed about this last night, I forgot to remove it :D

2022-08-03 07:52 UTC, jensneuse approved these changes

2022-08-03 07:53 UTC, merged