feat: implement typescript orm
wundergraph/wundergraph pull request #783
Opened 2023-04-02 02:10 UTC by timkendall

## Motivation and Context

Implementation of #597 

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-03 23:53 UTC, timkendall commented on packages/sdk/src/configure/index.ts
> +		Apis: resolvedApis,
I added this to get access to the individual namespaced APIs in-order-to simplify code-generation. We generate a separate un-namespaced TypeScript representation of each API's GraphQL schema (this is primarily in-consideration of TS performance but also more ergonomic in general).

2023-04-03 23:54 UTC, timkendall commented on packages/sdk/src/definition/index.ts
> +		this.Namespace = namespace
See above comment. i.e need access to each API's namespace for efficient/simple code-generation.

2023-04-04 00:08 UTC, timkendall commented on packages/sdk/src/server/server.ts
> +				orm: ormModule ? ormModule.orm : null,
Not safe. Are you guys fine requiring the orm be generated (i.e we can throw above if it is not)? cc. @jensneuse

2023-04-04 00:10 UTC, timkendall commented on pkg/operations/operations.go
> +// @todo we need to ensure the ORM is generated for every
Same question, are you guys fine making the orm a required component? @jensneuse

2023-04-04 00:13 UTC, timkendall commented on testapps/simple/.wundergraph/operations/users/getWeather.ts
> +import { Weather } from '../../generated/orm'
I think this primarily only matters for enums used in operation variables. Some options:

1. Rely on static imports (not very ergonomic)
2. Expose enum references on handler context (maybe on `graph`?)
3. Replace enum types w/string literal unions (still get editor auto-complete, maybe the best option?)

2023-04-04 00:20 UTC, timkendall commented on testapps/simple/.wundergraph/operations/users/getWeather.ts
> +		// @note `select` will need to have a max parameters of "10"
I think we should iterate on this API. The example below really stress-tests the current API. 

While tweaking `select` to support selecting all nested scalar fields by default will help this example (e.g `select('weather', 'weather.summary', 'weather.temperature', 'weather.wind')`) it still feels unnecessarily verbose.

Perhaps we can decorate the GraphQL API schema w/additional metadata to let the ORM infer what objects are values (automatically selected) vs. entities (require explicit selection)

2023-04-04 01:58 UTC, timkendall commented on testapps/simple/.wundergraph/operations/users/getWeather.ts
> +import { Weather } from '../../generated/orm'
Made the change to string literals as it seemed the obvious solution. Happy to re-visit if needed.

2023-04-04 11:16 UTC, jensneuse commented on testapps/simple/.wundergraph/operations/users/getWeather.ts
> +		// @note `select` will need to have a max parameters of "10"
Would it be possible to do `weather.summary.*` & `weather.temperature.*` to include all scalars on the current object, or `weather.**` to include all fields exhaustively? (except _join to prevent recursion)

2023-04-04 11:21 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +		Apis: resolvedApis,
I think this makes sense.

2023-04-04 11:21 UTC, jensneuse commented on packages/sdk/src/definition/index.ts
> +		this.Namespace = namespace
yup

2023-04-04 11:22 UTC, jensneuse commented on packages/sdk/src/server/server.ts
> +				orm: ormModule ? ormModule.orm : null,
To me it sounds like the server should not start if the orm is not generated. Opinions?

2023-04-04 11:23 UTC, jensneuse commented on packages/sdk/src/server/server.ts
> +		const ormModulePath = buildOrm(wundergraphDir)
@StarpTech is this the way to go? We already use esbuild internally from Go

2023-04-06 15:43 UTC, timkendall commented on testapps/simple/.wundergraph/operations/users/getWeather.ts
> +		// @note `select` will need to have a max parameters of "10"
Yeah I was thinking that could be the way to go. Nice and explicit. Exhaustive select-all may be tricky (and a nice-to-have IMO) but I think the former are do-able. Will spike.

2023-04-15 20:52 UTC, StarpTech commented
> Utilize internal GraphQL handler (doesn't exist yet, cc. @jensneuse )

Hi @timkendall we're currently working on the internal graphql handler. In Middle of the next week, we should have a working version.

> Add developer documentation (i.e architecture, contributing, etc.)

In the meantime, it would be valuable, before we merge this PR that we have some docs about the architecture.

2023-04-16 00:21 UTC, timkendall commented
@StarpTech Yep will do.

2023-04-16 10:08 UTC, timkendall commented on packages/sdk/src/server/server.ts
> +		const ormModulePath = buildOrm(wundergraphDir);
@StarpTech acceptable for now (see Jens original [comment](https://github.com/wundergraph/wundergraph/pull/783#discussion_r1157103488); outdated due to rebase)?

2023-04-19 03:52 UTC, timkendall commented
Added some minimal documentation here:
- [Architecture doc](https://github.com/timkendall/wundergraph/blob/feat/orm/packages/orm/docs/architecture.md)
- Community docs
   - [`/docs/features/typescript-orm`](https://github.com/timkendall/wundergraph/blob/feat/orm/docs-website/src/pages/docs/features/typescript-orm.md)
   - [`/docs/typescript-operations-reference/accessing-data-sources-from-operations`](https://github.com/timkendall/wundergraph/blob/feat/orm/docs-website/src/pages/docs/typescript-operations-reference/accessing-data-sources-from-operations.md)

2023-04-19 12:33 UTC, StarpTech requested changes

2023-04-19 12:36 UTC, StarpTech commented
@timkendall please rebase :smile:

2023-04-20 03:25 UTC, timkendall commented on packages/sdk/src/codegen/templates/typescript/orm.template.ts
> +  {{#each namespaces}}
Yeah this was cruft, good callout. We can improve slightly right now (implemented, see changes) but TypeScript still requires us to statically reference the `Schema` interface and `SCHEMA` constant (so we can't do `schema.Schema`).

(this could be further simplified by sharing the schema representation type between comp time and runtime like is done with operations)

2023-04-20 04:41 UTC, timkendall commented on packages/sdk/src/server/server.ts
> +		const ormModulePath = buildOrm(wundergraphDir)
Not sure if anything does, likely just my ignorance here. As long as we've ensured that the ORM code-generator has run we can transpire within the Go-implemented `generate` command.

2023-04-20 15:57 UTC, timkendall commented on pkg/operations/operations.go
> +// @todo we need to ensure the ORM is generated for every
Yeah idk. My assumption is that it'd be fairly negligible impact in either context (could be wrong, haven't quantified).

Regardless, we need to ensure that we're generating a valid reference (to `orm`) here; always generating the ORM is just the first solution that came to mind for me. Let me know how you guys want to handle 👍

2023-04-20 16:48 UTC, StarpTech commented
@timkendall, the internal graphql handler has been merged.

2023-04-20 17:02 UTC, timkendall commented
@StarpTech Yep saw, update. Is [this](https://github.com/timkendall/wundergraph/blob/feat/orm/packages/sdk/src/codegen/templates/typescript/orm.ts#L64) the appropriate way to reference the new internal endpoint (tested locally and it works)?

2023-04-25 16:40 UTC, StarpTech commented
> Yep saw, updated. Is [this](https://github.com/timkendall/wundergraph/blob/feat/orm/packages/sdk/src/codegen/templates/typescript/orm.ts#L64) the appropriate way to reference the new internal endpoint (tested locally and it works)?

Looks good!

2023-04-27 00:42 UTC, timkendall commented
@StarpTech @jensneuse is moving the ORM transpilation to build-time a blocker for this being merged? If so I can focus on solutions for that. In the mean-time I will continue fixing bugs and implementing small improvements to the functionality.

2023-04-27 09:51 UTC, Pagebakers commented
Wanted to give this a test run in the nextjs testapp, but not all code generation seems to be up to date yet.

Updating `wundergraph.factory.ts` to the following works. 
```ts
// Code generated by wunderctl. DO NOT EDIT.

import type {InternalClient} from "./wundergraph.internal.client";
import {Queries,Mutations,Subscriptions} from "./wundergraph.internal.operations.client";
import type {Role} from "./wundergraph.server";
import type {CustomClaims} from "./claims";
import {createOperationFactory} from "@wundergraph/sdk/operations";
import {orm} from './orm'

export {z, AuthorizationError} from "@wundergraph/sdk/operations";
export const createOperation = createOperationFactory<InternalClient, Role, CustomClaims, Queries, Mutations, Subscriptions, typeof orm>();
```

@wundergraph/orm needs to be a dependency of the project right now, next to @wundergraph/sdk. Ideally sdk is the only requirement.

We use es5 target in a lot of examples, which is outdated and incompatible with the generated orm, setting the target to 2019 fixes (same target as the sdk) this.

The weather API doesn't work, but the only error message I get is `Client error` so not sure what's wrong.

Really great work! Can't wait to use this.

2023-04-27 13:42 UTC, StarpTech commented
> @StarpTech @jensneuse is moving the ORM transpilation to build-time a blocker for this being merged? 

I'd like to give it at least a spin before we give up on this. But yes, if the effort is too high, we can merge it as it is.

2023-04-27 16:41 UTC, StarpTech commented on packages/orm/src/fragment-definition-builder.ts
> +		return this as any;
Curious if `unknown` works here too.

2023-05-02 03:34 UTC, timkendall commented on packages/orm/src/fragment-definition-builder.ts
> +		return this as any;
It doesn't

2023-05-02 04:30 UTC, timkendall commented
@StarpTech I think we actually should be able to bundle/transpile the generated ORM after we finish executing the config in Node ([here](https://github.com/timkendall/wundergraph/blob/feat/orm/cli/commands/generate.go#L147)). I'll spike this out shortly.

(confused myself there for a minute ;)

2023-05-02 04:56 UTC, timkendall commented
@StarpTech alright there we go (scrappy but works, let me know what should be adjusted please 🙏 )

2023-05-02 16:36 UTC, timkendall commented on testapps/default/.wundergraph/operations/federation/CustomPriceUpdates.ts
> +		// @bug this seems to cause the WunderNode (Go) server to crash
I mentioned this to @Pagebakers but running this operation from `main` results in a segfault in the Go server it seems (cc. @StarpTech )

2023-05-02 17:53 UTC, jensneuse commented on testapps/default/.wundergraph/operations/federation/CustomPriceUpdates.ts
> +		// @bug this seems to cause the WunderNode (Go) server to crash
I've tried this using "go debug", no issues.
However, I found another problem.
We're not canceling the subscription when the client request disconnects.
On the operations client, we've exposed a cancelSubscriptions func to the fastify server to cancel all subscriptions on client disconnect. We could use a similar pattern if there's no alternative:
https://github.com/wundergraph/wundergraph/blob/1e3cf6094c23e1c5830cdef23db8399e5e259319/packages/sdk/src/server/operations-client.ts#L72

2023-05-02 20:20 UTC, timkendall commented on testapps/default/.wundergraph/operations/federation/CustomPriceUpdates.ts
> +		// @bug this seems to cause the WunderNode (Go) server to crash
Ah good catch, will address 👍

2023-05-03 06:58 UTC, jensneuse commented
@timkendall I found another issue

Given the following operation:

```typescript
const capsule = await graph.from('spacex')
			.query('capsule')
			.select('id','status','type','dragon.id','dragon.active')
			.exec()
```

The response object will have the path `dragon.id` and `draong.active`.

If I change the operation to this:

```typescript
const capsule = await graph.from('spacex')
			.query('capsule')
			.select('id','status','type','dragon','dragon.id','dragon.active')
			.exec()
```

Now dragon is an empty object on the response shape.

I think in both cases, the response shape should be the same.
Additionally, I'm not sure what's the value of selecting 'dragons' at all.

That said, I had an idea that we previously named `dragons.*`.
If a user wants to select all scalar fields on dragons, they could just use the following operation:

```typescript
const capsule = await graph.from('spacex')
			.query('capsule')
			.select('id','status','type','dragon')
			.exec()
```

WDYT`

2023-05-07 20:52 UTC, StarpTech commented
@timkendall I haven't forgotten you. I'll revisit the PR tomorrow :smile:

2023-05-08 17:29 UTC, timkendall commented
@StarpTech All good :) @Pagebakers and I were chatting and I think we'll need to further optimize the ORM codegen piece. What I have implemented now runs the transpilation/bundling at build time in Go properly, but we're still re-generating the ORM every time and operation file changes. This is very noticeable (~10+ seconds on my M1 w/the default test app). Do we have any support for caching codegen plugins already (cc. @jensneuse )?

2023-05-08 17:35 UTC, jensneuse commented
> @StarpTech All good :) @Pagebakers and I were chatting and I think we'll need to further optimize the ORM codegen piece. What I have implemented now runs the transpilation/bundling at build time in Go properly, but we're still re-generating the ORM every time and operation file changes. This is very noticeable (~10+ seconds on my M1 w/the default test app). Do we have any support for caching codegen plugins already (cc. @jensneuse )?

The code gen should actually never do anything for the ORM when operations change, as the ORM only really depends on the virtual graph. We don't yet have it, but we need a system to cache results of certain steps. E.g. if the outcome of generating the virtual graph doesn't change, there's really no need to re-generate the ORM.

2023-05-08 17:38 UTC, timkendall commented
@jensneuse Implemented the tweak for auto-selecting all scalars on object types (only one level deep). Solves the majority use-case maybe? Let me know what you guys think.

Relation/nested complex type selection still needs improvement IMO. I need to think on it some more. Would be nice to support N-level deep selections but something like this feels ambiguous `select('dragon', 'dragon.diameter', 'dragon.heat_shield')` 🤔

2023-05-08 17:39 UTC, jensneuse commented
> @jensneuse Implemented the tweak for auto-selecting all scalars on object types (only one level deep). Solves the majority use-case maybe? Let me know what you guys think.
> 
> Relation/nested complex type selection still needs improvement IMO. I need to think on it some more. Would be nice to support N-level deep selections but something like this feels ambiguous `select('dragon', 'dragon.diameter', 'dragon.heat_shield')` 🤔

When you select `dragon.diameter`, can it auto select `dragon`?

2023-05-08 17:42 UTC, timkendall commented
@jensneuse Exactly. I can whip something up for the ORM. 

Maybe a longer term solution could be to integrate a first-class build system like Turbopack or something to optimize the codegen steps optimally (maybe overkill...)? i.e WunderCtl could generate the build system config and execute that in the codegen step.

2023-05-08 17:44 UTC, timkendall commented
@jensneuse I suppose so (will have to see if this complicates the implementation too much...). Still seems ambiguous to me (i.e are we selecting _only_ `dragon.diameter`?) but maybe this isn't an issue w/IntelliSense

2023-05-08 18:57 UTC, jensneuse commented
> @jensneuse I suppose so (will have to see if this complicates the implementation too much...). Still seems ambiguous to me (i.e are we selecting _only_ `dragon.diameter`?) but maybe this isn't an issue w/IntelliSense

I thought about it a bit more. dragon is an object, so it doesn't really make sense to select it except you'd want a "select all". So either select dragon and disable all other fields, or select individual fields.

2023-05-09 06:48 UTC, jensneuse commented on packages/sdk/src/server/plugins/functions.ts
> +											asyncContext.ormOperationControllers.forEach((controller) => controller.abort());
@timkendall Is this async through the forEach or will the forEach return after all controllers are aborted?

2023-05-09 06:54 UTC, jensneuse commented
@timkendall regarding cancelling subscriptions, here's how you can do it without globals

Make a copy of the ORM (operations client) with an empty array of subscriptions similar to this:
https://github.com/timkendall/wundergraph/blob/feat/orm/packages/sdk/src/server/plugins/functions.ts#L58

Then, on unsubscribe call the cancel func:
https://github.com/timkendall/wundergraph/blob/feat/orm/packages/sdk/src/server/plugins/functions.ts#L99

2023-05-10 09:26 UTC, Pagebakers commented
We discussed this morning that we'd like to introduce a feature flag before releasing this. So users/customers can opt-in to use it while we test it and we have a solution for the build times.

I'm happy to help implementing this.

```ts
configureWunderGraphServer({
  experimental: {
    orm: true
  }
})

2023-05-10 12:43 UTC, StarpTech commented
Hi @timkendall I did some CPU profiling for the startup performance. It doesn't look too bad. Around 25% degradation. I think there are places where we import way more than necessary or don't lazy load the feature. Maybe, we can find some quick improvements.

2023-05-11 17:05 UTC, timkendall commented on packages/sdk/src/server/plugins/functions.ts
> +											asyncContext.ormOperationControllers.forEach((controller) => controller.abort());
It will return after all controllers have been aborted (since `controller.abort` is synchronous).

2023-05-11 17:06 UTC, timkendall commented on packages/sdk/src/server/plugins/functions.ts
> +										operationClient.cancelSubscriptions();
As you mentioned @jensneuse we can do more major refactoring here at some point (see comment on line 71).

2023-05-11 17:59 UTC, timkendall commented
@StarpTech yeah thats a lot of JS to load :) Put both the codegen and runtime instantiation being the `experimental.orm` flag for now as recommended. Will look into optimizing in the future (thats the fun part ;).

2023-05-12 11:43 UTC, StarpTech approved these changes
LGTM

2023-05-13 02:50 UTC, timkendall commented
@StarpTech small tweaks included in conflict resolution if you could review before I merge (nothing changing functionality, just renaming some bindings and tweaking type parameter order on `HandlerContext`)

2023-05-15 09:19 UTC, StarpTech commented
@timkendall LGTM

2023-05-15 09:19 UTC, StarpTech approved these changes
LGTM

2023-05-15 10:29 UTC, Pagebakers commented
We should set ORM to never in wundergraph.factory.ts if it's not enabled, otherwise it results in a type error

```
// Code generated by wunderctl. DO NOT EDIT.

/**
 * "Warning: `Enable the ORM by setting `experimental.orm` to `true` in your `wundergraph.config.ts`.";
 */
export type ORM = never

```

2023-05-15 16:57 UTC, closed without merging