feat: relay client
wundergraph/wundergraph pull request #791
Opened 2023-04-04 09:49 UTC by DaniAkash

## Motivation and Context

Draft implementation of WunderGraph relay client that can be used with react & next.js projects.

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-04 10:07 UTC, jensneuse commented on packages/relay-nextjs/src/createRelayApp.ts
> +						operationName: `relay/${id}`,
I'm not sure if it will be a problem if we hardcode the `relay` prefix.
If there's no way out, we might go with this approach, but if it's possible, I'd prefer if you can make this configurable.

2023-04-04 10:07 UTC, jensneuse commented on packages/relay-nextjs/package.json
> +  "description": "WunderGraph Solid Query Integration",
Copy Pasta error

2023-04-04 10:08 UTC, DaniAkash commented on packages/relay-nextjs/src/createRelayApp.ts
> +						operationName: `relay/${id}`,
Will look for a way

2023-04-05 07:18 UTC, Pagebakers commented on testapps/nextjs-relay/pages/index.tsx
>  export default withRelay(Home, IndexQuery, {
You could abstract this also `withWunderGraphRelay` for example, that handles setting up the environment, but also make sure it can be extended.

2023-04-05 07:21 UTC, Pagebakers commented on testapps/nextjs-relay/lib/createRelayApp.ts
> +export const { createClientEnvironment, createServerEnvironment, useLivePreloadedQuery } = createRelayApp(client);
We can also create a codegen template for this file, what do you think?

2023-04-05 07:23 UTC, DaniAkash commented on testapps/nextjs-relay/lib/createRelayApp.ts
> +export const { createClientEnvironment, createServerEnvironment, useLivePreloadedQuery } = createRelayApp(client);
Yup would be a good idea!

2023-04-05 09:09 UTC, DaniAkash commented on testapps/nextjs-relay/pages/index.tsx
>  export default withRelay(Home, IndexQuery, {
Have created the withWunderGraphRelay HOC 👍🏽

2023-04-06 08:53 UTC, Pagebakers commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +import type {} from 'next';
I think there is another way, you can add the next types to the tsconfig.json

There was a similar issue for zod some time ago reported in the issues.

2023-04-06 09:05 UTC, Pagebakers requested changes

2023-04-06 09:05 UTC, Pagebakers commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +	const useLivePreloadedQuery = <TQuery extends OperationType>(
Now everything is a live query by default. Can you infer the query type from the parameters? eg if it's query or subscription?

LiveQueries should be enabled using `liveQuery: true`

Subscriptions should support `subscribeOnce: true` parameter, which makes them behave as a regular query.

We  can also simply use `usePreloadedQuery` as the name I think.

2023-04-12 11:28 UTC, DaniAkash commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +export const createWunderGraphRelayApp = (client: Client) => {
I'm not sure if the sdk itself will need any changes for making this work 🤔

2023-04-12 11:31 UTC, DaniAkash commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +	const useLivePreloadedQuery = <TQuery extends OperationType>(
I tried changing it but as per relay docs, `usePreloadedQuery` is used on component level for getting the data. But if we keep the name usePreloadedQuery with subscription status - we'll have to force existing users of relay to refactor their components. Taking into account, it's a safer to keep a separate hook for live queries. If the user doesn't need livequery they don't have to refactor any existing components

2023-04-12 12:18 UTC, DaniAkash commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +import type {} from 'next';
Tried adding
```
"include": ["src/**/*", "next-env.d.ts", "tests"],
```
to tsconfig.json & created `next-env.d.ts` in root similar to next.js project but the build still fails :(

2023-04-13 12:00 UTC, Pagebakers commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +export const createWunderGraphRelayApp = (client: Client) => {
Also not sure, in any case it's better to make it so that it accepts an options object, so we can easily extend it later when adding more features.

```
export const createWunderGraphRelayApp = (options: CreateWunderGraphRelayOptions) => {
```

2023-04-13 12:00 UTC, Pagebakers commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +	const useLivePreloadedQuery = <TQuery extends OperationType>(
As discussed we will add subscriptions support later.

2023-04-17 10:32 UTC, DaniAkash commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +import type {} from 'next';
Fixed after removing nextjs specific dependencies completely

2023-04-17 10:33 UTC, DaniAkash commented on packages/relay-nextjs/src/createWunderGraphRelayApp.ts
> +export const createWunderGraphRelayApp = (client: Client) => {
Solved by making the options an object based config

2023-04-17 10:34 UTC, DaniAkash commented on testapps/nextjs-relay/lib/createRelayApp.ts
> +export const { createClientEnvironment, createServerEnvironment, useLivePreloadedQuery } = createRelayApp(client);
will create codegen after first version release

2023-04-17 11:58 UTC, Pagebakers requested changes
🙌 a few minor comments

2023-04-17 11:58 UTC, Pagebakers commented on cli/commands/loadoperations.go
> +		return os.WriteFile(outFile, []byte(out), os.ModePerm)
This was required for relay?

2023-04-17 11:58 UTC, Pagebakers commented on docs-website/src/pages/docs/getting-started/index.jsx
> +						description="Learn how to use WunderGraph with Remix."
Typo: remix -> relay

2023-04-17 11:58 UTC, Pagebakers commented on docs-website/src/pages/docs/getting-started/relay-quickstart.md
> +- [Official Tutorial](https://relay.dev/docs/tutorial/intro/)
Also link to the reference docs

2023-04-17 11:58 UTC, Pagebakers commented on packages/react-relay/src/createWunderGraphRelayApp.tsx
> +		options = { liveQuery: true },
I'd move this up in the root object

2023-04-17 11:58 UTC, Pagebakers commented on pkg/loadoperations/loader.go
> +		case ".json":
Should we be more specific here? eg not all .json files are relay files?

2023-04-17 13:09 UTC, DaniAkash commented on pkg/loadoperations/loader.go
> +		case ".json":
@Pagebakers users can define any name for the persisted json file created by relay. Either we'll have to read the relay config or let it be ".json" files for now

2023-04-17 13:42 UTC, jensneuse commented on cli/commands/loadoperations.go
> +		return os.WriteFile(outFile, []byte(out), os.ModePerm)
ioutil is deprecated

2023-04-18 07:38 UTC, Pagebakers approved these changes

2023-04-18 09:02 UTC, jensneuse approved these changes

2023-04-18 09:02 UTC, merged