feat: Add SvelteKit Auth example
wundergraph/wundergraph pull request #801
Opened 2023-04-05 03:21 UTC by leoalves

## Motivation and Context

Add Wundergraph cookie based authentication example with SvelteKit

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-06 08:15 UTC, Pagebakers requested changes
Awesome work and great showcase for WunderGraph! I left a few comments.

2023-04-06 08:15 UTC, Pagebakers commented on examples/sveltekit-oidc-cookies-auth/package.json
> +	"name": "sveltekit-oidc-cookies-auth",
Please prefix the name with `wundergraph-`

2023-04-06 08:15 UTC, Pagebakers commented on examples/sveltekit-oidc-cookies-auth/src/lib/components/Navbar.svelte
> +	const { getAuth, createQuery } = createWGClient();
I'd initiate the client in lib/svelte-query already so you can simply import getAuth / createQuery in components and routes.

Is there any specific reason why you decided for this with Svelte?

2023-04-06 08:15 UTC, Pagebakers commented on examples/sveltekit-oidc-cookies-auth/src/lib/components/UserFromCookie.svelte
> +	const { getUser } = createWGClient();
Idem, import getUser from $lib/svelte-query

2023-04-06 08:15 UTC, Pagebakers commented on examples/sveltekit-oidc-cookies-auth/src/routes/+page.ts
> +  await queryClient.prefetchQuery({
Will look into your other PR to add this to the client asap.

2023-04-06 14:32 UTC, leoalves commented on examples/sveltekit-oidc-cookies-auth/src/lib/components/Navbar.svelte
> +	const { getAuth, createQuery } = createWGClient();
This was a mistake from my part.  I was trying a few different things with the customFetch function provided by SvelteKit and didn't change it afterwards.  I will change it now.

2023-04-11 07:27 UTC, Pagebakers approved these changes
LGTM!

2023-04-11 08:28 UTC, Pagebakers commented
Can you update the example to use the new prefetchQuery method?
https://docs.wundergraph.com/docs/clients-reference/svelte-query#ssr

2023-04-12 01:17 UTC, leoalves commented
> Can you update the example to use the new prefetchQuery method? https://docs.wundergraph.com/docs/clients-reference/svelte-query#ssr

I updated the code. But I don't think the changes are updated in the NPM repository.

2023-04-14 03:48 UTC, DaniAkash commented on examples/sveltekit-oidc-cookies-auth/package.json
> +		"@wundergraph/svelte-query": "^0.1.0"
Changing this svelte query package version to latest should be enough to merge this PR :D 
```suggestion
		"@wundergraph/svelte-query": "^0.2.2"
```

2023-04-14 04:04 UTC, DaniAkash approved these changes

2023-04-19 13:50 UTC, DaniAkash approved these changes

2023-04-19 19:59 UTC, leoalves commented
> CI is failing https://github.com/wundergraph/wundergraph/actions/runs/4744045831/jobs/8424403243?pr=801 @leoalves could you take a look?

I believe the issue was a mismatch in the `@tanstack/svelte-query` version installed in this package and the one from `@wundergraph/svelte-query` it should be good now.

2023-04-20 18:08 UTC, Pagebakers commented
Getting the following error in the tests:

```
Warning: G] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-04-20 19:33 UTC, leoalves commented
> Getting the following error in the tests:
> 
> ```
> Warning: G] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
> 
>     tsconfig.json:2:12:
>       2 │   "extends": "./.svelte-kit/tsconfig.json",
>         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

Tthat is just a warning.  That tsconfig.json is generated afterwards when running the `build`, `dev` or `sync` commands. 

The error is coming from the QueryClient type (same error as before).  It's comparing types from 2 different versions of the `@tanstack/svelte-query` package. One from this example and the other one installed in the `@wundergraph/svelte-query`. 
Both types are exactly the same and when running the check command locally `npm run check` I don't get any errors.
I can try to to copy the `@tanstack/svelte-query` version from the `@wundergraph/svelte-query` package into this example `package.json`.  But I am not sure if that will solve the problem

2023-04-25 13:23 UTC, merged