feat: mark operations as internal when inside internal folder
wundergraph/wundergraph pull request #803
Opened 2023-04-05 12:51 UTC by thisisnithin

## Motivation and Context

Operations are now marked as internal when under an `internal` folder.

## Marketing Changelog

WunderGraph will now automatically consider operations as internal when placed inside a directory name `internal`. This can be nested as well. All operations below are internal.

```
.wundergraph/
└── operations/
    ├── internal/
    │   └── Weather.graphql
    └── hello/
        └── internal/
            ├── user.ts
            └── more/
                └── admin.ts
                
```

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-05 13:07 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +			'Use of the internal prop will be deprecated soon. ' +
I would say that it is already deprecated, rather than soon

2023-04-05 13:08 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> -		Internal: implementation.internal ? implementation.internal : false,
who wrote this :joy:

2023-04-05 13:13 UTC, Aenimus commented on docs-website/src/pages/docs/typescript-operations-reference/security.md
> +The internal folder can be nested and the same applies to nested operations within the internal folder.
The internal folder can be nested, and the same applies to nested operations within the internal folder.

2023-04-05 13:14 UTC, Aenimus commented on packages/sdk/src/configure/index.ts
> +			'Use of the internal prop will be deprecated soon. ' +
By which I mean, we're still going to allow them to use it, right?

2023-04-05 13:17 UTC, Aenimus commented on packages/sdk/src/graphql/operations.ts
> +export const internalPathRegex = '.*\\/?internal\\/.*';
I think something like `/(?:^|/)internal/(?:\w|-)+/` is more robust.

2023-04-05 13:17 UTC, Aenimus commented on packages/sdk/src/graphql/operations.ts
> +								'Use of internalOperation directive will be deprecated soon. ' +
Same deprecated point as above

2023-04-05 13:19 UTC, StarpTech requested changes

2023-04-05 13:19 UTC, StarpTech commented on docs-website/src/pages/docs/typescript-operations-reference/security.md
> +The internal folder can be nested and the same applies to nested operations within the internal folder.
Could you add a directory example?

2023-04-05 13:19 UTC, StarpTech commented on docs-website/src/pages/docs/directives-reference/internal-operation-directive.md
> +This directive is deprecated. Operations are now automatically marked internal when inside a folder named _internal_ (even if nested).
Could you add a directory example?

2023-04-05 13:19 UTC, StarpTech commented on packages/sdk/src/graphql/operations.ts
> +							Logger.warn(
Why should we warn about this a second time?

2023-04-05 13:21 UTC, StarpTech commented on packages/sdk/src/graphql/operations.ts
> +							Logger.warn(
Never mind, I didn't see that you warned about different operation types.

2023-04-05 13:33 UTC, StarpTech commented on packages/sdk/src/graphql/operations.ts
> +						operation.Internal = internalOperationDirective || RegExp(internalPathRegex).test(operationFile.file_path);
You don't need a regex. Search for `/internal` in the path.

2023-04-05 13:35 UTC, Aenimus commented on packages/sdk/src/graphql/operations.ts
> +export const internalPathRegex = '.*\\/?internal\\/.*';
@StarpTech searching for /internal/ doesn't work. It must be either the start of the string or be preceded by `/`

2023-04-05 13:39 UTC, devsergiy requested changes

2023-04-05 13:39 UTC, devsergiy commented on packages/sdk/src/graphql/operations.test.ts
> +	const internalPaths = ['internal/foo.ts', 'internal/bar.graphql', 'nested/internal/bat.ts'];
false positive
```
hellointernal/bob
```

2023-04-05 13:39 UTC, devsergiy commented on packages/sdk/src/graphql/operations.test.ts
> +	const internalPaths = ['internal/foo.ts', 'internal/bar.graphql', 'nested/internal/bat.ts'];
and what about windows? on windows, we will have opposite slashes

2023-04-05 13:47 UTC, devsergiy commented
@thisisnithin could you also extend a tests in the default test app?

https://github.com/wundergraph/wundergraph/blob/a2c94f6b081f8ed3d3f2df2e9bf605fa1278713d/testapps/default/test/index.test.ts#L14

2023-04-05 13:52 UTC, fiam reviewed
Great job. The most important thing is avoiding exposing a regex for testing whether an operation is internal, the rest is mostly nitpicking.

2023-04-05 13:52 UTC, fiam commented on packages/sdk/src/graphql/operations.ts
> +export const internalPathRegex = '.*\\/?internal\\/.*';
Wrap this into a function instead of exposing a regex, please.

2023-04-05 13:52 UTC, fiam commented on docs-website/src/pages/docs/directives-reference/internal-operation-directive.md
> +This directive is deprecated. Operations are now automatically marked internal when inside a folder named _internal_ (even if nested).
`folder` => `directory`, please. I know Windows makes this confusing, but they're not the same. A folder can be something virtual (e.g. a "smart folder" from live search results)

2023-04-05 18:16 UTC, devsergiy approved these changes

2023-04-05 18:57 UTC, StarpTech commented on packages/sdk/src/graphql/operations.test.ts
> +	const internalPaths = ['internal/foo.ts', 'internal/bar.graphql', 'nested/internal/bat.ts'];
I think you can parse the path to normalize and do the check then.

2023-04-05 18:59 UTC, StarpTech commented
How does the user identify an internal operation in the clients? Did you test it?

2023-04-05 19:11 UTC, StarpTech commented
Missing marketing notes for Stefan.

2023-04-05 19:11 UTC, StarpTech approved these changes
LGTM but please add marketing notes.

2023-04-06 07:49 UTC, jensneuse requested changes

2023-04-06 07:49 UTC, jensneuse commented on examples/learn-wundergraph/.wundergraph/operations/users/internal/getAdminUser.ts
> +import { createOperation, z } from '../../../generated/wundergraph.factory';
You set the path as "internal", but the docs state to use "_internal_". What's correct? "_internal_" sounds good to me, but you can also stay with "internal". If you go with "_internal_", calling an operation will look a bit weird.

2023-04-06 07:49 UTC, jensneuse commented on packages/sdk/src/graphql/operations.ts
> +export const isInternalOperationByPath = (path: string) => {
Here's an alternative:

```typescript
function containsInternalPathElement (filePath: string): bool {
  // Determine the directory separator based on the platform
  const separator = process.platform === 'win32' ? '\\' : '/';

  // Split the file path by the directory separator
  const elements = filePath.split(separator);

  // Remove the last element (the file name)
  elements.pop();

  // check if the resulting array contains internal
  return elements.includes('internal');
}
```

2023-04-06 07:49 UTC, jensneuse commented on testapps/default/test/index.test.ts
> +		for (let ii = 0; ii < 50; ii++) {
What's this good for?

2023-04-06 08:33 UTC, thisisnithin commented on testapps/default/test/index.test.ts
> +		for (let ii = 0; ii < 50; ii++) {
There was a comment by Alberto above. Updated it here as well.

2023-04-06 08:34 UTC, thisisnithin commented on packages/sdk/src/graphql/operations.ts
> +export const isInternalOperationByPath = (path: string) => {
Cleaner, I like it. Updated test to include windows paths as well.

2023-04-06 08:35 UTC, thisisnithin commented on examples/learn-wundergraph/.wundergraph/operations/users/internal/getAdminUser.ts
> +import { createOperation, z } from '../../../generated/wundergraph.factory';
This is clarified.

2023-04-06 08:37 UTC, jensneuse approved these changes

2023-04-06 08:52 UTC, Aenimus approved these changes

2023-04-06 09:21 UTC, fiam approved these changes
LGTM

2023-04-06 09:28 UTC, merged