feat: sveltekit & vite-svelte examples
wundergraph/wundergraph pull request #805
Opened 2023-04-06 07:05 UTC by DaniAkash

## Motivation and Context

This PR continues the work done for Svelte Query Client in https://github.com/wundergraph/wundergraph/pull/683 by adding examples & SSR support for sveltekit. This moves the code in [Wundergraph Client for sveltekit](https://github.com/DaniAkash/wundergraph-svelte-query) to the examples folder

## Marketing Changelog

WunderGraph will now have example templates for SvelteKit & Svelte projects created with vite!

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-06 08:21 UTC, fiam commented on examples/sveltekit/.gitignore
> +vite.config.ts.timestamp-*
Duplicated line in .gitignore

2023-04-06 08:23 UTC, Pagebakers requested changes
Please add links to the examples in the READ.md and also in the docs website examples index and menu

2023-04-06 08:23 UTC, Pagebakers commented on examples/sveltekit/package.json
> +	"name": "sveltekit",
`wundergraph-sveltekit`, we prefix all examples.

2023-04-06 08:23 UTC, Pagebakers commented on examples/sveltekit/src/routes/about/+page.svelte
> +	<pre>npm create svelte@latest</pre>
Use the create-wundergraph-app command here with --example sveltekit

2023-04-06 08:23 UTC, Pagebakers commented on examples/sveltekit/src/routes/about/+page.svelte
> +		This is a <a href="https://kit.svelte.dev">SvelteKit</a> app. You can make your own by typing the
with a WunderGraph backend

2023-04-06 08:23 UTC, Pagebakers commented on examples/sveltekit/src/routes/sverdle/+page.server.ts
> +	const game = new Game(cookies.get('sverdle'));
would be nice if you could implement this with ts operations for example, instead of the default users examples.

2023-04-06 08:23 UTC, Pagebakers commented on examples/sveltekit/src/lib/wundergraph/wundergraph.ts
> +import { createSvelteClient } from '@wundergraph/svelte-query';
you can name this file index.ts you can import from lib/wundergraph instead of wundergraph/wundergraph

2023-04-06 08:23 UTC, Pagebakers commented on examples/vite-svelte/package.json
> +  "name": "vite-svelte",
wundergraph-vite-svelte

2023-04-06 08:23 UTC, Pagebakers commented on packages/svelte-query/src/lib/createSvelteClient.ts
> +	const prefetchQuery: PrefetchQuery<Operations> = (options, queryClient) => {
Nice we should include this in the lib, there is an PR open to implement this, we can probably mix this together and release it.

2023-04-06 08:25 UTC, fiam commented
Please, take a look at this [README](https://github.com/wundergraph/wundergraph/blob/main/examples/README.md) to check the conventions the example scripts must follow. Otherwise, CI won't pass. Thanks!

2023-04-06 13:02 UTC, DaniAkash commented on packages/svelte-query/src/lib/createSvelteClient.ts
> +	const prefetchQuery: PrefetchQuery<Operations> = (options, queryClient) => {
Do I have to open a separate PR for this?

2023-04-09 09:20 UTC, DaniAkash commented on examples/sveltekit/src/routes/sverdle/+page.server.ts
> +	const game = new Game(cookies.get('sverdle'));
@Pagebakers due to an issue with the autogenerated `wundergraph.factory.ts` file when used along with sveltekit, i'm unable to use the default users example. will create a detailed issue details in our internal tracker

2023-04-10 07:03 UTC, DaniAkash commented
> Please add links to the examples in the READ.md and also in the docs website examples index and menu

@Pagebakers the docs website & README.md have been updated! 🎉

2023-04-11 07:23 UTC, Pagebakers requested changes
One little detail left, then it LGTM

2023-04-11 07:23 UTC, Pagebakers commented on docs-website/src/pages/docs/getting-started/sveltekit-quickstart.md
> +```
Can you use Learn more as the last section and link to the SvelteKit client reference, and also to the sveltekit docs.

2023-04-11 07:23 UTC, Pagebakers commented on packages/svelte-query/src/lib/createSvelteClient.ts
> +	const prefetchQuery: PrefetchQuery<Operations> = (options, queryClient) => {
Looks like it's included already now  👍

2023-04-11 07:35 UTC, DaniAkash commented on examples/sveltekit/src/routes/sverdle/+page.server.ts
> +	const game = new Game(cookies.get('sverdle'));
Temporarily excluding this issue

2023-04-11 08:07 UTC, DaniAkash commented on docs-website/src/pages/docs/getting-started/sveltekit-quickstart.md
> +```
done

2023-04-11 08:09 UTC, Pagebakers approved these changes

2023-04-11 08:12 UTC, StarpTech approved these changes
LGTM, core changes looks good. Anything else can be improved over time.

2023-04-11 08:24 UTC, merged