feat: vue-query client
wundergraph/wundergraph pull request #809
Opened 2023-04-06 14:09 UTC by Hebilicious

## Motivation and Context

Wundergraph have support for React, Svelte and Solid Tanstack query, but not for Vue. This PR adds support for Vue-Query.

## Marketing Changelog

This PR adds a new package `vue-query`.

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

I'm waiting on reviews/CI before touching anything outside the newly created directory.

This probably needs some tidy-up before being good to go, waiting on your feedback!

2023-04-06 14:19 UTC, Pagebakers requested changes
Amazing work, thank a bunch for opening a PR.

A few minor issues that I noticed.

2023-04-06 14:19 UTC, Pagebakers commented on packages/vue-query/src/hooks.ts
> +		// const onSuccessRef = ref(onSuccess);
Do we need this?

2023-04-06 14:19 UTC, Pagebakers commented on packages/vue-query/src/hooks.ts
> +				console.log('Enabled !');
Whoops

2023-04-06 14:19 UTC, Pagebakers commented on packages/vue-query/src/hooks.ts
> +			console.log('Mounted Subscriber', queryHash);
Whoopsie

2023-04-06 15:49 UTC, Hebilicious commented
> Amazing work, thank a bunch for opening a PR.
> 
> A few minor issues that I noticed.

Fixed these. What would be the next steps ?

From the top of my head : 
-  Update docs with support framework
- 1 example with vite/vue/vue-query/wundegraph-vue-query
- A nuxt module (The module itself is quite trivial, as much of the work is done here, but I'm not sure if that should be in the same package)

2023-04-07 02:58 UTC, DaniAkash commented
> > Amazing work, thank a bunch for opening a PR.
> > A few minor issues that I noticed.
> 
> Fixed these. What would be the next steps ?
> 
> From the top of my head :
> 
> * Update docs with support framework
> * 1 example with vite/vue/vue-query/wundegraph-vue-query
> * Some info for nuxt users (Setting everything together can be a little fiddly)
> 
> Maybe adding @DamianOsipiuk to the thread should be useful as he maintains the vue-query package

A [Nuxt 3 SSR](https://tanstack.com/query/v4/docs/vue/guides/ssr#nuxt-3) example would be great for Nuxt users!

2023-04-07 10:22 UTC, Hebilicious commented
> > > Amazing work, thank a bunch for opening a PR.
> > > A few minor issues that I noticed.
> > 
> > 
> > Fixed these. What would be the next steps ?
> > From the top of my head :
> > 
> > * Update docs with support framework
> > * 1 example with vite/vue/vue-query/wundegraph-vue-query
> > * Some info for nuxt users (Setting everything together can be a little fiddly)
> > 
> > Maybe adding @DamianOsipiuk to the thread should be useful as he maintains the vue-query package
> 
> A [Nuxt 3 SSR](https://tanstack.com/query/v4/docs/vue/guides/ssr#nuxt-3) example would be great for Nuxt users!

Added a Nuxt 3 example based on the React Query example.

![Kapture 2023-04-07 at 17 16 06](https://user-images.githubusercontent.com/13395944/230592080-3297e359-5064-40a4-a0fe-e3f9f9fa498c.gif)

I add some issues with the resolution of @wundergraph/sdk and had to modify the workspace configuration locally, this shouldn't be the case when the packages are imported from npm though.

2023-04-07 11:22 UTC, Pagebakers commented
Great stuff!

Regarding the docs

- Add the examples to the main README.md
- Add the examples to the examples in the docs: https://docs.wundergraph.com/docs/getting-started
- Add a new section in the clients reference for the `Vue Query` client. See: https://docs.wundergraph.com/docs/clients-reference/solid-query

You can adjust the docs navigation in navigation.jsx under `docs-website` the pages are added as .md files the `pages` folder. Let me know if you need help with this.

2023-04-08 06:53 UTC, Hebilicious commented
Added docs. The docs could use some love though, it's currently a bit tedious :

- All navigation links should be generated from the frontmatter in the markdown files (href, title, logo etc)
- Remove duplicate information : I followed the Next pages to creates the Nuxt ones, it looks like roughly the same information is duplicated across the board... Here's a list of all the md files added  

     - Supported Frontend Framework Vue 
     - Supported Frontend Framework Nuxt 
     - Client Reference Vue-Query
     - Getting Started Nuxt Quickstart
     - Getting Started Nuxt (Empty because the others were empty too)
     - Examples Nuxt
    
Some suggestions from the top of my head : 

- The Examples could just be the README.md of the \/examples, and not duplicated in docs-website/examples. They should also all be the ones used in the cloud templates. 
- The client reference could be the README from the packages too
- The supported frontend frameworks and the quickstart should be connected, for example the quickstart page could explain how to clone the relevant example, then explain how to add wundergraph to an existing project, then it should link to the 3 other pages : Supported framework nuxt, Client reference, example
- Navigation could have some horizontals sections to declutter the vertical navigation on the left : All client references and examples could moved to a top navigation, Database/Supported datasources could be merged/switched up etc

2023-04-10 15:45 UTC, Hebilicious commented
@Pagebakers What would be the next steps ?

2023-04-11 07:42 UTC, Pagebakers commented
@Hebilicious Thanks a lot for your comments on the docs website, very helpful.

We'll do another review and test the apps and then we should be ready to merge this in later this week 👍

> The Examples could just be the README.md of the /examples, and not duplicated in docs-website/examples. They could also be just a Stackblitz/Codesandbox with the /examples/example-name repo loaded, and deployable in the cloud.
Examples will get an complete separate section on the website, including screenshots, etc, more like a marketplace.

> The client reference could be the README from the packages too
The markdown format is a bit different and I don't think we can include these external paths easily. Perhaps a symlink can work.

> The supported frontend frameworks and the quickstart should be connected, for example the quickstart page could explain how to clone the relevant example, then explain how to add wundergraph to an existing project, then it should link to the 3 other pages : Supported framework nuxt, Client reference, example
Good idea

> Navigation could have some horizontals sections to declutter the vertical navigation on the left : All client references and examples could moved to a top navigation, Database/Supported datasources could be merged/switched up etc
This is something we can consider indeed. Merging the db/datasources is a good idea, we were planning to do this already.

2023-04-11 08:06 UTC, Hebilicious commented on docs-website/src/pages/getting-started/nuxt.md
> +---
I don't know what's the purpose of the file in this directory as they're all empty, so I added it because the others were here. Was hoping you could tell me what they are for ? Can remove them if they're useless.

2023-04-11 08:08 UTC, Pagebakers requested changes

2023-04-11 08:08 UTC, Pagebakers commented on packages/vue-query/package.json
> +  "version": "0.1.1",
Set to 0.0.1

2023-04-11 08:08 UTC, Pagebakers commented on examples/nuxt/package.json
> +    "@wundergraph/vue-query": "workspace:*",
You can set this to ^0.0.1 and also update vue-query version

2023-04-11 08:09 UTC, Hebilicious commented on examples/nuxt/.npmrc
> +shamefully-hoist=true
Yes this is required for Nuxt until [this](https://github.com/nuxt/nuxt/issues/14146) get resolved. I think in the next minor version ?

2023-04-11 08:21 UTC, Pagebakers commented
I had to remove the .npmrc file with hoisting settings and install `"@unhead/vue": "^1.1.25",`  to make it work locally.

2023-04-11 08:23 UTC, Pagebakers commented on docs-website/src/pages/getting-started/nuxt.md
> +---
Ah, yeah these are still placeholder, that actually got replaced by the quickstarts. You don't need to include it.

2023-04-11 09:05 UTC, Hebilicious commented
> I had to remove the .npmrc file with hoisting settings and install `"@unhead/vue": "^1.1.25",` to make it work locally.

I don't like the hoisting settings either, but I think it's safer to remove it once Nuxt support it officially. For now it's a little bit fiddly, ie you might have to import more packages depending on what's in your pnpm cache or not.

> The markdown format is a bit different and I don't think we can include these external paths easily. Perhaps a symlink can work.
Symlink could work, but this could be achieved with a simple script that would copy the markdown from the packages, README.md could run manually or as a pre-commit hook/build hook etc. As more packages are added it keeps everything in sync and avoid duplications. But it might be a little heavy handed.

2023-04-11 09:18 UTC, DaniAkash commented
@Hebilicious awesome work with the Nuxt example! You can add Nuxt to our homepage in [website](https://github.com/wundergraph/website) repo (Refer our recent [sveltekit release](https://github.com/wundergraph/website/pull/184))

2023-04-11 10:10 UTC, Hebilicious commented
> @Hebilicious awesome work with the Nuxt example! You can add Nuxt to our homepage in [website](https://github.com/wundergraph/website) repo (Refer our recent [sveltekit release](https://github.com/wundergraph/website/pull/184))

I'm getting a 404 trying to access it, is it a private repo ?

2023-04-11 11:01 UTC, Pagebakers commented
> > @Hebilicious awesome work with the Nuxt example! You can add Nuxt to our homepage in [website](https://github.com/wundergraph/website) repo (Refer our recent [sveltekit release](https://github.com/wundergraph/website/pull/184))
> 
> I'm getting a 404 trying to access it, is it a private repo ?

Yeah it's private, I'll add it once everything is ready 👍

2023-04-11 11:04 UTC, Pagebakers commented
> I don't like the hoisting settings either, but I think it's safer to remove it once Nuxt support it officially. For now it's a little bit fiddly, ie you might have to import more packages depending on what's in your pnpm cache or not.

Hmm but the issue only applies to when you run it inside our PNPM monorepo right? or is this a known incompatibility between Nuxt an PNPM, also in regular repos?

2023-04-11 11:26 UTC, Hebilicious commented
> > I don't like the hoisting settings either, but I think it's safer to remove it once Nuxt support it officially. For now it's a little bit fiddly, ie you might have to import more packages depending on what's in your pnpm cache or not.
> 
> Hmm but the issue only applies to when you run it inside our PNPM monorepo right? or is this a known incompatibility between Nuxt an PNPM, also in regular repos?

The latter, should be fixed soon though, as the Nuxt team mentioned it [recently](https://nuxt.com/blog/v3-3#%EF%B8%8F-build-changes). I referenced the issue below one of your comments

2023-04-13 11:20 UTC, Pagebakers approved these changes
Let's get it merged in.

BTW would it make sense to make release the plugin boilerplate into an official vue plugin? or is it best practise to define the plugin (with vue query) in the project?

2023-04-13 11:22 UTC, DaniAkash approved these changes

2023-04-13 11:55 UTC, merged

2023-04-13 13:48 UTC, Pagebakers commented
Released! Great work @Hebilicious thank you 🙌
https://www.npmjs.com/package/@wundergraph/vue-query

2023-04-13 14:08 UTC, Hebilicious commented
> Let's get it merged in.
> 
> BTW would it make sense to make release the plugin boilerplate into an official vue plugin? or is it best practise to define the plugin (with vue query) in the project? 

🚀🚀🚀 Because it relies on vue-queey, releasing like this is the most 'universal' Vue way imo, but a Nuxt plugin might be something desirable down the road