feat: implement internal graphql handler
wundergraph/wundergraph pull request #853
Opened 2023-04-17 17:07 UTC by thisisnithin

## Motivation and Context

There is a need for a graphql handler to be mounted for internal operations. This also helps fix a vulnerability where internal operations were exposed through the public router by having a new router running in a different port.

## Marketing Changelog

Internal operations now have a `/graphql` endpoint when enabled. A vulnerability where internal operations were exposed to the public has also been patched as a result.

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-18 15:42 UTC, StarpTech requested changes
You have covered almost all the places. Great PR.

2023-04-18 15:42 UTC, StarpTech commented on packages/sdk/src/testing/index.ts
> +				WG_NODE_INTERNAL_PORT: internalNodePort.toString(),
Please also update the docs.

2023-04-18 15:42 UTC, StarpTech commented on pkg/apihandler/internalapihandler.go
> +		if operation.Internal {
Why should we register internal operations on the public router?

2023-04-18 15:42 UTC, StarpTech commented on pkg/apihandler/internalapihandler.go
> +		if operation.Internal {
Here too

2023-04-18 15:42 UTC, StarpTech commented on pkg/node/config.go
> +		Host: "localhost",
We should use the same host as the node.

2023-04-18 15:42 UTC, StarpTech commented on pkg/node/node.go
> +			n.log.Info(fmt.Sprintf("Internal node listening at http://%s", l.Addr().String()))
I'd not log it as info. The internal server is private and implementation detail.

2023-04-18 15:42 UTC, StarpTech commented on pkg/node/node_test.go
> +	ports, err := freeport.GetFreePorts(2)
:+1:

2023-04-18 15:42 UTC, StarpTech commented on packages/sdk/src/server/internal-client.ts
> +		const url = `${baseNodeUrl}/operations/${options.operationName}`;
What is baseNodeUrl? It should point to the node host and contain the internal port.

2023-04-18 15:42 UTC, StarpTech commented on packages/sdk/src/server/internal-client.ts
> -		const url = `${baseNodeUrl}/internal/operations/${options.operationName}`;
The `packages/sdk/src/server/operations-client.ts` also has a reference to `/internal`

2023-04-18 15:45 UTC, StarpTech requested changes

2023-04-18 15:45 UTC, StarpTech commented on packages/sdk/src/testing/index.ts
>  		let nodePort = await this.freeport();
You can acquire all of them concurrently with `Promise.all`

2023-04-18 15:46 UTC, StarpTech requested changes

2023-04-18 15:46 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +	InternalNodePort = 'WG_NODE_INTERNAL_PORT',
NodeInternalPort instead InternalNodePort?

2023-04-18 15:47 UTC, StarpTech requested changes

2023-04-18 15:47 UTC, StarpTech commented on pkg/apihandler/apihandler.go
> -			ctx.Variables, _, _, _ = jsonparser.Get(variablesBuf.Bytes(), "input")
Where did you re-add it? I can't find it.

2023-04-18 18:11 UTC, thisisnithin commented on packages/sdk/src/configure/options.ts
> +export const defaultInternalNodePort = '9994';
Using 9993 now

2023-04-18 18:12 UTC, thisisnithin commented on packages/sdk/src/testing/index.ts
> +				WG_NODE_INTERNAL_PORT: internalNodePort.toString(),
Done

2023-04-18 18:14 UTC, StarpTech commented on pkg/apihandler/internalapihandler.go
> +		if operation.Internal {
Nevermind, I read it wrong. Public ops are registered on the public and internal. Thats fine.

2023-04-18 18:14 UTC, thisisnithin commented on pkg/apihandler/internalapihandler.go
> +		if operation.Internal {
It is the internal router, this is in `internalapihandler.go`. The log is added since we dont log registering internal operations in public api handler.

2023-04-18 18:14 UTC, thisisnithin commented on pkg/apihandler/internalapihandler.go
> +		if operation.Internal {
Explained in the above comment

2023-04-18 18:15 UTC, thisisnithin commented on pkg/node/node.go
> +			n.log.Info(fmt.Sprintf("Internal node listening at http://%s", l.Addr().String()))
Logging it as debug instead.

2023-04-18 18:15 UTC, thisisnithin commented on packages/sdk/src/server/internal-client.ts
> +		const url = `${baseNodeUrl}/operations/${options.operationName}`;
It does. I pass the url containing internal port to the factory

2023-04-18 18:16 UTC, thisisnithin commented on packages/sdk/src/server/internal-client.ts
> -		const url = `${baseNodeUrl}/internal/operations/${options.operationName}`;
Thanks, missed it. Fixed.

2023-04-18 18:16 UTC, thisisnithin commented on packages/sdk/src/testing/index.ts
>  		let nodePort = await this.freeport();
Done

2023-04-18 18:16 UTC, thisisnithin commented on packages/sdk/src/configure/options.ts
> +	InternalNodePort = 'WG_NODE_INTERNAL_PORT',
Done

2023-04-18 18:17 UTC, StarpTech commented on packages/sdk/src/server/internal-client.ts
> +		const url = `${baseNodeUrl}/operations/${options.operationName}`;
Great!

2023-04-18 18:21 UTC, thisisnithin commented on pkg/apihandler/apihandler.go
> -			ctx.Variables, _, _, _ = jsonparser.Get(variablesBuf.Bytes(), "input")
I think it is handled [here](https://github.com/wundergraph/wundergraph/blob/nithin/eng-1835-implement-internal-graphql-handler/pkg/apihandler/internalapihandler.go#L351).

2023-04-19 09:08 UTC, thisisnithin commented on packages/sdk/src/server/server.ts
> +			const nodeUrl = fallbackNodeUrl({
Done.

2023-04-19 10:11 UTC, StarpTech requested changes

2023-04-19 10:11 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +				nodeInternalUrl: new EnvironmentVariable(WgEnv.NodeInternalUrl, fallbackNodeInternalUrl(options)),
Did you test the setup with different overwrites in `wundergraph.config.ts` and `wundergraph.server.ts` + WG_* environment variables? (Also try in watch mode)

Is there a reason why you made the internal URL configurable? It should always be in sync with the nodeUrl because running the internal server on a different host is not required.

2023-04-19 10:14 UTC, fiam commented on packages/testsuite/apps/hooks/index.test.ts
> +		expect(directResult.error).toBe(undefined);
Maybe `expect(directResult.error).toBeUndefined()` looks clearer? Same for the test on the next line.

2023-04-19 10:17 UTC, fiam commented on pkg/node/config.go
> +			return nil, fmt.Errorf("can't parse internal node port %q: %w", graphConfig.Api.NodeOptions.ListenInternal.Port, err)
You want the second argument here to be ``rawInternalNodePort` not `graphConfig.Api.NodeOptions.ListenInternal.Port`

2023-04-19 10:28 UTC, thisisnithin commented on packages/sdk/src/configure/options.ts
> +				nodeInternalUrl: new EnvironmentVariable(WgEnv.NodeInternalUrl, fallbackNodeInternalUrl(options)),
I had a conversation with @fiam regarding this. Right now dynamically creating the URL from other envs doesn't seem to be viable. The config JSON is always written with default values. The only other solution is how I was doing it before, constructing it during runtime and not in the config step. [Here](https://linear.app/wundergraph/issue/ENG-1917/consider-dropping-host-and-port-variables) is the related issue. So right now it is left for the user to ensure that all variables are in sync.

I have tested it with overrides.

2023-04-19 10:32 UTC, thisisnithin commented on packages/testsuite/apps/hooks/index.test.ts
> +		expect(directResult.error).toBe(undefined);
Done

2023-04-19 10:32 UTC, thisisnithin commented on pkg/node/config.go
> +			return nil, fmt.Errorf("can't parse internal node port %q: %w", graphConfig.Api.NodeOptions.ListenInternal.Port, err)
Done

2023-04-19 10:33 UTC, fiam approved these changes
Great job - LGTM

2023-04-19 10:52 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +				nodeInternalUrl: new EnvironmentVariable(WgEnv.NodeInternalUrl, fallbackNodeInternalUrl(options)),
Great point; I came to the same conclusion after https://github.com/wundergraph/wundergraph/pull/840

2023-04-19 10:52 UTC, StarpTech approved these changes
Well done! LGTM

2023-04-19 12:31 UTC, merged