feat: add support for using proxies in data sources
wundergraph/wundergraph pull request #854
Opened 2023-04-17 20:00 UTC by fiam

## Motivation and Context

In some environments, it's desirable for the WunderGraph node to only talk to the public Internet using intermediate machines (security, accountability, logging, etc..). To support these use cases, we now allow setting a global HTTP(S)
proxy that will be used when querying the data sources. Additionally, the global proxy can be overridden on a per-source basis.

## Marketing Changelog

WunderGraph can now use an HTTP(S) proxy to talk to its connected APIs.

2023-04-18 09:57 UTC, StarpTech requested changes

2023-04-18 09:57 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +	defaultHttpProxyUrl?: InputVariable;
Two things I couldn't find in this PR.

1. Did you cover the introspection HTTP client as well?
2. It should be possible for cloud that our environment variable precedes the users.

2023-04-18 09:57 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +	ProxyUrl = 'WG_PROXY_URL',
Can we call it `WG_HTTP_PROXY` it's more concret.

2023-04-18 09:57 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +  defaultHttpProxyUrl: ConfigurationVariable | undefined;
Why do you prefix it with `default` ?

2023-04-18 09:57 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +  proxyUrl: ConfigurationVariable | undefined;
Here as well. `httpProxyUrl`

2023-04-18 10:06 UTC, fiam commented on packages/protobuf/wgpb/wundernode_config.ts
> +  defaultHttpProxyUrl: ConfigurationVariable | undefined;
This is the default for all data sources, then each data source can override it

2023-04-18 10:10 UTC, fiam commented on packages/sdk/src/configure/options.ts
> +	defaultHttpProxyUrl?: InputVariable;
1 - No, the issue only mentioned the Go side, but you make a good point. I think this is not going to be very useful if we don't support both the Go and the TS sides
2 - Should we always override it with an environment variable we control?

2023-04-18 10:19 UTC, StarpTech commented on packages/sdk/src/configure/options.ts
> +	defaultHttpProxyUrl?: InputVariable;
2) Yes, the same as it works with WG_NODE_PORT etc...

2023-04-18 10:21 UTC, fiam commented on packages/sdk/src/configure/options.ts
> +	defaultHttpProxyUrl?: InputVariable;
I was already overridden with `WG_PROXY_URL` when running in cloud, so renaming it to `WG_HTTP_PROXY_URL` should cover that. Keeping the conversation unresolved until I handle point 1.

2023-04-18 10:21 UTC, fiam commented on packages/protobuf/wgpb/wundernode_config.ts
> +  proxyUrl: ConfigurationVariable | undefined;
Thanks. Renamed.

2023-04-18 10:24 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +  defaultHttpProxyUrl: ConfigurationVariable | undefined;
Ah ok, ty.

2023-04-18 16:37 UTC, fiam commented on packages/sdk/src/configure/options.ts
> +	defaultHttpProxyUrl?: InputVariable;
I've added support for using proxies during introspection in the previous to last commit. I'll ask for a re-review once the tests are in, no rush for now.

2023-04-18 17:55 UTC, StarpTech commented on packages/sdk/src/definition/graphql-introspection.ts
> +			throw new Error(`invalid HTTP proxy URL '${proxyUrlString}': ${e}`);
Can we be more specific about the datasource?

2023-04-18 20:02 UTC, fiam commented on packages/sdk/src/definition/graphql-introspection.ts
> +			throw new Error(`invalid HTTP proxy URL '${proxyUrlString}': ${e}`);
I've added the upstream URL to the message

2023-04-19 12:31 UTC, StarpTech requested changes

2023-04-19 12:31 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +export type ApiIntrospector<T> = (options: ApiIntrospectionOptions) => Promise<Api<T>>;
What was the reason for introducing it?

2023-04-19 12:39 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +export type ApiIntrospector<T> = (options: ApiIntrospectionOptions) => Promise<Api<T>>;
To document a bit better what the introspect.something() are expected to return

2023-04-19 12:41 UTC, fiam commented on packages/sdk/src/configure/index.ts
> +export type ApiIntrospector<T> = (options: ApiIntrospectionOptions) => Promise<Api<T>>;
Re-reading it, maybe you were asking why we changed the return type. It was to be able to pass some data to the introspection functions (specifically, the global proxy to use, but we can extend that if needed)

2023-04-19 12:43 UTC, fiam commented
Just noticed that some of the code that generates snapshots needs to be updated

2023-04-19 12:54 UTC, fiam commented
> Just noticed that some of the code that generates snapshots needs to be updated

Updated

2023-04-19 18:08 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +export type ApiIntrospector<T> = (options: ApiIntrospectionOptions) => Promise<Api<T>>;
Alright thanks.

2023-04-19 18:08 UTC, StarpTech approved these changes
Great! LGTM

2023-04-19 21:42 UTC, fiam commented
@StarpTech I know you already approved this, but I added a test using a local proxy as well as a workaround for supporting HTTPS over HTTP proxies (due to a bug in axios). If possible, PTAL. Thanks!

2023-04-20 08:53 UTC, StarpTech requested changes

2023-04-20 08:53 UTC, StarpTech commented on packages/testsuite/apps/generation/index.test.ts
> +		process.env.WG_HTTP_PROXY = invalidProxy;
Can we extend the client in a way that this is configurable through the interface instead env?

2023-04-20 08:53 UTC, StarpTech commented on packages/testsuite/apps/generation/test-setup.ts
> +export default async function () {
This is not necessary when you generate in the test.

2023-04-20 08:53 UTC, StarpTech commented on packages/testsuite/apps/generation/docker-compose.yml
> +services:
What prevents us from starting a http server with node.js in the tests instead starting a container?

2023-04-20 09:04 UTC, fiam commented on packages/testsuite/apps/generation/test-setup.ts
> +export default async function () {
We do for the initial imports

2023-04-20 09:14 UTC, fiam commented on packages/testsuite/apps/generation/docker-compose.yml
> +services:
It doesn't support CONNECT for sending requests to HTTPS hosts through HTTP proxies

2023-04-20 09:19 UTC, StarpTech commented on packages/testsuite/apps/generation/docker-compose.yml
> +services:
For reference: https://github.com/berstend/straightforward

2023-04-20 10:19 UTC, fiam commented on packages/testsuite/apps/generation/docker-compose.yml
> +services:
Looking into it, thanks!

2023-04-20 10:42 UTC, fiam commented on packages/testsuite/apps/generation/index.test.ts
> +		process.env.WG_HTTP_PROXY = invalidProxy;
I'm now passing them through the functions instead of using `process.env` PTAL

2023-04-20 10:42 UTC, fiam commented on packages/testsuite/apps/generation/docker-compose.yml
> +services:
Replaced the container with [berstend/straightforward](https://github.com/berstend/straightforward). It's significantly faster now. Great idea!

2023-04-20 11:23 UTC, fiam commented
@StarpTech @jensneuse I've addressed the requested changes and I've also added a new guide. PTAL. Thanks!

2023-04-20 11:31 UTC, StarpTech commented on packages/testsuite/apps/generation/index.test.ts
> +	if (!proxyFromEnvironment) {
Why is it configurable?

2023-04-20 11:31 UTC, StarpTech commented on packages/testsuite/apps/generation/index.test.ts
> +			await regenerate({
Can't we make it part of a beforeEach?

2023-04-20 12:01 UTC, jensneuse commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +well as when performing operations. This affects APIs that are transported through HTTP,
I'd rephrase this somehow to "...proxies for both introspection and to make HTTP requests at runtime".

2023-04-20 12:02 UTC, jensneuse commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +server, WunderGraph will open an socket using and HTTP CONNECT request.
"a socket"

2023-04-20 12:03 UTC, jensneuse commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +All data sources that use HTTP a transport have an `httpProxyUrl` field that can be set when
"that use a HTTP transport"

2023-04-20 12:04 UTC, jensneuse commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +  httpProxyUrl: 'http://my.proxy.server:3128',
Should we name this httpProxyURL or just proxyURL?
In any case, I'd suggest to use URL instead or Url.

2023-04-20 12:24 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +	const resolvedApis = await Promise.all(generators.map((generator) => generator(apiIntrospectionOptions)));
Why async twice? Feels weird. Is the creation of the generator async?

2023-04-20 12:28 UTC, jensneuse commented on packages/testsuite/apps/generation/index.test.ts
> +const localProxyPort = 3138;
Should we use freeport() here?

2023-04-21 09:21 UTC, fiam commented on packages/testsuite/apps/generation/index.test.ts
> +const localProxyPort = 3138;
Not worth it IMHO. The `freeport` package doesn't support promises and I would need to write our own function (like we did for the testing SDK). This is only used for testing, so it should only matter in environments we control. Additionally, 3128 (I'll fix the number) is Squid's default port and unlikely to be used by something else.

2023-04-21 09:23 UTC, fiam commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +  httpProxyUrl: 'http://my.proxy.server:3128',
Last time this came up we agreed to use this convention for TypeScript/Javascript https://google.github.io/styleguide/jsguide.html#naming-camel-case-defined - According to that, it would be `Url` - I know in the Go side it would be `URL`. Regarding the full name, the initial draft had it as `proxyUrl` but it was requested that I changed it to `httpProxyUrl`. I don't have a strong opinion on that and I mind changing it back, you just need to make a deal with @StarpTech :-)

2023-04-21 09:24 UTC, fiam commented on packages/testsuite/apps/generation/index.test.ts
> +			await regenerate({
Not all tests run regenerate with the same arguments, and some don't run it at all.

2023-04-21 09:25 UTC, fiam commented on packages/testsuite/apps/generation/index.test.ts
> +	if (!proxyFromEnvironment) {
In case you want to spin up a separate proxy and test against it. It's handy if you have to debug something (like it happened with Axios not support CONNECT)

2023-04-21 09:29 UTC, fiam commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +All data sources that use HTTP a transport have an `httpProxyUrl` field that can be set when
Updated, PTAL

2023-04-21 09:29 UTC, fiam commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +server, WunderGraph will open an socket using and HTTP CONNECT request.
Updated

2023-04-21 09:30 UTC, fiam commented on packages/testsuite/apps/generation/index.test.ts
> +const expectQuerySuccess = async (env: Record<string, string>) => {
I've moved them to a separate file, PTAL

2023-04-21 09:36 UTC, StarpTech commented on docs-website/src/pages/docs/guides/using-http-proxies.md
> +  httpProxyUrl: 'http://my.proxy.server:3128',
How do we name things right now? Do we already uppercase acronyms? If not, I'd not follow that convention because it's not common in javascript ecosystem as alberto pointed out with that example.

2023-04-21 09:38 UTC, StarpTech commented on packages/testsuite/apps/generation/index.test.ts
> +	if (!proxyFromEnvironment) {
ok

2023-04-21 09:38 UTC, StarpTech commented on packages/testsuite/apps/generation/index.test.ts
> +			await regenerate({
You can group those again in `describe` to separate them.

2023-04-21 09:41 UTC, StarpTech approved these changes
Great work! LGTM

2023-04-21 10:14 UTC, jensneuse approved these changes
LGTM,.great work. One comment, does it work with the openapiv2 data source?

2023-04-21 11:25 UTC, fiam commented
> LGTM,.great work. One comment, does it work with the openapiv2 data source?

Thanks for the heads up! I had assumed it would just work, but I tested it and it does work. The code path used to send the request to load the schema is different than what we use for loading the schema from a "real" GraphQL server, so the former will never use a proxy.

2023-04-21 11:28 UTC, fiam commented on packages/testsuite/apps/generation/index.test.ts
> +			await regenerate({
They're just 2 test that call `regenerate()` with the same arguments. I feel like moving them to a separate describe to add a `beforeEach()` breaks the logical organization (valid/invalid proxy, test generation, then test queries) and it ends up less readable..

2023-04-21 11:28 UTC, merged