feat: inconsistencies in ts clients api
wundergraph/wundergraph pull request #857
Opened 2023-04-18 16:22 UTC by Pagebakers

## Motivation and Context

We use different implementations of clients across the sdk, this PR consolidates all implementation, so all clients use the typescript client as the base implementation.

The internalClient has been deprecated for backwards compatibility.

## Marketing Changelog

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

closes #810

2023-04-18 16:24 UTC, Pagebakers commented on packages/sdk/src/server/server.ts
> +function configureWunderGraphServer(configWrapper: () => WunderGraphServerConfig): WunderGraphServerConfig;
Switch this to using overloads, which are augmented in the generated code, this way you don't need to annotate `createWunderGraphServer` anymore in the config.

2023-04-18 21:19 UTC, StarpTech requested changes

2023-04-18 21:19 UTC, StarpTech commented on packages/sdk/src/server/operations-client.ts
> +	private convertGraphQLResponse(resp: GraphQLResponse, statusCode: number = 200): ClientResponse {
What needs to be handled differently here? Navily, I'd assume the typescript client already implements the full spec.

2023-04-18 21:19 UTC, StarpTech commented on packages/sdk/src/codegen/templates/typescript/server.template.ts
> +declare module "@wundergraph/sdk/server" {
It looks odd to overwrite a module from the same package, but in that way, we can skip to configuring the types ourselves, correct? Can we apply this to `configureWunderGraphOperations`. Very nice.

2023-04-18 21:19 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +function configureWunderGraphServer(configWrapper: () => WunderGraphServerConfig): WunderGraphServerConfig;
I haven't read this. Check my comment above :smile:

2023-04-18 21:19 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +// export const configureWunderGraphServer = <
Remove?

2023-04-18 21:19 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +				operations: new OperationsClient({
Reminder: We need to update OTEL integration as well.

2023-04-18 21:19 UTC, StarpTech commented on packages/sdk/src/codegen/templates/typescript/server.template.ts
> +
Could you create an issue to remove the internal client on 1st June?

2023-04-18 21:19 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +function configureWunderGraphServer(configWrapper: () => WunderGraphServerConfig): WunderGraphServerConfig;
Please add tests to our test suite after the implementation has been settled.

2023-04-18 21:24 UTC, StarpTech requested changes

2023-04-19 13:07 UTC, Pagebakers commented on packages/sdk/src/codegen/templates/typescript/server.template.ts
> +declare module "@wundergraph/sdk/server" {
Exactly, it gets overwritten in the generated code, so 'outside' the sdk package. 

I'll apply the same to configureWunderGraphOperations

2023-04-19 13:09 UTC, Pagebakers commented on packages/sdk/src/server/operations-client.ts
> +	private convertGraphQLResponse(resp: GraphQLResponse, statusCode: number = 200): ClientResponse {
I managed to extend the ts client so this is not needed anymore.

2023-04-19 13:11 UTC, Pagebakers commented on packages/sdk/src/codegen/templates/typescript/server.template.ts
> +
Done

2023-04-21 08:13 UTC, jensneuse requested changes

2023-04-21 08:13 UTC, jensneuse commented on packages/sdk/src/client/client.ts
> +		if (cb && 'EventSource' in globalThis && options.sse !== false) {
I'd rename "sse" to "disableSSE", then it needs to be explicitly set to true.

2023-04-21 08:13 UTC, jensneuse commented on packages/sdk/src/client/types.ts
> +	sse?: Boolean;
see comment above

2023-04-21 08:13 UTC, jensneuse commented on packages/sdk/src/codegen/templates/typescript/hooks.template.ts
> +import { InternalOperationsClient } from "./wundergraph.internal.operations.client";
One question regarding code generation. I'm not sure how exactly you've solved it, but I think what we could do is generate types for "public" operations as well as types for "internal" operations, all in one file. Then, for the external client, we only inject the public operations, while for the internal client, we inject the union of public and internal operations types. This way, it should be quite clean and organized. WDYT?

2023-04-21 08:13 UTC, jensneuse commented on packages/sdk/src/codegen/templates/typescript/internal.operations.client.template.ts
> +export type Queries = {
See comment above. I think we can just have one "operations client template", then generate types for internal and public, create a union and have one exported interface for the external client, one for the internal client. This could keep the code generation clean and reduce files.

2023-04-21 08:13 UTC, jensneuse commented on packages/sdk/src/configure/index.ts
> +import hash from 'object-hash';
Why is this here? I think @StarpTech replaced it in another place with a lightweight function. Is it needed at all? I don't see any usage.

2023-04-21 08:23 UTC, StarpTech commented on packages/sdk/src/configure/index.ts
> +import hash from 'object-hash';
It is used. You mixed it up with something else. https://github.com/wundergraph/wundergraph/blob/9b9675a94fc6b61d1d72b35725a30716e18a7a50/packages/sdk/src/configure/index.ts#L1284

2023-04-21 08:24 UTC, StarpTech commented on docs-website/src/pages/docs/wundergraph-server-ts-reference/pre-resolve-hook.md
> -export default configureWunderGraphServer<HooksConfig, InternalClient>(() => ({
Very nice, that we simplify it further.

2023-04-21 10:21 UTC, Pagebakers commented on packages/sdk/src/codegen/templates/typescript/hooks.template.ts
> +import { InternalOperationsClient } from "./wundergraph.internal.operations.client";
Not sure that'll work, since public operations have different properties. We can investigate, but i'd open another issue for that, as this PR is big enough already.

2023-04-21 10:22 UTC, Pagebakers commented on packages/sdk/src/configure/index.ts
> +import hash from 'object-hash';
Actually it can be removed again, I added it since applicationHash was required, but I made it optional instead.

2023-04-21 10:23 UTC, Pagebakers commented on docs-website/src/pages/docs/wundergraph-server-ts-reference/pre-resolve-hook.md
> -export default configureWunderGraphServer<HooksConfig, InternalClient>(() => ({
Yep, simplify the API and gives us more freedom to extend or change the types later without breaking anything.

2023-04-24 08:12 UTC, Pagebakers commented on docs-website/src/pages/docs/upgrade-guides/internal-client-deprecated.md
> +      subscribeOnce: true,
That shouldn't be there indeed :D

2023-04-24 08:14 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +		cb?: SubscriptionEventHandler<Data, Error>
It has to be, since in the operations client we don't have a callback, it's just a generator.

In the ts client, you can omit the cb now and it will return a generator.

2023-04-24 15:07 UTC, jensneuse approved these changes

2023-04-25 08:39 UTC, StarpTech commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> -export default configureWunderGraphServer<HooksConfig, InternalClient>(() => ({
How does it work when the type definitions aren't imported? :thinking:

2023-04-25 08:41 UTC, StarpTech requested changes

2023-04-25 10:27 UTC, Pagebakers commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> -export default configureWunderGraphServer<HooksConfig, InternalClient>(() => ({
This is a requirement in tsconfig.json

```
  "include": [".wundergraph/**/*.ts"]
```

If this is not added, it will only work by adding `HooksConfig, InternalClient` generics.

2023-04-25 10:34 UTC, Pagebakers commented on packages/sdk/src/server/plugins/hooks.ts
> +			req.ctx.operations = req.ctx.operations.withHeaders({ 'Wg-Cycle-Counter': body.cycleCounter });
Yes, this works as well.

2023-04-25 12:50 UTC, StarpTech commented on testapps/nextjs/.wundergraph/wundergraph.server.ts
> -export default configureWunderGraphServer<HooksConfig, InternalClient>(() => ({
Should we document it somewhere? Docs?

2023-04-25 12:59 UTC, StarpTech approved these changes
LGTM but please document the tsconfig changes.

2023-04-26 07:48 UTC, merged