fix: ensure input is undefined when not defined as schema
wundergraph/wundergraph pull request #864
Opened 2023-04-19 14:14 UTC by StarpTech

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-19 16:12 UTC, jensneuse requested changes

2023-04-19 16:28 UTC, Aenimus approved these changes

2023-04-19 16:28 UTC, Aenimus requested changes
CI failing

2023-04-19 20:50 UTC, StarpTech commented on packages/sdk/src/operations/operations.ts
> +	<Input extends z.ZodTypeAny, InferredResponse, ZodResponse>({
Check latest commit

2023-04-20 10:22 UTC, jensneuse approved these changes

2023-04-20 11:11 UTC, Pagebakers approved these changes

2023-04-20 11:43 UTC, merged