test: fix changed files detection for external PRs
wundergraph/wundergraph pull request #875
Opened 2023-04-20 20:36 UTC by fiam

Use a simpler approach to determine the refs that define the interval
of the changes contained in either the PR of the push.
For pull requests, use github.event.pull_request.base.sha and for
pushes just compare HEAD against its previous commit. This should
for the both use cases we support with external repos.

2023-04-20 21:47 UTC, StarpTech requested changes

2023-04-20 21:47 UTC, StarpTech commented on .github/workflows/packages-ci.yaml
> +      - name: Determine base and current refs
How did you test it? Did you create an external PR?

2023-04-21 07:53 UTC, fiam commented on .github/workflows/packages-ci.yaml
> +      - name: Determine base and current refs
Yep, I tested it in this PR I sent from a personal fork https://github.com/wundergraph/wundergraph/pull/869

2023-04-21 09:39 UTC, DaniAkash approved these changes

2023-04-21 09:43 UTC, StarpTech approved these changes
LGTM

2023-04-26 08:20 UTC, StarpTech approved these changes
LGTM

2023-04-26 09:17 UTC, merged