Dustin/add datasource mocking ability
wundergraph/wundergraph pull request #893
Opened 2023-04-25 16:26 UTC by StarpTech

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-04-26 12:20 UTC, StarpTech commented on packages/sdk/src/client/client.ts
> +		if (!init.signal && this.options.requestTimeoutMs && this.options.requestTimeoutMs > 0) {
@Pagebakers any objections that could break clients? As far I know, we already assume a polyfill of `AbortController`. https://docs.wundergraph.com/docs/clients-reference/typescript-client#browser

2023-04-26 22:33 UTC, StarpTech commented on .github/actions/wunderctl/action.yaml
> +    - uses: actions/cache@v3
Cache wunderctl. This saves us up to 2min per run.

2023-04-26 22:34 UTC, StarpTech commented on .github/workflows/packages-ci.yaml
> +      - name: Run testsuite
Splitting it from `pnpm run` fixes the tests and also make the output more readable.

2023-04-26 22:34 UTC, StarpTech commented on docs-website/src/pages/docs/guides/index.md
> +{% quick-link title="TypeSafe API Integrations" icon="core" href="/docs/guides/typesafe_api_integrations_with_typescript_operations_and_graphql" description="Easily integrate APIs with TypeScript Ope
Fixed several links

2023-04-27 07:49 UTC, jensneuse requested changes

2023-04-27 07:49 UTC, jensneuse commented on .github/workflows/packages-ci.yaml
> +      - name: Run testsuite
Are you ensuring that we exclude this pipeline (and any other) from the oss metrics?

2023-04-27 07:49 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +        ...templates.typescript.all,
I suggest that we generate the required typescript templates always, by default.
Can we just always append them to the templates config?
There's no harm in doing so.
It would make the config leaner and examples less verbose.

2023-04-27 07:49 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +    dir: join(__dirname, '..'),
Can you explain `__dirname` for noobs?

2023-04-27 07:49 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +We use `beforeAll` to start the test and mock server instances. The `ts.start()` method returns a cleanup function to shutdown all servers. In vitest you can return an async function to do a cleanup.
Add a single line break before "In vitest".

2023-04-27 07:49 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +    mockedAPIs: ['COUNTRIES_URL'],
I understand what you're doing here, but it doesn't feel intuitive.
Is it actually required? Could the "mock" function simply decide by checking the host if it wants to handle the request and if not, we use the "real" origin.

2023-04-27 07:49 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +When you setup a mock with `mock` and the request match, the interceptor is removed internally from the list. This means that you can intercept **2** or more calls to the same URL and return differen
I don't feel like this is intuitive.
The fact that it needs this level of explanation might be a smell that it's too complex.

E.g. when I define a mock, will it get multiple requests? or one? Or one in case it's matched? I'm not sure.

2023-04-27 07:49 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +    expect(body.query).toEqual(
Question: When this fails, will the stack trace point to exactly this position?
I'm using this technique to intentionally "fail" at a certain line of code to identify what the correct assertion should look like to then correct the test.

2023-04-27 07:49 UTC, jensneuse commented on packages/sdk/src/testing/mock-server.test.ts
> +		let scope = server.mock(
Should be const.

2023-04-27 07:49 UTC, jensneuse commented on packages/sdk/src/testing/mock-server.test.ts
> +		const scope = server.mock(
I'm wondering if it's possible to define with the mocks a certain order of requests.
E.g. is it possible with this structure to mock in a way that the request chain MUST be "/foo" and then "/bar" and not the other way around?

2023-04-27 07:49 UTC, jensneuse commented on packages/sdk/src/testing/mock-server.test.ts
> +	test('Should try the next interceptor when the previous does not match or throws an error', async () => {
In addition, is it possible to use this to mock an "embedded" GraphQL server (wundergraph.server.ts) or an omnigraph REST API (running as part of the fastify server, making requests to OpenAPI origins, but the fetch happens within fastify, not go)

2023-04-27 07:59 UTC, StarpTech commented on .github/workflows/packages-ci.yaml
> +      - name: Run testsuite
No, but I can provide a fix.

2023-04-27 08:00 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +        ...templates.typescript.all,
Yes, please create an issue

2023-04-27 08:01 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +    dir: join(__dirname, '..'),
It's a global constant that points to the absolute directory of the current file.

2023-04-27 08:01 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/mocking.md
> +        ...templates.typescript.all,
Yeah I was thinking the same, just generate all required files in the .wundergraph/generate dir by default. 
Out of scope for this though.

2023-04-27 08:05 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +When you setup a mock with `mock` and the request match, the interceptor is removed internally from the list. This means that you can intercept **2** or more calls to the same URL and return differen
That's exactly how nock works, and it is the most popular mocking solution for Node.js

2023-04-27 08:06 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +    mockedAPIs: ['COUNTRIES_URL'],
Could you elaborate? The node has to request the running mock server. If you would handle all the same then you will lose the functionality to mock individual origins. This approach also does not work when you want to mock an external API like an opensearch server.

2023-04-27 08:09 UTC, StarpTech commented on packages/sdk/src/testing/mock-server.test.ts
> +		let scope = server.mock(
No, I overwrite in the following lines.

2023-04-27 08:11 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +When you setup a mock with `mock` and the request match, the interceptor is removed internally from the list. This means that you can intercept **2** or more calls to the same URL and return differen
It's very simple maybe we should rephrase it. You can always mock one request. If the request does not match with any mock or the mock throws after it matches an error is thrown when calling `scope.done()`.

2023-04-27 08:13 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +    expect(body.query).toEqual(
Yes, that's way `scope.done` rethrows them original error.

2023-04-27 08:16 UTC, StarpTech commented on packages/sdk/src/testing/mock-server.test.ts
> +		const scope = server.mock(
If the order matters, I'd assume it was implemented like that, and the mocks can be written in that order. Other than that, the library does not ensure that, but you can simply use a variable in your tests to validate when each request arrived and check that afterward.

2023-04-27 08:17 UTC, StarpTech commented on packages/sdk/src/testing/mock-server.test.ts
> +	test('Should try the next interceptor when the previous does not match or throws an error', async () => {
That's the power of this generic approach. You can mock any HTTP data source as long as you can point your service  URL to an environment variable.

2023-04-27 08:18 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +  ts = createTestAndMockServer({
Yes, it could be. What are your thoughts?

2023-04-27 08:26 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +When you setup a mock with `mock` and the request match, the interceptor is removed internally from the list. This means that you can intercept **2** or more calls to the same URL and return differen
I rephrased it. Please check

2023-04-27 08:34 UTC, Pagebakers requested changes

2023-04-27 08:34 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/mocking.md
> +    mockedAPIs: ['COUNTRIES_URL'],
We have this method, we could just check if url starts with `https://countries.trevorblades.com/` for example?

```
 async ({ url, method }) => {
    return url.path === '/' && method === 'POST';
  },
```

2023-04-27 08:34 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/mocking.md
> +When you setup a mock with `mock` and the request match, the interceptor is removed internally from the list. This means that you can intercept **2** or more calls to the same URL and return differen
Does it support methods from nock? like twice() trice()?

2023-04-27 08:34 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +		if (!init.signal && this.options.requestTimeoutMs && this.options.requestTimeoutMs > 0) {
I checked, it's supported everywhere except IE11, which we don't need to support.

2023-04-27 08:34 UTC, Pagebakers commented on packages/sdk/src/testing/mock-server.test.ts
> +		let scope = server.mock(
scope is set again after this one completes.

2023-04-27 08:34 UTC, Pagebakers commented on packages/testsuite/apps/basic/openapi-generation.test.ts
> +import { describe, expect, it } from 'vitest';
Let's move everything to vitest.

2023-04-27 08:34 UTC, Pagebakers commented on packages/testsuite/apps/mock/test/mock-datasource.test.ts
> +		const scope = ts.mockServer.mock(
Regarding types, we could potentially do something like:
```ts
const scope = ts.mockServer.from('countries_GetCountries').mock(async (request) => {
   const body = await request.json() // typed from the GetCountries input schema
   
   return {
     body: {} // typed from the models?
   }
}
```

We can get the URL from the api namepsace countries, and the path and types from the operation name.

2023-04-27 08:34 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/mocking.md
> +    mockedAPIs: ['COUNTRIES_URL'],
```ts
ts.start({ apiNamespaces: ['countries'] }) // this can be typed
````


Also in one tests you do the above already:
```ts
		const scope = ts.mockServer.assertHTTPConnect(async ({ url }) => {
			return url === 'countries.trevorblades.com:443';
		});
```

2023-04-27 08:39 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/mocking.md
> +  ts = createTestAndMockServer({
simply createTestServer

if you configure `mockedAPIs: ['COUNTRIES_URL'],` it also sets up the mock server, for example.

2023-04-27 08:44 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +    mockedAPIs: ['COUNTRIES_URL'],
I could imagine that we add a "middleware" into the apitransport.go which gets activated e.g. when we set an evironment variable, like WG_MOCK_SERVER, which we use to inject the mock server.
We will then call the mock server for every request and run it against the "match" function.
If it matches, the mock server can return the response from the mock function.
If it doesn't match, we can indicate that we don't want to mock the response, e.g. by returning a special response status code or header. In this case, the transport middleware will do a regular request.

With this approach, we could simplify the config as we don't have to mock specific namespaces or URLs, which forces the user to use environment variables for URLs, which might not be desired or not always possible.

Simply match the URL in the matcher function and decide whether you'd like to mock the response or pass it back to the transport to do a regular request.

2023-04-27 08:47 UTC, jensneuse commented on packages/testsuite/apps/mock/test/mock-datasource.test.ts
> +		const scope = ts.mockServer.mock(
We might be confusing something here. These mocks should work on "origin" requests, right?
There are no models for origin requests (yet).
Operations are only known to the client.
One client Operations doesn't necessarily map to one single origin request, it could be many different origin requests.

2023-04-27 08:47 UTC, jensneuse commented on .github/actions/wunderctl/action.yaml
> +    - uses: actions/cache@v3
really nice!

2023-04-27 08:49 UTC, jensneuse commented on docs-website/src/pages/docs/guides/mocking.md
> +    dir: join(__dirname, '..'),
I suggest to make this clear in the documentation.

2023-04-27 08:50 UTC, jensneuse commented on packages/sdk/src/testing/mock-server.test.ts
> +	test('Should try the next interceptor when the previous does not match or throws an error', async () => {
I'm not sure if I see it as a feature that I have to make every URL an environment variable.

2023-04-27 09:24 UTC, StarpTech commented on packages/sdk/src/testing/mock-server.test.ts
> +	test('Should try the next interceptor when the previous does not match or throws an error', async () => {
How do you configure your node for different environments?

2023-04-27 10:11 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +  ts = createTestAndMockServer({
mockedEnvUrls

2023-04-27 10:13 UTC, fiam commented on docs-website/src/pages/docs/guides/mocking.md
> +  ts = createTestAndMockServer({
I would also prefer this approach.

2023-04-27 10:18 UTC, fiam commented on docs-website/src/pages/docs/guides/mocking.md
> +    mockedAPIs: ['COUNTRIES_URL'],
Since the namespace needs to be unique, I think a better approach would be referencing the APIs to be mocked by their namespaces, then sending it up to wunderctl via environment variables that override the URL. e.g. `WG_URL_OVERRIDES=countries=http://our-internal-proxy.url:1234`

2023-04-27 10:19 UTC, fiam commented on docs-website/src/pages/docs/guides/mocking.md
> +When you setup a mock with `mock()` and the request match, the mock server will return the response. If the request does not match, the mock server will return a 404 response and the call to `scope.d
`match` => `matches`

2023-04-27 10:21 UTC, fiam commented on docs-website/src/pages/docs/guides/mocking.md
> +You have also the ability to throw an error inside the response function to fail the mock. This is useful if you want to verify with test assertion that the request is correct. A thrown error is hand
I don't like this, if a handler function throws I think we should fail right there rather than failing later.

2023-04-27 10:21 UTC, fiam commented on docs-website/src/pages/docs/guides/mocking.md
> +  async ({ url, method }) => {
Can we support non-async functions here? It feels like too much ceremony.

2023-04-27 10:39 UTC, fiam commented on packages/sdk/src/client/client.ts
> +		if (!init.signal && this.options.requestTimeoutMs && this.options.requestTimeoutMs > 0) {
I would leave this entirely to the caller, via custom fetch fu

2023-04-27 11:29 UTC, Pagebakers approved these changes
LGTM

2023-04-27 11:46 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +When you setup a mock with `mock()` and the request match, the mock server will return the response. If the request does not match, the mock server will return a 404 response and the call to `scope.d
Done, ty

2023-04-27 11:49 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +You have also the ability to throw an error inside the response function to fail the mock. This is useful if you want to verify with test assertion that the request is correct. A thrown error is hand
We throw directly, but because the request is handled asynchronously, we can't throw it in the handler. It would also make it impossible to add multiple mocks because the first mock that throws would fail the test. We use `expect` (which throws) to validate if a request matches.

2023-04-27 11:51 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +You have also the ability to throw an error inside the response function to fail the mock. This is useful if you want to verify with test assertion that the request is correct. A thrown error is hand
We rethrow the error as soon as the user calls `.done` the moment when the user expects that the mock was called.

2023-04-27 11:54 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +  async ({ url, method }) => {
Yes, we can. Good point.

2023-04-27 12:17 UTC, StarpTech commented on packages/testsuite/apps/mock/test/mock-datasource.test.ts
> +		const scope = ts.mockServer.mock(
I like this and will keep it in mind when reworking the implementation to consider the Virtual Graph separately.

2023-04-27 12:56 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +  async ({ url, method }) => {
Done

2023-04-27 12:58 UTC, StarpTech commented on docs-website/src/pages/docs/guides/mocking.md
> +  ts = createTestAndMockServer({
We abandon this because it does not work with mocking apis that aren't part of the virtual graph. We use a simpler approach to cover both cases.

2023-04-27 12:58 UTC, StarpTech commented on packages/sdk/src/testing/mock-server.test.ts
> +	test('Should try the next interceptor when the previous does not match or throws an error', async () => {
Can we resolve it?

2023-04-27 12:59 UTC, StarpTech commented on .github/actions/wunderctl/action.yaml
> +    - uses: actions/cache@v3
thx

2023-04-27 13:25 UTC, jensneuse approved these changes

2023-04-27 14:03 UTC, fiam approved these changes
LGTM

2023-04-27 14:59 UTC, merged