feat: context factories
wundergraph/wundergraph pull request #914
Opened 2023-04-28 14:40 UTC by fiam

This pull request adds support for using a custom context in hooks and TS functions. To use it, the application must declare a factory function when configuring the server:

```typescript
// wundergraph.server.ts
import { GraphQLObjectType, GraphQLSchema, GraphQLString } from 'graphql';
import { configureWunderGraphServer } from '@wundergraph/sdk/server';

export class MyContext {
	greet () { console.log('say hello')}
}

// Function doesn't need to have any specific name nor to be exported
const createContext = async() => {
	return new MyContext();
}

export default configureWunderGraphServer(() => ({
	hooks: {
		queries: {
			Countries: {
				preResolve:async ({operations, context}) => {
					// context here is fully typed
					context.greet();
				}
			}
		},
		mutations: {},
	},
	context: {
         request: {
             create: createContext,
         }
	},
}));
```

This makes the context instance available for functions too:

```typescript

import { createOperation, z } from '../../generated/wundergraph.factory';

export default createOperation.query({
	input: z.object({
		id: z.string(),
	}),
	handler: async ({ input, context }) => {
		context.greet();
		return {
			id: input.id,
			name: 'Jens',
			bio: 'Founder of WunderGraph',
		};
	},
});
```

## Motivation and Context

Several customers have expressed their desire to inject arbitrary objects into the request pipeline. This provides
support for both a global context and request context, satisfying those use cases.

## Marketing Changelog

WunderGraph now supports dependency injection and IoC using context factories. This enables new patterns, like
opening and keeping stateful connections to remote services that can't be mapped to data sources (e.g. a Redis instance, Temporal, ...)

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-09 14:05 UTC, fiam commented
@jensneuse @Pagebakers Code is ready, but we need some new docs. How should we document this? A new guide?

2023-05-09 15:12 UTC, fiam commented
I went ahead and added a guide

2023-05-09 15:15 UTC, Pagebakers commented on docs-website/config/navigation.tsx
> +						title: 'Use a custom context',
Maybe call it `Extend the WunderGraph server context` ?

2023-05-09 15:23 UTC, Pagebakers requested changes
Found a few small issues.

In the future it'd be great if we can use the same context factory to build the internal context (log, operations, etc), instead of re-using the same code everywhere.

2023-05-09 15:23 UTC, Pagebakers commented on docs-website/src/pages/docs/guides/custom-context.md
> +  context: makeContext,
typo, `createContext`

2023-05-09 15:29 UTC, Pagebakers requested changes
One more thing, please add it to the wundergraph.server.ts reference too

https://docs.wundergraph.com/docs/wundergraph-server-ts-reference

2023-05-09 18:31 UTC, fiam commented on docs-website/config/navigation.tsx
> +						title: 'Use a custom context',
I was just thinking, what if we rename the whole document as "Using a Context Factory"?

2023-05-09 18:31 UTC, fiam commented on docs-website/src/pages/docs/guides/custom-context.md
> +  context: makeContext,
Thanks! Fixed

2023-05-09 18:32 UTC, fiam commented on docs-website/src/pages/docs/guides/custom-context.md
> +  context: makeContext,
👍

2023-05-10 08:07 UTC, StarpTech requested changes
The context should be available in all server components.

- [ ] Functions
- [ ] Webhook
- [X] Hooks
- [x] GraphQL servers

2023-05-10 09:02 UTC, jensneuse commented
@fiam make sure that the following resources are present and accessible in the create context factory:
- client request
- user (if authenticated)
- operations (client)

2023-05-10 19:42 UTC, fiam commented on docs-website/config/navigation.tsx
> +						title: 'Use a custom context',
I've renamed using the title you suggested

2023-05-10 19:43 UTC, fiam commented
> The context should be available in all server components.
> 
> * [x]  Functions
> * [x]  Webhook
> * [x]  Hooks
> * [x]  GraphQL servers

It was only missing from the webhooks, but I've now fixed that.

2023-05-10 19:43 UTC, fiam commented
> @fiam make sure that the following resources are present and accessible in the create context factory:
> 
> * client request
> * user (if authenticated)
> * operations (client)

It now receives the same context as hooks/functions, minus the custom context field

2023-05-10 19:56 UTC, fiam commented
> One more thing, please add it to the wundergraph.server.ts reference too
> 
> [docs.wundergraph.com/docs/wundergraph-server-ts-reference](https://docs.wundergraph.com/docs/wundergraph-server-ts-reference)

I've added it

2023-05-10 20:08 UTC, fiam commented on packages/testsuite/apps/basic/.wundergraph/wundergraph.server.ts
> +	// This works, declaring return type makes no difference
@Pagebakers Could you please take a look at this one? Quite the head scratcher. I've outlined when it fails.

2023-05-10 20:26 UTC, fiam commented on packages/testsuite/apps/basic/.wundergraph/wundergraph.server.ts
> +	// This works, declaring return type makes no difference
Got it. It was because the import at the top of a type also named `ContextFactoryContext`, but different

2023-05-10 20:34 UTC, fiam commented on packages/testsuite/apps/basic/.wundergraph/wundergraph.server.ts
> +	// This works, declaring return type makes no difference
Well, false alarm. That makes it work by passing the explicit parameter but if I remove the explicit parameter it goes back to `any`- I'll continue investigating

2023-05-11 10:34 UTC, fiam commented on packages/testsuite/apps/basic/.wundergraph/wundergraph.server.ts
> +	// This works, declaring return type makes no difference
Thanks for the help @Pagebakers, now it's working 👍

2023-05-11 11:03 UTC, StarpTech requested changes

2023-05-11 12:07 UTC, fiam commented on docs-website/src/pages/docs/guides/context-factory.md
> +    return new MyContext();
It was requested that the context creation had optional access to the user, the client request and the operation client. Keep in mind that you can have like a "master" context and then make a copy for every request which holds additional per-request data. The block in your comment will work if you wrap `new MyContext()` in a function.

2023-05-11 12:42 UTC, StarpTech commented on docs-website/src/pages/docs/guides/context-factory.md
> +    return new MyContext();
Why should we pass all the data again through `createContext` if the user already has access to data where context is available?

2023-05-11 12:42 UTC, jensneuse commented on docs-website/src/pages/docs/guides/context-factory.md
> +    return new MyContext();
As a user, I'd like to be able to define per-request dependencies. If we don't enable this, someone will ask for it eventually.

From an implementation point of view, we can simply call the "createContext" function from within the fastify handler before we call an actual hook or a TypeScript operation. This means, the client request and user object is already present. If it's already present, we can just expose it to the user to be able to have more choices in terms of how they want to build the dependencies.

Hook flow: req -> node -> fastify -> create context -> hook
TS Operation flow: req -> node -> fastify -> create context -> ts operation

If we don't expose the data that's already present in the same request to the create context function, you might not be flexible enough in building the dependencies. So, I don't see the point in omitting this.

2023-05-11 13:02 UTC, jensneuse commented on docs-website/src/pages/docs/guides/context-factory.md
> +    return new MyContext();
Yes, I think we need the following things:

1. One function to create a global context, persistent across ALL requests, this gets called when the fastify server starts
2. One function that gets called before the fastify server is shut down to clean up the global context
3. One function that gets called right before the we make a function call into a hook or typescript operation
4. One function that gets called right after we make a function call into a hook or typescript operation (for cleanup purposes)

The global persistent hook functions will, obviously, have no request or user, as they are run outside of the request lifecycle.
The request local hooks run immediately before and after calling a hook or typescript function, so we can (and should) pass the client request, user, and operations client, just in case a user needs it.

OnFastifyStart: global create context
OnBeforeFastifyStop: global cleanup context
OnBeforeCallHookOrFunction: local create context
OnAfterCallHookOrFunction: local cleanup context

In addition to the hooks, there should be a centralized way to define and extend the types of the context. Not sure if the hooks themselves can do this, or if we do it in one place.

2023-05-11 13:08 UTC, jensneuse commented on docs-website/src/pages/docs/guides/context-factory.md
> +    return new MyContext();
Oh, please don't take the function names literally.

2023-05-12 15:03 UTC, StarpTech requested changes

2023-05-12 15:03 UTC, StarpTech commented on packages/sdk/src/server/server.ts
> +			releaseContext(req.ctx.context);
You forgot to await. That result in an unhandled promise rejection on error.

2023-05-12 15:06 UTC, fiam commented on packages/sdk/src/server/server.ts
> +			releaseContext(req.ctx.context);
Good catch! Fixing

2023-05-12 15:06 UTC, fiam commented on packages/sdk/src/server/server.ts
> +			releaseContext(req.ctx.context);
Fixed now. Thanks!

2023-05-12 18:03 UTC, StarpTech approved these changes
LGTM

2023-05-12 18:03 UTC, merged