feat: add support for reading OpenAPI error responses
wundergraph/wundergraph pull request #916
Opened 2023-05-01 13:20 UTC by fiam

- Extend GraphQLError with OAS specific extensions
- Read OAS extensions in ResponseError and make them available in a field

Fixes #822

## Motivation and Context

Reading error responses allows the upstream to send meaningful error messages and
response codes which make their way down to the client.

## Marketing Changelog

OAS support in augmented with extended support for error handling over OAS data sources

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-01 20:58 UTC, jensneuse commented
How will this work with multiple nested requests? One RPC Operation might map to N root requests and M nested requests. Will it be possible to understand the response status codes and headers for all of them and what field/resolve path they belong to?

2023-05-02 10:43 UTC, fiam commented
> How will this work with multiple nested requests? One RPC Operation might map to N root requests and M nested requests. Will it be possible to understand the response status codes and headers for all of them and what field/resolve path they belong to?

We return the extra information from the first error that has it. However, the caller can also iterate over ResponseError.errors and pass an specific one.

2023-05-02 11:43 UTC, Pagebakers requested changes

2023-05-02 11:43 UTC, Pagebakers commented on packages/sdk/src/client/errors.ts
> +interface GraphQLErrorExtensions {
Twice the same interface name?

2023-05-02 12:12 UTC, StarpTech requested changes

2023-05-02 12:12 UTC, StarpTech commented on packages/sdk/src/client/errors.ts
> +	/**
Remove?

2023-05-02 12:33 UTC, fiam commented on packages/sdk/src/client/errors.ts
> +interface GraphQLErrorExtensions {
Typo and autocomplete. Fixed.

2023-05-02 12:34 UTC, fiam commented on packages/testsuite/apps/openapi/index.test.ts
> +	createOpenAPITestServer(8090);
Because I also want to easily run all components manually when debugging

2023-05-02 12:35 UTC, fiam commented on packages/sdk/src/client/errors.ts
> +	/**
Good catch! Deleted.

2023-05-02 12:44 UTC, StarpTech commented on packages/testsuite/apps/openapi/index.test.ts
> +	createOpenAPITestServer(8090);
Can we improve our current solution? That might be something that our users want as well.

2023-05-02 13:26 UTC, Pagebakers approved these changes

2023-05-02 14:23 UTC, StarpTech commented on packages/sdk/src/client/errors.ts
> +export const getHttpResponseError = (error?: ResponseError | GraphQLError) => {
The error should not be optional if you want to extract something from it.

2023-05-02 14:29 UTC, fiam commented on packages/sdk/src/client/errors.ts
> +export const getHttpResponseError = (error?: ResponseError | GraphQLError) => {
This is just for ergonomics. The idea is that you can pass something that’s possibly undefined and only check the return value, to avoid having to check for undefined twice.

2023-05-02 14:32 UTC, StarpTech commented on packages/sdk/src/client/errors.ts
> +export const getHttpResponseError = (error?: ResponseError | GraphQLError) => {
I don't like it because it expresses that you get something even in case of undefined, but I will also not block it.

2023-05-02 14:38 UTC, fiam commented on packages/sdk/src/client/errors.ts
> +export const getHttpResponseError = (error?: ResponseError | GraphQLError) => {
No strong feelings about it. I'd made it required. PTAL.

2023-05-02 15:33 UTC, StarpTech commented on packages/testsuite/apps/openapi/.wundergraph/wundergraph.config.ts
> +	baseURL: 'http://localhost:8090/',
We will address it in a separate PR.

2023-05-02 19:41 UTC, StarpTech requested changes

2023-05-02 19:41 UTC, StarpTech commented on packages/testsuite/apps/openapi/.wundergraph/wundergraph.server.ts
> +import { getHttpResponseError } from '@wundergraph/sdk/dist/client/errors';
wrong import

2023-05-02 19:41 UTC, StarpTech commented on packages/sdk/src/client/errors.ts
> +export const getHttpResponseError = (error: ResponseError | GraphQLError) => {
I think you should accept an array of errors in that case you can call without iterate over all yourself.

2023-05-02 19:54 UTC, fiam commented on packages/testsuite/apps/openapi/.wundergraph/wundergraph.server.ts
> +import { getHttpResponseError } from '@wundergraph/sdk/dist/client/errors';
Good catch, updated.

2023-05-02 19:55 UTC, fiam commented on packages/sdk/src/client/errors.ts
> +export const getHttpResponseError = (error: ResponseError | GraphQLError) => {
I've made it accept a `GraphQLError[]` too PTAL

2023-05-02 19:55 UTC, fiam commented on packages/testsuite/apps/openapi/.wundergraph/wundergraph.server.ts
> +					const error = response?.errors?.[0];
I'm now passing the whole array to `getHttpResponseError()`

2023-05-02 20:27 UTC, StarpTech approved these changes
LGTM

2023-05-03 13:59 UTC, merged