chore: enable subscription in nextjs-relay testapp
wundergraph/wundergraph pull request #923
Opened 2023-05-03 15:04 UTC by fiam

It doesn't crash the node anymore

2023-05-03 19:20 UTC, ggeijteman-wg approved these changes

2023-05-03 19:33 UTC, Aenimus requested changes
down with curlies!

2023-05-03 20:54 UTC, fiam commented
> down with curlies!

Updated, PTAL

2023-05-04 09:34 UTC, Aenimus approved these changes

2023-05-04 10:19 UTC, merged