fix: don't skip second level operations in Postman collections, skip internal
wundergraph/wundergraph pull request #930
Opened 2023-05-04 18:31 UTC by fiam

Rewrite the algorithm to use a simpler method to build the directories and the
child/parent relationships. Skip internal operations while generating the
collection.

2023-05-04 18:55 UTC, StarpTech requested changes
Looks good! Only a few nuts.

2023-05-04 18:55 UTC, StarpTech commented on packages/sdk/src/postman/builder.test.ts
> +test.only('PostmanBuilder', async () => {
I'd remove `only` otherwise, the next person wonders why his test isn't running :smile:

2023-05-04 18:55 UTC, StarpTech commented on packages/sdk/src/postman/builder.test.ts
> +const countPostmanOperations = (obj: any) => {
Can we replace any with some basic types?

2023-05-04 19:26 UTC, fiam commented on packages/sdk/src/postman/builder.test.ts
> +test.only('PostmanBuilder', async () => {
🤦‍♂️

2023-05-04 19:48 UTC, fiam commented on packages/sdk/src/postman/builder.test.ts
> +test.only('PostmanBuilder', async () => {
Thanks! Fixed

2023-05-04 19:50 UTC, fiam commented on packages/sdk/src/postman/builder.test.ts
> +const countPostmanOperations = (obj: any) => {
Unfortunately, it seems the types are quite messed up. Every field that has a declaration in the root `Collection` is `undefined`. The data seems to be stored inside an `item` property (note the singular), but it's not declared in the type.

2023-05-05 06:40 UTC, jensneuse commented on packages/sdk/src/postman/builder.test.ts
> +const countPostmanOperations = (obj: any) => {
Postman SDK types are not in good shape. Let's keep it as is.

2023-05-05 06:46 UTC, jensneuse approved these changes
I've tested it locally, good work! LGTM

2023-05-05 10:13 UTC, StarpTech commented on packages/sdk/src/postman/builder.test.ts
> +const countPostmanOperations = (obj: any) => {
ok

2023-05-05 10:14 UTC, StarpTech approved these changes
LGTM

2023-05-05 10:27 UTC, merged