feat(sdk): add custom fetch options
wundergraph/wundergraph pull request #948
Opened 2023-05-10 13:28 UTC by Hebilicious

# Add custom fetch options and remove fetch defaults

## Motivation and Context

The wundergraph client is incompatible with cloudflare workers/pages. Some runtime like workers [don't support](https://github.com/cloudflare/workerd/blob/902b65ace3c5c0f5ae4b432fae976f28ddaec1ec/src/workerd/api/http.h#L510-L517) some of the fetch options that are injected by the wundergraph client and that can't be overwritten by a customFetch.

This PR remove these default options, and add a way to pass custom fetch options to the wundergraph client to give more flexibility.

## Marketing Changelog

Add custom fetch options and remove fetch defaults. 
This makes the wundergraph client compatible with cloudflare workers/pages.

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-10 18:11 UTC, jensneuse requested changes
With your change, you modified the default behavior. Can you change the implementation so that the default behaviour stays as is, but you're able to change the fetchOptions, e.g. by removing credentials and mode if you don't need it.

2023-05-11 04:32 UTC, jensneuse commented
> > With your change, you modified the default behavior. Can you change the implementation so that the default behaviour stays as is, but you're able to change the fetchOptions, e.g. by removing credentials and mode if you don't need it.
> 
> Done. However, I personally think it's better if it works out of the box, as many people will encounter this issue in the future. In terms of security, the browser defaults look safe enough...
> 
> Maybe this needs to be documented somewhere ?

Let me in investigate in various browsers what happens if we drop it.

2023-05-11 12:42 UTC, Pagebakers commented
How about doing this on cloudflare.

```ts
const client = createClient({
  customFetch: (init) => {
    const {mode, credentials, ..._init} = init
    return fetch(_init)
  }
})
```

2023-05-18 08:29 UTC, Hebilicious commented
@Pagebakers haven't had the chance to try this yet as I've been using my fork. But this proposed change isn't breaking, just add an easier way to pass custom fetch options.

2023-07-10 09:01 UTC, Hebilicious commented
> Can you share the fetch config you use on cloudflare workers?

I'm using a pnpm patch

```
diff --git a/dist/client/client.js b/dist/client/client.js
index d1dd3698a33f60273dbb8a7c28d5d55a4b2c724e..5b275b14a58e94419178a8606e79132a987167a2 100644
--- a/dist/client/client.js
+++ b/dist/client/client.js
@@ -50,8 +50,6 @@ class Client {
             ...init.headers,
         };
         return fetchImpl(input, {
-            credentials: 'include',
-            mode: 'cors',
             ...init,
         });
     }
```

2023-07-18 12:52 UTC, Pagebakers commented
We looked into this again and decided to go a slightly different approach for now, since we don't want to expose both customFetch and customFetchOptions. #1137 should fix support for Cloudflare workers.

Thanks again for opening this PR, we really appreciate your input. 🙏

2023-07-18 12:52 UTC, closed without merging

2023-07-18 14:28 UTC, Hebilicious commented
@Pagebakers Thanks pagebreaks, the fix in #1137 should allow me to get rid of my pnpm patch 🙏🏽 
Still, I'm surprised that no-one else had the issue ... Was I the only one using the client on cloudflare ?