feat: improve Cache-Control support
wundergraph/wundergraph pull request #959
Opened 2023-05-13 11:04 UTC by fiam

- Declare cache as public by default for anonymous operations, private
for authenticated ones
- Include a must-revalidate header by default
- Allow disabling max-age and stale-while-revalidate

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-13 11:05 UTC, jensneuse commented
@fiam add marketing section to description maybe?

2023-05-16 07:52 UTC, Pagebakers requested changes
Oh this is very nice!

We should also reflect this change in the docs
https://docs.wundergraph.com/docs/wundergraph-operations-ts-reference/configure-caching

2023-05-16 08:25 UTC, jensneuse approved these changes

2023-05-16 14:31 UTC, StarpTech approved these changes
LGTM

2023-05-16 14:31 UTC, StarpTech commented on packages/sdk/src/configure/operations.ts
> +	 * Set to undefined to omit this component.
Does `0` works too?

2023-05-16 15:04 UTC, fiam commented on packages/sdk/src/configure/operations.ts
> +	 * Set to undefined to omit this component.
It does, I've added a test for it too.

2023-05-17 07:29 UTC, Pagebakers approved these changes

2023-05-17 08:12 UTC, merged