fix: wait for the hooks server to start up before listening on the node
wundergraph/wundergraph pull request #973
Opened 2023-05-16 20:27 UTC by fiam

Hooks server and node were started in parallel. This causes a problem
when the node is ready and starts listening before the hooks server has
had time to do its own setup and opening its port, because operations that
call into the hooks server will fail inmmediately due to the connection
to the hooks server being refused.

To fix this, wait for the hooks server to be ready (by connecting to
its port) during startup for wunderctl up and wunderctl start (iff the
hooks server is also started by us).

## Motivation and Context

This has caused problems for apps using OpenAPIv2, since its queries are routed through
the hooks server.

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-16 20:38 UTC, Aenimus approved these changes

2023-05-16 22:27 UTC, StarpTech commented
From a architectural perspective this task should be done by the load balancer. Passing a request only to a WunderNode if the healthcheck is successful. The WunderNode healthcheck endpoint only returns 200 when the hooks server health endpoint returned with 200 as well.

If fly doesn't doesn't guarantee that at their proxy we can ensure it on our heindall.

2023-05-17 15:56 UTC, fiam commented
> From a architectural perspective this task should be handled from the load balancer. Passing a request only to a WunderNode if it has been registered with a successful healthcheck. The WunderNode healthcheck endpoint only returns 200 when the hooks server health endpoint returned with 200 as well (until max retry).
> 
> If fly doesn't doesn't guarantee that at their proxy (revisit?) we can ensure it on our heimdall.
> 
> Did you also try to increase the timeout of the healthcheck request to the hooks server?

I've verified that the fly load balancer doesn't wait for a successful  health-check when resuming the node, so that doesn't solve the problem, and in any case that wouldn't solve the problem for standalone deployments.

We can't check that in Heimdall either because we do not know when a request is going to wake up a node. We could arrange for the node to notify Heimdall before it goes to sleep, somehow keep that state and poll the health endpoint if we believe the request will wake up the node but that is more complicated than needed.

The node has all the information because it knows that it has just started and also knows the hooks server URL. This way, once we start listening on the port everything is ready to dispatch requests. The only drawback is a small startup penalty for operations that were not going to use the hooks server anyway.

I've refactored the PR to reuse the existing `hooks.Client` instead of implementing and ad-hoc check. PTAL. Thanks!

2023-05-17 16:41 UTC, StarpTech requested changes

2023-05-17 16:41 UTC, StarpTech commented on pkg/node/node.go
> +			fmt.Println("HC CRAP", time.Now())
Remove

2023-05-17 16:41 UTC, StarpTech commented on pkg/node/node.go
> +				fmt.Println("HC OK", time.Now())
Here too

2023-05-17 16:41 UTC, StarpTech commented on pkg/node/node.go
> +			if n.hooksServerHealthIsOk(initialHealthCheckCtx, hooksClient) {
This will make requests as fast as the machine is, right? This will flood the server. We should add a short delay of 50ms.

2023-05-17 16:41 UTC, StarpTech commented on pkg/node/node.go
> +	n.hooksServerInitialHealthCheck(hooksClient)
Please add a comment about it.

2023-05-17 16:41 UTC, StarpTech commented on pkg/node/node.go
> +		options.hooksHealthCheck.periodic = true
Not needed if it can't be configured and if it is the default.

2023-05-17 16:41 UTC, StarpTech commented on pkg/node/node.go
> +	initialHealthCheckCtx, cancel := context.WithTimeout(context.Background(), initialHealthCheckWaitTimeout)
Do we need it, if we can just retry w. max-retry it until it succeeds?

2023-05-17 16:41 UTC, StarpTech commented on pkg/node/node.go
> +	initialHealthCheckCtx, cancel := context.WithTimeout(context.Background(), initialHealthCheckWaitTimeout)
I also found out that not all methods of the `hooksClient` use the `httpClient` of the struct.

2023-05-17 17:02 UTC, fiam commented on pkg/node/node.go
> +			fmt.Println("HC CRAP", time.Now())
Ooops. Thanks for pointing that out. I've deleted this and the other two print statements

2023-05-17 17:07 UTC, fiam commented on pkg/node/node.go
> +		options.hooksHealthCheck.periodic = true
I would refactor that at a later point. I remember you and I discussed this thing a few weeks ago in the context of the testing SDK (the hooks server not being health-checked in some cases)

2023-05-17 17:11 UTC, fiam commented on pkg/node/node.go
> +			if n.hooksServerHealthIsOk(initialHealthCheckCtx, hooksClient) {
The request will be retried using the underlying `retryablehttp.Client`, so it shouldn't max the CPU.

2023-05-17 17:15 UTC, fiam commented on pkg/node/node.go
> +	n.hooksServerInitialHealthCheck(hooksClient)
I've added a comment explaining what we do in case of failure. PTAL

2023-05-17 21:42 UTC, StarpTech commented on pkg/node/node.go
> +			if n.hooksServerHealthIsOk(initialHealthCheckCtx, hooksClient) {
Good point, in order to not slow down the cold start the timeout must be low but the max retry high otherwise we waste time. We put a lot of effort into this.

This also means we will wait for the server to start before the WunderNode is started. This also has an effect on the cold start. Please test it and share your results. Currently, we have cold start of around 600ms with a hello world wundergraph app.

2023-05-18 10:43 UTC, fiam commented on pkg/node/node.go
> +			if n.hooksServerHealthIsOk(initialHealthCheckCtx, hooksClient) {
If we're going to use that as a measure to approve PRs, the first thing we need is a documented and repeatable way of producing those numbers. I'm not getting numbers in the same ballpark when measuring TTFB without his PR applied.

2023-05-18 15:52 UTC, StarpTech commented on pkg/node/node.go
> +			if n.hooksServerHealthIsOk(initialHealthCheckCtx, hooksClient) {
The agreement is to not make it worse than before but having a script would be beneficial.

> I'm not getting numbers in the same ballpark when measuring TTFB without this PR applied.

What do you mean by that?

2023-07-09 03:37 UTC, closed without merging