feat: propagate authentication, client request and key headers between operations
wundergraph/wundergraph pull request #982
Opened 2023-05-21 11:03 UTC by fiam

- Add authentication middleware to internal operations
- Forward Authentication and X-Request-ID headers between operations
- Decode the client request correctly before passing it to function handlers
- Fix returning falsy data from TS operations
- Add tests for all these

Fixes ENG-2216
Fixes ENG-2215
Fixes ENG-1383
Fixes ENG-1179
Fixes ENG-1073

## Motivation and Context

Internal operations didn't support these features that external operations did.
Additionally, some features didn't work properly when they involved multiple
operation calls.

## Marketing Changelog

Authentication, request logging and accesing client headers now work with internal
operations.

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-22 18:07 UTC, Pagebakers commented on packages/sdk/src/client/client.ts
> +		if (resp.data === undefined) {
So null can be valid?

2023-05-22 18:11 UTC, Pagebakers approved these changes

2023-05-22 20:07 UTC, fiam commented on packages/sdk/src/client/client.ts
> +		if (resp.data === undefined) {
I think so, an operation might return null and we should handle that gracefully. Maybe I'm missing something? 😅 Keep in mind that we use this to handle return values from TS operations too, and they don't necessarily have to abide by GQL conventions.

2023-05-23 13:37 UTC, StarpTech requested changes

2023-05-23 13:37 UTC, StarpTech commented on pkg/apihandler/authentication.go
> +		panic("API is nil or hashkey, blockkey, csrfsecret invalid: This should never have happened. Either validation didn't detect broken configuration, or someone broke the validation code")
Why not return an error?

2023-05-23 13:55 UTC, fiam commented on pkg/apihandler/authentication.go
> +		panic("API is nil or hashkey, blockkey, csrfsecret invalid: This should never have happened. Either validation didn't detect broken configuration, or someone broke the validation code")
I'd say whoever added that block intended the API misuse to be very evident. You can ignore an error, but it's way more difficult to ignore a panic. I don't usually I don't think it's a bad idea.

2023-05-23 19:38 UTC, StarpTech commented on pkg/apihandler/authentication.go
> +		panic("API is nil or hashkey, blockkey, csrfsecret invalid: This should never have happened. Either validation didn't detect broken configuration, or someone broke the validation code")
Panic should be only used when there is no other way. Here we can simply return an error and let the callee decide.

2023-05-23 20:29 UTC, StarpTech approved these changes
LGTM

2023-05-24 08:22 UTC, fiam commented
Thanks @StarpTech!

2023-05-24 08:52 UTC, merged