feat: use Prometheus to track and expose operation counts
wundergraph/wundergraph pull request #991
Opened 2023-05-23 20:14 UTC by fiam

## Motivation and Context

## Marketing Changelog

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

2023-05-24 18:40 UTC, jensneuse approved these changes
I suggest adding at least one test to cover the functionality somehow.

2023-05-24 19:58 UTC, StarpTech requested changes

2023-05-24 19:58 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
> +export interface PrometheusOptions {
I'm missing `enabled` flag to enable or disable the feature.

2023-05-24 19:58 UTC, StarpTech commented on pkg/apihandler/metrics.go
> +	metricsNamespace = "wunderctl"
`wunderctl` is a bit misleading. let's call it `wundernode`.

2023-05-24 19:58 UTC, StarpTech commented on pkg/apihandler/metrics.go
> +func (h *operationMetricsHandler) Handler(operationHandler http.Handler) http.Handler {
Please add some tests for this handler.

2023-05-24 19:58 UTC, StarpTech commented on pkg/metrics/prometheus.go
> +func (m *prometheusMetrics) NewGaugeVec(opts MetricOpts, labelNames ...string) GaugeVec {
Please also add some tests. See https://github.com/zeromicro/go-zero/blob/master/core/metric/counter_test.go

2023-05-24 19:58 UTC, StarpTech commented on pkg/metrics/prometheus.go
> +type prometheusGaugeVec struct {
Please put the types in different files. counter.go, histogram.go... This is easier to grasp.

2023-05-24 19:58 UTC, StarpTech commented on pkg/apihandler/metrics.go
> +// XXX: Do NOT create more than one of these because the metric names will conflict.
I don't understand.

2023-05-24 19:58 UTC, StarpTech commented on pkg/apihandler/metrics.go
> +		subsystem = "api_transport"
I also need to choose names for these things in otel. What is better `subsystem` or `component`?

2023-05-24 19:58 UTC, StarpTech commented on pkg/apihandler/metrics.go
> +func newOperationMetrics(m metrics.Metrics, operation *wgpb.Operation) operationMetrics {
Let's not couple to the protobuf config. Let the module be standalone.

2023-05-24 19:58 UTC, StarpTech commented on pkg/apihandler/metrics.go
> +func (h *operationMetricsHandler) estimateRequestSize(r *http.Request) int {
The implementation does not follow any standard. You can rely on content-length but counting header length is odd.

2023-05-25 07:56 UTC, ggeijteman-wg commented on docs-website/src/pages/docs/guides/monitoring-and-observability.md
> +            port: 8881, // Set to zero to disable
is that:

`*nothing*`, `port: zero,`, `port: ,` or something else :D?

2023-05-25 07:58 UTC, StarpTech commented on docs-website/src/pages/docs/guides/monitoring-and-observability.md
> +            port: 8881, // Set to zero to disable
We should introduce `enabled` flag. The default behavior of a zero port is random on most systems.

2023-05-25 07:58 UTC, ggeijteman-wg commented on docs-website/src/pages/docs/guides/monitoring-and-observability.md
> +            port: 8881, // Set to zero to disable
Honestly, I would go for a `enable` field, that seems to be the more common pattern. Hinging this on the availability of the port field will only cause trouble when toggling on/off for testing.

2023-05-25 07:59 UTC, StarpTech requested changes

2023-05-25 07:59 UTC, StarpTech commented on packages/protobuf/wgpb/wundernode_config.ts
You forgot to introduce new `WG_` envs and update the docs.

2023-05-25 10:37 UTC, fiam commented on pkg/apihandler/metrics.go
> +// XXX: Do NOT create more than one of these because the metric names will conflict.
It's outdated, I figured a way to be able to instant them multiple times. I've removed it.

2023-05-25 10:37 UTC, fiam commented on docs-website/src/pages/docs/guides/monitoring-and-observability.md
> +            port: 8881, // Set to zero to disable
I've added an `enabled` option

2023-05-25 10:45 UTC, fiam commented on packages/protobuf/wgpb/wundernode_config.ts
Added them to the docs

2023-05-25 10:48 UTC, fiam commented on packages/protobuf/wgpb/wundernode_config.ts
> +export interface PrometheusOptions {
I've added it

2023-05-25 10:48 UTC, fiam commented on pkg/apihandler/metrics.go
> +	metricsNamespace = "wunderctl"
Renamed

2023-05-25 11:40 UTC, fiam commented on pkg/metrics/prometheus.go
> +type prometheusGaugeVec struct {
I moved them to separate files. They ended up being < 10 lines each, though 😅

2023-05-25 11:41 UTC, fiam commented on pkg/metrics/prometheus.go
> +func (m *prometheusMetrics) NewGaugeVec(opts MetricOpts, labelNames ...string) GaugeVec {
I've added tests

2023-05-25 11:41 UTC, fiam commented on pkg/apihandler/metrics.go
> +func (h *operationMetricsHandler) Handler(operationHandler http.Handler) http.Handler {
Test for this added too

2023-05-25 11:41 UTC, fiam commented
@StarpTech @ggeijteman-wg Thanks for the reviews! I've updated the PR addressing your feedback, PTAL.

2023-05-26 08:02 UTC, StarpTech commented on packages/testsuite/apps/basic/prometheus.test.ts
> +	it('should include operation metrics', async () => {
Nice :+1:

2023-05-26 08:03 UTC, StarpTech approved these changes
Great work!

2023-05-26 08:05 UTC, ggeijteman-wg approved these changes

2023-05-26 08:24 UTC, merged